1992/nathan/README.md, 1992/nathan/nathan.c, 2020/ferguson2/README.md, years.html
It has been deemed that this should be okay now so we decided to add the code.
This required a minor change in 2020/ferguson2 which I have made here as well in this commit.
=> Add original before unseen 1992/nathan/nathan.c

1984/anonymous/README.md, 1984/decot/Makefile, 1984/decot/README.md, 1984/laman/Makefile, 1984/laman/README.md, 1984/mullender/Makefile, 1984/mullender/README.md, 2019/adamovsky/Makefile, 2019/burton/Makefile, 2019/diels-grabsch1/Makefile, 2019/diels-grabsch2/Makefile, 2019/dogon/Makefile, 2019/endoh/Makefile, 2019/giles/Makefile, 2019/lynn/Makefile, 2019/mills/Makefile, 2019/poikola/Makefile, 2019/yang/Makefile, var.mk
Update 1984 README.md files and one Makefile
Just some clean up and general notes as well as add a 'To run:' section
to each README.md.
=> Update 1984 README.md files and one Makefile

1989/tromp/Makefile, 1989/tromp/tromp.c, winners.html
After renaming some of the winner directories to be the winner surname 
the winners.html was not updated in every case (particularly for Howe).
=> Link fixes in winners.html

1989/tromp/Makefile, 1989/tromp/tromp.c, 1990/stig/README.md, 1990/tbr/README.md, 1990/westley/README.md, winners.html
Add thank you note to Cody in some README.md files, remove the warning
that 1990/westley/westley.c might not compile with modern compilers
(since I fixed it) and reworded a statement slightly. Yes I'm thanking
myself but it's actually from the judges.
=> Minor updates to 1990

1985/README.md, 1985/shapiro/.gitignore, 1985/shapiro/Makefile, 1986/holloway/README.md, 1987/biggar/README.md, 1987/wall/README.md, 1989/tromp/Makefile, 1989/tromp/tromp.c, 1990/stig/README.md, 1990/tbr/README.md, 1990/westley/README.md, winners.html
Typo fix in 1987/biggar/README.md.
Add another try in 1987/wall/README.md with a question to ponder.
=> Minor changes to 1987

1985/README.md, 1985/shapiro/.gitignore, 1985/shapiro/Makefile, 1986/holloway/README.md, 1987/biggar/README.md, 1987/wall/README.md, 1988/dale/Makefile, 1988/dale/README.md, 1989/fubar/README.md, 1989/jar.2/README.md, 1989/paul/README.md, 1989/robison/Makefile, 1989/robison/README.md, 1989/roemer/README.md, 1989/tromp/Makefile, 1989/tromp/tromp.c, 1990/stig/README.md, 1990/tbr/README.md, 1990/westley/README.md, winners.html
Mostly this involves README.md files in some entries but the 
1989/robinson/Makefile was updated. Force -include option in CINCLUDE 
variable not CDEFINE.
=> Minor updates to 1989 files

1996/gandalf/README.md, 1996/gandalf/gandalf.c
As I love the theme and layout I kept the code that can no longer compile in just commented out.
Fun fact: did you know that the original name of Gandalf was Bladorthin? He was not the only character who originally had different names in The Hobbit. In fact the original name of Thorin was Gandalf! (... I know the former is true and I'm almost certain the latter is true but it's been a long time since I've read it in The History of the Hobbit).
=> Fix 1996/gandalf

2000/primenum/README.md, 2000/primenum/primenum.c
This was done by making main() return type int not void.
=> Make 2000/primenum more portable

1984/decot/README.md, 1985/applin/README.md, 1986/holloway/README.md, 1986/marshall/README.md, 1986/wall/README.md, 1987/westley/README.md, 1989/robison/README.md, 1989/tromp/README.md, 1989/westley/README.md, 1990/cmills/README.md, 1990/dds/README.md, 1990/jaw/README.md, 1990/scjones/README.md, 1990/tbr/README.md, 1990/theorem/README.md, 1990/westley/Makefile, 1990/westley/README.md, 1991/ant/.gitignore, 1991/brnstnd/README.md, 1992/westley/README.md, 1993/jonth/README.md, 1996/gandalf/README.md, 1998/schweikh2/Makefile, 1998/schweikh2/README.md, 2000/anderson/README.md, 2000/bellard/README.md, 2000/bmeyer/README.md, 2000/primenum/README.md, 2000/primenum/primenum.c
The file hill was not in the .gitignore file and it should have been so
it now is.
=> Add a git to 1991/ant/.gitignore :-)

1987/westley/README.md, 1988/westley/README.md, 1989/westley/README.md, 1990/westley/README.md, 1991/westley/README.md, 1992/westley/README.md, 1994/westley/README.md, 1996/dalbec/README.md, 1996/dalbec/dalbec.c, 1996/schweikh1/Makefile, 1996/schweikh1/README.md, 1996/westley/.gitignore, 1996/westley/Makefile, 1996/westley/README.md, 1996/westley/westley.alt.c, 1996/westley/westley.c, 2001/herrmann2/README.md, 2001/herrmann2/herrmann2.c, 2001/westley/.gitignore, 2001/westley/Makefile, 2001/westley/README.md
The author noted in the Makefile that for Solaris the compiler flag 
-I/usr/include should be included so I have added that.
As well I updated the README.md - formatting fixes (possibly typos as 
well but no longer sure).
=> Minor fixes to 1996/schweikh1

2004/newbern/README.md, 2004/newbern/newbern.c, 2020/ferguson2/README.md
I meant to commit with that commit 2020/ferguson2/README.md as this file used to refer to a hint file from another entry but it should be a README.md.
=> Add missing file to commit 005fd7

1993/lmfjyh/README.md, 1998/bas1/README.md, 1998/bas2/README.md, 1998/chaos/README.md, 1998/df/README.md, 1998/dlowe/README.md, 1998/dloweneil/README.md, 1998/schnitzi/README.md, 1998/schweikh3/README.md, 1998/schweikh3/samefile.1.dupe, 2000/primenum/README.md, 2004/anonymous/README.md, 2004/arachnid/README.md, 2004/gavare/.gitignore, 2004/gavare/README.md, 2004/gavin/README.md, 2004/hibachi/README.md, 2004/sds/README.md, 2004/vik2/README.md, 2005/aidan/README.md, 2005/vik/README.md, 2006/sloane/README.md, 2006/sloane/sloane.c
Formatting and other notes. Many more need to be checked for this but I
wanted these changes out of the way of git status to try and clean my
working changes.
=> Many README.md files updated

1993/lmfjyh/README.md, 1998/bas1/README.md, 1998/bas2/README.md, 1998/chaos/README.md, 1998/df/README.md, 1998/dlowe/README.md, 1998/dloweneil/README.md, 1998/schnitzi/README.md, 1998/schweikh3/README.md, 1998/schweikh3/samefile.1.dupe, 2000/primenum/README.md, 2004/anonymous/README.md, 2004/arachnid/README.md, 2004/gavare/.gitignore, 2004/gavare/README.md, 2004/gavin/README.md, 2004/hibachi/README.md, 2004/sds/README.md, 2004/vik2/README.md, 2005/aidan/README.md, 2005/vik/README.md, 2006/sloane/README.md, 2006/sloane/sloane.c, bugs.md
A line for one entry was in the wrong entry.
I added that I'm working on them (with some humour injected there) but
others may try too .. if they are okay making people very sad :-)
Added more information / examples in some of the status sections and
possibly some of the entries that are listed.
=> Fixes and improvements to bugs.md

2001/bellard/.gitignore, 2001/bellard/README.md, 2001/bellard/bellard.c, 2001/bellard/bellard.otccex.c, 2011/akari/README.md, 2011/fredriksson/README.md, 2011/goren/README.md, 2011/konno/README.md, 2012/hamano/README.md, 2012/hou/README.md, 2012/vik/README.md, 2013/birken/README.md, 2013/morgan2/README.md, 2013/robison/README.md, bugs.md
Typos / spelling errors and other such things. Many many more need to be checked still.
=> Several README.md files updated

1988/phillipps/phillipps.c
Previously the call in main() returned a recursive call to main() (with !) but the function that this became was called by main() but main() did not return it. Now it does.
As well I changed the formatting ever so slightly of main(), making it one line instead of three (counting the { and }).
=> Slight fix in 1988/phillipps

1988/phillipps/phillipps.c, 1991/dds/.gitignore, 1991/dds/Makefile, 1991/dds/README.md, 1991/dds/dds.alt.c, 1992/adrian/README.md, 1992/adrian/adrian.c, 1992/albert/README.md
Formatting and add 'try' section.
=> Minor fixes to 1992/albert/README.md

1988/phillipps/phillipps.c, 1991/dds/.gitignore, 1991/dds/Makefile, 1991/dds/README.md, 1991/dds/dds.alt.c, 1992/adrian/README.md, 1992/adrian/adrian.c, 1992/albert/README.md, bugs.md
The question of whether this is worth calling a bug (or a bug that 
should be fixed) or not is certainly one to consider and I put that in
there. Nevertheless with non-binary digits the program will crash.
Should this be fixed? I don't know. I'll certainly look at it in time
though.
=> Add 1989/robison to bugs.md

faq.html, faq.md
I tried to keep the formatting as close to the original as possible. It's very likely links have to be fixed and it's very likely formatting has to be fixed.
Some things necessarily had to change but very few did in fact need to change.
As tempting as it was to change it to British English I did not (though I started to when fixing a link but I caught myself in time) :-)
Naturally as this is a major change problems are expected but these will be worked out. I guess the next step would be to do this for other raw html files but I don't fancy doing more than one in a day. This can be discussed later though as some will be automatically generated anyway so no need for a markdown file (faq.md was discussed as a good idea).
=> Add faq.md, remove faq.html

1993/ant/README.md, 1993/cmills/README.md, 1993/dgibson/README.md, faq.html, faq.md
This includes removing a statement that this could not compile under 
macOS. I'm not sure what happened but I suspect it was the wrong data 
file perhaps one of the files left by the script. Either way it does 
work with macOS.
Fixed formatting as well.
=> Fix 1993/dgibson/README.md

1984/mullender/.gitignore, 1984/mullender/Makefile, 1984/mullender/README.md, 1984/mullender/mullender.alt.c, bugs.md, faq.md
Format fixes (besides line lengths other formatting changes were made in 
hopes to make things clearer / easier to see / better).
Reword some answers a bit to hopefully make them better.
Typo fixes here and there. There is one I'm not sure if it's meant to be
a typo or rather if I should change it since it's actually a quote: that
from 1984/anonymous. Thus I have not changed it.
=> Improvements and fixes to faq.md

1984/mullender/Makefile, 1984/mullender/README.md, 1984/mullender/mullender.alt.c, faq.md
Now you can specify the number of microseconds to sleep in between writes! This makes it easier to experiment with different speeds as well as solve any problems if your CPU is too slow or too fast
BTW: is there such a thing as too fast a CPU ? :-) actually yes for certain code which is probably not as uncommon as you think :-) ).
=> Improve 1984/mullender alt code

1984/anonymous/README.md, 1984/mullender/Makefile, 1984/mullender/README.md, 1984/mullender/mullender.alt.c, faq.md
Some years after the entry was published the judges asked them if they
wished to remain anonymous. They said yes but added that they are well
known for their there connection to the C language.
I fixed at the same time the typo that was in this quote as it seemed 
that it's better to be clear than to keep a quote exactly as is 
especially as it might have not been a copy paste in the first place.
=> Add author comments to 1984/anonymous

2018/hou/README.md, 2018/mills/README.md, 2018/poikola/Makefile, 2018/poikola/README.md, 2018/vokes/README.md, 2018/yang/.gitignore, 2018/yang/README.md, bugs.md, faq.md
Formatting fixes in README.md.
Add entry to bugs.md as it will abort due to assertion failure. But this
is expected and the entry works fine (open the html file and you'll see
that). So INABIAF.
=> Minor adjustments to 2018/hou

2018/endoh2/README.md, 2018/giles/README.md, faq.md
The try section actually triggers a long (or infinite? .. didn't check) loop so I note this and also say how to break out of it (though most would probably know how).
=> Minor note added to 2018/endoh2/README.md

1994/ldb/Makefile, 1994/ldb/README.md, 2019/burton/README.md, 2019/ciura/README.md, 2019/ciura/de.sh, 2019/ciura/getwords.sh, 2019/ciura/it.sh, 2019/ciura/pl.sh, 2019/ciura/ru.sh, 2019/diels-grabsch1/.gitignore, 2019/diels-grabsch1/README.md, 2019/diels-grabsch1/guidelines.txt, 2019/diels-grabsch1/prog.c, 2019/diels-grabsch2/README.md, 2019/diels-grabsch2/prog.c, 2019/dogon/README.md, bugs.md, faq.md
As Landon believes that the spelling of this word that is usually four 
words is intentional (and I suspect it too) I have done what he
suggested - surround it with quotes. That is:
-Input should be less than ten million octets toavoidthisproblem.  
+Input should be less than ten million octets "toavoidthisproblem".
=> Minor adjustment to 2019/burton

all/README.md, all/summary.txt, bugs.md
I by accident had left an incomplete sentence in the file (probably
jumping to another entry when updating the file with multiple entries
and then forgetting to go back .. numerous times). Fixed that and added
a bit of information (or at least elaborated a bit?).
=> Fix to bugs.md for 1986/hague

1992/imc/README.md, 2018/bellard/README.md, 2020/endoh1/README.md
I've not gone through the file entirely but I have some significant 
fixes to make and I want to get my working repo clean so I can do these
fixes. I'll go through this file in full later.
=> Partial fix (format etc.) in 2020/endoh1/README.md

1992/imc/README.md, 2018/bellard/README.md, 2018/ferguson/test.sh, 2020/endoh1/README.md
Make it a bit more portable (assuming env is under /usr/bin):
#!/usr/bin/env bash
instead of
#!/bin/bash
And although Landon suggested that I will never be done with changes in
my entries (which is probably true I confess ... :-) ) I suggest that in
this case this is rather useful (in fact I should do this for 
2020/ferguson1 as there are several scripts there .. maybe 
2020/ferguson2 but I don't know for sure).
=> Fix shebang in 2018/ferguson/test.sh

1988/spinellis/README.md, 1992/imc/README.md, 2018/bellard/README.md, 2018/ferguson/test.sh, 2020/endoh1/README.md
One needs to make clobber for this entry to work right! It cannot easily
be added to the Makefile as the rule depends on the source code. This 
probably should be fixed.
=> Add important note to 1988/spinellis/README.md

2019/mills/README.md
Some commands were incorrect and caused errors.
=> Fix try section in 2019/mills

1991/fine/README.md
This text actually is from Merlyn LeRoy (who is none other than Brian Westley) on usenet rec.puzzles in a post on 22 August 1992 and of course I linked to his winning entries and the usenet post!
=> Add fun text to 1991/fine try command

2012/endoh2/README.md, 2012/endoh2/endoh2.c, 2012/endoh2/everything.sh, 2012/grothe/README.md, 2012/hamano/README.md, 2012/kang/README.md, 2012/vik/.gitignore, 2012/vik/Makefile, 2012/vik/README.md, 2012/vik/vik.alt.c, 2012/zeitak/README.md, bugs.md, tmp/winners.csv, winners.html
Link was also added to winners.{html,csv}.
Found via his email address - I checked to see if the domain was valid 
(or at least attempted to) and saw it's their website.
=> Add link to and format fix 2012/kang/README.md

1991/dds/README.md, 2012/endoh2/README.md, 2012/endoh2/endoh2.c, 2012/endoh2/everything.sh, 2012/grothe/README.md, 2012/hamano/README.md, 2012/kang/README.md, 2012/vik/.gitignore, 2012/vik/Makefile, 2012/vik/README.md, 2012/vik/vik.alt.c, 2012/zeitak/README.md, bugs.md, tmp/winners.csv, winners.html
The clang issue does have an alternate version which I made a while back
but I added a note earlier in the file that most likely it'll be needed
for clang - depends on the default CFLAGS possibly but for macOS at
least it does not work. I never tested linux but I probably should.
=> Clarify a feature and clang issue in 1991/dds

1998/dlowe/README.md, 1998/dloweneil/README.md, 2000/dlowe/README.md, 2011/dlowe/README.md, 2012/dlowe/README.md, 2013/cable1/README.md, 2013/dlowe/README.md, tmp/winners.csv, winners.html
I know that in bugs.md there is a missing URL for him or at least about
one of the entries but I'll have to look at that later. It might be that
it should stay there as it was a website for the entry itself and it 
would be nice to have it back but for now this is unaddressed.
=> Update David Lowe URL

tmp/winners.csv, winners.html
Many other links have to be fixed. The link, incidentally, was actually correct in the README.md file but not in the other files.
=> Fix format of winners.csv + check one link

bin/check_awards.sh
... and how it was generated ...
=> Add comments to bin/check_awards.sh explaining it

2004/arachnid/.gitignore, 2004/arachnid/arachnid.alt.c
Forgetfully I forgot :-) to add the source file so it only worked with my local copy. The README.md file was modified and the Makefile was updated but the source code was not added so using make alt would only result in an error. This fixes that blunder.
=> Actually add 2004/arachnid/arachnid.alt.c

1993/plummer/.gitignore, 1993/plummer/Makefile, 1993/plummer/README.md, 1993/plummer/plummer.alt.c, 2001/anonymous/try.me.sh
Alt code is so that one can see with modern systems what is actually 
happening. The time to sleep is configurable.
=> Format check 1993/plummer/README.md + add alt code

1993/plummer/.gitignore, 1993/plummer/Makefile, 1993/plummer/README.md, 1993/plummer/plummer.alt.c, 1995/dodsond2/README.md, 2000/thadgavin/.gitignore, 2001/anonymous/try.me.sh
It appears I might not have done some of the earlier years after all. I'll have to check.
This however is just a clean up so I can get back to the json thing - today, tomorrow or the next day but hopefully not later than that (hopefully tomorrow I can work it out at the latest but we'll see).
=> Format 1995/dodsond2/README.md

1993/plummer/.gitignore, 1993/plummer/Makefile, 1993/plummer/README.md, 1993/plummer/plummer.alt.c, 1995/dodsond2/README.md, 2000/thadgavin/.gitignore, 2001/anonymous/try.me.sh, 2015/yang/README.md
More to do but I'm getting the changes made out of the way for issue #4.
=> Initial check of 2015/yang/README.md

1985/applin/README.md, 1985/applin/applin.c, 1985/august/README.md, 1985/lycklama/README.md
Move try section below to run section.
Added try command.
Possible format fixes.
=> Minor fixes and updates in 1985/lycklama/README.md

2005/giljade/giljade.c, todo.md
I've actually figured out the problem and now the errors (on running the
program on its output) is down to 3 errors instead of I think it was 9.
I have not updated bugs.md but I will in time if I don't end up fixing 
this (in the end I will most likely fix it or at least attempt to). A 
look at the diff here might give a clue however. Still I do intend to 
address this further to get it to work properly.
=> Make progress on 2005/giljade with clang

1988/dale/Makefile, 1988/dale/README.md, 1994/ldb/README.md, 2004/gavin/README.md, 2004/gavin/gavin.md, bugs.md, tmp/author.csv, winners.html
Reword / clarify a point and a typo fix in README.md.
Format fix in gavin.md.
=> Minor fixes in 2004/gavin

1991/rules.txt, 1992/guidelines.txt, 1993/guidelines.txt, 1994/guidelines.txt, 1995/guidelines.txt, 1996/guidelines.txt, 1998/guidelines.txt, 2000/briddlebane/Makefile, 2000/briddlebane/README.md, 2000/guidelines.txt, 2000/rince/README.md, 2001/guidelines.txt, 2004/guidelines.txt, 2005/guidelines.txt, 2006/guidelines.txt, 2011/guidelines.txt, 2012/guidelines.txt, 2013/guidelines.txt, 2014/guidelines.txt, 2015/guidelines.txt, 2018/guidelines.txt, 2019/diels-grabsch1/guidelines.txt, 2019/guidelines.txt, 2020/guidelines.txt
The is a file excluded from this commit that has had the change because
there are other changes but the file is incomplete. That file will be 
committed when the fixes are complete which will happen at a later date.
=> Change 'tri-graphs' to 'trigraphs' - it's one word

faq.md
This is important as it's in the question about entries of themes that are used a lot and thus that are less likely to win.
=> Add missing state machine entries to faq.md

2015/endoh1/README.md, faq.md
I'm trying to get my git status clean right now so I can get working on the other repo so it's only partial for now. I'll worry about the rest another day. I hope to look at `jprint` soon though I'd rather be asleep I must admit.
=> Partial format fix 2015/endoh1/README.md

2015/endoh1/README.md, 2015/schweikhardt/README.md, faq.md
This commit also has the last remaining 'tri-graph' -> 'trigraph' fix.
=> Partial format fix 2015/schweikhardt

thanks-for-fixes.md
It was a yank paste thing and it was something I was likely going to 
remove anyway as it wasn't really relevant after all. It was fine as it
was and at best trivially interesting to have the other point.
=> Remove entry with no context from thanks

1988/spinellis/README.md, 1988/westley/README.md, 1991/dds/README.md, thanks-for-fixes.md
There were several fixes that needed to be made. Some were done and in the process I discovered some fixed entries that really should be an alternate version. That was not yet done but I have kept track of some and will find the others - another time.
As there are more important things to do (like the jprint tool in the mkiocccentry repo) and since I need a break I have decided to make a pull request with the changes made.
Some README.md files had to be updated for this commit as well.
=> Fixes in thanks-for-fixes.md file

2004/jdalbec/jdalbec.c, 2015/yang/Makefile, thanks-for-fixes.md
Not all systems implicitly link in libm so this is necessary for those 
systems.
=> Add -lm to 2015/yang/Makefile

2004/jdalbec/jdalbec.c, 2015/yang/Makefile, 2018/bellard/Makefile, 2018/hou/Makefile, thanks-for-fixes.md
=> Add -lm to 2018/hou/Makefile

2004/jdalbec/jdalbec.c, 2015/yang/Makefile, 2018/bellard/Makefile, 2018/hou/Makefile, 2019/dogon/Makefile, thanks-for-fixes.md
=> Add -lm to 2019/dogon/Makefile

2004/jdalbec/jdalbec.c, 2015/hou/Makefile, 2015/yang/Makefile, 2018/bellard/Makefile, 2018/hou/Makefile, 2019/dogon/Makefile, thanks-for-fixes.md
=> Add -lm to 2015/hou/Makefile

2004/jdalbec/jdalbec.c, 2005/jetro/Makefile, 2015/hou/Makefile, 2015/yang/Makefile, 2018/bellard/Makefile, 2018/hou/Makefile, 2019/dogon/Makefile, thanks-for-fixes.md
=> Add -lm to 2005/jetro/Makefile

2004/jdalbec/jdalbec.c, 2005/jetro/Makefile, 2013/morgan1/Makefile, 2015/hou/Makefile, 2015/yang/Makefile, 2018/bellard/Makefile, 2018/hou/Makefile, 2019/dogon/Makefile, thanks-for-fixes.md
=> Add -lm to 2013/morgan1/Makefile

2004/jdalbec/jdalbec.c, 2005/jetro/Makefile, 2012/blakely/Makefile, 2012/endoh1/Makefile, 2013/morgan1/Makefile, 2015/hou/Makefile, 2015/yang/Makefile, 2018/bellard/Makefile, 2018/hou/Makefile, 2019/dogon/Makefile, thanks-for-fixes.md
=> Add -lm to 2012/blakely/Makefile

faq.md
The question in question :-) is to do with the .orig.c files restored in commit 2ba12ecc3cdafc4688020dae061f3a6736104f6b. This seems like a useful FAQ entry to have.
=> Add question/answer to faq.md

2006/toledo2/.gitignore
Hopefully that solves the problem with pulling if the file exists ... maybe not necessary for that but it should be in the file anyway.
Off to do other things again!
=> Add C to 2006/toledo2/.gitignore

tmp/README.md
=> Typo and format fix tmp/README.md

bugs.md, tmp/README.md
Although it maybe could be fixed and I might look at it in the future (I
would have to look at Xlib API first at the least) the fact that there 
is a known workaround means that (based on discussion with Landon) it 
can be considered a known issue that need not be fixed necessarily. Thus
it's now considered, at least tentatively, a feature not a bug. As for 
what it is: when you start the game everything moves over to the right 
of the screen and quickly ends but if you click on the game screen it 
goes back to the centre to allow you to play.
=> Change bug status of 1992/kivinen

src/sgit/Makefile, src/sgit/README.md, src/sgit/sgit.sh
Typo fix in sgit usage for -e option.
=> Sync sgit from sgit repo

1986/hague/README.md, 1986/wall/README.md, 1992/kivinen/README.md, how-to-enter.md, thanks-for-fixes.md
This should already be in bugs.md but it's worth putting it in the 
README.md file too as most people will probably not look at it when 
looking at entries.
=> Add a INABIAF to 1992/kivinen/README.md

thanks-for-fixes.md
As 2004/burley involved quite a few changes to get it to work I have reworded and expanded on the changes in thanks-for-fixes.md as is done for the other entries that were fixed.
=> Update thanks file w/information about 2004/burley

1990/dds/dds.c, 1990/tbr/tbr.c, thanks-for-fixes.md
I gave an example of one of the challenging bug fixes that Yusuke Endoh
made just like I have done for me.
I also made the fact that there are complicated fixes bold for both
Yusuke and me. Not strictly necessary but I am proud and I should be
too. Plus it's simply better this way.
=> Improve top of thanks-for-fixes.md format a bit

1987/wall/wall.c, 1990/cmills/cmills.c, faq.md, thanks-for-fixes.md
Redefined gets to use fgets() with the appropriate args so that the code
can refer to gets() in the way it originally did.
=> Improve my fix to 1990/cmills

thanks-for-fixes.md
This includes the sgit tool that will be published on the website (I am proud even if it was originally only written for me based on a persistent problem I had over the years) and it also includes rewording things to hopefully make them clearer and grammatical fixes (or a fix?) as well.
=> Minor updates to thanks-for-fixes.md

src/sgit/Makefile
.. okay this will likely be all I do today .. resting now and after that other things to do.
=> Add shellcheck rule to sgit/Makefile

1995/cdua/README.md, 1998/schweikh1/README.md, bugs.md, thanks-for-fixes.md
Although there might be others the entries that Yusuke fixed that are
listed here are worthy of mentioning. It only seemed right that since 
some of my fixes are mentioned at the top that so too should his.
=> List some entries fixed by Yusuke Endoh in thanks

thanks-for-fixes.md
It now reads a bit better and puts the more important fixes earlier in the description.
=> Reorder/reword thanks for 1990/dds

1986/marshall/README.md, 1990/dds/README.md, 2005/mikeash/.gitignore, thanks-for-fixes.md
...about the strange problems that prevented this entry from working,
depending on whether the optimiser was enabled or not (different
problems) that I fixed. This was documented at the idea of Landon as it 
is rather interesting and amusing.
=> Minor clarifications in 1986/marshall/README.md

2000/natori/README.md, src/sgit/README.md, src/sgit/sgit.1, src/sgit/sgit.sh
Usage string improved a bit.
Updated man page - added examples. Not all from the README.md have been
added but it refers to the README.md (that section). Some of the 
examples refer to different files.
Slightly changed formatting/wording of some of the examples.
Clarify what the '.' glob means for those who do not know.
There possibly were other things as well.
New version 0.0.12-1 29-04-2023.
=> sgit updates (man page, usage string, README.md)

2000/natori/README.md
Typo fix and added note about the alternate code earlier in the file to note what it's for (southern hemisphere). Also added questions to ponder for the users of the alternate code in the northern hemisphere.
=> Minor fixes and adjustments to 2000/natori

src/sgit/README.md, src/sgit/sgit.1, src/sgit/sgit.sh
Sync commits from the sgit repo:
commit 6a1032d4dcc9e8677f9f40c1951fa9cdd6048b4f (HEAD -> master, origin/master)
Date:   Sun Oct 1 08:12:49 2023 -0700
Minor fixes and updates to sgit.1
That includes in comments but also a typo fix and added the AUTHOR
section. Yes according to some it's discouraged but I don't care even if
that makes me a git to some people :-) since it is my tool and in any
case just because something is discouraged does not mean it's a bad
idea.
commit 168ef107434cfb2aece7ba9fea74c55b595ebc0e
Date:   Sun Oct 1 08:12:27 2023 -0700
Add comment in sgit about the man page
commit 229e61cd4ee42de79094f139720fbee7c8666f0e
Date:   Sun Oct 1 08:11:27 2023 -0700
Minor fixes and updates to README.md
Removed duplicate text, added a dedications section (the most important
part to …
=> Minor sgit commits

1993/rince/.gitignore, 1993/rince/Makefile, 1993/rince/README.md, 1993/rince/design.md, 1993/rince/rince.alt.c, thanks-for-fixes.md, tmp/src/Makefile, tmp/src/ioccc_status/.gitignore, tmp/src/ioccc_status/Makefile, tmp/src/ioccc_status/ioccc_status.sh
Since I have sgit in my own repository (https://github.com/xexyl/sgit)
and it has been removed from this repo but installed on Landon's system
rather than on the website I have updated the text regarding the tool.
=> Update thanks file with respect to sgit

faq.md
The prototype answer is from discussion on GitHub, suggested by Landon, but I added to it and fixed typos as well. I probably introduced some other problems at this hour and at least one thing comes to mind as perhaps not ideal to have but these things can be worked out now that they're in the file.
=> Add FAQ about clang -Weverything being too strict

faq.md
=> Minor update to FAQ about clang defects

thanks-for-fixes.md, todo.md
Yes this is partly a joke littered with irony but to be fair I did make 
some fixes that had to be done some of which were not my fault. :-)
There was another entry that was added here as it had a relation to 
2020/ferguson2: I referred to it in my original remarks.
=> Updated thanks file for my entries :-)

thanks-for-fixes.md, todo.md
Reworded the thanks to be a bit clearer and added a bit more information
that feels useful to note (not so much for the thanks but for the way
the alternate code is configurable at compile time).
=> Update thanks-for-fixes.md wrt 2013/birken

thanks-for-fixes.md, todo.md
Some fixes were missing from the file.
=> Added some entries to thanks file (for 2019)

1984/README.md, 1985/README.md, 1986/README.md, 1987/README.md, 1988/README.md, 1989/README.md, 1990/README.md, 1991/README.md, 1992/README.md, 1993/README.md, 1994/README.md, 1995/README.md, 1996/README.md, 1998/README.md, 2013/mills/README.md, todo.md
I also updated the todo.md file as I left some things out that have to
be done. I only explicitly named one thing but when I go over them as a
final pass I will address the things in question (some will require
discussion).
=> Format fix 1980s and 1990s README.md files

1984/README.md, 1985/README.md, 1986/README.md, 1987/README.md, 1988/README.md, 1989/README.md, 1990/README.md, 1990/tbr/README.md, 1990/tbr/tbr.alt.c, 1990/tbr/tbr.c, 1991/README.md, 1992/README.md, 1993/README.md, 1994/README.md, 1995/README.md, 1996/README.md, 1998/README.md, 2013/mills/README.md, faq.md, thanks-for-fixes.md, tmp/src/ioccc_status/ioccc_status.sh, todo.md
I gave example output of a program where not changing it caused 
confusing output, particularly in macOS, which is one of the strongest
reasons to make the change as it affects usability (in that it can make 
one wonder what to do albeit probably briefly so).
=> Update FAQ about gets() -> fgets() change

1984/decot/decot.c, 2014/skeggs/.gitignore, 2014/skeggs/Makefile, faq.md, thanks-for-fixes.md
It seems to me that it is a good idea to show people how to see what
changed in order to get an entry to work in modern systems. I gave an
example where it's harder to tell because it's a very long line and an
example where it's easier to tell as it's not long lines but rather
shorter lines. Well it's easier to see on a line-by-line basis ..
whether it's easy to see what actually changed is probably another
matter entirely (especially since it's easier to see when you have
compiler errors in front of you) :-)
=> Add to FAQ about seeing fix changes

1991/fine/README.md, author/Thomas_A_Fine.json
Undo rot13 and fix formatting.
Added mastodon handle. This was done in the author/Thomas_A_Fine.json file too.
=> Update 1991/fine/README.md + add mastodon handle

1984/decot/decot.c, 1986/wall/Makefile, 1986/wall/README.md, 1987/hines/README.md, 1987/korn/README.md, 1987/lievaart/README.md, 1987/lievaart/lievaart.c, 1987/lievaart/lievaart2.c, 1987/wall/README.md, 1987/westley/Makefile, 1987/westley/README.md, 1987/westley/westley.c, 1988/applin/Makefile, 1988/applin/README.md, 1988/dale/README.md, 1988/isaak/README.md, 1988/litmaath/README.md, 1988/phillipps/README.md, 1988/phillipps/phillipps.c, 1988/reddy/README.md, 1988/robison/README.md, 1988/spinellis/README.md, 1988/westley/README.md, 1988/westley/demo.sh, 1991/fine/Makefile, 1991/fine/demo.sh, thanks-for-fixes.md
The return in main() to pain() can be negated just like main() did to 
itself (and now pain() does). Now the program exits with 0.
=> Improve my fix to 1988/phillipps

1987/hines/README.md, 1987/korn/README.md, 1987/lievaart/README.md, 1987/lievaart/lievaart.c, 1987/lievaart/lievaart2.c, 1987/wall/README.md, 1987/westley/Makefile, 1987/westley/README.md, 1987/westley/westley.c, 1991/fine/Makefile, 1991/fine/demo.sh, thanks-for-fixes.md
This should shorten it a bit and yet still provide the same information
(or actually more :-) ) as before.
There was slight formatting changes in the file as well, both at the top
and lower down.
=> Reword top of thanks file

1984/decot/decot.c, 1986/wall/Makefile, 1986/wall/README.md, 1987/hines/README.md, 1987/korn/README.md, 1987/lievaart/README.md, 1987/lievaart/lievaart.c, 1987/lievaart/lievaart2.c, 1987/wall/README.md, 1987/westley/Makefile, 1987/westley/README.md, 1987/westley/westley.c, 1988/dale/README.md, 1988/isaak/README.md, 1991/fine/Makefile, 1991/fine/demo.sh, thanks-for-fixes.md
Added a section with historical notes about the entry (that is I added
the section heading and put the respective text, some of which I
previously added, under it).
This file should be in good order except perhaps a pending issue of
formatting the alternate code/to build/try sections.
=> Format/typo check 1988/isaak/README.md

1984/decot/decot.c, 1986/wall/Makefile, 1986/wall/README.md, 1987/hines/README.md, 1987/korn/README.md, 1987/lievaart/README.md, 1987/lievaart/lievaart.c, 1987/lievaart/lievaart2.c, 1987/wall/README.md, 1987/westley/Makefile, 1987/westley/README.md, 1987/westley/westley.c, 1988/applin/Makefile, 1988/applin/README.md, 1988/dale/README.md, 1988/isaak/README.md, 1988/litmaath/README.md, 1988/phillipps/README.md, 1988/phillipps/phillipps.c, 1988/reddy/README.md, 1988/robison/README.md, 1988/spinellis/README.md, 1988/westley/README.md, 1988/westley/demo.sh, 1991/fine/Makefile, 1991/fine/demo.sh, thanks-for-fixes.md
I have clarified that the reason I fixed the segfault in macOS is 
because without it the entry did not work.
=> Clarify fix for 1989/paul

2014/endoh1/Makefile
I forgot to update the DATA variable when I renamed read_me.md to spoilers.md.
=> Fix 2014/endoh1/Makefile

1987/lievaart/lievaart.c, 1987/lievaart/lievaart2.c, 1989/ovdluhe/Makefile, 1989/ovdluhe/README.md, 1989/ovdluhe/ovdluhe.alt.c, 1989/ovdluhe/ovdluhe.c, bugs.md, faq.md, thanks-for-fixes.md
I have provided some examples as well and included how to use other diff
programs like colordiff. Checking formatting (including how it looks on
GitHub) and typo checks notwithstanding this entry is in good condition.
=> Update FAQ about make diff rules

1987/lievaart/lievaart.c, 1987/lievaart/lievaart2.c, 1989/ovdluhe/Makefile, 1989/ovdluhe/README.md, 1989/ovdluhe/ovdluhe.alt.c, 1989/ovdluhe/ovdluhe.c, 1990/baruch/README.md, author/Diomidis_Spinellis.json, bugs.md, faq.md, thanks-for-fixes.md
The mastodon handle that was listed is for his Greek/Greece one and not
the technical one. It seems for the IOCCC it would be better to have the
tech one.
Also added his GitHub handle.
=> Update json file for Diomidis Spinellis

1987/lievaart/Makefile, 1987/lievaart/lievaart.c, 1987/lievaart/lievaart2.c, 1989/jar.1/Makefile, 1989/jar.1/README.md, 1989/jar.1/jar.1.alt.sh, 1989/jar.1/jar.1.sh, thanks-for-fixes.md, todo.md
This is done so that I can provide another thing I forgot to mention in the previous log. I fixed the scripts to not have the ill-famed useless use of cat. Why is it ill-famed?
Because there's no such thing as a useless cat, that's why! In fact the fact they exist proves that the Earth is NOT flat: if it was flat they would have knocked everything off it by now! :-) Besides, they offer all us ailurophiles hours and hours and years and years of joy and fun and companionship. And contrary to popular belief, they most certainly do have a personality and they can be very sociable.
=> Minor update to 1989/jar.1/README.md

thanks-for-fixes.md, todo.md
Added an entry that was missing that both Yusuke and I suggested a fix
(used Yusuke's idea but both -ansi and -trigraphs would work fine).
Minor corrections in a couple other entries.
=> Minor fixes/update in thanks-for-fixes.md

1990/cmills/README.md, 1990/scjones/README.md
.. i.e. remove it from the README.md file, this time of Yusuke Endoh
(not his fault at all but rather a problem that occurred before the
superior idea of a single file was thought up).
I had already format fixed this file and the only other thing I did was
remove the address (but this is not strictly necessary as the author 
information will eventually be generated from the JSON files).
=> Correct thanks in 1990/scjones

1984/laman/README.md, 1993/plummer/README.md, bugs.md
To make sure that this looks okay before doing it for the rest of the 
entries I am doing this test commit to make sure the link works okay and
the format looks okay. If any problems are found (which I expect) they 
will be corrected and once things look okay the rest of the files will 
be done as well.
=> Test new concept of (mis)features/bugs in README

faq.md
I also fixed some other issues in the FAQ some to do with the entry differences (from alt, orig and current) and some other things as well.
=> Update FAQ about make diff_ rules + other fixes

1984/decot/README.md, 1984/mullender/.gitignore, 1984/mullender/Makefile, 1984/mullender/README.md, 1984/mullender/gentab.c, 1984/mullender/mullender.alt.c, 1984/mullender/mullender.alt2.c, 2020/endoh3/run_clock.sh, bugs.md, faq.md, thanks-for-fixes.md, tmp/awards_check.sh, tmp/check_path_list.sh, tmp/fix_manifest_csv.sh, tmp/gen_path_list.found.sh
Typo fixes and slight rewording.
=> Update alt code details in 1984/decot

1984/decot/README.md, 1984/mullender/.gitignore, 1984/mullender/Makefile, 1984/mullender/README.md, 1984/mullender/gentab.c, 1984/mullender/mullender.alt.c, 1984/mullender/mullender.alt2.c, 1985/lycklama/README.md, 1985/sicherman/Makefile, 1985/sicherman/README.md, 1985/sicherman/sicherman.c, 2020/endoh3/run_clock.sh, bugs.md, faq.md, thanks-for-fixes.md, tmp/awards_check.sh, tmp/check_path_list.sh, tmp/fix_manifest_csv.sh, tmp/gen_path_list.found.sh
As the GitHub bold is rather close in colour to regular text (at least
in my admittedly poor vision) I have made the thanks, the complicated
and technically challenging stand out more by making them all upper
case.
I also made the wording (of thanks to me) closer to that of Yusuke but 
changing in his 'VERY' to 'EXTREMELY': better to have it consistent and
some were quite challenging.
For entries listed under my name at the top I did not add the word 
technically as I think that that's implied.
=> Make thanks/complicated/etc. stand out in thanks

1984/laman/README.md, 1984/laman/laman.c, 1992/buzzard.1/README.md, 1992/buzzard.1/buzzard.1.c, 1992/gson/README.md, 1992/westley/westley.alt.c, 1992/westley/westley.c, 1993/plummer/README.md, 1993/plummer/plummer.alt.c, 1993/plummer/plummer.c, 1994/horton/Makefile, 1994/horton/README.md, 1994/horton/horton.c, 2001/cheong/README.md, 2001/cheong/cheong.c, 2001/ollinger/ollinger.c, 2001/schweikh/README.md, 2001/schweikh/schweikh.c, 2006/stewart/README.md, 2006/stewart/stewart.c, bugs.md, thanks-for-fixes.md
Added to the INABIAF that not only is there a way to cheat which was 
documented at the time and which I discovered when fixing the code but 
there is actually a way that I discovered recently where you can cheat 
but it still actually wins! Does that mean it is cheating as well? :-) 
Or is it that one cannot actually cheat a cheater? :-) Either way this
felt like a good thing to add to the bugs.md as well.
=> Update 1991/westley in bugs.md

1984/laman/README.md, 1984/laman/laman.c, 2001/schweikh/README.md, 2001/schweikh/schweikh.c, 2006/stewart/README.md, 2006/stewart/stewart.c, bugs.md, thanks-for-fixes.md
This was not documented. The limitations have not been addressed as they
were documented. The bugs.md and README.md have been updated for this.
=> Fix 2001/schweikh - check args

1996/august/README.md, bugs.md, thanks-for-fixes.md
=> Explain the magic behind 1989/westley in bugs

1992/westley/README.md, 2006/hamre/README.md, 2006/hamre/hamre.c, bugs.md
After it was suggested this be fixed I went ahead and did it. I kept the
format almost the same by careful placement and line ending.
=> Add arg check to 2006/hamre

2005/giljade/.gitignore, 2005/giljade/README.md, bugs.md, thanks-for-fixes.md
Remove duplicate INABIAF from README.md file.
=> Minor fixes in 2005/giljade

2005/anon/README.md, bugs.md
The things that were changed to bug status the other day are features 
and in fact they provide for some fun interaction too.
=> Change back bug status of 2005/anon

thanks-for-fixes.md
I've declared myself the IOCCC's resident corrections officer and according to Landon I'm a fine one at that.
I also elaborated on the reason for fgets() change but also added a note that in some cases it's not possible or ideal and in some cases it's not easy especially due to the annoying fact that for 'compatibility' reasons fgets() retains the newline and gets() does not.
=> Minor update to thanks file

1984/anonymous/README.md, 1984/anonymous/anonymous.c, 1984/mullender/README.md, 1994/schnitzi/.gitignore, 1994/schnitzi/Makefile, 1994/schnitzi/README.md, 1994/schnitzi/schnitzi.alt2.c, 1998/schnitzi/Makefile, 1998/schnitzi/README.md, 1998/schnitzi/schnitzi.c, 1998/schnitzi/try.sh, bugs.md, faq.md, thanks-for-fixes.md, todo.md
Minor corrections in the README.md and bugs.md.
The README.md was not checked for other issues at this time. When that 
happens 1984 should be complete in every way except that 1984/README.md
has to be checked again but that will happen after the other entries of 
all the other years are done.
=> Minor updates to 1984/mullender

1990/baruch/README.md, 1990/dds/README.md, 1990/pjr/.gitignore, 1990/pjr/Makefile, 1990/pjr/README.md, 1990/pjr/pjr.alt.c, 1990/stig/README.md, 1990/tbr/README.md, 1991/dds/README.md, 1998/schweikh3/.gitignore, 1998/schweikh3/Makefile, 1998/schweikh3/README.md, 1998/schweikh3/try.sh, bugs.md, thanks-for-fixes.md, tmp/format-headers.sh
Properly document the fact that there is alt code. This involved a note
about the fixes in 2023 as the alt code had to have fixes applied too
and it was referred to in the description of it (that was not referred
to as alt code).
I have not yet checked the README.md file for formatting or typo issues.
=> Updates to 1990/tbr - alt code

1990/baruch/README.md, 1990/dds/README.md, 1998/schweikh3/.gitignore, 1998/schweikh3/Makefile, 1998/schweikh3/README.md, 1998/schweikh3/try.sh, bugs.md, thanks-for-fixes.md, tmp/format-headers.sh
=> Fix order of two entries in thanks file

1990/jaw/Makefile, 1990/jaw/README.md, 1990/jaw/btoa, 1990/jaw/shark.sh, 1990/tbr/README.md, 1990/theorem/README.md, 1990/westley/README.md, bugs.md, thanks-for-fixes.md
I believe that this completes 1990.
=> Typo/format check 1990/theorem/README.md

1990/jaw/Makefile, 1990/jaw/README.md, 1990/jaw/btoa, 1990/jaw/shark.sh, 1990/tbr/README.md, 1990/theorem/README.md, 1990/westley/README.md, 1991/fine/README.md, 1991/fine/try.sh, 2020/tsoj/.gitignore, 2020/tsoj/Makefile, 2020/tsoj/README.md, 2020/tsoj/prog.alt.c, bugs.md, thanks-for-fixes.md
I updated the try.sh with a new string that I discovered that is for fun
output especially given something the judges say in the guidelines.
Also since some of the strings are from Brian Westley's entry from 1989
and another one was credited to him I briefly referred to the entry as 
well.
=> Minor updates to 1991/fine

1991/ant/README.md, 1991/cdupont/README.md, 1991/fine/try.sh, 1996/jonth/README.md, bugs.md, index.html, thanks-for-fixes.md, tmp/README.md, tmp/run_all.sh
Also since it has been requested that the award + author information be
removed from the README.md files this has been done here as these 
changes were already done but not committed. Once the remaining (not 
counting this one) five other README.md files have been committed there
will be a mass edit.
=> Minor fixes in 1991/cdupont/README.md

1992/adrian/Makefile, 1992/adrian/README.md, 1992/adrian/adrian.c, 1992/albert/README.md, 1992/westley/Makefile, 1992/westley/README.md, 1992/westley/try.sh, 1992/westley/westley.alt.orig.c, 1992/westley/whereami.alt.c, 1992/westley/whereami.c, bugs.md, thanks-for-fixes.md
There is a known bug in the code that is triggered by some inputs. I
have included some debugging information for those who wish to try and
solve it.
The README.md has been typo/format checked.
This should complete 1992/albert except for hopefully the bug being
resolved in the future.
=> Format/typo check 1992/albert + update bugs.md

1992/nathan/.gitignore, 1992/nathan/README.md, 1992/nathan/try.sh, 1992/vern/README.md, bugs.md, thanks-for-fixes.md
The bugs.md has both a feature and a bug or maybe mis-feature that might
be good to fix. I gave a tip in the bugs.md that might help with parsing
the code a bit.
The README.md file has been typo and format checked/fixed.
This should complete 1992.
=> Format/typo check + update bugs.md for 1992/vern

1993/ejb/README.md, 1993/ejb/patience.md, 1993/jonth/README.md, 1993/leo/Makefile, 1993/leo/README.md, 1993/lmfjyh/README.md
This includes updates to the patience.md file. The hanoi.md did not
require any changes.
=> Format/typo check 1993/ejb

1994/horton/Makefile, 1994/horton/README.md, 1994/imc/README.md, 1994/schnitzi/README.md, 1994/shapiro/README.md, 1994/shapiro/shapiro.md, 1994/smr/README.md, faq.md, thanks-for-fixes.md
... not that there is much to document :-)
=> Format/typo checks in 1994/smr/README.md

1994/horton/Makefile, 1994/horton/README.md, 1994/imc/README.md, 1994/schnitzi/README.md, 1994/shapiro/README.md, 1994/shapiro/shapiro.md, 1994/smr/README.md, 1994/tvr/Makefile, 1994/tvr/README.md, 1994/tvr/tvr.c, 1994/weisberg/Makefile, 1994/weisberg/README.md, bugs.md, faq.md, thanks-for-fixes.md
Added -Wno-implicit-int to Makefile.
=> Format/typo check 1994/weisberg + update Makefile

1995/dodsond1/README.md, 1995/dodsond1/try.sh, 1995/garry/README.md, 1995/garry/garry.alt.test.sh, 1995/heathbar/README.md, thanks-for-fixes.md
Format fixes in README.md.
Add missing garry.alt.test.sh script I supposedly added a while back.
=> Minor fixes in 1995/garry

1996/gandalf/Makefile, 1996/gandalf/README.md, 1996/gandalf/try.sh, thanks-for-fixes.md
The script is rather elaborate in that it runs the programs in the different ways the judges previously suggested as well as some additional runs and shows the difference (or if no difference says they are identical) of the different commands, using temporary files that are deleted if the script is sent (some) signals, the script is quit (when prompted to press a key pressing 'q' will quit the script) or if the script runs to completion.
The README.md file was format/typo checked.
BTW: it is absolutely perilous to try the patience of [Gandalf](https://www.glyphweb.com/arda/g/gandalf.html). Go ahead, try it! :-)
The Makefile has had -Wno-implicit-int added to CSILENCE.
=> Add 1996/gandalf/try.sh and format README.md

1991/ant/ant.alt.c, 1992/kivinen/.gitignore, 1992/kivinen/Makefile, 1992/kivinen/README.md, 1992/kivinen/kivinen.alt.c, 1998/schweikh3/Makefile, 1998/schweikh3/README.md, 1998/schweikh3/schweikh3.c, 1998/schweikh3/try.sh, 1998/tomtorfs/README.md, 1998/tomtorfs/tomtorfs.c, 1998/tomtorfs/try.sh, 2006/toledo2/toledo2.alt.c, bugs.md, faq.md, thanks-for-fixes.md
The constant that was in the code was changed to a macro in the Makefile
called SZ. Though it's highly unlikely that this will ever be needed the
author noted that increasing the value has some merit in a rare case so
it's now easier to do this (though one might have to type more,
admittedly, as all the -D options have to be specified but it no longer
is required to modify the code).
The README.md file has been format and typo checked. I did change the 
way the man page was displayed (in the README.md) so this has to be 
verified to look good but everything else should be good anyway.
The try.sh script I added was updated to have another command that was 
in the judges' remarks. Instead it's now all in the try section and the
judges' remarks just have the comments, not the command to try. …
=> Fixes and other updates to 1998/schweikh3

1998/dorssel/README.md, 1998/dorssel/dorssel.md, 1998/dorssel/try.sh, thanks-for-fixes.md
Added try.sh script with some additions beyond what the judges suggested, making it a bit more fun.
Format and typo checked README.md file as well as the dorssel.md file.
=> Updates to 1998/dorssel

faq.md
Only the first two sections have had a change so that we can see it side
by side to see what looks better.
=> Test change in format of FAQ table of contents

1989/jar.2/Makefile, 1989/jar.2/try.sh, 1989/westley/Makefile, 1989/westley/compile.sh, 1989/westley/try.sh
Allow CC to be set and used for compilation.
=> Improve 1989/jar.2/try.sh

1995/dodsond1/try.sh, 1995/esde/try.sh, 1996/august/try.sh, 1996/gandalf/try.sh, 1996/schweikh2/try.sh, 1996/westley/try.alt.sh, 1996/westley/try.sh, 1998/bas2/try.sh, 1998/dorssel/try.sh, 1998/fanf/try.sh, 1998/schnitzi/try.sh, 1998/schweikh3/try.sh, 1998/tomtorfs/try.sh, 2000/tomx/try.alt.sh, 2000/tomx/try.sh, 2001/anonymous/try.sh, 2011/akari/try.sh, 2011/dlowe/try.sh, 2012/kang/de.alt.sh, 2012/kang/de.sh, 2012/kang/en.alt.sh, 2012/kang/en.sh, 2012/kang/try.sh, 2013/birken/try.sh
Gets CC, defaults to cc.
For some other scripts there were improvements specific to those scripts.
=> Improve many of the try and related scripts

2013/birken/Makefile, 2013/birken/README.md, 2013/birken/birken.alt.c, 2013/birken/birken.c, 2013/birken/try.sh, 2013/misaka/try.sh, thanks-for-fixes.md
=> Improve 2013/misaka/try.sh

1996/huffman/try.sh, 2000/schneiderwent/README.md
Get CC, defaulting to cc.
```
So, that's to end the story for you and me
If you still give a listen, you just may
Hear a big wolf-man or little piggy say
Little pig, little pig, let me in
Not by the hair of my chinny, chin, chin
Little pig, little pig, let me in
Not by the hair of my chinny, chin, chin
Well, I'm huffin', I'm puffin', I'll blow your house in
Huffin', puffin', blow your house in
Huffin', puffin', blow your house in
Huffin' and a puffin' and I'll blow your house in!
And the moral of the story is
band with no talent can easily amuse
Idiots with a stupid, puppet show
```
:-)
=> Improve 1996/huffman/try.sh

2001/jason/README.md, 2001/ollinger/README.md, thanks-for-fixes.md
The bug status in the README.md was also incorrect.
=> Fixes in 2001/ollinger

2001/anonymous/Makefile, 2001/anonymous/README.md, 2001/ctk/Makefile, 2001/ctk/README.md, 2001/ctk/ctk.c, 2001/jason/README.md, 2001/ollinger/README.md, 2001/schweikh/README.md, 2001/schweikh/try.sh, thanks-for-fixes.md
README.md file format/typo checked.
Updated warnings in Makefile as well.
I believe this completes the review of 2001/anonymous.
=> Format/typo check 2001/anonymous

1985/sicherman/sicherman.c, 2001/coupard/Makefile, 2001/coupard/README.md, 2001/coupard/coupard.c, thanks-for-fixes.md
The subr() function can now be called.
=> Further improve fix to 1985/sicherman

2004/gavin/README.md, 2004/gavin/gavin.md, 2004/jdalbec/.gitignore, 2004/jdalbec/Makefile, 2004/jdalbec/README.md, 2004/jdalbec/jdalbec.alt.c, 2004/jdalbec/try.alt.sh, 2004/jdalbec/try.sh, bugs.md, thanks-for-fixes.md
There are also documented features that are now in bugs.md as features,
not bugs, but just linking back to the section provided by the author.
The README.md file has been format and typo checked.
The gavin.md file has been format and typo checked.
=> Update bugs of 2004/gavin + format/typo checks

2005/timwi/README.md, 2005/timwi/try.sh, 2005/toledo/README.md, 2005/vik/README.md, thanks-for-fixes.md
It only has one command. This is because I don't want to knacker my 
brain and I don't want to damage anyone else's brain either.
=> Add 2005/timwi/try.sh + format/typo checks

2000/natori/README.md, 2000/natori/try.sh, thanks-for-fixes.md
This script will show the current phase of White Face ('Moon' :-) ) in artistic ways. Rather than write the different ways here I would suggest one just try it out.
=> Add 2000/natori/try.sh

2006/borsanyi/README.md, 2006/sykes2/README.md, 2006/sykes2/sykes2.sh, 2006/sykes2/try.sh, 2006/toledo1/README.md, bugs.md, thanks-for-fixes.md
The bug status is it's not a bug but a feature.
=> Update bug status / format/typo 2006/borsanyi

1991/cdupont/.gitignore, 1991/cdupont/Makefile, 1991/cdupont/README.md, 1991/cdupont/cdupont.alt.c, 1991/cdupont/cdupont.alt2.c, 1991/cdupont/cdupont.alt3.c, thanks-for-fixes.md
.. in the thanks file that is.
=> Link to alt code in README.md of 1991/rince

1991/cdupont/.gitignore, 1991/cdupont/Makefile, 1991/cdupont/README.md, 1991/cdupont/cdupont.alt.c, 1991/cdupont/cdupont.alt2.c, 1991/cdupont/cdupont.alt3.c, 1992/kivinen/Makefile, 1992/kivinen/kivinen.alt.c, 1992/kivinen/kivinen.c, thanks-for-fixes.md
=> Make 1992/kivinen main() have 2 args, not 1

1991/cdupont/.gitignore, 1991/cdupont/Makefile, 1991/cdupont/README.md, 1991/cdupont/cdupont.alt.c, 1991/cdupont/cdupont.alt2.c, 1991/cdupont/cdupont.alt3.c, 1992/kivinen/Makefile, 1992/kivinen/kivinen.alt.c, 1992/kivinen/kivinen.c, 1992/marangon/Makefile, 1992/marangon/marangon.c, 1994/weisberg/Makefile, 1994/weisberg/README.md, 1995/cdua/cdua.alt.c, 1995/cdua/cdua.c, thanks-for-fixes.md
=> Add second arg to main in 1995/cdua

2012/blakely/README.md, 2012/blakely/try.sh, 2012/omoikane/.gitignore, 2012/omoikane/Makefile, 2012/omoikane/README.md, 2012/omoikane/nyaruko.alt.c, 2012/omoikane/nyaruko.alt2.c, 2012/omoikane/try.alt.sh, 2012/omoikane/try.sh, bugs.md, news.html, thanks-for-fixes.md
The bugs.md was also updated with a INABIAF section.
=> Format/typo check + add try.sh to 2012/blakely

2013/morgan1/README.md
I also included the dates for the two unnamed undated comets that the author referred to so that one can see what is meant: Comet Halley and Comet Hale-Bopp, labelled Ha and Hb in the program which is now noted in the README.md file too.
=> Format/typo check 2013/morgan1

2015/hou/README.md, 2015/hou/rfc1321.txt, thanks-for-fixes.md
The README.md file now links to the downloaded copy. This entry is not done but I needed the change to the README.md out of the way for a commit I plan on that will be a mass edit to README.md files.
=> Add 2015/hou/rfc1321.txt

1985/lycklama/Makefile, 1985/lycklama/README.md, 2015/hou/README.md, 2015/hou/rfc1321.txt, 2015/howe/spoiler/err.h, 2015/muth/machine_beaver_4_2.h, 2015/muth/machine_champ_2_4.h, 2015/muth/machine_chaos_5_2.h, 2015/muth/machine_cmplx_5_2.h, 2015/muth/machine_count_5_2.h, 2015/muth/machine_great_3_2.h, 2015/muth/machine_ru_2_4.h, thanks-for-fixes.md
With Makefile variables one can just do for instance:
make SLEEP=700 clobber alt
which will set the macro Z to 700.
=> Improve how to define sleep time in 1985/lycklama

thanks-for-help.md
There was a line that was duplicated and more importantly than that some entries that had been added yesterday before the merge conflicts were resolved.
I believe this should complete the merge conflicts resolution and I believe I got the '/' in front of the paths in all the right places. The anchors (as in html <a ..>) should be in place as well.
=> Further fixes to thanks file

2000/dhyang/README.md, 2000/dhyang/try.sh
The script dumped text too fast as there are numerous commands with long output. The script now prompts with 'read'.
Minor fix in README.md file.
=> Minor improvements to 2000/dhyang/try.sh

1994/shapiro/.gitignore, 1994/shapiro/Makefile, 1994/shapiro/README.md, 2000/dhyang/README.md, 2000/dhyang/try.sh, bugs.md
Added -Wno-implicit-int to Makefile.
The .gitignore file was also updated.
=> Update bugs for 1994/shapiro

1994/shapiro/.gitignore, 1994/shapiro/Makefile, 1994/shapiro/README.md, 2000/dhyang/README.md, 2000/dhyang/try.sh, 2018/vokes/README.md, 2018/vokes/try.sh, bugs.md, thanks-for-help.md
The bugs.md file was also updated with INABIAF status.
=> Add 2018/vokes/try.sh + format/typo checks

faq.md
Three different image utility packages have been described for macOS (MacPorts and Homebrew) and Red Hat Linux. I don't have any other linux so I can't explain how to do those with certainty (except for copy/paste somewhere which might or might not be correct).
=> Update FAQ about different image tools

2014/birken/Makefile, 2014/birken/README.md, 2018/poikola/README.md, 2018/poikola/try.sh, thanks-for-help.md
Now one can do
make clobber PORT=31337 TIME=50000 alt
or whatever.
=> Simplify how to redefine macros in 2014/birken

2018/poikola/README.md, 2018/poikola/try.sh, thanks-for-help.md
I believe this completes the review of the entry.
=> Add 2018/poikola/try.sh + format/typo checks

2013/birken/Makefile, 2013/birken/README.md, 2014/birken/Makefile, 2014/birken/README.md, 2018/poikola/README.md, 2018/poikola/try.sh, thanks-for-help.md
Now one can just do
make clobber SLEEP=500 alt
or whatever.
=> Improve how to redefine sleep in 2013/birken alt

2018/algmyr/README.md, 2018/algmyr/try.sh, bugs.md, thanks-for-help.md
Add 2018/algmyr/try.sh + format/typo checks
This entry was also expanded some in bugs.md.
=> Add 2018/algmyr/try.sh + format/typo checks

2019/diels-grabsch2/try.sh, faq.md
Before doing 'diff -s sha512sum.txt prog.txt' it does a cat on both 
files (in one command) so that one can see what is being compared 
(or to verify what is being compared).
=> Improve 2019/diels-grabsch/try.sh

2019/diels-grabsch2/try.sh, faq.md
... and what one should do, of course. This includes an example of an 
invalid link (albeit an extreme one :-) ) that I fixed quite some time 
back (months ago) just to give an idea. But it's more useful to check 
for dead links in the IOCCC website itself (linking to pages/files in 
the website that is). Of course I'll be doing that once the README.md 
files are in order but there's a high chance I won't be able to find 
them all esp as after the website is done I have more to do.
=> Add FAQ about dead and invalid links

thanks-for-help.md
Also I changed (in the honour roll) 'Cody' to 'Cody Boone Ferguson' and 'Yusuke' to 'Yusuke Endoh'.
=> Minor typo fix in thanks file

faq.md
Let's just say that these minor issues have also gone up in smoke.
=> Minor fixes in FAQ

2020/carlini/README.md, 2020/carlini/try.sh, bugs.md, thanks-for-help.md
Why a try.sh for this? It shows that you can also automate the play (it happens to come from the author's remarks, however, so there's that too). Then it tells you to be serious by playing with a friend, either real or imagined, rather than doing something so silly.
Update bugs.md with a INABIAF section.
=> Add 2020/carlini/try.sh, update bugs.md

2019/giles/README.md, 2020/endoh1/README.md, 2020/endoh2/README.md, 2020/endoh2/try.sh, 2020/endoh3/README.md, thanks-for-help.md
The program play comes from SoX but this was not noted by accident.
=> Add note about SoX in 2019/giles

thanks-for-help.md
For 2020/ferguson1 it was listed as ferguson2.
=> Typo fix in thanks file - wrong directory

2020/kurdyukov2/README.md, 2020/kurdyukov2/makegif.sh, 2020/kurdyukov2/try.sh, thanks-for-help.md
Also made a minor change to makegif.sh to use $0 instead of literal 'makegif.sh' in usage string.
=> Add 2020/kurdyukov2/try.sh + format/typo checks

tmp/things-todo.md
Some (or at least one?) was removed because there is another item that where these things will be done together.
=> Remove a number of items from the todo file

tmp/gen_author_json.sh, tmp/gen_path_list.found.sh, tmp/gen_winner_json.sh, tmp/run_all.sh
There are certainly more including some I encountered yesterday that are not fixed but these can be fixed later on. These are just quick (and incomplete) looks at some of the scripts.
=> Typo fixes in scripts in tmp/

Makefile, thanks-for-help.md
It had a stray 'fi;' in it without an 'if'.
=> Fix top level Makefile 'all' rule

bugs.md
=> Add 2024 to bugs.md

2020/ferguson1/.gitignore, 2020/ferguson1/Makefile
The DATA variable still had html files which I removed a while back. This made make fail.
Also there is a joke Easter egg that I added: something to do with eating as that's also kind of the point of the entry: though eating insects (or bugs for a joke I made originally, so that it can say there are bugs that are not bugs). Snakes are carnivores: they don't eat apples and although insects are not going to be filling enough they can eat them. But what the joke is one has to discover for themselves!
=> Fix 2020/ferguson1/Makefile

1987/biggar/README.md, 1987/biggar/try.sh, 1987/heckbert/README.md, 1987/heckbert/try.sh, thanks-for-help.md
The script runs a variety of commands to show how it can fold files
(mostly itself) into different column lengths but it also shows how that
folded code can recreate the original (uses diff -s).
It also asks a question that was in the try section as well.
=> Add 1987/heckbert/try.sh

1987/biggar/README.md, 1987/biggar/try.sh, 1987/heckbert/README.md, 1987/heckbert/try.sh, 1987/hines/.gitignore, 1987/hines/README.md, 1987/hines/goto.c, 1987/hines/goto.txt, 1987/hines/try.sh, 1987/wall/README.md, 1987/wall/try.sh, thanks-for-help.md
This script automates through a pipeline some of the input suggested in
the README.md. The README.md still has some of what try.sh has because
it shows that you can do it entering line by line.
=> Add 1987/wall/try.sh

1985/sicherman/try.alt.sh, 1985/sicherman/try.sh, 1987/biggar/README.md, 1987/biggar/try.sh, 1987/heckbert/README.md, 1987/heckbert/try.sh, 1987/hines/.gitignore, 1987/hines/README.md, 1987/hines/goto.c, 1987/hines/goto.txt, 1987/hines/try.sh, 1987/wall/README.md, 1987/wall/try.sh, thanks-for-help.md
It suggests the user figure out any differences in the last command 
(this was previously done in the README.md file).
=> Minor update to 1985/sicherman/try scripts

bugs.md
Not sure how it was undone. But I'm sending it again, also corrected a small header error. Notes on the pull are in #1835
=> Removed again 1992/adrian bug. Correction in header in Bugs.md

1989/jar.1/README.md, 1989/jar.2/README.md, 1989/jar.2/try.sh, 1989/ovdluhe/README.md, 1989/robison/README.md, 1989/robison/try.sh, bugs.md, thanks-for-help.md
Also updated bugs.md with another case where the program might 'break 
into tiny bits' but as a feature not a bug. Checking the source code
will give all you need to know about the 'problem' quite well.
=> Add 1989/robison/try.sh

1989/jar.1/README.md, 1989/jar.2/README.md, 1989/jar.2/try.sh, 1989/ovdluhe/README.md, 1989/robison/README.md, 1989/robison/try.sh, 1989/vanb/try.sh, 1990/baruch/README.md, 1990/baruch/try.sh, 1990/dg/README.md, 1990/dg/try.sh, bugs.md, thanks-for-help.md
It runs the program with a couple strings and then it feeds the source 
code to the program (piped to less) as well (after showing the source 
code with less).
=> Add 1990/dg/try.sh

1989/jar.1/README.md, 1989/jar.2/README.md, 1989/jar.2/try.sh, 1989/ovdluhe/README.md, 1989/robison/README.md, 1989/robison/try.sh, 1989/vanb/try.sh, 1990/baruch/README.md, 1990/baruch/try.sh, 1990/dg/README.md, 1990/dg/try.sh, 1990/jaw/try.sh, 1990/scjones/.gitignore, 1990/scjones/README.md, 1990/scjones/try.sh, bugs.md, thanks-for-help.md
The script allows one to more easily see (and verify) what the entry
does. This involves a temporary file that is created (and removed at the
end of the script but which has also been added to .gitignore).
=> Add 1990/scjones/try.sh

1989/jar.1/README.md, 1989/jar.2/README.md, 1989/jar.2/try.sh, 1989/ovdluhe/README.md, 1989/robison/README.md, 1989/robison/try.sh, 1989/vanb/try.sh, 1990/baruch/README.md, 1990/baruch/try.sh, 1990/dg/README.md, 1990/dg/try.sh, 1990/jaw/try.sh, 1990/scjones/.gitignore, 1990/scjones/README.md, 1990/scjones/try.sh, 1990/tbr/README.md, 1990/theorem/Makefile, 1990/theorem/README.md, 1990/theorem/try.sh, bugs.md, thanks-for-help.md
This script shows not just theorem but the sorter and the Fibonacci
generator as well. For the sorter it reverses output of ls (redirected
to a file) and then shows how using sorter on it results in the same
output of ls (with no options specified). Of course if different ls
sorts output differently this could fail but I did not think of that 
until after I wrote it.
=> Add 1990/theorem/try.sh

1990/baruch/README.md, 1990/baruch/try.sh, bugs.md
A feature is that as the number specified gets bigger so too does the runtime, the amount of resources and the number of lines of output.
The script has another example command (that isn't too long but is a number of pages of less(1) output).
=> Add 1990/baruch to bugs.md, update try.sh

1990/baruch/README.md, 1990/baruch/try.sh, 1991/brnstnd/README.md, 1991/brnstnd/try.sh, 1991/brnstnd/try.txt, 1991/fine/try.sh, bugs.md, thanks-for-help.md
I'll now suggest that now it's 'quite fine' :-)
=> Improve 1991/fine/try.sh

1990/baruch/README.md, 1990/baruch/try.sh, 1991/brnstnd/README.md, 1991/brnstnd/try.sh, 1991/brnstnd/try.txt, 1991/fine/try.sh, 1992/lush/README.md, 1992/lush/lush.sh, 1992/lush/runme.sh, 1992/nathan/try.sh, bugs.md, thanks-for-help.md
The script now lets one specify which compiler to use so that one can
(in the case that their cc is clang, for instance like it is with macOS)
specify a path to a real gcc compiler.
=> Rename 1992/runme.sh lush.sh and improve it

1989/fubar/fubar.c, 1989/fubar/fubar.sh, 1992/adrian/.gitignore, 1992/adrian/README.md, 1992/adrian/try.sh, 1992/albert/README.md, 1992/albert/try.alt.sh, 1992/albert/try.sh, 1992/ant/README.md, 1992/ant/ant.test.mk, 1992/ant/try.sh, 1992/buzzard.2/.gitignore, 1992/buzzard.2/Makefile, 1992/buzzard.2/README.md, 1992/buzzard.2/buzzard.2.alt.c, 1992/buzzard.2/help.th, 1992/buzzard.2/try.alt.sh, 1992/buzzard.2/try.sh, 1993/ant/README.md, 1993/ant/ants.txt, 1993/ant/try.sh, 1993/dgibson/README.md, 1993/dgibson/dgibson.sh, 1993/dgibson/try.sh, 1993/ejb/README.md, 1993/ejb/try.sh, 1993/vanb/README.md, 1993/vanb/try.sh, thanks-for-help.md
The ants.txt file is something that kids throughout the English speaking
world are tortured with, some having been forced to repeat it many,
many, many, too many times, but which fits well here: a grep program 
called 'ant' should find lots of ants :-) (and it is a fun use .. or
maybe I just wish to subject others to the torture I was subjected to
decades ago? :-) )
=> Add 1993/ant/try.txt and ants.txt

1989/fubar/fubar.c, 1989/fubar/fubar.sh, 1992/ant/README.md, 1992/ant/ant.test.mk, 1992/ant/try.sh, 1992/buzzard.2/.gitignore, 1992/buzzard.2/Makefile, 1992/buzzard.2/README.md, 1992/buzzard.2/buzzard.2.alt.c, 1992/buzzard.2/help.th, 1992/buzzard.2/try.alt.sh, 1992/buzzard.2/try.sh, thanks-for-help.md
If you like ants there are now 1992 of them here to try out (whatever 
that means :-) ).
Some typos in the test Makefile were also fixed (just those that I saw
as the command was scrolling by - I didn't look at the whole file).
=> Add 1992/ant/try.sh

1985/august/primes.sh, 1985/august/try.sh, bin/README.md, bin/ioccc-status.sh
The output in a command had blank lines which is invalid input to 
primes.
=> Fix bug in 1985/august/primes.sh

1985/august/primes.sh
Allow one to specify compiler to use.
=> Minor adjustments to 1985/august/primes.sh

1994/schnitzi/.gitignore, 1994/schnitzi/Makefile, 1994/schnitzi/README.md, 1994/schnitzi/try.alt.sh, 1994/schnitzi/try.sh, 1994/schnitzi/try.txt, 1994/shapiro/README.md, 1994/tvr/README.md, 1994/tvr/try.alt.bw.sh, 1994/tvr/try.alt.color.sh, 1994/tvr/try.bw.sh, 1994/tvr/try.color.sh, thanks-for-help.md
This required an update to the .gitignore file.
=> Add alt scripts to 1994/schnitzi

1995/makarios/Makefile, 1995/makarios/makarios.c, 1996/rcm/.gitignore, 1996/rcm/README.md, 1996/rcm/try.sh, 1996/schweikh1/README.md, 1996/schweikh1/try.sh, 1996/schweikh2/README.md, 1996/schweikh2/try.sh, faq.md, thanks-for-help.md
The script was changed to run a certain command only once but the 
README.md file stated the old way of it running several times in a row.
I can't see the use of running it several times when we can just pipe it
through less to see the look. The author's suggested command, meanwhile,
is hard to see what is happening as it doesn't go slow enough and it 
floods the screen until one hits ctrl-c/sends intr.
=> Fix comment about 1996/schweikh2/try.sh

1995/makarios/Makefile, 1995/makarios/makarios.c, 1996/rcm/.gitignore, 1996/rcm/README.md, 1996/rcm/try.sh, 1996/schweikh1/README.md, 1996/schweikh1/try.sh, 1996/schweikh2/README.md, 1996/schweikh2/try.sh, 1996/schweikh3/Makefile, 1996/schweikh3/README.md, 1996/westley/try.alt.sh, 1996/westley/try.sh, 1998/banks/README.md, 1998/bas2/README.md, 1998/bas2/try.sh, 1998/chaos/README.md, 1998/chaos/try.sh, faq.md, thanks-for-help.md
The script runs the program on each data file, explaining how to use the 
program, things to try and how to quit the program and how to terminate
the script prematurely.
=> Add 1998/chaos/try.sh

1995/makarios/Makefile, 1995/makarios/makarios.c, 1996/rcm/.gitignore, 1996/rcm/README.md, 1996/rcm/try.sh, 1996/schweikh1/README.md, 1996/schweikh1/try.sh, 1996/schweikh2/README.md, 1996/schweikh2/try.sh, 1996/schweikh3/Makefile, 1996/schweikh3/README.md, 1996/westley/try.alt.sh, 1996/westley/try.sh, 1998/banks/README.md, 1998/bas2/README.md, 1998/bas2/try.sh, 1998/chaos/README.md, 1998/chaos/try.sh, 1998/df/README.md, 1998/df/try.sh, faq.md, thanks-for-help.md
This script runs repeatedly until (when prompted) one hits 'q' (or 'Q')
or else sends ctrl-c/intr. I also added a question to the extra credit
questions: are there any misspelt words and if there are what are they?
I also added that there's a way to cheat very easily but I did not say
how to do it. It should be pretty obvious how to do it to anyone who
tries the program once or if not once a few times.
=> Add 1998/df/try.sh

faq.md
Some typo fixes and various other changes and improvements.
=> Improve FAQ 3.7 - how to compile/run X11 entries

1998/bas1/README.md, 1998/bas1/bas1.sh, 2000/natori/README.md, 2000/natori/try.alt.sh, 2004/arachnid/README.md, 2004/gavare/README.md, 2004/hibachi/README.md, 2004/hibachi/src/localhost/index.html, 2004/hibachi/src/localhost/test/shell/test0.sh, 2004/hoyle/.gitignore, 2004/hoyle/README.md, 2004/hoyle/try.sh, 2004/jdalbec/try.alt.sh, 2004/jdalbec/try.sh, 2004/kopczynski/try.sh, 2004/newbern/README.md, 2004/newbern/try.sh, thanks-for-help.md
One of the features the author noted is also in the script. It was 
documented by Yusuke but I chose to use the letters IOCCC instead (it
seemed more fitting). This is noted in the thanks file.
=> Add 2004/newbern/try.sh

2000/natori/README.md, 2000/natori/try.alt.sh, thanks-for-help.md
The try.alt.sh script is slightly different from try.sh in that the order is reversed.
The try.sh script now at the end always starts out in a sequence of northern hemisphere then southern hemisphere so that one can guarantee to get that form. The try.alt.sh does the same but starts out with the southern hemisphere first.
=> Add 2000/natori/try.alt.sh + improve try.sh

1998/bas1/README.md, 1998/bas1/bas1.sh, 2000/natori/README.md, 2000/natori/try.alt.sh, thanks-for-help.md
This simplifies the running of the program as the command lines 
(different options) can be long and more complicated to type, especially
the last one. The script is menu driven. Initially I made it a loop so 
one can run the command once to try multiple modes but this seems 
unnecessary and created some display problems (depending on how 
invocations were done).
=> Add 1998/bas1/bas1.sh

1998/bas1/README.md, 1998/bas1/bas1.sh, 2000/natori/README.md, 2000/natori/try.alt.sh, 2004/arachnid/README.md, 2004/gavare/README.md, 2004/hibachi/README.md, 2004/hibachi/src/localhost/index.html, 2004/hibachi/src/localhost/test/shell/test0.sh, 2004/hoyle/.gitignore, 2004/hoyle/README.md, 2004/hoyle/try.sh, thanks-for-help.md
This involved an update to .gitignore.
=> Add 2004/hoyle/try.sh

1985/sicherman/try.alt.sh, 1985/sicherman/try.sh, 1988/dale/try.sh, 1993/plummer/try.alt.sh, 1993/plummer/try.sh, 1994/ldb/try.sh, 1995/garry/try.alt.sh, 1995/garry/try.sh, 1998/df/try.sh, 1998/fanf/try.sh, 2000/bmeyer/try.sh, 2000/rince/try.sh, 2005/aidan/try.alt.sh, 2005/aidan/try.sh, 2005/anon/README.md, 2005/boutines/README.md, 2005/boutines/try.sh, 2005/giljade/test.sh, 2005/giljade/try.sh, 2005/klausler/try.sh, thanks-for-help.md
Fun fact: the Lion king is an anagram for 'thinking Leo'. And what is 
Leo? The Lion constellation! :-)
=> Improve and typo fix 2005/klausler/try.sh

1985/sicherman/try.alt.sh, 1985/sicherman/try.sh, 1988/dale/try.sh, 1993/plummer/try.alt.sh, 1993/plummer/try.sh, 1994/ldb/try.sh, 1995/garry/try.alt.sh, 1995/garry/try.sh, 1998/df/try.sh, 1998/fanf/try.sh, 2000/bmeyer/try.sh, 2000/rince/try.sh, 2005/aidan/try.alt.sh, 2005/aidan/try.sh, 2005/anon/README.md, 2005/boutines/README.md, 2005/boutines/try.sh, 2005/giljade/test.sh, 2005/giljade/try.sh, thanks-for-help.md
Prompt to run test suite after the main feature is done and improve the
prompting. The test suite script gives a warning that it may take a bit
of time to run.
=> Improve scripts for 2005/giljade

2006/borsanyi/.gitignore, 2006/borsanyi/README.md, 2006/borsanyi/try.sh, 2006/grothe/README.md, 2006/grothe/try.sh, 2006/hamre/try.sh, 2006/monge/README.md, 2006/monge/try.alt.sh, 2006/monge/try.sh, 2006/stewart/README.md, 2006/stewart/try.sh, 2006/sykes1/README.md, 2006/sykes1/try.sh, 2006/toledo1/try.sh, bin/ioccc-status.sh, man/man1/ioccc-status.1, thanks-for-help.md
The script runs in a loop until the user answers anything but 'y' or 'Y'
when asked if they wish to make another one. It does NOT check the valid
range of characters or the length. Instead it suggests one try and see 
what happens if they do not follow the rules.
=> Add 2006/borsanyi/try.sh

2006/grothe/README.md, 2006/grothe/try.sh, bin/ioccc-status.sh, man/man1/ioccc-status.1, thanks-for-help.md
After each command it prompts if you wish to resume as some people 
(including myself) might find that only one file is enough.
=> Add 2006/grothe/try.sh

2006/grothe/README.md, 2006/grothe/try.sh, 2006/hamre/try.sh, 2006/monge/README.md, 2006/monge/try.alt.sh, 2006/monge/try.sh, bin/ioccc-status.sh, man/man1/ioccc-status.1, thanks-for-help.md
The alt script will reconfigure the width, height and iterations for the
second invocation.
Note that in some platforms this entry will not work (this is
documented in the remarks). That is one of the reasons there is only one 
expression tested as one of the platforms it will not work with is arm64
which is what I primarily use.
=> Add 2006/monge/try scripts

2006/grothe/README.md, 2006/grothe/try.sh, 2006/hamre/try.sh, 2006/monge/README.md, 2006/monge/try.alt.sh, 2006/monge/try.sh, 2006/stewart/README.md, 2006/stewart/try.sh, 2006/sykes1/README.md, 2006/sykes1/try.sh, 2006/toledo1/try.sh, bin/ioccc-status.sh, man/man1/ioccc-status.1, thanks-for-help.md
If one does not hit enter for the prompting of the press any key the 
next echo will be on the same line.
=> Minor fixes in 2006/toledo1/try.sh

1992/gson/mkdict.sh, 1992/westley/try.sh, bin/gen-inventory.sh
Now shows coordinates for each location shown.
=> Further improve 1992/westley/try.sh

1994/westley/.gitignore, 1994/westley/Makefile, 1994/westley/README.md, 1994/westley/try.alt.sh, 1994/westley/westley.alt.c, 1996/gandalf/try.sh, 2011/akari/try.sh, 2011/borsanyi/try.sh, 2011/dlowe/try.sh, 2011/eastman/README.md, 2011/fredriksson/.gitignore, 2011/fredriksson/try.sh, 2011/goren/try.sh, 2011/hamaji/try.sh, 2011/hou/try.sh, 2011/konno/try.sh, 2011/richards/README.md, 2011/richards/try.alt.sh, 2011/richards/try.sh, bugs.md, thanks-for-help.md
The bugs.md refers to the alt try script for testing any fix with the 
Apple silicon chip. If someone gets it to work the entry could be 
removed from the bugs.md file and the README.md file updated to refer to
the alternate code. As the alternate code does not work (though it has a
different type of crash) the alt build/try is not mentioned in the 
README.md file. It is not clear if it's helpful or not to have it in the
README.md at this point as the important part is in bugs.md.
=> Add 2011/richards try scripts

1994/westley/.gitignore, 1994/westley/Makefile, 1994/westley/README.md, 1994/westley/try.alt.sh, 1994/westley/westley.alt.c, 1996/gandalf/try.sh
Running ./try.sh by itself will not show this improvement. It might be
an inside joke between Landon and me but which adds fun to the entry in
a way that many people will appreciate, given the entry name. Those who
do not, however, will not be bothered by it as running ./try.sh won't do
anything different from before: it'll just run the program in a variety
of ways as before.
=> Further improvements to 1996/gandalf/try.sh

1994/westley/.gitignore, 1994/westley/Makefile, 1994/westley/README.md, 1994/westley/try.alt.sh, 1994/westley/westley.alt.c, 1996/gandalf/try.sh, 2011/akari/try.sh, 2011/borsanyi/try.sh, 2011/dlowe/try.sh, 2011/eastman/README.md, 2011/fredriksson/.gitignore, 2011/fredriksson/try.sh
The script now writes the output to a file (via tee(1)) and uses diff -s
on the file and fredriksson.c. It also fixes a problem where if one were
to hit space after the prompt (lines would be merged) rather than
enter/return. 
Fixed shellcheck warning (no need to ignore it).
=> Improve and fix 2011/fredriksson/try.sh

2012/hamano/Makefile, 2012/hamano/README.md, 2012/hamano/try.sh, 2012/hou/try.sh, 2012/kang/README.md, 2012/kang/de.alt.sh, 2012/kang/de.sh, 2012/kang/en.alt.sh, 2012/kang/en.sh, 2012/kang/try.alt.sh, 2012/kang/try.sh, thanks-for-help.md
The try.alt.sh uses the alt code. This helps further show how a single 
letter can change so much and thus one can really appreciate the 
subtlety of the entry even more. The other scripts were improved.
=> Improve scripts (and add one) of 2012/kang

2012/hamano/Makefile, 2012/hamano/README.md, 2012/hamano/try.sh, 2012/hou/try.sh, 2012/kang/README.md, 2012/kang/de.alt.sh, 2012/kang/de.sh, 2012/kang/en.alt.sh, 2012/kang/en.sh, 2012/kang/try.alt.sh, 2012/kang/try.sh, 2012/konno/README.md, 2012/konno/try.sh, thanks-for-help.md
Now randomly selects 10 numbers (in range $((RANDOM % 101))).
Also allows one to pass in numbers (or if they wish to they can pass in
non-numbers) to pass to the program.
The script has new fun numbers.
Removed that the valid range is from 0 - 255 as numbers bigger than 255
not only work but some show some fun output (a number of which are used
in the script now).
=> Improve 2012/konno/try.sh

2013/endoh2/README.md
Don't cat jpeg.c as it's longer than a page. Use less(1) instead.
=> Improve try section of 2013/endoh2

1998/schweikh3/.gitignore, 1998/schweikh3/Makefile, 2013/endoh2/README.md, 2013/endoh3/.gitignore, 2013/endoh3/Makefile, 2013/endoh3/README.md, 2013/endoh3/endoh3.c, 2013/endoh3/try.sh, 2013/endoh4/Makefile, 2013/endoh4/README.md, 2013/endoh4/endoh4.sh, 2013/hou/README.md, 2013/hou/try.sh, 2013/misaka/try.sh, 2013/morgan1/README.md, 2013/morgan1/try.sh, bin/all-run.sh, bugs.md, thanks-for-help.md
Needs to remove samefile.alt.
Updated .gitignore too.
=> Fix make clobber in 1998/schweikh3

1998/schweikh3/.gitignore, 1998/schweikh3/Makefile, 2013/endoh2/README.md, 2013/endoh3/.gitignore, 2013/endoh3/Makefile, 2013/endoh3/README.md, 2013/endoh3/endoh3.c, 2013/endoh3/try.sh, 2013/endoh4/Makefile, 2013/endoh4/README.md, 2013/endoh4/endoh4.sh, 2013/hou/README.md, 2013/hou/try.sh, 2013/misaka/try.sh, 2013/morgan1/README.md, 2013/morgan1/try.sh, 2015/yang/.gitignore, 2015/yang/Makefile, bin/all-run.sh, bugs.md, thanks-for-help.md
=> Fix make clobber in 2015/yang + update .gitignore

.gitignore, 1998/schweikh3/.gitignore, 1998/schweikh3/Makefile, 2013/endoh2/README.md, 2013/endoh3/.gitignore, 2013/endoh3/Makefile, 2013/endoh3/README.md, 2013/endoh3/endoh3.c, 2013/endoh3/try.sh, 2013/endoh4/Makefile, 2013/endoh4/README.md, 2013/endoh4/endoh4.sh, 2013/hou/README.md, 2013/hou/try.sh, 2013/misaka/try.sh, 2013/morgan1/README.md, 2013/morgan1/try.sh, 2014/deak/try.alt.sh, 2015/yang/.gitignore, 2015/yang/Makefile, 2018/burton1/.gitignore, 2018/burton1/Makefile, bin/all-run.sh, bugs.md, thanks-for-help.md
Make less(1) options consistent with other scripts.
=> Improve 2014/deak/try.sh

2020/kurdyukov2/.gitignore, 2020/kurdyukov2/Makefile, 2020/kurdyukov2/README.md, 2020/kurdyukov2/makegif.sh, 2020/kurdyukov2/try.sh, 2020/kurdyukov4/try.sh, thanks-for-help.md
The author stated that it gets progressively slower with less context so
it now uses time(1).
=> Improve 2020/kurdyukov4/try.sh

2020/kurdyukov1/try.sh, 2020/kurdyukov2/.gitignore, 2020/kurdyukov2/Makefile, 2020/kurdyukov2/README.md, 2020/kurdyukov2/makegif.sh, 2020/kurdyukov2/try.sh, 2020/kurdyukov4/try.sh, 2020/otterness/.gitignore, 2020/otterness/README.md, 2020/otterness/try.sh, 2020/yang/Makefile, 2020/yang/try.sh, thanks-for-help.md
The make clobber now removes decoded, code.c and encoded.c which try.sh
creates.
=> Improve 2020/yang/try.sh

2020/ferguson1/chocolate-cake.md, 2020/ferguson2/chocolate-cake.md, tmp/things-todo.md
Minor rewording here and there.
Updated the todo file to remove this issue.
=> Fix formatting in chocolate cake recipe

2001/westley/README.md, 2001/westley/try.sh, 2020/ferguson1/chocolate-cake.md, 2020/ferguson2/chocolate-cake.md, bugs.md, tmp/things-todo.md
The try script was improved slightly.
The bugs.md file now refers to a new status type for this entry.
Updated the todo file removing this item.
=> Update 2001/westley/try.sh + bugs.md

2000/tomx/.gitignore, 2000/tomx/try.alt.sh, 2000/tomx/try.sh
Updated .gitignore as the scripts now generate two new files.
=> Further improvements to 2000/tomx/try scripts

2000/schneiderwent/README.md, 2000/schneiderwent/try.sh, 2000/tomx/.gitignore, 2000/tomx/try.alt.sh, 2000/tomx/try.sh
Now allows one to override how long to sleep and how many iterations to
go through. It is an error if non positive values are specified.
=> Further improve 2000/schneiderwent/try.sh

2000/rince/try.sh, 2000/schneiderwent/README.md, 2000/schneiderwent/try.sh, 2000/tomx/.gitignore, 2000/tomx/try.alt.sh, 2000/tomx/try.sh
Show how the commands that use 'dmy2jd' come up with the values.
=> Further improvements to 2000/rince/try.sh

2000/briddlebane/README.md, 2000/briddlebane/try.sh, 2000/dhyang/try.sh, 2000/natori/try.alt.sh, 2000/natori/try.sh, 2000/primenum/try.sh, 2000/rince/try.sh, 2000/schneiderwent/README.md, 2000/schneiderwent/try.sh, 2000/tomx/.gitignore, 2000/tomx/try.alt.sh, 2000/tomx/try.sh, thanks-for-help.md
Especially useful for those who feel a bit too confident, cocky or even
happy :-)
=> Add 2000/briddlebane/try.sh

2001/coupard/README.md, 2001/coupard/try.sh, 2001/ollinger/try.sh, thanks-for-help.md
The question is if I updated the less options by adding an option to
less(1) is it really less options? Perhaps it is more (or if you prefer:
more(1)) options for less? But since less is more, as they say, is it
really more options for more(1) or less options for more(1)? This leaves
more questions unanswered than answered questions (or questions 
answered), more or less! :-)
=> Update less options in 2001/ollinger/try.sh

1992/westley/whereami.alt.sh, 1992/westley/whereami.sh, 2000/bmeyer/try.sh, 2001/coupard/README.md, 2001/coupard/try.sh, 2001/dgbeards/README.md, 2001/ollinger/try.sh, 2013/endoh3/try.sh, thanks-for-help.md, tmp/update-manifest.sh
Remove reference to the jargon file. The bugs.md file already notes that
the entry is supposed to crash if it loses.
=> Minor update to 2001/dgbeards/README.md

1992/westley/whereami.alt.sh, 1992/westley/whereami.sh, 2000/bmeyer/try.sh, 2001/coupard/README.md, 2001/coupard/try.sh, 2001/dgbeards/README.md, 2001/ollinger/try.sh, 2004/hoyle/try.sh, 2004/newbern/try.sh, 2004/omoikane/try.sh, 2004/sds/try.sh, 2005/aidan/Makefile, 2013/endoh3/try.sh, thanks-for-help.md, tmp/update-manifest.sh
Make sure program is compiled first.
=> Fix make test in 2005/aidan

2005/aidan/try.alt.sh, 2005/aidan/try.sh, 2005/chia/chia.c, 2005/jetro/README.md
In README.md it's fine to fix a spelling error. Not so in the code but
it was changed without really thinking about it on 22 March 2023. This 
fixes that problem: for problem it is.
=> Restore original comment in 2005/chia

2005/klausler/try.sh
Now includes: Dennis Ritchie, Ken Thompson and Linus Torvalds. Fun anagrams, some of which are not shown in the output:
DENNIS RITCHIE = INDECENT IRISH = SHIRE INCIDENT
KEN THOMPSON = SPOKEN MONTH
LINUS TORVALDS = VILLOUS STRAND (VILLOUS is a word of anatomy,
medical and botany).
=> Add more strings to 2005/klausler/try.sh

2000/natori/Makefile, 2006/birken/try.sh, 2006/stewart/Makefile, Makefile, thanks-for-help.md
The -Wno-foo options were in the CDEFINE variable which although works 
it is not congruent with the other Makefiles and it is slightly more 
confusing (even though not confusing).
=> Fix 2000/natori/Makefile - wrong variable used

1984/anonymous/README.md
=> Minor format fix in 1984/anonymous/README.md

1992/gson/try.sh, 2011/blakely/try.sh, 2011/borsanyi/try.sh, 2011/hamaji/try.sh, 2011/hou/try.sh, 2011/konno/try.sh, bin/all-run.sh
It seemed that output stopped in one of the commands.
=> Fix in 2011/blakely/try.sh

2020/ferguson1/play.sh
Did you know some people believe in snake human hybrids? I added a link to the script that discusses this and gives supposed examples.
=> Add fun link to 2020/ferguson1/play.sh

2020/ferguson1/play.sh, faq.md
This used commit afb9e54a4c9849a474782000d80239b7dcbb1f66 as an example
(an example commit and pull request was suggested to me by Landon).
Note that I did NOT update the html file as I am not clear how to do 
this (for the moment).
=> Add FAQ entry about opening pull requests

Makefile, faq.html, faq.md
'FAQ 6.10: How does someone make a change to a file and submit that
change as a GitHub pull request?' has been updated to note that the 
authors of winning entries tend to have more deference but that the 
judges still have the final say in the matter.
There were some typos (including links) and formatting fixes as well.
=> Minor fixes and updates to FAQ

1992/.filelist, 2013/morgan1/README.md, 2013/morgan1/try.sh, 2020/.filelist
In other words:
* Right : go forwards one day.
* Left  : go backwards one day.
* Up    : go forwards 20 days.
* Down  : go backwards 20 days.
The try.sh script also has this detail and improves the way it tells the
user about Comets Halley and Hale-Bopp.
=> Add UI description to to use in 2013/morgan1

1992/.filelist, 2013/dlowe/try.sh, 2013/morgan1/README.md, 2013/morgan1/try.sh, 2020/.filelist
It is important that this script does NOT prompt the user for each run 
as this will break diff.sh. It might have been good if another script
allowed this but issue 3 is drawing to a close (as we all want) and it's
not that big of a deal anyway.
=> Add warning comment to 2013/dlowe/try.sh

bin/all-run.sh, bin/all-years.sh, bin/chk-entry.sh, bin/gen-authors.sh, bin/gen-location.sh, bin/gen-other-html.sh, bin/gen-sitemap.sh, bin/gen-status.sh, bin/gen-top-html.sh, bin/gen-year-index.sh, bin/gen-years.sh, bin/md2html.sh, bin/output-index-author.sh, bin/output-index-inventory.sh, bin/output-year-index.sh, bin/pandoc-wrapper.sh, bin/quick-readme2index.sh, bin/readme2index.sh, bin/sort.gitignore.sh, bin/status2html.sh, bin/subst.default.sh, bin/subst.entry-index.sh, bin/subst.year-index.sh, bin/tar-all.sh, bin/tar-entry.sh, bin/tar-year.sh
In particular the notice for macOS users now tells how to install bash with Homebrew (brew install bash).
=> Typo fix and improve brew instructions in bin/

1984/mullender/Makefile, bin/all-run.sh, bin/all-years.sh, bin/chk-entry.sh, bin/gen-authors.sh, bin/gen-location.sh, bin/gen-other-html.sh, bin/gen-sitemap.sh, bin/gen-status.sh, bin/gen-top-html.sh, bin/gen-year-index.sh, bin/gen-years.sh, bin/md2html.sh, bin/output-index-author.sh, bin/output-index-inventory.sh, bin/output-year-index.sh, bin/pandoc-wrapper.sh, bin/quick-readme2index.sh, bin/readme2index.sh, bin/sort.gitignore.sh, bin/status2html.sh, bin/subst.default.sh, bin/subst.entry-index.sh, bin/subst.year-index.sh, bin/tar-all.sh, bin/tar-entry.sh, bin/tar-year.sh, faq.html, faq.md
This improves the names of links and adds some new links as well. A 
point of interest that could easily be missed with a diff is that the 
link of Yusuke Endoh was changed from his GitHub account to his 
authors.html section. Also, since the first successful pull request to 
the winner repo was acknowledged by author (Yusuke Endoh) I added the 
author of the first successful pull request to the temp-test-ioccc repo
(as the commit was cited) (and that indeed would be me). It might be 
that keeping the GitHub accounts would be better and I can certainly 
change them back but it seemed nicer to acknowledge the author entries 
as that's the real honour of being a winner.
There were other things besides the above but they were all along the 
same lines.
=> Finish editing of FAQ 1.2

2000/dlowe/README.md, 2000/dlowe/index.html, bugs.html, bugs.md
The doesn't work with some platforms is wrong. It's the perl version and the author noted this.
There is however a bug that was noted in the bugs file that was not in the README.md file. This has been moved in the bugs.md file and README.md file to above the INABIAF part.
=> Fix bug statuses of 2000/dlowe

bugs.html, bugs.md
The bugs.md/bugs.html file stated it was a bug to be fixed but it's actually a feature, not a bug, and that's how it is in the README.md for the entry too. Thus bugs.md was updated and the bugs.html was regenerated.
=> Fix bug status of 1990/baruch in bugs.md

1984/laman/README.md, 1984/laman/index.html, 2013/misaka/Makefile, faq.html, faq.md
The try.sh script ran commands that were explicitly listed under try.sh in the 
try section.
Rebuilt index.html.
=> Fix 1984/laman try section

1991/buzzard/README.md, 1991/buzzard/index.html, 1991/westley/README.md, 1991/westley/index.html, faq.html, faq.md, thanks-for-help.html, thanks-for-help.md
=> Minor update to 1991/westley/README.md

.github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/other_issue.yml, .github/ISSUE_TEMPLATE/website_issue.yml
The content can certainly be improved or added to. I still have to come up with a form for other problems. It is not clear to me that an issue form for bugs should be here as the code is not actually maintained and one can see bugs.md for more details on this subject.
=> Add issue form templates

.github/ISSUE_TEMPLATE/author_details.yml
The file in question is author_details.yml.
=> Add template for issue form for author details

1996/august/README.md, 1996/august/index.html, 2020/kurdyukov4/README.md, 2020/kurdyukov4/index.html
=> Fix format in 2020/kurdyukov4/README.md

2001/ollinger/README.md, 2001/ollinger/index.html, 2001/ollinger/ollinger.c, 2004/anonymous/README.md, 2004/anonymous/index.html, bugs.html, bugs.md, thanks-for-help.html, thanks-for-help.md
Some link fixes/additions and a fun fact or two added/clarified.
Precious made me do it! If this file is updated again it will be for
link fixes or format fixes when I go through the index.html files.
=> Fixes/updates to 2004/anonymous/README.md

README.html, README.md, contact.html, contact.md, faq.html, faq.md
README.html looks good now, minus possibly something that is to be 
discussed.
=> Minor fixes in README.{md,html}

1987/README.md, 1987/index.html, 1987/lievaart/README.md, 1987/lievaart/index.html, Makefile
In particular 1987/index.html and 1987/lievaart/index.html. Other files
in 1987 seemed to be okay.
=> Fixes in 1987 html files

author/Byron_Rakitzis.json, ioccc.css
This email comes from their website.
=> Add email to Byron_Rakitzis.json

bugs.html
Forgot to do this after the last edit to bugs.md.
=> Regenerated bugs.html

1992/buzzard.1/README.md, 1992/buzzard.1/index.html
This took some careful editing but it now looks nice on an iPhone 14 Pro Max and it also looks nice on a laptop (16"). In Safari responsive mode at 500 x 100 it also looks okay which I think is pretty good. For some macros the function line had to be split up and it might look like the formatting is wrong in a few cases but this took trial and error to get it to align right (or very close if not completely).
=> Fix format of table in 1992/buzzard.1

contact.html, contact.md
Although 'Email' is sometimes used it feels more out of place in the middle of a sentence. There might be other files where this could be done but at the same time there are files that this should not be done - like source code.
=> Change 'Email' to 'email' in contact.{md,html}

.github/ISSUE_TEMPLATE/author_details.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/other_issue.yml, .github/ISSUE_TEMPLATE/website_issue.yml, Makefile, faq.html, faq.md, next/guidelines.html, next/guidelines.md, next/rules.html, next/rules.md
.. though this certainly can be improved some still, the entire wording
of the sentence. That will be considered later.
Thank you to @SirWumpus for indirectly making me aware of this: I know 
he hates templates so I feel like I should thank him specially :-)
=> Minor grammar improvement in issue templates

Makefile, faq.html, faq.md, next/guidelines.html, next/guidelines.md, next/rules.html, next/rules.md
The rest of the file has to be looked at later.
=> Partial review of guidelines updates

Makefile
Part of the edit to the Makefile was in error - a yank paste error on my part that I fixed in a commit that came after but the restoration of the change put the problem back in.
=> Fix Makefile from d273ba

Makefile, faq.html, faq.md, next/guidelines.html, next/guidelines.md, next/rules.html, next/rules.md
The guidelines had many fixes and where necessary updates (about new tools for instance) plus some fun for people to discover.
The FAQ was slightly updated as well for the guidelines.
=> Fixes in guidelines and rules

2020/ferguson1/Makefile, inc/guidelines.closed.hdr, inc/guidelines.open.hdr, inc/guidelines.pending.hdr, inc/rules.open.hdr, inc/rules.pending.hdr, next/guidelines.html, next/guidelines.md
This is more for those who are interested in how they can run each step
of the mkiocccentry tool as well as how to make it easier to edit a 
submission tarball.
Although it looks okay (the rendered html) a more thorough review will 
have to be done, tomorrow if possible.
=> Update guidelines - add new tools description

faq.html, faq.md, next/guidelines.html, next/guidelines.md, next/rules.html, next/rules.md
The new FAQ is about how to report bugs in mkiocccentry tools. The rules and guidelines link to this FAQ.
The rules and guidelines have been corrected and clarified in a number of ways.
=> Fixes in rules, guidelines, additional FAQ

status.html, status.md
Instead of just bold or italic it's now a link to that specific status.
=> Add link to status in status.html

next/rules.html, next/rules.md
=> Fix validation for rules.html

bugs.html, bugs.md
The change made was incomplete with the other changes in the commit that addressed the other bug status added (and the gets(3)/fgets(3) one that was modified).
=> Fix bugs status in 1992/gson

faq.html, faq.md
FAQ 3.21 tells what try.sh and try.alt.sh scripts are and why one might want to use them.
FAQ 4.7 discusses why some files were renamed.
FAQ 4.8 discusses additions and removal of some files.
=> Add a few FAQ entries

ioccc.css, next/guidelines.html, next/guidelines.md, next/rules.html, next/rules.md
Some of these are very important technical fixes as they stated things
that were not accurate. Other things were (hopefully) clarified. Another
check will have to be done sometime soon.
=> Numerous technical fixes in the guidelines & rules

next/guidelines.html, next/guidelines.md, next/rules.html, next/rules.md
This includes updates from a recent change in txzchk and more details about the tools and what they check (warnings and errors) and how to use them individually.
This does need to be reviewed further, possibly being shorted or referring to an FAQ, but it's a good start.
The rules had a typo fix as well.
=> More details in guidelines

1991/fine/README.md, 1991/fine/index.html
In case someone wants more of a challenge in a subsection of the judges' remarks it has the notice about trying to figure it out by looking at the code and only (unless they are not looking for an additional challenge) if they get stuck should they come back to read the author's remarks.
=> Add challenge note to 1991/fine

faq.html, faq.md
These are very detailed as they are very important parts of the mkiocccentry toolkit. The guidelines will likely refer to these for those who want to know more details but that is for another commit.
=> Add FAQs about .auth.json and .info.json

1992/gson/README.md, 1992/gson/index.html, 1992/gson/try.sh, bin/README.md, bin/csv2entry.sh, bin/index.html, bugs.html, bugs.md
The text 'If you want to try and fix this (mis)feature, you are welcome
to try' was problematic because these things are not (mis)features but
bugs. Thus it now reads '... fix this, ...'.
Also in one case that was noticed it was not actually anything that 
should be fixed at all as they were documented features, not bugs.
=> Fixes in bugs.{md,html}

1991/README.md, 1991/index.html, 1992/README.md, 1992/index.html, 1993/README.md, 1993/index.html, 1994/README.md, 1994/horton/.entry.json, 1994/horton/README.md, 1994/horton/index.html, 1994/index.html, 1995/README.md, 1995/index.html, bin/quick-readme2index.sh, markdown.html, markdown.md
The fixes include a manifest update wrt the alternate code.
=> Fixes in 1994/horton

faq.html, faq.md
Typo fixes, added a link name (for the other repo's FAQ) and maybe some other minor fixes/updates.
=> Minor fixes/updates to FAQ

faq.html, faq.md
I also fixed a format issue and some incorrect terms.
=> Add named links to FAQs

2001/anonymous/README.md, 2001/anonymous/index.html, 2001/bellard/README.md, 2001/bellard/index.html, 2001/coupard/README.md, 2001/coupard/index.html, 2001/ctk/README.md, 2001/ctk/index.html, 2001/dgbeards/README.md, 2001/dgbeards/index.html, 2001/herrmann1/README.md, 2001/herrmann1/index.html, 2001/jason/README.md, 2001/jason/index.html, 2001/kev/README.md, 2001/kev/index.html, 2001/ollinger/README.md, 2001/ollinger/index.html, 2001/rosten/README.md, 2001/rosten/index.html, 2001/schweikh/README.md, 2001/schweikh/index.html, 2001/westley/README.md, 2001/westley/index.html, 2001/williams/README.md, 2001/williams/index.html, bugs.html, bugs.md
This also includes a few updates to the bugs file.
=> Fix html files in 2001

2001/README.md, 2001/index.html, 2004/README.md, 2004/anonymous/README.md, 2004/anonymous/index.html, 2004/arachnid/README.md, 2004/arachnid/index.html, 2004/burley/README.md, 2004/burley/burley.c, 2004/burley/index.html, 2004/hibachi/README.md, 2004/hibachi/index.html, 2004/index.html, 2005/README.md, 2005/index.html, 2006/README.md, 2006/index.html, 2011/README.md, 2011/index.html, 2012/README.md, 2012/index.html, 2013/README.md, 2013/index.html, 2014/README.md, 2014/index.html, 2015/README.md, 2015/index.html, thanks-for-help.html, thanks-for-help.md
This commit does anonymous, arachnid and hibachi. Along with an earlier
commit the next one I think to work on is gavare.
=> Some 2004 html files fixed

2001/README.md, 2001/index.html, 2004/README.md, 2004/index.html, 2005/README.md, 2005/index.html, 2006/README.md, 2006/index.html, 2011/README.md, 2011/index.html, 2012/README.md, 2012/index.html, 2013/README.md, 2013/index.html, 2014/README.md, 2014/index.html, 2015/README.md, 2015/index.html, author/Anders_Gavare.json, authors.html
This is specific to their winning entry (which is actually referred to 
in the index.html file).
=> Add alt url to Anders Gavare

2004/jdalbec/README.md, 2004/jdalbec/index.html, 2004/kopczynski/README.md, 2004/kopczynski/index.html, 2004/omoikane/README.md, 2004/omoikane/index.html, 2004/schnitzi/README.md, 2004/schnitzi/index.html, 2004/vik1/README.md, 2004/vik1/index.html, 2004/vik2/README.md, 2004/vik2/index.html, bugs.html, bugs.md, thanks-for-help.html, thanks-for-help.md
There is one thing brought up on GitHub that might necessitate a minor change but that can happen later.
=> Finish fixing html files in 2004

Makefile, bin/README.md, bin/index.html
In aced0d06ebb55c8429279641c438c17d04a9640c I forgot to build the 
bin/index.html and I also have changed:
^NOTE:
to be:
**NOTE**:
(not regexp for the update, obviously.)
=> Minor updates to bin/index.html

2014/birken/README.md, 2014/birken/index.html, 2014/maffiodo1/README.md, 2014/maffiodo1/index.html, 2014/skeggs/README.md, 2014/skeggs/index.html, 2014/vik/README.md, 2014/vik/index.html, bugs.html, faq.html, faq.md
This commit also adds the faq.html and bugs.html file that should have been committed with 2013. The reason the faq.md is updated with only the version update (backdated to yesterday) is because the version was not updated with the previous update.
=> Format fixes in html files of 2014

faq.html, faq.md
Much more work needs to be done here still.
=> More more questions/answers in FAQ

faq.html, faq.md
That is I did:
sgit -e '/^<\/li>$/d' -e '/^<li>$/d' \
-e '/^<ol>$/d' -e -e 's/^<\/ol>$/g' faq.md
The next steps are to move the question/answers to the appropriate sections and to try and shorten as many answers as possible, possibly merging some or even getting rid of some.
=> Remove lists and list items from FAQ

faq.html, faq.md
The new question is 'What is the mkiocccentry tool, how do I obtain it and how do I use it?'. This one still needs more work, however.
=> Merge two FAQs about the mkiocccentry toolkit

faq.html, faq.md, next/guidelines.html, next/guidelines.md
More work might need to be done in this section and other sections might need checking too but I believe this section is more helpful. An attempt was made to shorten some of it without compromising the usefulness but more will have to be done to make sure this is the case.
=> Improve FAQ section for submitting

faq.html, faq.md, thanks-for-help.html, thanks-for-help.md
The first one is now simpler and simply says some of the things that might have changed. The other one, a sub-question, discusses the Makefile rules and such.
=> Split into two the FAQ about changes in entries

thanks-for-help.html, thanks-for-help.md
Also made quite a few fixes (of various kinds).
=> Improve navigability of thanks file

bin/format-headers.sh, thanks-for-help.html, thanks-for-help.md
Make it clearer how it came to be and what it does.
=> Fix header in bin/format-headers.sh

2006/toledo2/README.md, 2006/toledo2/index.html, 2006/toledo3/README.md, 2006/toledo3/index.html, bin/README.md, bin/format-headers.sh, bin/gen-sitemap.sh, bin/index.html, bin/md2html.cfg, bin/subst.default.sh, nojs-menu.html, nojs-menu.md, thanks-for-help.html, thanks-for-help.md
The script now uses git ls-files instead of find, so that other files in
the directories are not added to the sitemap.
=> Improve bin/gen-sitemap.sh

bin/combine_author_handle.sh
Make JSON lower case in filenames (this was only in comments in this case).
=> Typo fix in combine_author_handle.sh

1337.mk, Makefile, thanks-for-help.html, thanks-for-help.md
=> Inject some last minute fun :-)

1994/shapiro/.entry.json, 1994/shapiro/Makefile, 1994/shapiro/README.md, 1994/shapiro/index.html, 1994/shapiro/shapiro.alt.c, 2001/westley/README.md, 2001/westley/index.html, Makefile, bugs.html, bugs.md, thanks-for-help.html, thanks-for-help.md
With a tip from Leo the missing alt code has been added to the website.
Ta, Leo (🦁⭐️🌌)!
=> Add missing 1994/shapiro/shapiro.alt.c

2001/rosten/.entry.json, 2001/rosten/README.md, 2001/rosten/greasymouse.man, 2001/rosten/index.html, bin/README.md, bin/entry2csv.sh, bin/gen-authors.sh, bin/gen-location.sh, bin/gen-years.sh, bin/index.html, bin/jfmt-wrapper.sh, bin/manifest.entry.json.awk, bin/output-index-author.sh, bin/output-year-index.sh, bin/subst.entry-index.sh, bugs.html, bugs.md
The new file, greasymouse.man, IS the cat man page noted by the author
in their remarks. This file was provided by Leo as remark.txt but to
make it render better I have made it a .man file and, for syntax
highlighting, I moved the section titles to the first column of the
file.
I thought of making it a true man page but as the author suggested that
it is a cat man page I decided against this.
=> Add missing file in 2001/rosten

bin/entry2csv.sh, bin/gen-authors.sh, bin/gen-location.sh, bin/gen-years.sh, bin/output-index-author.sh, bin/output-year-index.sh, bin/subst.entry-index.sh
Tested from mkiocccentry copy by make www.
=> Update jstrdecode min version in bin/ tools

next/guidelines.html, next/guidelines.md
These changes clarify some things and add some missing details.
=> Make some important changes to guidelines

thanks-for-help.html, thanks-for-help.md
A typo fix was made which until corrected did not make sense.
Some other minor changes were made, to account for some missing things.
I believe that unless something glaringly bad is noticed, this should be the last update of this file, unless of course something new comes up, but if that does I guess it'll be after the great fork merge and IOCCC28.
=> Typo fix / updates in thanks file

thanks-for-help.html, thanks-for-help.md
This was supposed to be for 03694c587d7101e17846c71bf5f4083c23a47f27 from yesterday but didn't make it in.
=> Slight update to thanks

next/register.html, next/register.md
I have not looked at everything but some fixes have been made.
=> Some fixes in next/register.html

faq.html, faq.md, thanks-for-help.html, thanks-for-help.md
The FAQ has a better title for a question.
The thanks file was very slightly shortened.
=> Minor updates to FAQ, thanks file
