ioccc-src/temp-test-ioccc

bin/sgit

Script no longer requires GNU sed but works with other sed implementations as well (only other one tested is macOS however).
Uses getopts to parse options. Usage is now:
usage: sgit [-h] [-V] [-v level] [-e command] <glob...>
-h                      print help and exit
-V                      print version and exit
-v level                set verbosity level
-e command              append sed command to execute on globs
which means that yes one can specify more than one glob. As long as one sed command is specified (chose -e to match sed) and one arg is specified after the last option then the command line is okay (whether the sed command or file is okay is another matter entirely).
Verbose output to help test / debug features or if just interested in what's being done.

Greatly improve my sgit script

---

1986/stein/Makefile
1986/stein/README.md
1986/stein/stein.orig.c
1987/hines/README.md
1987/wall/README.md
bin/sgit

Since the original program does not compile and more than one of us
fixed it (the judges and me and probably others as well) and the fix is
in stein.c we remove the stein.orig.c.
Updated Makefile so this would not be a problem. Updated README.md to
not refer to make alt.
..and of course Yusuke Endoh fixed it as well in his commentary.

Remove 1986/stein/stein.orig.c

---

winners.html

Originally 2015/endoh1 was submitted anonymously but it was changed. The winners.html file has under Endoh the entry but it still was under A as 'Someone Anonymous'.

Inconsistent state fix in winners.html

---

1984/decot/Makefile
1984/decot/README.md
1984/decot/decot.c

This will not compile with clang which is actually what gcc is under macOS. Unfortunately clang does not support -traditional-cpp which this entry requires for modern systems.
We would like to thank Yusuke Endoh for the patch to get this to compile with gcc. Thank you very much Yusuke!

Make 1984/decot compile under linux

---

1987/heckbert/Makefile

It was removed because it depends on the .orig.c file that no longer exists but it was a mistake to remove it altogether so I have restored it as requested at
https://github.com/ioccc-src/temp-test-ioccc/pull/24#issuecomment-1451367869.

Restore alt rule in 1987/heckbert/Makefile

---

1992/nathan/README.md
1992/nathan/nathan.c

In nathan.c there was also a typo fix but since it's not the original entry (or any thing like it) it's okay to do this. This is actually the subject of a discussion to be had on GitHub which I'll be addressing in a bit.
In README.md there was also a typo fixed.

Typo fixes in 1992/nathan

---

1992/nathan/README.md
1992/nathan/nathan.c
bin/sgit

Spaces haven't been a problem for some time but I neglected to copy the script to the bin/ directory here.

Remove no longer true comment in big/sgit

---

1992/nathan/README.md
2014/vik/README.md
2020/ferguson2/README.md
years.html

This is to let the viewers know that sometimes the program will display
invalid input. The note is modelled after some of the other entries that
have bug reports. Okay it's also some shameless self promotion but never
mind that! :-)
As well a few minor changes in 2014/vik/README.md mostly being removing
double spaces in favour of single spaces (particularly in the general
text). There were some other formatting fixes as well.
In 2020/ferguson2/README.md I made a few adjustments as well (though I'm
aware of a few more changes in 2020/ferguson[12]/README.md I want to
make).

Point out minor bug in 2014/vik in years.html

---

1992/nathan/README.md
1993/Makefile
2014/vik/README.md
2020/ferguson2/README.md
years.html

Remove no longer relevant text in 1993/Makefile
I added a temporary workaround for a problem in compilation that no
longer is needed but the XXX comment was not removed by mistake.

Remove no longer relevant text in 1993/Makefile

---

2020/ferguson1/README.md
2020/ferguson1/chocolate-cake.html
2020/ferguson1/chocolate-cake.md
2020/ferguson2/.gitignore
2020/ferguson2/chocolate-cake.html
2020/ferguson2/chocolate-cake.md

There were some things I wanted to reiterate and stress even more that are important notes about the cake.
Of course the ferguson2 files are still encrypted with a specific key for the Enigma machine (one of the keys I provided in recode.md / recode.html but which is a challenge though probably pointless since it's also in ferguson1 unencrypted).
Updated 2020/ferguson2/.gitignore: added data files specific to the encryption of the cake files so I can more easily fix it should I need to update the files under 2020/ferguson2 (unlikely as that might be).

Update chocolate cake files (2020/ferguson[12])

---

2019/adamovsky/Makefile
2019/burton/Makefile
2019/diels-grabsch1/Makefile
2019/diels-grabsch2/Makefile
2019/dogon/Makefile
2019/endoh/Makefile
2019/giles/Makefile
2019/lynn/Makefile
2019/mills/Makefile
2019/poikola/Makefile
2019/yang/Makefile
var.mk

As per a request on GitHub the LESSECHO variable has been removed from all the Makefiles. It was only in the 2019 and 2020 Makefiles as well as var.mk.

Remove LESSECHO from Makefiles (including var.mk)

---

2014/vik/README.md
2020/ferguson2/README.md
years.html

As the years.html file will be generated with a tool (yet to be written) having the bug notice will (greatly)? complicate the generation. Thus the bug notice (which I discovered when working on 2020/ferguson2) was moved to 2014/vik/README.md.
But why? Because it is a good idea, I think, to note that although mostly correct, there is a minor problem with it. I don't have a fix for it but whether I ever look at that I do not know.
I also made a minor change in 2020/ferguson2/README.md: changed a full stop to an exclamation mark as it seemed better.

Move 2014/vik bug notice from years to README.md

---

1989/tromp/.gitignore
1989/tromp/Makefile
1989/tromp/README.md
1989/tromp/tromp.alt.c

Previously after the game ran the game segfaulted and the high score file HI was not created. Now the file is created and sorted so that the highest score is at the top. This file was not even created because 'd' was an int and not a FILE * (to show how much has changed over the years!) which popen() returns.
It seemed that popen() could not have the stty re-enabling of echo either so it's now in a system() call (it might have been because of a problem I later fixed as described below).
But reinstating echo did not work right and in fact one could not even type the character 'u'. The important changes here are:
```diff
- 25||i%12<2?7:0;srand(getpid());system("stty cbreak -echo stop u");sigaction(14,v,
+ 25||i%12<2?7:0;srand(getpid());system("stty cbreak -echo");sigaction(14,v,
```
and …

High score file and other bug fixes in 1989/tromp

---

1985/README.md
1985/shapiro/.gitignore
1985/shapiro/Makefile
1989/tromp/Makefile
1989/tromp/tromp.c
1990/stig/README.md
1990/tbr/README.md
1990/westley/README.md
winners.html

The README.md referred to Obfuscated C Code Contest but at this point it
was the International Obfuscated C Code Contest.
Add ALT_{OBJ,TARGET} to 1985/shapiro/Makefile as the alt source code
file was there.

Minor fixes in 1985

---

1985/README.md
1985/shapiro/.gitignore
1985/shapiro/Makefile
1986/holloway/README.md
1987/biggar/README.md
1987/wall/README.md
1988/dale/Makefile
1988/dale/README.md
1989/tromp/Makefile
1989/tromp/tromp.c
1990/stig/README.md
1990/tbr/README.md
1990/westley/README.md
winners.html

Thus one can now enjoy it as long as they have a compiler that supports
it. Unfortunately clang does not but gcc does.

1988/dale requires -traditional-cpp to compile

---

1989/westley/.gitignore
1989/westley/Makefile
1989/westley/README.md
1989/westley/westley.c

Some important notes here should be made. First of all with clang the recommended commands in the README.md (which was also formatted and typo fixed) will seemingly generate the correct files but still only westley.c and ver0.c will compile with clang. With gcc they do compile and seem to work as expected.
However I found a bug in the original code too where ver2 will sometimes segfault. This also goes for the fix (again when compiled with gcc).
I did get ver[123].c to also compile but this seemed to cause invalid output in some of the commands. That being said it might (though I don't think so at this time) have been not knowing exactly what should be displayed. Maybe I will look at it in the future but at least it now works with clang even if not all of the generated files will compile …

Get 1989/westley to compile with clang

---

1989/westley/.gitignore
1989/westley/Makefile
1989/westley/README.md
1989/westley/westley.c
1991/westley/README.md
1991/westley/ttt.sh

Don't assume '.' is in the path.
I note that at least under macOS this game does not work. I'll be
looking at the entries of this year at another time. I just need this
commit in to make some other changes unrelated.
The README.md was also updated - formatting fixes to turn it into a 
markdown file proper.

Fix in 1991/westley/ttt.sh

---

1989/robison/README.md
1989/westley/.gitignore
1989/westley/Makefile
1989/westley/README.md
1989/westley/westley.c
1991/buzzard/README.md
1991/cdupont/README.md
1991/davidguy/README.md
1991/dds/README.md
1991/fine/README.md
1991/rince/README.md
1991/westley/README.md
1991/westley/ttt.sh
1992/albert/README.md

Mostly formatting fixes but some typos were fixed as well. This commit is being made now so I can roll back ad04d21fda51110ce1d6c4ef02bfbb549e65c1ce as it seems to have been a mistake to do. Another way to more easily identify same authors will have to be figured out, perhaps in future files that are yet to be generated. This upcoming commit will hopefully not cause any problems  but if there are any they will be worked out.
Landon and I both came to the same conclusion that although the renaming directories seemed to have been warranted in theory they shouldn't have been renamed after all. This was briefly discussed in issue #3.

Various README.md files updated

---

1992/westley/.gitignore
1992/westley/Makefile
1992/westley/README.md
1992/westley/westley.c

Since the third and fourth args of main() were being used as ints I have made them ints inside main() as clang does not allow the second, third or fourth args to main() to be anything but char **. An important note (which the author noted but which I put in the Makefile as well as under the 'To run:' section) is that the terminal must wrap at 80 columns in order for this to work right. I had to shrink down the terminal size to get to show that this change worked okay - it was the simplest way I could think of to do it.

Fix 1992/westley to compile with clang

---

1996/gandalf/README.md
1996/gandalf/gandalf.c
2000/thadgavin/Makefile

In this case fedora but presumably other linux distributions as well.
Specifically some systems need -lm for linking.

Get 2000/thadgavin to compile under linux

---

1991/brnstnd/README.md
1991/brnstnd/brnstnd.c
1996/gandalf/README.md
1996/gandalf/gandalf.c
2000/thadgavin/Makefile

This was a fun one to fix. There were two invalid operands to binary
expression errors to fix which was resolved with the comma operator.
More fun was dealing with a C pre-processor change. The macro C was used
like e/C to do e/=G but this is no longer allowed. The solution was to
not use the C macro and instead just do the /= etc.

Fix 1999/brnstnd

---

1998/schweikh2/Makefile
1998/schweikh2/README.md
2000/primenum/README.md
2000/primenum/primenum.c

This is because it doesn't compile in all systems though it is supposed 
to I think.

Remove alt target from TARGETS in 1998/schweikh2

---

1984/decot/README.md
1985/applin/README.md
1986/holloway/README.md
1986/marshall/README.md
1986/wall/README.md
1987/westley/README.md
1989/robison/README.md
1989/tromp/README.md
1989/westley/README.md
1990/cmills/README.md
1990/dds/README.md
1990/jaw/README.md
1990/scjones/README.md
1990/tbr/README.md
1990/theorem/README.md
1990/westley/Makefile
1990/westley/README.md
1991/brnstnd/README.md
1992/westley/README.md
1993/jonth/README.md
1996/gandalf/README.md
1998/schweikh2/Makefile
1998/schweikh2/README.md
2000/anderson/README.md
2000/bellard/README.md
2000/bmeyer/README.md
2000/primenum/README.md
2000/primenum/primenum.c

In some files changed the formatting was fixed to be a proper markdown
file.
There were some typos including that some README.md files that linked to
/winners.html#Cody_Boone_Ferguson actually linked to the non-existent
file /years which obviously would not work.
I also added links to the rest of the places I have fixed entries (but
see below) and I did the same for Yusuke Endoh's fixes.
As well apparently one entry I thought he fixed to compile under modern
systems does not seem to so that entry will have to be revisited another
time. That entry was 1993/jonth.
Those are the main changes here if not all of them.

Fix typos, formatting and thank yous (add links)

---

1991/ant/README.md

In the judges' comments add some humour.
Add a try section.
Note that a file is needed for the program to do anything (that is a file that exists) - not specifying an arg will exit without doing anything at all.
Explain how to enter form-feed as this is important.
Fix formatting.

Add to / fix formatting in 1991/ant/README.md

---

2001/herrmann2/README.md
2001/herrmann2/herrmann2.c

This was done by changing the types of the args in main() to be int and char ** respectively and (where necessary) casting the argv (V) to int which was the previous type.
I also noted that prior to and after the fix certain invocations segfaulted though Yusuke Endoh did not have this problem (I linked to his analysis of the entry).

Fix 2001/herrmann2 for clang

---

1996/dalbec/README.md
1996/dalbec/dalbec.c
2001/herrmann2/README.md
2001/herrmann2/herrmann2.c

I made the recommended change by the author so that each number is on a
line by itself rather than one long line. I changed the try section to
stop at the output that was the output noted by the judges. This was
possible with the change of making it a newline rather than a space
after each number.
I had originally proposed the change in commit
9b6b5a0376f3f443d8a8ef0721ae9418d06fdc61 but I did not implement it
because the output of the command versus what the try section included
was misleading (maybe that was correct :-) ) and when looking at Yusuke
Endoh's output I missed that it continued after the number (he had '...'
but I missed it in the long line of output). I linked to his analysis as
well. Thank you Yusuke for confirming it is correct output!

Further fix 1996/dalbec

---

1996/dalbec/README.md
1996/dalbec/dalbec.c
1996/westley/.gitignore
1996/westley/Makefile
1996/westley/README.md
1996/westley/westley.alt.c
1996/westley/westley.c
2001/herrmann2/README.md
2001/herrmann2/herrmann2.c

It always segfaulted (though with the correct input it still showed the
right results) and when argc == 1 it showed an environmental variable.
The body of the for loop can now be empty (or so it appears). I put the
original in westley.alt.c because it has some interesting techniques in
which he wrote about (which I preserved in the README.md file). I also 
put in the original code because I'm not entirely sure if the for loop 
really can be empty in all cases. Certainly it can be in the scripts 
provided but I don't know if there is a valid invocation that would need
it (but in any case it would always segfault with that loop body).
Updated 1996/westley/.gitignore (added westley.alt) and the Makefile so
that make alt will build westley.alt.
Formatting fixes in README.md.

Fix 1996/westley

---

1987/westley/README.md
1988/westley/README.md
1989/westley/README.md
1990/westley/README.md
1991/westley/README.md
1992/westley/README.md
1994/westley/README.md
1996/dalbec/README.md
1996/dalbec/dalbec.c
1996/westley/.gitignore
1996/westley/Makefile
1996/westley/README.md
1996/westley/westley.alt.c
1996/westley/westley.c
2001/herrmann2/README.md
2001/herrmann2/herrmann2.c
2001/westley/.gitignore
2001/westley/Makefile
2001/westley/README.md

The main link was dead but looking at the Internet Wayback Machine I
found that he changed domains and it's still valid. One entry had a
different URL but with a quick check I could not determine that it had
anything to do with him so I changed it to his own domain (which I
verified is his).
The 2001/westley/.gitignore was also updated as it has other source
files that are generated by the commands in the try section.

Fix Westley's entries (dead link, .gitignore)

---

1987/westley/README.md
1988/westley/README.md
1989/westley/README.md
1990/westley/README.md
1991/westley/README.md
1992/westley/README.md
1994/westley/README.md
1996/august/.gitignore
1996/august/README.md
1996/dalbec/README.md
1996/dalbec/dalbec.c
1996/eldby/README.md
1996/huffman/README.md
1996/jonth/README.md
1996/rcm/README.md
1996/schweikh1/Makefile
1996/schweikh1/README.md
1996/schweikh2/README.md
1996/schweikh3/README.md
1996/westley/.gitignore
1996/westley/Makefile
1996/westley/README.md
1996/westley/westley.alt.c
1996/westley/westley.c
2001/herrmann2/README.md
2001/herrmann2/herrmann2.c
2001/westley/.gitignore
2001/westley/Makefile
2001/westley/README.md

Update the README.md files - at least with those not in a previous
commit. The updates mostly include formatting (make them markdown) but
probably also typos here and there. More probably has to be done with 
these files.
The 1996/august/.gitignore was updated as well with a file that is
generated by one of the suggested commands.

1996 fixes and updates

---

1986/holloway/Makefile
1987/westley/README.md
1988/westley/README.md
1989/westley/README.md
1990/westley/README.md
1991/westley/README.md
1992/westley/README.md
1994/westley/README.md
1996/august/.gitignore
1996/august/README.md
1996/dalbec/README.md
1996/dalbec/dalbec.c
1996/eldby/README.md
1996/huffman/README.md
1996/jonth/README.md
1996/rcm/README.md
1996/schweikh1/Makefile
1996/schweikh1/README.md
1996/schweikh2/README.md
1996/schweikh3/README.md
1996/westley/.gitignore
1996/westley/Makefile
1996/westley/README.md
1996/westley/westley.alt.c
1996/westley/westley.c
2001/herrmann2/README.md
2001/herrmann2/herrmann2.c
2001/westley/.gitignore
2001/westley/Makefile
2001/westley/README.md

It works fine with modern compilers now.

Remove obsolete note in 1986/holloway/Makefile

---

2006/monge/Makefile
2006/monge/README.md
var.mk

The problem was that SDL2 removed two functions that are used in this code. Since SDL1 is still available and since changing it to SDL2 is more complicated than it is worth I've decided to keep it as SDL1, changing sdl2-config to sdl-config. Nevertheless it actually segfaults or it does at least in macOS. I have not tested it in linux but I will in time. At this point I will try debugging it but at least now it will link.
Typo fixes in README.md and update the reference to SDL2 to be SDL1. I noted that currently it does not work at least under macOS. I've not yet put it in the bugs.md file but will in time if I don't get it to work (again once I test it under linux).

Get 2006/monge to link (won't work on anything but x86/x86_64 or at least not on arm64)

---

2005/giljade/Makefile
2005/giljade/README.md

I've discovered that this entry has to have the optimiser disabled and it also requires 32 bit. I believe the 32-bit is to do with the many bitwise operations but the size of the ints are different. This is just a hunch though from what I saw earlier when debugging it. The fact it's 32-bit only (at this time?) means it won't easily compile under macOS as Apple has made it hard to compile 32-bit programs.
It might be possible to change the size of the ints to fix this problem but it of course could also be entirely true that I'm wrong here. I've not added this to the bugs file but perhaps it should be added.

Get 2005/giljade to work

---

2005/giljade/Makefile
2005/giljade/README.md
2005/mynx/README.md
2005/mynx/mynx.c
bugs.md

Though this will not work as is I have changed the code to scan for
https as well (it exited before). This is so if someone comes up with a
clever command line to make it work it can. A secure connection has to
be established before http commands can be given but now it at least can
connect (though it's been a while since I've played with sockets so
maybe I'm forgetting some detail - one does have to specify the port but
I gave an example in the README.md file for that).
In the README.md I pointed out that one has to specify http:// (or else
https though with the caveat noted above). I also explained how to 
specify an alternative port.
I also noted the https issue in the bugs.md file in the INABIAF section 
('it's not a bug it's a feature').
As well I changed the try command in the entry …

Minor updates to 2005/mynx

---

2000/dlowe/README.md
2000/dlowe/dlowe.c

The problem was that they renamed 'na' to 'PL_na' so the code did not compile. I note that it segfaults in macOS but I've not had a chance to look into that yet. It works fine in linux.

Fix 2000/dlowe for more recent perl versions

---

.gitignore

Discovered more globs for vim swap files that somehow were in a directory in my local repo. These were discovered as I'm working on getting the directory clean.

Update root .gitignore

---

1998/schweikh3/README.md
1998/schweikh3/samefile.1.dupe

The formatting of README.md has been changed.
Added a try section and a duplicate file to the directory (copy of samefile.1) so that the users can see how it looks. The copy is samefile1.1.dupe. Yes dupe means to deceive and also a victim of being deception but it also means duplicate. For the IOCCC though it actually makes sense if a file (in fact all the source files :-) and thus you're a dupe! :-)

Update 1998/schweikh3/README + add dupe file

---

1998/schweikh3/README.md
1998/schweikh3/samefile.1.dupe
2004/gavare/.gitignore
2004/gavare/README.md

It referred to ./prog but in 2004 prog was not the target but rather the
winner handle was.
Updated .gitignore: add ioccc_ray.ppm which the README.md try section
refers to.

Typo fix in 2004/gavare/README.md

---

1998/schweikh3/README.md
1998/schweikh3/samefile.1.dupe
2004/gavare/.gitignore
2004/gavare/README.md
2006/sloane/README.md
2006/sloane/sloane.c

The problem was that the second arg was not of type char ** but an
implicit int and broken record though I am clang forces the types to be
correct without any option to disable this.
As it happens though the second arg is not even used so I removed it as
clang does allow this for some reason. This helps with keeping the
original format as close as possible. This triggers a different warning
but that's okay.
I also added a warning to the README.md about how it is a lot of change
in text very quickly as this could cause some problems for some people.

Fix 2006/sloane for clang

---

2001/bellard/.gitignore
2001/bellard/README.md
2001/bellard/bellard.c
2001/bellard/bellard.otccex.c
bugs.md

This still crashes and may very well not work even if it doesn't but I cannot determine that. I just fixed the initial segfault when opening the file. I believe it will take much debugging, a 32-bit system to test it on and also a knowledge of the ELF format. There might be other things but I believe those are the minimum requirements.
I did fix the supplementary program bellard.otccex.c so it does not segfault and seemingly it works too (I didn't really evaluate that the output is correct but it does process the args anyway).
I updated bugs.md to note that this entry does not work and any help would be appreciated.

Partially fix 2001/bellard

---

2015/hou/Makefile

As in there were spaces instead of tabs.

Fix Makefile missing separator in 2015/hou

---

1988/phillipps/README.md
1988/phillipps/phillipps.c
1988/spinellis/.gitignore
1988/spinellis/Makefile
1988/spinellis/README.md
1988/spinellis/spinellis.alt.c
bugs.md

This was fun to do even though it's also a very simple one liner plus
special handling in the Makefile (the latter part is so you can use it
the exact same way as the original). The original code just #included
/dev/tty. This does something just as magical! It can be used like:
make alt
^D
./spinellis
For instance:
make alt
#include <stdio.h>
int main() { puts("hello world"); }
^D
./spinellis
Now those with clang can enjoy the entry without any functional
difference.
I have a very twisted point to make about the original version and this
version too: with a very slight change one can actually make a C++
version. Ick! :-)

Add 1988/spinellis/spinellis.alt.c for clang

---

1988/phillipps/README.md
1988/phillipps/phillipps.c
1988/spinellis/.gitignore
1988/spinellis/Makefile
1988/spinellis/README.md
1988/spinellis/spinellis.alt.c
1989/jar.1/README.md
1989/ovdluhe/README.md
bugs.md

Split judges' comments to be a to build, try and judges' comments. The 
to build section already existed.
Also added ./ in front of the binary name so commands would actually 
work.

Minor fixes to 1989/ovdluhe/README.md

---

1988/phillipps/README.md
1988/phillipps/phillipps.c
1988/spinellis/.gitignore
1988/spinellis/Makefile
1988/spinellis/README.md
1988/spinellis/spinellis.alt.c
1989/jar.1/README.md
1989/ovdluhe/README.md
1989/paul/Makefile
1989/paul/README.md
1989/paul/paul.c
bugs.md

The problem was that the int * needed to be a long *. It became apparent
to me when evaluating it with lldb as I noticed a pointer was long, not
an int. This does not cause a problem with linux. I have no 32-bit
system to test but I don't believe this will be an actual problem.

Fix segfault in macOS with 1989/paul

---

1991/dds/Makefile
1991/dds/README.md
1991/dds/dds.c

This was a fun one! There were up to three segfaults fixed and with clang the generated file could not be compiled. The latter part was fixed with (unfortunately) something of a hack. I explain below and in the README.md how to change that part to use just cc if you have gcc (macOS gcc is actually clang).
The first segfault which was always triggered was due to the code
*q>' '&&(*q)--;
This seems odd at first glance but it's pointing to 's' which was read-only memory as a char *s.  It's now a char s[]. The second and third segfaults were caused if a file was not specified (or it the one specified did not exist or couldn't be opened for some reason) and if the output file could not be opened for writing. The allowing the generated code to compile with clang is something of a hack …

Fix 1991/dds

---

1988/phillipps/phillipps.c
1992/adrian/README.md
1992/adrian/adrian.c

There was only one call to gets() and one call to fgets(). gets() reads
from stdin so the fgets() call has to as well. But why was it using
gets() and not fgets()? My guess is because fgets() stores the final
newline which means that the output had extra lines. The entry was
relying on this string NOT having a newline printed after the line
matched! Having a newline in turn broke the generation of some output
like that of adhead.c. Thus if fgets() != NULL we trim off the trailing
newline first. This allows the entry and all generated code to compile
successfully (adhead.c ended up having a multi-line macro messed up
because of an empty line after the \ at the end of the line). Since
gets() does not store the final newline and since we trim that off the
code is functionally equivalent but …

Make 1992/adrian use fgets() not gets()

---

1988/phillipps/phillipps.c
1991/dds/.gitignore
1991/dds/Makefile
1991/dds/README.md
1991/dds/dds.alt.c
1992/adrian/README.md
1992/adrian/adrian.c

The dds.c now does return system(q-6); and the dds.alt.c does the return
system("make a");. This way those who have gcc (more people than not
most likely) they can use it like originally designed. Those with clang
can use the alt target in almost the same way only instead of a.out use
just a.
Updated the README>md to explain everything.
Updated the .gitignore with some globs that should have been there all
along ('a' and 'dds.alt' being the ones that are new).

Improve fix on 1991/dds - add alt code

---

2018/vokes/README.md
2018/yang/.gitignore
2018/yang/README.md

Update .gitignore with files created by the commands in the README.md
(and some that can be with the right combinations that are not noted).
Typo and formatting fixes in README.md.

Fixes in 2018/yang

---

2018/poikola/Makefile
2018/poikola/README.md
2018/vokes/README.md
2018/yang/.gitignore
2018/yang/README.md

I had put in the README.md that the entry needs XQuartz for macOS
because it uses X11 but this is not true (I should have known as this
was my favourite entry that year in the preview and it still is). The
point was that Terminal.app of macOS might not work. This has been
corrected.
As it happens it appears to work fine for me which I noted in the 
README.md. 
Formatting fixes, slight improvements and possibly typo fixes.
Add missing make rule docs that was referred to in the README.md but was
missing from the Makefile. It was found in the 
archive/2020/poikola/Makefile.

Fixes in 2018/poikola

---

2018/mills/README.md
2018/poikola/Makefile
2018/poikola/README.md
2018/vokes/README.md
2018/yang/.gitignore
2018/yang/README.md
faq.md

Typo fixes, formatting fixes and other things.
Updated faq.md with a note that this entry can also be used to run 
1984/mullender.

Fixes to 2018/mills/README.md

---

2018/giles/README.md
faq.md

Mostly this update is about SDL and SDL2 and how to compile and run entries that make use of it. But I first saw reference to this idea in 2018/giles/README.md.
I added to macOS section MacPorts which is another very popular package manager for macOS (I personally don't like Homebrew and I use MacPorts instead).
Minor fixes in 2018/giles/README.md (formatting plus make a URL an actual link).

Update 2018/giles + faq.md

---

2018/endoh2/README.md

These were found on Yusuke Endoh's analysis of all the IOCCC winning entries. I kept the ASCII art he had for the comments but his comments for the entry seem like a good idea to include especially as he wrote them himself and they add to the entry itself.

Add author comments to 2018/endoh2/README.md

---

2018/ciura/Makefile
2018/ciura/README.md
2018/endoh2/README.md

Formatting fixes and possibly typos (but mostly formatting).
On bold code blocks: I removed the bold because it appeared that some of
the formatting was messed up. I think this is okay though rather than 
trying to fix the formatting of bold code blocks.
Set alt related target variables in Makefile so that make alt actually 
works.

Fixes in 2018/ciura/README.md + Makefile

---

1994/ldb/README.md
1994/ldb/ldb.c
bugs.md

I had already fixed this entry to compile with modern compilers but a problem existed where lines longer than 231 characters (which generally would not happen but is not impossible) would overflow the buffer. Now it uses fgets() so this does not happen. A couple notes about this though.
It right now does print a newline after the output unless the line length is in fact 231 characters. This seems like a worthy compromise though. In time I hope to address this so that it does not ever print a newline (a blank line notwithstanding which does happen and is part of the entry).
The second thing to be aware of is just a subtlety with the entry: what happens with a line of length 394? What you'll find is that it might print the first 231 characters or it might print the last 163 characters plus …

Make 1994/ldb use fgets()

---

1994/ldb/README.md
1994/ldb/ldb.c
1994/schnitzi/README.md
bugs.md

Formatting fixes in README.md.  Also refer to bugs.md file where I give
hints on the magic of the entry in order that it can hopefully be made
to use fgets() and have an increased buffer size.
Updated bugs.md about this entry with an important point about the
fgets() / buffer size issue: it can very easily be made to use fgets()
and having an increased buffer size. But the program is supposed to be
able to be fed its own source code and generate output that can do the
same thing and is compilable. Changing the code to use fgets() will
cause compiler errors in the generated output. As well even though I
changed the buffer size it is not generated in the output when feeding
the program its own source code.
In the bugs.md file I also pointed out just how sensitive this program
is (by …

Fixes and updates in 1994/schnitzi

---

1994/ldb/Makefile
1994/ldb/README.md

Remove warning from Makefile that this entry uses gets() as this is no longer true.
Update README.md pointing out that this will print a newline after the output.

Minor fixes to 1994/ldb

---

1994/ldb/Makefile
1994/ldb/README.md
2019/ciura/README.md
2019/ciura/de.sh
2019/ciura/getwords.sh
2019/ciura/it.sh
2019/ciura/pl.sh
2019/ciura/ru.sh
bugs.md

Fixed scripts to use LC_ALL=C. This was necessary especially for de.sh 
as the tr invocation had invalid bytes. Similar requirement was in
getwords.sh. But since I changed the one I decided to change the others 
too.
I note that both before and after the fix the alternative languages do 
not work under macOS or fedora linux. I don't know if this is the wrong
locale (the author does suggest UTF-8) or the dictionary or something 
else but I noted it anyway.
I added this latter problem to bugs.md. Whilst at it I added some notes
and fixes to bugs.md.

Fixes in 2019/ciura + update to bugs.md

---

1994/ldb/Makefile
1994/ldb/README.md
2019/ciura/README.md
2019/ciura/de.sh
2019/ciura/getwords.sh
2019/ciura/it.sh
2019/ciura/pl.sh
2019/ciura/ru.sh
2019/diels-grabsch1/.gitignore
2019/diels-grabsch1/README.md
2019/diels-grabsch1/guidelines.txt
2019/diels-grabsch1/prog.c
2019/diels-grabsch2/README.md
2019/diels-grabsch2/prog.c
bugs.md
faq.md

Make the author's statement that it compiles cleanly true (just like
with diels-grabsch1) :-)
Typo fixes in README.md.
Format fixes in README.md.

Fixes in 2019/diels-grabsch2

---

2019/endoh/.gitignore
2019/endoh/Makefile
2019/endoh/README.md

Remove optimisation from Makefile and add -g to compile line as it's a backtrace quine.
Add to .gitignore prog2.c as the author's comments suggest a command that will create it.
I believe that the llvm should be lldb as that's the debugger (macOS) and the llvm tools are not.
Format fixes in README.md.

Fixes in 2019/endoh

---

2019/endoh/.gitignore
2019/endoh/Makefile
2019/endoh/README.md
2019/giles/README.md
2019/karns/.gitignore
2019/karns/Makefile
2019/karns/README.md

A strange problem is that although it worked with macOS and linux for me
numerous times in the past it stopped working under both. I went to try
and figure it out but when disabling the optimiser for debug symbols the
problem vanished. Changing it back to -O3 and the problem reappeared
both with macOS and linux. Thus it appears that the entry should not
have -O level > 0. I'm not sure if this is the same issue the author
reported where it sometimes segfaults but I did not try and figure it
out either (in any event the crash disappeared when -O0 was specified so
it'd be harder to debug).
Added to .gitignore the file the author noted the program is called (as
the command he gives creates). To make it easier I just made it a
symlink to prog.
Fixed formatting in README.md.

Fix 2019/karns

---

1992/gson/README.md
2019/endoh/.gitignore
2019/endoh/Makefile
2019/endoh/README.md
2019/giles/README.md
2019/karns/.gitignore
2019/karns/Makefile
2019/karns/README.md

By accident I stated that I changed this entry to not use gets() but
instead fgets(). This is unfortunately not true because of the way
gets() is used. I have now made it (I hope) a bit clearer. I also
pointed out that it's theoretically safe. Since it uses gets() which
comes from stdin ARG_MAX should be relevant. Thus I made the buffer size
ARG_MAX+1. But something I am not so clear on is whether or not ARG_MAX
is the entire command line or a single argument. Looking did not help
here as some say one thing and others say the other. Doing xargs
--show-limits and also checking the value of ARG_MAX suggests that it's
for the entire command but I don't know for sure of that. Nevertheless 
it is safer than it was if not completely safe.

Clarify gets()/fgets()/ARG_MAX in 1992/gson

---

all/README.md
all/summary.txt

Reword the lines in the form of 'There is no YYYY IOCCC contest' (which
was unintentionally redundant with IOCCC contest for last two words 
contest contest :-) ) to be instead 'There was no IOCCC in YYYY'.
Added the years 2021 and 2022 to the file (in the form as above).
A question that remains is whether or not this file should be turned
into a markdown file. On the one hand a markdown file might be nice if 
rendered to html for browsers but a text file is nice for text editor 
(obviously vim :-) ).

Fixes in all/summary.txt

---

1984/anonymous/README.md
1984/anonymous/anonymous.c
1984/decot/Makefile
1984/decot/README.md
1984/decot/decot.alt.c
1984/decot/decot.c
all/README.md
all/summary.txt
bugs.md

This one was also fun. By chance I noticed the '{' next to the read()
function. Easy enough to miss when very tired. Anyway I had to prototype
that function as 'int read(int, void *, int)' and then in that function,
in the call to write(2), cast 'i' (which is the void *) to int. This 
fixes the problem and now it works with macOS and linux.
Removed this entry from bugs.md.

Fix 1984/anonymous for macOS (clang?)

---

1986/wall/.gitignore
1986/wall/Makefile
1986/wall/README.md
1986/wall/wall.alt.c
bugs.md

This was also a lot of fun to fix. It took a fair bit of tinkering but it was a lot of fun to figure out and now it works like it does with -traditional-cpp!
Removed this entry from the bugs.md file as it now works.
Also added to the bugs.md a minor clarification about another entry that is in status INABIAF (about warnings).
--
I forgot to add that the original (since it's so wonderfully strange) is in `wall.alt.c` so people can enjoy just how twisted it is.

Fix 1986/wall to no longer need -traditional-cpp

---

bugs.md

When fixing the entries that did not work I went a bit too far and fixed other problems as well. This should not have been done and there was ever a doubt in my mind about it. The coming commits will be undoing these changes (though the vast majority that were modified were not in this category). An INABIAF now includes segfaults both that are documented and not documented unless it prevents the entry from working. It also includes other things that are both documented and not documented.
After all it's not like the winning entries are meant to be code that is maintainable or good quality (even if they work well). One might even say that they should be buggy! :-) (and in some cases which were never touched they're supposed to crash or do this or that).
In the case of gets() versus fgets() …

Redefine INABIAF status

---

1984/laman/Makefile
1984/laman/README.md
1984/laman/laman.c
bugs.md

As part of redefining INABIAF this is necessary. The README.md and 
Makefile both warn about the crash.

Undo segfault fix in 1984/laman w/o arg

---

1984/laman/Makefile
1984/laman/README.md
1984/laman/laman.c
1994/schnitzi/Makefile
1994/schnitzi/README.md
1994/schnitzi/schnitzi.alt.c
1994/schnitzi/schnitzi.c
bugs.md

As part of redefining INABIAF the entry now has an equivalent
functionality with the generated output. The bugs.md file still has
hints on how to get this to use fgets() (for why this is helpful see
that file). As a starting point I have the original buffer size increase
in schnitzi.alt.c as it would be useful to see how it works and to maybe
get the entry to use fgets(). Unfortunately keeping it using gets() is a
potential problem but changing it to fgets() is also a potential problem
(this goes for all of the entries that use or used gets()). This entry
however still uses gets(). The change is the smaller buffer size which
means that the entry can not handle big files. 
The Makefile and README.md now refer to the small buffer size.

Undo buffer size increase in 1994/schnitzi

---

1990/theorem/.gitignore
1990/theorem/README.md
1990/theorem/theorem.c
2019/mills/README.md
bugs.md

In this case these were not features.
The most important bug fix actually prevented the entry from working
properly: the generated code for the Fibonacci sequence just printed 0
over and over again. Added a segfault prevention here as it seemed like
if I'm going to fix it I might as well fix it properly. Removed this bug
from bugs.md.
A set of possible issues with the char m[][] array was also including 
the size limit in the fgets() calls (that was my fault due to missing 
the proper type of m at the time). Still might be good to test with 
longer lines of input. Commands with known output are correct 
nonetheless.
The other bug was due to the gets() to fgets() change where blank lines
were added where they shouldn't be. Now one can do ls | ./sorter and get
no blank lines after each file …

Fix bugs in 1990/theorem

---

1990/theorem/.gitignore
1990/theorem/README.md
1990/theorem/theorem.c
2018/README.md
2019/mills/README.md
bugs.md

For some reason this was missing from the repository. I was certain that 
there was one so I looked at my archive and found in the winner preview
repo for 2018 that there was indeed a README file (README.markdown).
This has been added as 2018/README.md. It felt important that this was 
added back.
I did NOT update the 2018 archive tarball as I'm not sure what to even 
call it - perhaps just README.markdown - but also because I'm not sure
what the status is of my archive/2018 is.
I fixed the formatting to match the style that is being used in this
repo.

Restore missing 2018/README.md from 2018 preview

---

1990/baruch/Makefile
1990/baruch/README.md
1990/baruch/baruch.c
1990/theorem/README.md

Fixed formatting in README.md.
Add alt code based on authors' suggestion except that the string
replacement was not done because it seems like the output would be not
better but worse. There's a joke in the alternate code section of the
README.md file.

Minor fixes + alt code in 1990/baruch

---

.gitignore
1990/baruch/Makefile
1990/baruch/README.md
1990/baruch/baruch.c
1990/theorem/README.md

Add readme.html to top level .gitignore + sort it
The rationale behind it is that it's useful to sometimes use discount 
(or rdiscount) to test that the README.md file formatting is correct but
readme.html is the obvious target file. This glob can be removed at a 
later date.
Sort .gitignore file.

Add readme.html to top level .gitignore + sort it

---

1990/theorem/Makefile
1990/theorem/README.md
1990/theorem/theorem.c
bugs.md

Due to a misunderstanding between Landon and me after some discussion on GitHub it was recommended that I reapply this fix so I have done so.
I've updated the bugs.md file to change the definition of INABIAF (it's not a bug it's a feature) as well as adding another known bug with this entry to the file (this has also been added to README.md).
In bugs.md I also added towards the top a note to the winning authors about fixes applied to their entries. Particularly if an author objects to the fix we'll be happy to undo it even if it impacts the usability of the program. There there is an apology too. We know there's a fine line and although we have tried to use good judgement invariably some will be the wrong decision. Thank you for understanding and apologies!

Reapply no arg check in 1990/theorem

---

1988/spinellis/README.md
1990/dds/README.md
1990/theorem/Makefile
1990/theorem/README.md
1990/theorem/theorem.c
1991/dds/README.md
1998/schnitzi/README.md
1998/schnitzi/schnitzi.c
bugs.md

After discussing it with Landon it was recommended that these fixes be
reapplied.
Updated bugs.md wrt this.
README.md has had formatting fixes as well.
Updated URL for author as it has changed. It's very little on his page
and the only page that suggests it is his is the ioccc.html page. I
couldn't find anything else.

Reapply segfault fixes in 1998/schnitzi

---

1988/spinellis/README.md
1990/dds/README.md
1990/theorem/Makefile
1990/theorem/README.md
1990/theorem/theorem.c
1991/dds/README.md
1993/schnitzi/README.md
1994/schnitzi/README.md
1995/schnitzi/README.md
1998/schnitzi/README.md
1998/schnitzi/schnitzi.c
2004/schnitzi/README.md
bugs.md

As noted in commit 3958bbdb04081a7704619f22520f02bb0005c37e:
Updated URL for author as it has changed. It's very little on his
page and the only page that suggests it is his is the ioccc.html 
page. I couldn't find anything else.

Fix Mark Schnitzius's URL in README.md files

---

1995/cdua/Makefile
1995/cdua/README.md
1995/cdua/cdua.c

As modern systems are so much faster it's hard to see the maze being solved in real time so I added a call to usleep() with a macro defined in the Makefile (a macro in case someone finds it too slow or too fast or wants to do some strange experiment like setting it to 40000 which I actually tried). Called Z it defaults to 3000. To change it do something like:
make CFLAGS+="-DZ=1500" clobber all
To do this I had to remove the -include ... from the Makefile and instead add the proper #includes to the source code as the += was not concatenating to the CFLAGS.
This makes the entry a bit more enjoyable with current systems. There still is a known issue that I'll look at again another time.

Make 1995/cdua easier to see with modern systems

---

1995/cdua/Makefile
1995/cdua/README.md
1995/cdua/cdua.c
1995/garry/.gitignore
1995/garry/Makefile
1995/garry/README.md
1995/garry/garry.alt.c
tmp/winners.csv

Formatting fixes.
Remove address as there was a formatting issue. Besides it's probably
inaccurate by now. Kept the country.
There was a stray partial sentence in the judges' remarks that strayed
in (or to be more correct it was never moved properly) when I added the
try section. It's now been removed.
URL is dead so used the Internet Wayback Machine. Updated the URL in the
winners.csv file too. That might need to be done with others that I've
recently fixed but that will have to be checked on another time.

Fix 1995/garry/README.md and URL in winners.csv

---

1995/cdua/.gitignore
1995/cdua/Makefile
1995/cdua/README.md
1995/cdua/cdua.alt.c

This is to both preserve the original code (notwithstanding the bug fixes I made) and also to allow you to compare the two versions. I now have played with even slower values and I recommended trying it to see different results in the README.md (which of course describes the alt code, how to use it and reconfigure it etc.).
It's encouraged to use this version but it's also recommended to try the original version as well.
Updated Makefile to do this. This reinstates the -include stdio.h -include unistd.h in CINCLUDE but the -DZ=3000 is still in the CDEFINE variable.  Why? It doesn't hurt having it in the cdua.c compilation and it makes it easier to find. The cdua.alt.c still uses #include directives so that redefining CFLAGS at compilation does not cause any problems.
Thank you Landon for …

Move usleep() version of 1995/cdua to cdua.alt.c

---

1995/cdua/.gitignore
1995/cdua/Makefile
1995/cdua/README.md
1995/cdua/cdua.alt.c
tmp/example.dot_winner.json

Also changed "c" to "C" as it seemed better to honour the language (though honour is not really the best word maybe).

Typo fixes in example.dot_winner.json

---

1991/westley/README.md
1991/westley/ttt.sh

Make it so that the warnings/errors (i.e. stderr) of the compilation (as well as the echo saying it's going to compile) not show unless -e is used. This is because the warnings kind of ruin the experience.
Updated README.md to explain this.

Improve 1991/westley/ttt.sh

---

bin/sgit
bin/sgit.README.md

Add warning about use of -o n without -I depending on the sed command.
Updated version.
The README.md I'm not sure about but it feels like it might belong there anyway. It can be removed if it does not seem useful or it is out of context (and it might very well be). Nevertheless I think it's important that the warning be there so it's good to update sgit here as well.

Update sgit + add sgit.README.md

---

1990/stig/Makefile

This is because not all systems have zsh installed. Why not bash? Because it returned a syntax error. It might be possible to get it to work with bash but there's a chance that a system might not have bash. Of course SHELL is set to bash so that might be an irrelevant point. I know not all sh implementations are good so that's another thing to consider but for now it'll do.

Fix 1990/stig/Makefile to use ${SH}, not ${ZSH}

---

1991/dds/README.md
1991/dds/dds.alt.c
1991/dds/dds.c
bugs.md

I noticed that I unfortunately fixed two segfaults that should not have been fixed: if the input file cannot be opened for reading or the output file cannot be opened for writing this program will crash. Changed both dds.c and dds.alt.c (which I added to work with clang). The original fix that allows this entry to work at all (segfaulted always) remains in both versions.
Updated README.md and bugs.md. In bugs.md I also added a note that the compiled code uses gets() not fgets() - whatever it might be worth.

Undo two segfault fixes in 1991/dds - INABIAF

---

1991/dds/README.md
1991/dds/dds.alt.c
1991/dds/dds.c
bugs.md
faq.md

In other words after running a curses program (ANSI escape codes can 
also cause problems) the terminal can be quite insane; echo might be
disabled as a simpler example but many worse more annoying problems can
occur.
The simplest way is to run reset. This will restore everything though 
it'll clear the screen (clear command will not fix any problems but just
clear the screen). For echo disabled stty echo should work. Sometimes
you can get away with doing stty sane.
Now these are in the faq.md. I wrote more about this in 2020/ferguson1 
but that doesn't really matter other than it was the inspiration for 
this entry (which I think is a good idea to include).

Add entry to faq.md about terminal sanity

---

1991/dds/Makefile
1991/dds/README.md
2012/endoh2/README.md
2012/endoh2/endoh2.c
2012/endoh2/everything.sh
2012/grothe/README.md
2012/hamano/README.md
2012/kang/README.md
2012/vik/.gitignore
2012/vik/Makefile
2012/vik/README.md
2012/vik/vik.alt.c
2012/zeitak/README.md
bugs.md
tmp/winners.csv
winners.html

Well 'first target' :-) but git commit likes to have no more than 50 
columns for the summary.
The problem: if one did for instance
make CC=clang clobber all
they would get something like:
Makefile:89: *** recipe commences before first target.  Stop.
because of a missing \ at the end of a line in the middle of setting (or
appending to) CSILENCE.

Fix recipe commences before 1st target in 1991/dds

---

2006/toledo2/.gitignore
2014/maffiodo1/Makefile
2014/maffiodo1/README.md

The build requires SDL1, not SDL2. Linker errors otherwise.
Format fix and typo fix README.md.

Fix build + format README.md of 2014/maffiodo1

---

1984/mullender/README.md
1985/august/README.md
1985/lycklama/README.md
1985/sicherman/README.md
1986/wall/README.md
1988/dale/README.md
1988/litmaath/README.md
1988/phillipps/README.md
1988/reddy/README.md
1988/robison/README.md
1988/spinellis/README.md
1988/westley/README.md
1989/jar.2/README.md
1989/ovdluhe/README.md
1989/paul/README.md
1989/robison/README.md
1989/roemer/README.md
1989/vanb/README.md
2001/anonymous/README.md
2001/ollinger/README.md
2004/kopczynski/README.md
2005/mynx/README.md
2005/persano/README.md
2005/sykes/README.md
2005/toledo/README.md
2006/toledo2/.gitignore
2014/maffiodo1/Makefile
2014/maffiodo1/README.md
bin/check_awards.sh
tmp/year-auth-prize.csv

This was done quite easily with a bit of thought. I generated a script
that could be modified in vim if necessary (as it turned out to be
though some of it could have been generated too but I did not think of
everything at once and it is a hack).
This is how I generated it:
echo '#!/bin/bash' > bin/check_awards.sh ; ( while read -r g ; do echo grep "$g"; done < <(sed -e 's,_,/,g' -e 's/"/\\"/g' tmp/year-auth-prize.csv | awk -F, '{print grep "\x22" $2 "\x22" " " $1 "/" "README.md"}' ); ) >> bin/check_awards.sh
Then I modified the file (again this was a hack to make it easier and 
quicker and better for being tired too) in vim to make the grep use -Hc 
so I could pipe it to 'grep :0'. This found the files without the right
award. So the final command was: 
sh bin/check_awards.sh |grep :0 …

Fix consistency of award titles

---

1984/mullender/.gitignore
1984/mullender/Makefile
1984/mullender/README.md
1984/mullender/a.out.h
1984/mullender/gentab.c

This included adding the 'a.out.h' as not all systems have it and also I wanted it as close to the original as possible so I got a copy (https://raw.githubusercontent.com/dspinellis/unix-history-repo/Research-Release/usr/include/a.out.h) from the fabulous Unix History repo (https://github.com/dspinellis/unix-history-repo) which I highly recommend anyone interested in the evolution of Unix to check out!
... and yes: the repo is under the account of Diomidis Spinellis who is a previous IOCCC winner!
To generate the tool run `make gentab'. Note that keeping the short ints short generates a lot of negative numbers but this might or might not be a problem: the original mullender.c has a negative number for instance.
Updated .gitignore and README.md files.

Add table generator to 1984/mullender from author

---

1984/mullender/.gitignore
1984/mullender/Makefile
1984/mullender/README.md
1984/mullender/a.out.h
1984/mullender/gentab.c
tmp/author-wins.csv

As Landon noted on GitHub:
One of the key elements that we are missing from the SQL command set 
is a way to tie a winning author handle to the entry handles..
We think what is needed is an CVS file, perhaps, tmp/author-wins.csv 
that connects the author handle with the winning entries that they 
won.
The proposed tmp/author-wins.csv will be used to generate the list 
of winning entries that a given author has submitted. This will be 
used to generate the per-author JSON files.
As I just wanted to start it and I've not given any thought whatever at
how to generate it (except very briefly yesterday morning) I've only for
now included what Landon did. Once I've generated it all it'll be sorted
maybe by year or maybe by surname: that's to be determined later but 
this is a nice start at …

Add initial tmp/author-wins.csv

---

1984/mullender/.gitignore
1984/mullender/Makefile
1984/mullender/README.md
1984/mullender/a.out.h
1984/mullender/gentab.c
bin/extract_winner_handles.sh
tmp/author-wins.csv

This is the first step in making the new CSV file that identifies which
entries each author won. To get a list of all winning handles run
bin/extract_winner_handles.sh
...which is a very simple pipeline (that could probably be simplified 
further) acting on winners.html.

Add script to extract winner handles

---

2001/anonymous/.gitignore
2001/anonymous/Makefile
2001/anonymous/anonymous.sh

Using a script running ./anonymous will run the program after modifying it. This is a temporary workaround and it's not certain when this will be changed back or fixed if it even can be. I am aware of some things that might make it work IF it actually IS supposed to run the program that it's run on (an additional reading of README.md suggests this might indeed be the case). In any event the entry DOES modify 32-bit binaries (bit twiddling) and then running the script (made a copy of anonymous.sh where anonymous.c is compiled to anonymous_tmp) it will run the program after doing this, assuming that the program to modify actually exists.
It should be noted that because things have changed so much it is hard to know if the modifications to 32-bit ELF binaries are correct but if nothing else …

Add temporary workaround to 2001/anonymous

---

2001/anonymous/try.me.sh

For some reason the check that exists has opposite meanings in macOS and linux so instead of checking the status of make I check if the file exists after a make clobber all.

Fix 2001/anonymous/try.me.sh

---

2001/anonymous/Makefile

This is important so that make does not fail. Apparently I had a copy of cpp.c still in my directory so this was not detected.

Remove cpp from 2001/anonymous/Makefile TARGET

---

2001/anonymous/Makefile
2001/anonymous/README.md
2001/anonymous/anonymous.c

It now uses the G macro that was unused in the fix. I plan to look at 
the other macros that were changed to be unused as well. The hope is I 
can make it look much more like it originally looked but still let it 
work. Last I remember unfortunately it's not simply a matter of changing
that function that uses the macros but it might be worth trying that 
again.
Also in this commit I changed the literal "anonymous.c" to be __FILE__ 
like it was before.

Make 2001/anonymous more like before wrt CPP

---

1988/dale/.gitignore
1993/lmfjyh/.gitignore
1993/lmfjyh/Makefile
1993/lmfjyh/README.md
1993/lmfjyh/lmfjyh.alt.c
bugs.md

Why? Because! :-)
Added the entry to bugs.md.
Slightly modified the note in the Makefile so that the make all rule 
refers to make alt.
The README.md file was updated including succinctly giving the gist
(that might or might not be redundant :-) ) of the entry i.e. how it 
worked (though the author also stated this).

Add alt code for 1993/lmfjyh

---

1988/dale/.gitignore
1993/lmfjyh/.gitignore
1993/lmfjyh/Makefile
1993/lmfjyh/README.md
1993/lmfjyh/lmfjyh.alt.c
2001/anonymous/.gitignore
2001/anonymous/Makefile
2001/anonymous/README.md
2001/anonymous/try.me.sh
bugs.md

Running make alt will compile the anonymous.ten.c without specifying 
-m32: whether it'll end up being 64-bit or not would depend on the 
system but it'll be saved as anonymous.ten.64 anyway. 
The try.me.sh script will run this program directly, skipping the entry 
itself, if the anonymous.ten.c cannot be compiled as a 32-bit binary.

Add alt supplementary program to 2001/anonymous

---

1985/applin/README.md
1985/applin/applin.c

Now prints a newline after the output. This is to make the output more friendly to the user as seeing text like:
$ ./applin
Hello, world!$
can be confusing or at least annoying.
Further format fixed README.md.

Minor improvements to 1985/applin

---

1985/applin/README.md
1985/applin/applin.c
1985/august/README.md
1985/lycklama/README.md
1985/shapiro/.gitignore
1985/shapiro/Makefile
1985/shapiro/README.md
1985/shapiro/shapiro.alt.c

There was no functional difference; it was a matter of formatting: the
judges had split the last line into seven lines.

Remove 1985/shapiro alt code

---

2001/herrmann2/.gitignore
2001/herrmann2/Makefile
2001/herrmann2/README.md
2001/herrmann2/herrmann2.alt.c

Added herrmann2.alt.c. This is for a new try command to show a feature of the entry. It can generate the original code so the try command does this, redirecting stdout to a file (herrmann2.orig.c) and then does a diff on the two files, to show how they're the same.
The make alt rule was fixed so it doesn't compile with herrmann2.c but rather herrmann2.alt.c though I'm not even sure why that was defined at all except to say that it must have been something I forgot to change after fixing it properly.
Updated .gitignore to add herrmann2.orig.c.
Further format fixes in README.md.

Updates to 2001/herrmann2

---

2019/poikola/README.md
bugs.md

Yesterday I noticed that Timo wrote directly to me in his remarks and I wanted to address this by adding a link to myself (which is what is being done with all winners being referred to) but this naturally meant I should format fix the file too. I am very touched by this especially as 2019 was a very hard year for me and I didn't even think I was going to participate in that year (did in the end and didn't win but funnily enough some of my entry ideas actually won though with some differences of course) so I wanted to address it now. I might end up changing my name to my full name but I want to keep it as close to as possible (format fixed and links added notwithstanding) first to see how it looks. Thank you Timo! It means a great deal to me.
In the paragraph to me Timo wrote about his …

Format fix 2019/poikola/README.md

---

2019/poikola/README.md
2020/ferguson2/chocolate-cake.html
2020/ferguson2/chocolate-cake.md
bugs.md

With commit f46e68740fd35574bdcd8842c4d88b4df019fdcd twitter links were
converted to archived copies (due to Elon Musk threatening to delete 
accounts that are not active) and the chocolate cake files had a link to
a tweet. However the 2020/ferguson2 chocolate cake files were encrypted
with a key (one of 16 I gave to experiment with the entry itself) which
means that the files were not updated. Now they have been so that when 
properly decrypted they will link not to twitter itself but twitter on 
the Internet Wayback Machine.
Question: what's the difference between SpaceX rockets and Twitter? Elon
Musk hasn't yet managed to blow up twitter!

Fix Enigma chocolate cake files wrt twitter

---

2005/giljade/Makefile
2005/giljade/README.md
2005/giljade/giljade.alt.c
2005/giljade/giljade.c
2019/poikola/README.md
2020/ferguson2/chocolate-cake.html
2020/ferguson2/chocolate-cake.md
bugs.md

The version that compiles with clang now will run some of the self-tests
right. Unfortunately it does not run them all okay. Because of this I 
have decided to make the clang compilable version the alt code and the 
one that will work with compilers without clang's defect (or this 
specific defect amongst others of clang I might say) is the original 
(well the fixed original).
The clang version fix has something of a hack in it to make it work 
somewhat but it's not ideal. This is another reason that I have for now
moved it to the alt version. I explain more in bugs.md.
The Makefile has been updated to note that the code requires a compiler
that will let one have non-standard types of args to main() and that if
one does not have such a compiler they should use the alternate code 
instead. …

Partly fix and swap 2005/giljade alt and original

---

2005/giljade/README.md
2005/giljade/giljade.alt.c
2019/poikola/README.md
2020/ferguson2/chocolate-cake.html
2020/ferguson2/chocolate-cake.md
bugs.md

In order to not require being compiled as 32-bit the 'long*E' has to be
a 'int*E'. This version works fine and I wonder if it should be the main
version with alt being for clang that does not work fully: not sure.
Updated bugs.md with more information (what I came up with yesterday and 
today).
As a new issue was opened in the mkiocccentry repo I will be doing less
here for a while most likely but there probably will still be some
commits. I felt however that this was a needed commit to make as it was
left unfinished yesterday. I actually can provide a bit more information
on this entry but for now it'll suffice. The additional information has
to do with what system() is passed.

Fix 2005/giljade/giljade.alt.c

---

2019/duble/Makefile
2019/duble/README.md
bugs.md
todo.md

Of course the globs do not have a = at the end of the line; that's from
an aliased ls that shows different characters at EOL depending on the 
file type.
I also explained how to delete these files assuming that glob pattern.
In the README.md this was done in the new INABIAF section which is where
it belonged in the first place.

Fix details about 2019/duble sockets

---

2019/duble/Makefile
2019/duble/README.md
bugs.md

The entry appears to leave sockets lying about in the current working directory. Although undesirable this is not a bug it's a feature. Updated bugs.md and the README.md file as well as the Makefile.
A useful thing I thought of that might be good to look at for other entries that show notes in the Makefile is that it might be good (and in this entry I did do it) to have the note _after_ compilation as it will be more likely seen. In the case of entries that might not compile with clang (due to some defects in it) it will have to be done with either || or else printed before the compilation (for instance in some of these we have to say that one should use make alt for clang).
This will be added to the todo.md in a future commit.

Add note about sockets lying about in 2019/duble

---

2019/duble/Makefile
2019/duble/README.md
bugs.md
todo.md

What prompted this update is a 'problem' I noticed in 2019/duble: it 
leaves sockets lying round in the current working directory but it might 
not be safe for make clobber to delete them: involves '.' files and we
don't know if the glob will be different in different systems. In macOS
it appears to be `'^\.[A-Z].*'` (which in commit
cfb9c66fae54a7a83ce3de8aaf54df946bdabdef I made a mistake saying it
ended with `'+*'` which is obviously very wrong).
The README.md and bugs.md does show how to delete that pattern but it is
TBD if make clobber should do this.

Various updates in todo.md

---

1988/dale/Makefile
1988/dale/README.md
bugs.md

Reword a few things in README.md, add more commands to try (with some questions)
Add INABIAF section. Added same to bugs.md and put note in Makefile about it too: in linux the program appears to drop dump cores even though there is no error (at least at command line?).

Minor updates to 1988/dale

---

1988/dale/Makefile
1988/dale/README.md
1994/ldb/README.md
bugs.md
tmp/author.csv
winners.html

Unfortunately the link is dead so we have to use the Internet Wayback 
Machine until such a time that a new link is found. Perhaps this should
be added to the bugs.md with the status about dead links but this has 
not been done for the websites which were archived. This can be 
determined another time - or not.

Fix URL in 1994/ldb

---

1988/dale/Makefile
1988/dale/README.md
1994/ldb/README.md
2004/gavin/README.md
2004/gavin/gavin.md
2019/duble/README.md
bugs.md
tmp/author.csv
winners.html

The grep expression in particular was incorrect. This commit fixes the 
problem. Note that it doesn't look for lower case letters as there are 
legitimate dot files in the repo with lower case letters. Hopefully no 
system will leave lower case file sockets lying about (though for all I
know it's the entry deciding it - didn't look into it).

Fix command to find sockets in 2019/duble

---

1988/dale/Makefile
1988/dale/README.md
1994/ldb/README.md
2004/gavin/README.md
2004/gavin/gavin.md
2019/duble/README.md
bugs.md
faq.md
tmp/author.csv
var.mk
winners.html

Remove how to install SDL1 / SDL2 from var.mk as it's already in faq.md.
Instead refer to faq.md. How to compile (variables etc.) is still in the
var.mk file.
Reworded that section a bit and added 'Other linux distributions'
subsection to 'Linux' (in faq.md).
Minor typo fix in faq.md at the same time as the above change. Normally
I would not do this but it's one word changed and I am too tired at this
time (or can't be bothered?) to do another pull request for one word.

Improve documentation of installing SDL and SDL2

---

1988/dale/Makefile
1988/dale/README.md
1994/ldb/README.md
2004/gavin/README.md
2004/gavin/gavin.md
2015/yang/Makefile
2015/yang/README.md
2019/duble/.gitignore
2019/duble/README.md
bugs.md
faq.md
tmp/author.csv
var.mk
winners.html

A rather unfortunate typo in the Makefile made make try and compile 
already compiled C++ object code as source code.
Whilst I was at it I format fixed (and fixed other things I saw) the 
README.md file.

Fix 2015/yang to compile everything

---

2015/yang/README.md

I had put in the README.md by accident that the typo in the Makefile was making make compile the code properly rather than improperly. Obviously it was the opposite problem!

Fix thank you note / bug note in 2015/yang

---

2000/briddlebane/Makefile
2000/briddlebane/README.md

The entry would not compile in the systems that require the explicit use of -lm for libm. Two example systems are fedora and Rocky linux.
I also fixed a couple typos in README.md.

Add -lm to 2000/briddlebane/Makefile

---

bugs.md
thanks-for-fixes.md

As of moving the many thanks from the individual README.md files to one
file alone (a move I agree with and had thought of before) the bugs.md 
had to be updated to not refer to credits in the README.md files but 
rather the thanks file.

Credits go in the thanks file, not README.md files

---

thanks-for-fixes.md

As there already are thanks at the top there seems to be no reason to have the extra thanks for each entry. This was due to yank paste from the README.md files which naturally made the change much more efficient.
I also removed the links to both Yusuke and myself in the entries themselves as they're at the top of the file.
I also (because I am very proud) added some other things I did at the top of the honour list.

Remove extra thank yous + links in thanks file

---

1988/spinellis/README.md
1988/westley/README.md
1991/dds/README.md
1992/westley/README.md
1992/westley/westley.alt.c
1992/westley/westley.c
bugs.md
thanks-for-fixes.md

It was an error to fix the segfault without enough args in 1992/westley
as it does not in fact affect the usability of the program and that's 
the only time a segfault should be fixed except by anyone but the author
themselves.
This commit required also changing the alt code (that I added based on
the author's remarks) as well as the README.md, bugs.md and
thanks-for-fixes.md.

Change INABIAF status in 1992/westley

---

1989/westley/Makefile

The Makefile now has the other versions as alt targets. Running make ver0 will generate ver0.c and then try compiling it. Running make ver1 will do the same for ver1.c and running make alt will do this on ver0, ver1, ver2 and ver3. Error in compilation in these rules are not fatal so that make alt can continue. This is important for clang.
I have some other enhancements on the presentation of this entry but they have to be reworked and decided upon (it might be that it's not necessary with the alt rule but then the README.md file really ought to be updated too which it will be in another commit).
It might be that making these alt targets is not even the right approach but for now it'll do as at least it's easier to generate and compile the individual files even if one does not use make …

Improve how 1989/westley alt versions are built

---

2020/kurdyukov2/Makefile
2020/kurdyukov2/README.md
bugs.md
faq.md
how-to-bugfix.md
thanks-for-fixes.md
www-history.md

The -I/-L options to the compiler/linker have been updated for those who
use MacPorts with the default MacPorts prefix.

Improve 2020/kurdyukov2 for MacPorts build

---

bugs.md
faq.md

Added 2023 to the list of years noting that there probably won't be an
IOCCC this year but it is hoped that at least the IOCCCMOCK will be run
but that this is entirely dependent on the completion of this repo and 
the mkiocccentry repo.
Added more to final notes.

Minor update to bugs.md

---

2004/jdalbec/jdalbec.c
thanks-for-fixes.md

GCC objected to the '##' and some other cpp directives that were being used.
This unfortunately did mess up the formatting of the some of the code but I tried to preserve the art and the periodic table of elements formatting (this was preserved but whether I got all the art or not preserved I do not know) as these parts seemed too important to not preserve.

Fix 2004/jdalbec for gcc

---

2004/jdalbec/jdalbec.c
2015/yang/Makefile
2018/bellard/Makefile
thanks-for-fixes.md

Add -lm to 2018/bellard/Makefile

---

2004/jdalbec/jdalbec.c
2005/jetro/Makefile
2012/endoh1/Makefile
2013/morgan1/Makefile
2015/hou/Makefile
2015/yang/Makefile
2018/bellard/Makefile
2018/hou/Makefile
2019/dogon/Makefile
thanks-for-fixes.md

Add -lm to 2012/endoh1/Makefile

---

1998/dorssel/README.md
faq.md

Originally dorssel.hint was the hint file but then that was renamed to README.md
and the file the provided additional hint file was renamed to dorssel.md
but the README.md did not refer to dorssel.md but rather dorssel.hint.

Fix 1998/dorssel reference to a .hint file

---

1998/dorssel/README.md
bugs.md
faq.md
years.html

This changes in years.html the 2011/zucker/hint.html to
2011/zucker/README.md (at the top of the file - to do with the IOCCC
logo) and also 1998/dorssel/dorssel.hint to 1998/dorssel/dorssel.md in
years.html (which should have been done in
ccbbacb31b7bb145b529380cada5af54ae33110e but was left out by accident).
As well it fixes 2004/gavin in bugs.md to refer to (in the Makefile rule
that is included) README.md.
There are still files with 'hint' in the name however. I believe these
to be correct.

Remove last references to .hint files

---

2005/mikeash/README.md
2005/mikeash/mikeash.c
thanks-for-fixes.md

The problem was to do with an unknown escape sequence (\N) which was used in a string (also in a comment and the 'N' was referred to in code). It had been '\Newline' but this was changed to '\nNewline', the array size that stores part of the string was increased by 1 and the code was updated to check for 'n' instead of 'N'.
I also fixed a problem in README.md: might not have not might not of.

Fix 2005/mikeash for linux

---

1984/decot/decot.c
2005/mikeash/README.md
2005/mikeash/mikeash.c
thanks-for-fixes.md

Although my change of not requiring -traditional-cpp worked in macOS it
turns out one change had to be made for clang in linux which has now 
been done.

Further fix 1984/decot for clang (for linux)

---

1989/ovdluhe/Makefile
1990/theorem/Makefile
1994/ldb/Makefile
1994/ldb/ldb.c
1995/makarios/makarios.c
2019/dogon/Makefile
thanks-for-fixes.md

Disabled a warning that defaulted to an error. In this case it was 
easier to do it this way due to the way the entry works.

Fix 1990/theorem/Makefile for clang in linux

---

1985/lycklama/.gitignore
1985/lycklama/Makefile
1985/lycklama/README.md
1985/lycklama/lycklama.alt.c
1985/lycklama/lycklama.c
thanks-for-fixes.md

Now that we have the original code in lycklama.orig.c we can have what would more appropriately be an alternate version in lycklama.alt.c which is now done.
Typo fix was really unfortunate: it was in an example command to try which would have failed to work as the name was wrong.

Change how 1985/lycklama is built + fix typo

---

bugs.md
thanks-for-fixes.md

On another reading of one of the files it occurred to me that he hanging I observed with clang (after fixing it for gcc) was actually documented by the judges in the first place. They noted that some compilers compile the code into an infinite loop and that is indeed what clang does. Thus because it's documented it's a feature not a bug.

Change bug status of 1996/august

---

1984/mullender/README.md
1985/applin/README.md
1985/august/README.md
1986/marshall/Makefile
1986/marshall/marshall.c
bugs.md
thanks-for-fixes.md
tmp/README.md
todo.md

Choo choo! :-)                                            
There was a problem in linux where it either segfaulted or entered an
infinite loop depending on compiler / flags. This was caused by a for
loop that had an empty condition and the call to _exit().        
A game of cat and mouse occurred where fixing it for one compiler caused
the program to segfault with the other compiler. Unfortunately the
formatting did have to change a bit but it still mostly looks like a
train even if not quite as pretty.

Fix 1986/marshall for linux                        

---

1984/mullender/README.md
bugs.md
tmp/README.md

As discussed on GitHub this is considered the better way to go about it
as it is easier to see than spaces at the end of lines.

Add <br> to 1984/mullender author info

---

1986/marshall/.gitignore
1986/marshall/Makefile
1986/marshall/README.md
1986/marshall/marshall.alt.c
thanks-for-fixes.md

Add the code before the fixes to the entry that prevented it from working right depending on the compiler and optimiser (where having the optimiser with one compiler would let it work with one and not work with the other but having it disabled would reverse this in the same way) and documented the ways the compilers conflicted for instructional value and entertainment.

Add alt code to 1986/marshall

---

2001/bellard/Makefile
2001/bellard/bellard.otccex.c
thanks-for-fixes.md

Fixed supplementary program to add a newline after printing the first line: else the output of both lines were merged and hard to read.
Updated Makefile to always compile the supplementary program.
Modified thanks-for-fixes.md wrt this entry including fixing the link to the supplementary program (it did not specify the directory: it just had the file name itself).

More fixes in 2001/bellard

---

2001/bellard/Makefile
2001/bellard/bellard.otccex.c
bugs.md
thanks-for-fixes.md

The issue is that when fixing the interspersed output of the annoying 
warning in macOS about using gets() an extra newline is printed out. 
This is because fgets() stores the newline and gets() does not. But 
since the warning kind of ruins the entry and a blank line is better 
than the warning it seems like a worthy compromise. That was already 
agreed upon but as it's a one liner and it's already quite long it might
be better to just not worry about it as although kind of annoying a 
blank line isn't a big deal.

Change bug status of 1994/ldb

---

1990/tbr/tbr.c
thanks-for-fixes.md

The code now looks much more like the original. This was done through the use of macros to redefine exit() and gets() so that the exit() call uses the comma operator (,0) (because it is used in a binary expression) and gets() now uses fgets() (details below).
The usual problem with fgets() versus gets() (and it was changed primarily because with macOS the warning about gets() also occurs at runtime and it is interspersed with the interactive output of this program and this caused confusing output though a nice side effect is it's safer too) is that fgets() retains the newline whereas gets() does not (supposedly for backwards compatibility).
In some cases one can get away with not removing it (at the expense of a newline possibly being printed) but that was not possible here. This normally …

Improve my earlier fixes to 1990/tbr

---

1990/dds/dds.c
1990/tbr/tbr.c
thanks-for-fixes.md

Two things had to be done here to make the code look much more like the
original (though it is hardly discernible at first glance).
First thing was I redefined free() to be free() + the comma operator as
it was a binary expression error in modern systems (this fix was 
provided by Yusuke Endoh).
The second one was an improvement to one of my earlier several fixes and
in particular the prevention of warnings that cannot be disabled at 
compilation/linking/runtime (the latter of which can be interspersed 
with the output of the program): gets() to fgets(). The way this was 
done is redefining gets() to use fgets(). The second and third arg are 
the same so it was possible to just redefine gets() to use fgets() but 
gets() having one arg like the original function. It should be noticed 
that …

Improve fixes to 1990/dds

---

1992/adrian/README.md
1992/adrian/adrian.c
thanks-for-fixes.md

Originally there was one call to gets() and one call to fgets(). The gets() was changed to the fgets() to prevent warnings including (in macOS) warnings interspersed with output of the program.
But to make it more like the original gets() has been redefined to use fgets(). However this does not mean that we can make the macro do a && ... to strip off the newline as doing this will make a different file fail to generate properly (I might look at that later as it would be nicer if it looked exactly like before). Thus the 'Y[strlen(Y)-1]='\0';' is still there in the body of the while loop at least for now.
The README.md was updated to remove the address - just have name and country.
Updated thanks-for-fixes.md for the above change as well as some typo fixes elsewhere.

Slight improvement to my fix of 1992/adrian

---

1992/adrian/README.md
1992/adrian/adrian.c
1992/lush/README.md
1992/lush/lush.c
1992/westley/README.md
2004/burley/README.md
bugs.md
faq.md
thanks-for-fixes.md

As I was looking at 2004/burley/README.md it occurred to me that 
numerous entries have been modified in ways that are incongruent with 
what the author(s) originally wrote about the entry. In some cases this
has been noted in the README.md file (like has been added to 
2004/burley/README.md itself) but not in all. That should probably be 
checked for and I will do that in time most likely but in the meantime 
it felt even better to update the FAQ about this which this commit does
as well.

Update FAQ about incongruent code & author remarks

---

1987/wall/wall.c
1990/cmills/cmills.c
1993/schnitzi/schnitzi.c
faq.md
thanks-for-fixes.md

Redefined gets() so that the code can refer to gets() not fgets(). That
change was useful (as noted before) for preventing an annoying warning
being interspersed with the output and warnings at compiler and/or 
linking.

Improve my fix to 1993/schnitzi

---

faq.md
thanks-for-fixes.md

The following entries were added:
0. Makefile rules.
1. 32-bit entries not working in 64-bit systems.
2. Some entries not working in macOS either uncompilable or non-functional.
3. Entries that cannot be compiled with clang.
For (3) this especially is problematic for macOS as even /usr/bin/gcc is clang (as has been noted many times before this but not in the FAQ).
At least one typo fix was also made and at least one entry that already existed was updated a bit.
The fixes to the thanks file are related to the FAQ entries added.

Add entries to FAQ + minor fixes to thanks file

---

1987/wall/wall.c
faq.md
thanks-for-fixes.md

This improvement redefines gets() to use fgets() with the correct args
so that the code can refer to gets() to look more like the original
code.
Note that the prototype for gets() that is in the original code cannot
be there because of conflicting types of fgets() and a couple other 
errors that arise from redefining gets(). This fix is part of issue #936
which with this commit is more than halfway complete.

Improve my original fix to 1987/wall

---

2013/hou/Makefile
thanks-for-fixes.md

After 2013/hou/doc/example.markdown was renamed to
2013/hou/doc/example.md to match the rest of the repo running 'make'
would fail because of the file referenced in the Makefile no longer
exists.

Fix 2013/hou/Makefile

---

bugs.md

At one point prior to fixing (for clang) 1995/cdua I noticed that sometimes when running at runtime it would pause and ask you to press return/enter again to resume. I have not noticed the last several times (throughout many days) I have run it and that includes numerous runs each day and so I have changed the status to possible bug, not definitely a bug.
If I notice it again I will change it back or else look into the problem but without it happening it's obviously harder to verify that it's a problem (and since it's not every time it's also impossible to prove, especially with obfuscated code, that it's fixed).

Update bugs.md wrt 1995/cdua

---

src/sgit/README.md

Change './sgit' to just 'sgit'.
Remove space at end of lines.

Minor fixes in sgit/README.md

---

src/sgit/README.md
src/sgit/sgit.sh

This allows sgit -o to be used more than once.
This commit slightly changes the usage of -o: now one must specify - or (for long options) --. This is an improvement and a bug fix. Originally an oversight, it only allowed for the use of -o once (or rather each time it was used it was overwritten). That meant that one had to quote the options list but worse than that only one '-' was used which for more than one option is obviously an error.
Now one can specify more than one option either by one -o (quoting the option arg) or by using -o more than once. Not all options of sed have been tested and this will never be done by me.
New version 0.0.9-1 24-04-2023.
Significant improvements to README.md.
Updated top comments in sgit as well.

Change sgit -o (sed options) to be an array

---

src/sgit/Makefile
src/sgit/README.md
src/sgit/sgit.sh

If no sed command given (the first check on command line) say that at
least one sed command and one glob must be specified. This way they can
see that both are needed to help prevent the situation where one first
specifies no sed command and then after fixing that provides no glob. I
felt that it is not necessary to show this when there is no glob because
the check for sed commands comes first.
Add error message for unexpected value from getopts.

Improve some sgit error messages

---

1995/cdua/README.md
1998/schweikh1/README.md
bugs.md
thanks-for-fixes.md

There was 'I' in the README.md that was an artefact left over from
before the thanks file was introduced so that sentence was removed.
The thanks file was slightly updated too wrt this entry both as a new
category of fixes (the alternate code I made so that it works with macOS
but also referring to the README.md file).

Fixes in 1998/schweikh1/README.md

---

1995/cdua/README.md
bugs.md
thanks-for-fixes.md

What was once thought to be a bug or possible bug is actually a feature.
With a more lucid head I see that in a certain condition (which I noted
in bugs.md) it very clearly is intentional that one should have to hit a
key (it says return as '<RET>' but it uses getchar() via the pointer
'm'). The condition is !(g-a). I do not know the purpose of it but 
INABIAF and so should not be changed.
Thus it's not a possible bug or bug but a feature. This is noted also in
the README.md file.

Resolve bug/not a bug status in 1995/cdua

---

1985/applin/Makefile
1986/marshall/README.md
1990/dds/README.md
1990/tbr/.gitignore
1990/tbr/Makefile
1990/tbr/tbr.alt.c
1990/tbr/tbr.c
2005/mikeash/.gitignore
thanks-for-fixes.md

I fixed this quite some time back but never removed the warning. Test 
compiling everything in the new macOS I discovered this and other 
problems which will have to be looked at later.

Remove outdated message about macOS in 1985/applin

---

1990/dds/README.md
thanks-for-fixes.md

There was a note that I added that it is case sensitive but it did not
state that it's all caps which is required (the author noted this but
that's further down in the file). This might be one of the only times
caps lock is useful (though still not useful enough to enable :-) )

Clarify case-sensitivity in 1990/dds

---

1986/marshall/README.md
1990/dds/README.md
1990/tbr/.gitignore
1990/tbr/Makefile
1990/tbr/tbr.alt.c
1990/tbr/tbr.c
2005/mikeash/.gitignore
thanks-for-fixes.md

In particular the fix to make it more like the original. There was no 
need to have the function prototypes at the top of the file.
I also added a couple -Wno- options to the CSILENCE variable in the 
Makefile.
I also added to the Makefile so that make alt will build the alt version
(only functional difference is that there is gets() instead of fgets()).

Improve fix of 1990/tbr

---

1987/wall/Makefile
1987/wall/README.md

(Well .. some warnings. See below.)
Depending on system (compiler and possibly platform) different warnings were being triggered. It was easy to fix the code for some of them (like wrong prototypes and then #including stdlib.h) but this caused problems in another way (in macOS clang - clang is more strict and has -Werror or else an equivalent by default which might or might not be possible to disable .. haven't tried it) but since the code works as is I simply silenced the warnings in the Makefile.
A note that might be useful to know for other Makefiles that has to do with the fact that macOS gcc equates to clang (which I have noted many times as it's an unfortunate problem): since it is seen as gcc the Makefile check for gcc only will be triggered in macOS even though the compiler is …

Clean up 1987/wall warnings, fix README.md to run

---

1987/wall/Makefile
1987/wall/README.md
src/sgit/README.md
src/sgit/sgit.1
src/sgit/sgit.sh

Something that is lacking from the man page is that there are no 
examples. This is currently being justified by the fact that the
README.md has examples but since that might not always be available this
doesn't hold very well. This will likely be fixed another time when I
have more energy, time and patience for it.
As it is not clear to me how any documentation should be 'installed' I
have not updated the Makefile to address this. That can be done later -
or not for that matter.
The usage string has been improved a bit. There was one thing that could
be more clear and there was something missing too.
Fixed exit codes when command line error.
README.md now refers to the man page and the usage string was updated to
match the usage string change.
New version 0.0.11-1 28-04-2023.

Add sgit.1 man page, minor fixes in sgit

---

1988/reddy/reddy.c
thanks-for-fixes.md

It redefines gets() to use fgets() so that the only change is an additional #define macro.
Now the entry won't have an obnoxious warning at compiling, linking or runtime (the most annoying kind).

1988/reddy - fgets() to remove annoying warnings

---

tmp/check_awards.sh

Not strictly necessary as the script will go away but I didn't like that the script I wrote no longer worked (due to where it currently resides: since it's in tmp/ and the paths for the entries had been relative to the root directory the files no longer existed) so it has been fixed with my sgit tool like:
sgit -e 's/" \([0-9]\)/" ..\/\1/g' tmp/check_awards.sh
The script check_awards.sh was written as a quick hack (see the script for how it was generated) with some changes in vim (as it was quicker that way).

Fix tmp/check_awards.sh

---

tmp/check_awards.sh
tmp/src/Makefile
tmp/src/ioccc_status/.gitignore
tmp/src/ioccc_status/Makefile
tmp/src/ioccc_status/ioccc_status.sh

This was done quickly to give me something to do but if it's useful in
any form then so much the better but it seems it's more ideal to update
the status.json file automatically rather than having to do it manually.
The script does not have to update every field in the status.json file.
It doesn't even have to update any for that matter. The usage is:
usage: ioccc_status [-h] [-V] [-v level] [-s status] [-d] [-n] [-I status_ver] status.json
-h                          print help and exit
-V                          print version and exit
-v level                    set verbosity level
-s statue                   set contest status to open or closed
-d                          update status_date
-n                          update latest_news date
-I status_ver               update …

Add ioccc_status.sh to quickly update status.json

---

1993/rince/.gitignore
1993/rince/Makefile
1993/rince/README.md
1993/rince/design.md
1993/rince/rince.alt.c
thanks-for-fixes.md
tmp/src/Makefile
tmp/src/ioccc_status/.gitignore
tmp/src/ioccc_status/Makefile
tmp/src/ioccc_status/ioccc_status.sh

Change -I IOCCC_status_version to -i IOCCC_status_version.
Change sed separator of sed operations to be '|', not '/'. There still 
is the problem of if the version has a '|' in it the sed command will 
break but this might be solved by requiring a specific format (which 
might seem a good idea anyway) and then forcing it or some other way but
this will work for now. The other variables/fields would not trigger 
this problem because two use $(date) and the other is required to be 
'open' or 'closed' and nothing else.

Minor updates and fixes to ioccc_status.sh

---

faq.md
tmp/src/ioccc_status/ioccc_status.sh

The -i version variable was actually the same name as the script version
which means that if one were to use -V to determine the version they
would see not the version of the script but an empty string (unless of
course they first set the version with -i version).
Although this is mostly a cosmetic fix it is still important as the
variables served two very different purposes and should not be used for
both.
Instead the name of the version (variable) of the script was changed to 
IOCCC_STATUS_SCRIPT_VERSION. This seemed like a better way to go about 
it as the -i version modifies the variable in the status.json file 
IOCCC_status_version whereas ioccc_status.sh is the script that does it.
Clever I know :-)

Important bug fix in ioccc_status.sh script

---

faq.md
tmp/src/ioccc_status/ioccc_status.sh

As it seems like the version should be a specific format both for
consistency and to keep track of it I added a regexp check in the
ioccc_status.sh script I wrote the other day that does this.
The version must follow the regexp that was devised from the current
IOCCC_status_version of '0.2 2023-05-22' as:
[0-9]+\.[0-9]+ [0-9]{4}-[0-9]{2}-[0-9]{2}
The usage string has had this added and a new check was added to verify
that the '-i version' matches this format.
This update also will prevent sed from reporting an error if the
separator character (which I originally chose as '/' and then changed it
to '|' but which now could be either or ',' or something else) is in the
version as the version won't have that character.
The format of the version can certainly be changed but this seems like a …

Force regexp in IOCCC_status_version

---

1985/sicherman/Makefile
faq.md
tmp/src/ioccc_status/ioccc_status.sh

A warning that might not have been previously triggered, odd and
unlikely as it might seem, was triggered at least in macOS Sonoma and it
has now been disabled: -Wno-implicit-int.
The entry used to require in modern days -traditional-cpp but like the
others I fixed this and that did introduce new warnings as code had to
be commented out in some cases like this entry (it did not matter in
this entry if it was commented out but it had to be due to compiler
errors otherwise). Even so this warning should have been triggered
already due to main() and subr() not specifying a return type.

Silence compilation of 1985/sicherman

---

1985/sicherman/Makefile
1985/sicherman/sicherman.c
faq.md
thanks-for-fixes.md
tmp/src/ioccc_status/ioccc_status.sh

My original fix that made it not require -traditional-cpp translated
some macros that rather made the entry not look as good by which I mean
it did not look like it used to but now much less is commented out
because the macro is left as is (though in use it is commented out ..
does that mean it's not used or used? :-) ). But now the main() function
type and args looks like it originally did except for one difference. It originally looked like:
main(C,V)
char **V;
/*      C program. (If you don't
*      understand it look it
*/     up.) (In the C Manual)
and it was changed to:
main(/*/,('\b'*'\b'>=_|_>'\t'*'\n')
char **('\b'*'\b'>=_|_>'\t'*'\n')
* C program. (If you don't
* understand it look it
* up.) (In the /*/ /*C*/ manual)
but now it looks like:
main(/*C,V)
char **V;*/
/*  C program. …

Greatly improve my 1985/sicherman fix

---

faq.md

Includes Plan 9 source code and a html rendered man page. If there was a
unix or linux version the code can no longer be found.
Some README.md files refer to this tool. When an author's remarks it 
will not be removed or updated but if in the judges' remarks it might be
moved to a historical note subsection. This will happen in time with 
additional passes of the README.md files - for most it should be the 
final pass but the years 2011+ will need a pass before that.

Add item to FAQ about cb

---

faq.md

As I thought it was indeed in unix but it seems to have vanished. I had never seen it back then and it appears that only Plan 9 now has it. Plan 9, however, was never used for judging.
FAQ now links to Unix man page for cb.

Update FAQ about cb

---

thanks-for-fixes.md
todo.md

Since linking to html files on GitHub does not render the html I have changed the winners.html to be https://www.ioccc.org/winners.html instead.
In the process I have discovered that several README.md files still include '/winners.html' and these include some that have both Yusuke and me. Some of the names are supposed to stay there as they're mentioned by the author but some are not. These will be fixed in time: I have other modifications including to some README.md files and I don't want to accidentally commit the wrong files as some have changes that are not necessarily finished. Since it's the same kind of change it feels like a single pull request would be fitting (and easier) but since all the README.md files will have to be checked again (some once, some twice and that should be …

Fix links in thanks-for-fixes.md wrt winners.html

---

thanks-for-fixes.md
todo.md

Some days back I made the 1985/sicherman fix of mine to look much more
like the original. This was done in commit 
4836ed462265105cf380715f674c122ac9b6d99f.

Remove finished task from todo.md

---

1988/applin/Makefile

The rule zsmall.c comment suggested that applin rule (which is done via the ${PROG} variable which is the value of ${ENTRY} which is how every other entry Makefile is done) was below but actually it is above.
If ${CC} is clang then add to CSILENCE -Wno-gnu-line-marker. This unfortunately means one has to either have by default CC as clang or they have to specify e.g.:
make clobber CC=clang everything
as CC tends to be just 'cc'.
The warning cannot be silenced with gcc and although it allows one to use of -Wno-gnu-line-marker it has no effect other than to say it's unrecognised because gcc (at least in some versions?) does not allow this warning to be silenced, for whatever (invalid :-) ) reason(s). Thus unless one explicitly says that CC=clang they will get the warning.
Still at least …

Typo fix and warning silence in 1988/applin

---

2006/sloane/README.md
thanks-for-fixes.md

As the original entry is too fast for modern systems I have (after discussion with Landon) made the build and try sections refer to 'sloane.alt' instead of the original entry. The 'alternate section' now refers to 'sloane' instead. This is a rare case where the reversal of alt (in this case provided by me) and the original is valuable.
There are other entries where I will end up doing this as well for the same reason of the entry going too fast in modern systems and these will be updated in time, now that a method to do it has been established.

Swap 2006/sloane alt/main code in build/try

---

2013/endoh1/README.md

This also involved undoing the rot13 spoiler which uncovered some typos
as well. I did not rot13 it again as Landon has specified that unless an
entry is to be used to decipher text in the documentation (an example 
being my Enigma machine, 2020/ferguson2) then it should not be 
enciphered as the point of remarks in the contest has changed in some 
ways.

Format fix 2013/endoh1

---

2013/endoh4/README.md
2013/endoh4/run.sh
thanks-for-fixes.md

Format fixes and additions to 2013/endoh4
Based on the author's suggestions I added a script run.sh which 
temporarily disables the cursor, using trap to set it back (it also 
explicitly sets it back in case the signals specified are not sent to 
the program). If no arg is specified it will feed the source code of the
program into the program; otherwise it'll use the arg specified. It does
not check if the file exists and is readable or anything else as the 
shell/program will do that.

Format and typo fix 2013/endoh4/README.md

---

2013/endoh4/README.md
2013/endoh4/run.sh
2013/hou/.gitignore
2013/hou/Makefile
2013/hou/README.md
bugs.md
thanks-for-fixes.md

The way the Makefile was constructed meant that the program just
decompressed the real program which is only the first part of the
program. As the judges noted it could be said to break rule 2 (in a
way?) because the code actually is a decompressor of the real code. So
in order to get the entry to do what it's supposed to do the Makefile
rule was modified to be:
${PROG}: ${PROG}.c
${CC} ${CFLAGS} $< -o $@ ${LDFLAGS}
./${PROG} | ${CC} ${CFLAGS} -x c - -o $@ ${LDFLAGS}
which first compiles the program to hou and then runs hou, piping the
output to the compiler to compile it into hou again. This way when one
runs hou (after running make) the actual program is run, saving
viewers/users from the extra step (and potential confusion). The 
README.md file also shows how to just generate the …

Fix 2013/hou + format 2013/hou/README.md

---

1988/isaak/README.md
faq.md

The README.md pointed out that not having the file name being 'isaak.c' 
(see the source code why) would cause a problem but this was fixed by
use of the '__FILE__' macro, prior my fix to the entry itself and so the
README.md now points out that this feature (some might say 'defect' or
'limitation') no longer exists.

Minor updates to 1988/isaak/README.md

---

1988/isaak/README.md
2000/README.md
2001/README.md
2006/README.md
2011/README.md
2012/README.md
2013/README.md
2019/README.md
2020/README.md

This change was already applied in the README.md files of the years <
2000, yesterday, but I got tired of doing it manually as I do each year
so I used my sgit tool (https://github.com/xexyl/sgit) like:
sgit -e 's/\(Look at the README.md file for the given\) winner/\1 winning entry/g' -e \
's/\(on how to compile\) the winner/\1 it/g' .
which changed the text:
... for the given winner 
and
on how to compile the winner
to
... for the winning entry
and
... on how to compile it
This felt useful because the winner is not the entry itself but the 
author (and in some cases authors). This should be clearer now. When I 
do a final pass I will check for any consistency issues in the ones 
changed manually.
In this commit the year 2013/README.md was format fixed as the change 
was done in this …

Minor rewording in some YYYY/README.md files

---

2000/README.md
2001/README.md
2006/README.md
2011/README.md
2012/README.md
2013/README.md
2018/README.md
2019/README.md
2020/README.md

That is
sgit -e 's/Use make\( to compile\)/Use `make`\1/g' -e \ 
's/makefile/Makefile/g'  '20[0-9][0-9]/README.md'
This way 'make' is formatted with a code block (or whatever the term is
in markdown terminology) and 'makefile' is changed to Makefile.
BTW: fun fact: Landon was part of the recommendation of naming Makefiles 
Makefile instead of makefile which is shown in the man page make(1):
Normally you should call your makefile either makefile or Makefile.
(We recommend Makefile because it appears prominently near the
beginning of a directory listing, right near other important files
such as README.) The first name checked, GNUmakefile, is not 
recommended for most makefiles.  You should use this name if you
have a makefile that is specific to GNU Make, and will not be
understood by …

Fix make and makefile in README.md files

---

2001/anonymous/Makefile
2001/anonymous/README.md
2015/endoh3/README.md
thanks-for-fixes.md

Change (except in author's remarks in the wget command) the 
/1984/mullender/mullender.c to be just mullender.c as it's in the entry
directory itself.
Format fixes in README.md as well.

Minor fixes in 2015/endoh3/README.md

---

2013/dlowe/README.md
2013/dlowe/demo.sh
2013/dlowe/sflen.sh
2013/endoh2/Makefile
2013/endoh2/README.md
thanks-for-fixes.md

The README.md format was messed up (extraneous and erroneous '```'s) due
to the nightmare (or perhaps daymare :-) ) of the many merging conflicts
of yesterday which required repeatedly resolving conflicts in GitHub.
I also renamed 'slen.sh' to 'sflen.sh' as it shows the sparkle OF the
length of all the files rather than a sparkle length. References to 
slen.sh have been changed to sflen.sh instead.
The demo.sh script and the sflen.sh script now run:
make all || exit 1
before proceeding. It does not do make clobber before because this only
clutters the output and is unnecessary if everything is already
compiled.
Oh and just for those who wonder if daymare is or is not really a word:
it is but I redefined it; literally it refers to a frightening hallucinatory
experience whilst awake (though …
```

Improvements and fixes to 2013/dlowe

---

2001/bellard/Makefile
2001/bellard/README.md
2001/bellard/bellard.c
2013/dlowe/README.md
2013/dlowe/demo.sh
2013/dlowe/sflen.sh
2013/endoh2/Makefile
2013/endoh2/README.md
bugs.md
thanks-for-fixes.md

When trying to get this entry to work for modern systems I ended up
replacing some macros with what they translated to. This meant that it
did not look as close to what the original entry looked like.
There was another change as well in this commit. The variable that is
the file to open was changed to a FILE * instead of an int. Although it
did not crash after the change I made when trying to open the file (see
below for why this was done) it's not strictly correct either in modern
systems (and maybe not in older systems either though it clearly
worked).
Now as for why the fix to being able to open the file: it's because at
the time I was trying to get it to work with modern systems even though
the author stated that it was designed for i386 linux. Doing this proved
possible with a number …

Restore where possible macros in 2001/bellard

---

thanks-for-fixes.md

At the top in the honour roll I changed (based on discussion) the entries' links to the README.md files, not the source files, for both Yusuke Endoh and myself. At the same time I added another category of fixes that I have made.
Typo fixes as well.

Fixes and updates to thanks-for-fixes.md

---

1998/schweikh2/schweikh2.orig.c
thanks-for-fixes.md

By some chance the original code that was restored as schweikh2.orig.c 
was not the original. This has been fixed by copying it from the
archive. The file that is being updated is almost like my fix (which 
solves a gcc internal compiler error).

Restore 1998/schweikh2 original code

---

1998/schweikh2/.gitignore
1998/schweikh2/Makefile
1998/schweikh2/README.md
1998/schweikh2/schweikh2.c
thanks-for-fixes.md

There were a number of problems in the README.md that were fixed. A big one was in usage where it said you could run the program and then input a number. Although one could certainly go through that action it would have no effect. Not entering a number at the command line does something different (in a way different) from specifying a number.
Also the historical notes were updated to be more consistent and hopefully clearer than before.
Since the author called the program yarng (see README.md for why this is) the Makefile now creates a symlink to it, rather than forcing users to go back and forth as the author gives example uses as well. The to use and try sections now also use yarng. Running make clobber (from make clean) will remove the symlink.
The .gitignore file was updated: added …

Fixes in 1998/schweikh2

---

1998/schweikh1/Makefile
1998/schweikh1/README.md
1998/schweikh1/schweikh1.alt.c
1998/schweikh1/schweikh1.c
2001/README.md
2013/dlowe/README.md
2013/endoh1/README.md
2013/endoh3/README.md
2013/misaka/README.md
2013/misaka/demo.sh
2014/vik/.gitignore
2014/vik/Makefile
2014/vik/README.md
2014/vik/prog.alt.c
bugs.md
thanks-for-fixes.md

A link in the judges' remarks was dead and was replaced by a link in the
Internet Wayback Machine.
Format fix the README.md file.
As there are a lot of commands to try I added them in demo.sh, sleeping
approximately 1 second between each command (though I thought of
prompting instead).
And... since the author appears to love cats I'll throw out the word of 
us cat lovers: ailurophile(s). And to those who are afraid of cats
(though I don't know why :-) ), the phobia is: ailurophobia.
If you're an ailurophile see https://rationalwiki.org/wiki/Fun:Cat. Even
if you're not you might find it amusing.

Fixes for 2013/misaka and add demo.sh

---

1985/august/README.md
1985/august/primes.sh
thanks-for-fixes.md

The inspiration of the script is based on a 'try' command I added to the README.md a while back to have more fun with the entry. The difference is that it allows you to specify the number of lines to print (or up to the number of lines).
There might be some misleading output in a way but this is a mystery for users to solve.

Add script primes.sh to 1985/august for fun

---

1984/decot/decot.c
2014/skeggs/.gitignore
2014/skeggs/Makefile
thanks-for-fixes.md

I was able to bring back some code and only had to comment out one part
and make a minor change to another another. Originally the code had:
extern int floor;
but this is not possible in modern systems so it was changed to:
extern double floor(double);
The 
double (x1, y1) b;
could be brought back, changed from:
int b,
(the comma is not a typo there).
Now it looks rather more like the original.
The thanks-for-fixes.md file was updated here, including a diff to try
(to see what had to be done to fix the entry for modern systems) but I'm
afraid it has a minor change in another entry, something I accidentally
left out of 1984/mullender.

Make my 1984/decot fix look more like original

---

2014/skeggs/.gitignore
2014/skeggs/Makefile
thanks-for-fixes.md

When I got this entry to work apparently I never added a thanks for it so this is now done.
Also to make the compilation more portable I added -ldl to the LDFLAGS. This is something Yusuke Endoh did and although not necessary in the systems I tried it since it uses dlsym() it's better to have it.

Update thanks file wrt 2014/skeggs + add -ldl

---

1984/decot/decot.c
1996/eldby/Makefile
1996/eldby/README.md
2014/skeggs/.gitignore
2014/skeggs/Makefile
faq.md
thanks-for-fixes.md

This is one of the rare cases where the alternate version is preferable
in modern systems as it moves way too fast to see what is going on and
it can also be a problem for many because it flashes by too quickly.
Added to CSILENCE -Wno-implicit-int.

Swap alt/main in 1996/eldby to run/try

---

1991/fine/Makefile
1991/fine/README.md
1991/fine/demo.sh
1991/fine/fine.c
thanks-for-fixes.md

With clever use of the Makefile and removing a cast that is not strictly necessary (it does trigger a warning but it still produces correct output) I was able to get what was once 80 characters but when fixed increased to 106 characters all the way back down to 85. As for how this was done it might be helpful to look at what it was prior to this update as well as the original. The previous version was:
int main(int a, char **b){while((a=getchar())+1)putchar((b=64^a&223)&&(int)b<27?a&96|((int)b+12)%26+1:a);
and the original was:
main(a,b){while((a=getchar())+1)putchar((b=64^a&223)&&b<27?a&96|(b+12)%26+1:a);}
The problem with the original besides needing one of the casts is that clang is stricter with the types of args of main(). Now it looks like: …

Drop char count of 1991/fine to 85 (was 80 -> 106)

---

1991/fine/Makefile
1991/fine/demo.sh

The demo.sh script now shows a bit more what is going on, at least in so far as the text can go either way: instead of showing:
Green terra: Terra green
Vex: Irk
[...]
The rug gary lenT: Gur eht tnel yraG
it shows:
Green terra <->  Terra green
Vex <->  Irk
[...]
The rug gary lenT <->  Gur eht tnel yraG
The Makefile now silences as many warnings as possible.

Minor improvements to 1991/fine/{demo.sh,Makefile}

---

1987/hines/README.md
1987/korn/README.md
1987/lievaart/README.md
1987/lievaart/lievaart.c
1987/lievaart/lievaart2.c
1987/wall/README.md
1987/westley/Makefile
1987/westley/README.md
1987/westley/westley.c
1991/fine/Makefile
1991/fine/demo.sh
thanks-for-fixes.md

With the compilation fix of the code some symmetry was unfortunately 
destroyed. To try and keep it as close as possible to the original I had
just commented out the code. But looking at it again today it occurred 
to me that I can make it look more symmetrical by removing the commented
out code and then formatting the code a bit differently (another cast
was removed to do this). It is not any less authentic but it now has 
more symmetry which was an important part of the entry's layout.

Make 1987/westley more symmetrical after fix

---

1986/wall/Makefile
1986/wall/README.md
1987/hines/README.md
1987/korn/README.md
1987/lievaart/README.md
1987/lievaart/lievaart.c
1987/lievaart/lievaart2.c
1987/wall/README.md
1987/westley/Makefile
1987/westley/README.md
1987/westley/westley.c
1991/fine/Makefile
1991/fine/demo.sh
thanks-for-fixes.md

Add explicit rule to compile alt code and update CFLAGS to include (if
CC is gcc) -traditional-cpp. Clang does not support it. If CC is cc it
might support it depending on the system (macOS gcc is actually clang so
it won't but linux it will). This allows just running instead of:
make CFLAGS+="-traditional-cpp" alt
to do:
make CC=gcc alt
but still allowing for the former which might be necessary if CC is not
defined to be gcc.
The README.md points out that in macOS gcc is clang.
Improve the command (in the thanks file) of how to see the difference 
between the -traditional-cpp version and the fixed version so that it
doesn't need git but rather just diff (as git diff is unnecessary here).
Note that there is discussion about new make rules that will make this
type of thing not needed so …

Improve how 1986/wall alt code is built

---

1984/decot/decot.c
1986/wall/Makefile
1986/wall/README.md
1987/hines/README.md
1987/korn/README.md
1987/lievaart/README.md
1987/lievaart/lievaart.c
1987/lievaart/lievaart2.c
1987/wall/README.md
1987/westley/Makefile
1987/westley/README.md
1987/westley/westley.c
1988/dale/README.md
1991/fine/Makefile
1991/fine/demo.sh
thanks-for-fixes.md

This includes the thanks-for-fixes.md file where C code was actually in
the form of a diff (which happened when I was looking for the 
differences to put in the file in the first place, forgetting to remove
the [-+] at the time).

Format/typo check 1988/dale

---

1984/decot/decot.c
1986/wall/Makefile
1986/wall/README.md
1987/hines/README.md
1987/korn/README.md
1987/lievaart/README.md
1987/lievaart/lievaart.c
1987/lievaart/lievaart2.c
1987/wall/README.md
1987/westley/Makefile
1987/westley/README.md
1987/westley/westley.c
1988/applin/Makefile
1988/applin/README.md
1988/dale/README.md
1988/isaak/README.md
1988/litmaath/README.md
1991/fine/Makefile
1991/fine/demo.sh
thanks-for-fixes.md

The README.md and the Makefile were both updated. The Makefile because
of typos/unclear things. The README.md had formatting fixes and also
added the historical note about 1988 from the Makefile as it's far less
likely people will see that note versus that which is in the README.md.

Format/typo check 1988/applin

---

1984/decot/decot.c
1986/wall/Makefile
1986/wall/README.md
1987/hines/README.md
1987/korn/README.md
1987/lievaart/README.md
1987/lievaart/lievaart.c
1987/lievaart/lievaart2.c
1987/wall/README.md
1987/westley/Makefile
1987/westley/README.md
1987/westley/westley.c
1988/applin/Makefile
1988/applin/README.md
1988/dale/README.md
1988/isaak/README.md
1988/litmaath/README.md
1988/phillipps/README.md
1988/phillipps/phillipps.c
1991/fine/Makefile
1991/fine/demo.sh
thanks-for-fixes.md

As main() used K&R style I changed main() to use K&R. The function that
it became (to fix it), pain(), already has the same exact format of what
main() once was only named painfully. Since main() also had the function
on many lines, even just the return statement in the beginning, I did 
this in main() but given that main() only calls pain() obviously this is
not perfect. This has been documented in the thanks file like for all
the other improvements, to keep track of it.

Improve slightly my fix to 1988/phillipps

---

1984/decot/decot.c
1986/wall/Makefile
1986/wall/README.md
1987/hines/README.md
1987/korn/README.md
1987/lievaart/README.md
1987/lievaart/lievaart.c
1987/lievaart/lievaart2.c
1987/wall/README.md
1987/westley/Makefile
1987/westley/README.md
1987/westley/westley.c
1988/applin/Makefile
1988/applin/README.md
1988/dale/README.md
1988/isaak/README.md
1988/litmaath/README.md
1988/phillipps/README.md
1988/phillipps/phillipps.c
1988/reddy/README.md
1991/fine/Makefile
1991/fine/demo.sh
thanks-for-fixes.md

By some crazy chance the winner's name was not in the README.md file:
just a corporation (which has been removed along with the address). I
was able to locate it in the author/ subdirectory in the JSON file.
Format and typo checked the README.md and also added some things to try
to explore the entry more.

Format/typo fix 1988/reddy + restore winner name

---

1984/decot/decot.c
1986/wall/Makefile
1986/wall/README.md
1987/hines/README.md
1987/korn/README.md
1987/lievaart/README.md
1987/lievaart/lievaart.c
1987/lievaart/lievaart2.c
1987/wall/README.md
1987/westley/Makefile
1987/westley/README.md
1987/westley/westley.c
1988/applin/Makefile
1988/applin/README.md
1988/dale/README.md
1988/isaak/README.md
1988/litmaath/README.md
1988/phillipps/README.md
1988/phillipps/phillipps.c
1988/reddy/README.md
1988/robison/README.md
1988/spinellis/README.md
1988/westley/README.md
1988/westley/demo.sh
1991/fine/Makefile
1991/fine/demo.sh
thanks-for-fixes.md

The reason for the demo is because when one looks at the code and then
sees the output at the same time it's far more beautiful and magical.
The README.md has been typo and format checked.
With this commit, the README.md files for the 1988 entries have been 
checked and besides some things brought up on GitHub they should be in 
good order (for now?).

Add 1988/westley/demo.sh + format/typo check

---

1987/hines/README.md
1987/korn/README.md
1987/lievaart/README.md
1987/lievaart/lievaart.c
1987/lievaart/lievaart2.c
1987/wall/README.md
1987/westley/README.md
1991/fine/Makefile
1991/fine/demo.sh
thanks-for-fixes.md

Restored the #define D define even though it can't be used with modern
compilers, just so it looks as close to the original as possible. This 
goes for both versions, the one with the board and the entry (limited by
the contest restrictions).

Make 1987/lievaart slightly more like original

---

1987/hines/README.md
1987/korn/README.md
1987/lievaart/README.md
1987/lievaart/lievaart.c
1987/lievaart/lievaart2.c
1987/wall/README.md
1987/westley/Makefile
1987/westley/README.md
1991/fine/Makefile
1991/fine/demo.sh
thanks-for-fixes.md

Although this is very unlikely(?) nowadays the judges noted that 
putchar() has to exist and if compilation fails one should include 
stdio.h. This cannot be done in the file, however, as it would ruin the
symmetry (already some of this was messed up due to C standard changes).

Add -include stdio.h to 1987/westley/Makefile

---

1984/decot/decot.c
1986/wall/Makefile
1986/wall/README.md
1987/hines/README.md
1987/korn/README.md
1987/lievaart/README.md
1987/lievaart/lievaart.c
1987/lievaart/lievaart2.c
1987/wall/README.md
1987/westley/Makefile
1987/westley/README.md
1987/westley/westley.c
1991/fine/Makefile
1991/fine/demo.sh
thanks-for-fixes.md

When I restored the macros it allowed for reinstating the 'union'
instead of 'static struct' and it also allowed for reintroducing the 'x'
(which is '=') in that line so that it looks just like the original:
union tag u x{4};
For documentation purposes this was added in the thanks file (in the 
same part of that entry, the making it look more like the original which
is a worthy goal) as well.

Further improve my fixes to 1984/decot

---

1988/westley/demo.sh
2014/endoh1/Makefile

Check for executable 'westley' before compiling and only _after_ 
compilation (if necessary) is the source shown. This way if it's
already done (as likely the case) the result of the program will be
shown closer to the source code which is entirely the point. But even if
it's not already compiled since it's compiled first it'll have the 
result closer to the source (if it fails though it'll not show the 
source at all).

Improve 1988/westley/demo.sh

---

1987/lievaart/lievaart.c
1987/lievaart/lievaart2.c
bugs.md
thanks-for-fixes.md

It was documented that the program detected invalid input but it actually (now - it used to work) printed in an infinite loop 'You:'. Now doing invalid input forfeits the game which is better than flooding the screen. It is not yet clear if it should act like you put in 99 (see the README.md for details) so this is in bugs.md just in case. If it is supposed to just skip a move then this can be fixed but otherwise it can be removed from bugs.md without any change in the code. This fix applies to both versions, the one with the board display and the original entry (with contest restrictions on size of code).

Fix 1987/lievaart - check for invalid input

---

1987/lievaart/lievaart.c
1987/lievaart/lievaart2.c
1989/ovdluhe/Makefile
1989/ovdluhe/README.md
1989/ovdluhe/ovdluhe.alt.c
1989/ovdluhe/ovdluhe.c
bugs.md
thanks-for-fixes.md

As Landon said it is a bug (after I asked about it) I have fixed it.
Without this fix the program printed the same thing over and over again
in some cases. The problem was a for() loop that didn't always have the
pointer incremented. It looks like I could have got away with just
updating the increment part of the loop but I didn't do that as I didn't
see it at first.
The optimiser was disabled. That might not be strictly necessary but I
had it disabled for a time so I have kept it disabled.
Also I removed my name in the README.md: this was missed when the much
better idea of a general thanks file was come up with. When testing the
fix I came across part of my name which made me check. I have not yet
typo/format checked this file or any of 1989 so that was not done. That
might or might not …

Fix infinite loop in 1989/ovdluhe

---

1987/lievaart/lievaart.c
1987/lievaart/lievaart2.c
1989/ovdluhe/Makefile
1989/ovdluhe/README.md
1989/ovdluhe/ovdluhe.alt.c
1989/ovdluhe/ovdluhe.c
1990/baruch/README.md
bugs.md
faq.md
thanks-for-fixes.md

This was the last remaining missed case of me being in another README.md
which happened before the (I am a broken record, perhaps, but it's true)
vastly superior thanks-for-fixes.md file was thought of.
There are other entries not mine that refer to me but these come from 
the authors themselves, not fixes, so they should stay the same.
I still have to check if there are any README.md files that have 
references to Yusuke Endoh (for fixes) as well but that will be done in
another commit another time.
I updated the alternate code section and subsections here (the 
formatting and text) as well as added at the top that there is an alt 
version.

Remove me from 1990/baruch/README.md thanks

---

1987/lievaart/Makefile
1987/lievaart/lievaart.c
1987/lievaart/lievaart2.c
thanks-for-fixes.md
todo.md

Now the game will re-prompt the player if invalid input is entered both
for the level and for the move. The way it was fixed is described in the
thanks-for-fixes.md file but here is a summary of the previous problem
and the fix.
If one entered an invalid level it proceeded to prompt for the move.
Thus if one entered '.' or anything other than a number it would still
move on. As for the move if one entered invalid input it would prompt
again but in an infinite loop, not letting one enter anything and
instead flooding the screen. The format specifier was thus a '%d'. Now
it's a '%2s' on a 'char A[100]'. After the scanf() it uses atoi(). For
the level it checks if > 10 || < 0 || !isdigit(*A) and if the if is 1 it
goes back to prompting the level. Of course since '-' is not a digit the
check …

Properly fix 1987/lievaart invalid input checks

---

1987/lievaart/Makefile
1987/lievaart/lievaart.c
1987/lievaart/lievaart2.c
1989/jar.1/Makefile
1989/jar.1/README.md
1989/jar.1/jar.1.alt.sh
1989/jar.1/jar.1.sh
thanks-for-fixes.md
todo.md

There were some things unclear in the README.md file that have now been corrected.
Clarified in the README.md that running make clobber all will run the program itself.
The make alt target now runs the alt code just like the entry itself.  This is fine because it is a simulation (to avoid annoyance of writing binary data to /dev/tty) and since one may still run the program or script directly it's fine.
The alternate code section in the README.md was cleaned up and formatted as well.

Fix 1989/jar.2

---

1991/brnstnd/brnstnd.c
thanks-for-fixes.md
todo.md

Although the macro '#define D define' is unused, by adding it back to
the code the entry looks ever so slightly more like the original.

Make my 1991/brnstnd fix more like original

---

1990/cmills/README.md

I included a link in the judges' remarks written by Dennis Ritchie about C history in order to explain something the author noted, that I felt some might find interesting. It was stated:
... as well as the irritating compiler I was using which assumes
x=*p++ means x*=p++ !
but the explanation is quite simple. In early C and also B the compound assignments had the = first so that:
x += 5
used to be written as:
x =+ 5
This is also shown in Lions' Commentary on the Sixth Edition UNIX Operating System but not linked, only referenced. Both the document and the book are quite fascinating.

Format/typo check 1990/cmills

---

1990/cmills/README.md
1990/scjones/README.md
1991/dds/Makefile
1991/dds/README.md
thanks-for-fixes.md

Based on a slight modification to the Makefile the program will now 
compile to the same file as if dds.c was being used (a.out).
I updated the README.md with some changes in formatting to do with the 
alt code but the file has not been fully corrected or even checked.

Improve my 1991/dds alt code (required for clang)

---

2012/kang/.gitignore
2012/kang/Makefile
2012/kang/README.md
2012/kang/de.sh
2012/kang/en.sh
2012/kang/kang.alt.c
thanks-for-fixes.md

I was on the fence of whether it's a feature or bug that the program deciphers 'fier' as '4' instead of proper 'vier' but to help with preventing confusion to those who know German I ended up changing it. This was thought okay but after more thought and also playing with it a bit I have made that fix the alt version instead. It so happens that (and I wondered about this at the time but did not have examples then) by changing it to 'vier' it caused other number words to be wrong. Thus the version that I'll call vier (even though it's zwei or if alternatively if zero based eins :-) ) is now the alt version.
Added en.sh and de.sh scripts to count from 0 through 13 (reason below), showing the word and number and then the result. One can choose whether to use the alt version or not by passing …

Make current 2012/kang properly alt code

---

1984/laman/README.md
1987/lievaart/README.md
1988/dale/README.md
1989/fubar/README.md
1989/robison/README.md
1993/plummer/README.md
bugs.md

Having to click on the links in each README.md file will have to be done
to verify the links work but it appears to be in the form of:
/bugs.md#YYYYauthor-readmemd

Move INABIAF to bugs.md in 1980s entries

---

1984/laman/README.md
1987/lievaart/README.md
1993/plummer/README.md
bugs.md

It was actually declared it was a bug (the entry no longer did the 
invalid input check that it once did) and I fixed it so it no longer
needs to be documented at all.

Remove outdated INABIAF in 1987/lievaart

---

1990/baruch/Makefile
1990/baruch/baruch.c
bugs.md
faq.md
thanks-for-fixes.md

That is to say I removed the 'int' from the variables and added to the
Makefile -Wno-implicit-int instead. The newline added by the judges is
still there, however.

Make 1990/baruch look slightly more like original

---

faq.md
thanks-for-fixes.md

Rather than have the specific entries noted at the top (for Yusuke and
me) link to the README.md file of the entries, it seems better to me to
link to the entry in the file as that explains what was done which is
what is being honoured/appreciated.
I also added another section or two (both short). One has a joke in it.
Some of the entries had improvements in text of what had to be done to
fix them to work / what was wrong.

Improve links in thanks-for-fixes.md

---

bugs.md
faq.md
thanks-for-fixes.md

What this means is I changed the heading level from 2 to 3 of the STATUS
lines (under the entries) so that it shows that the status is for the 
respective entries.
This was thought of when I was working on moving the bugs/(mis)features
of the entries of 1980s to bugs.md (as in making the README.md files 
refer to the bugs.md but not include the details, just the status) and 
noticed that it just didn't look quite right. Hopefully this improves it
just a bit.

Slightly improve (I hope :-) ) bugs.md statuses

---

tmp/awards_check.sh
tmp/check_path_list.sh
tmp/fix_manifest_csv.sh
tmp/gen_path_list.found.sh

Typos and make the renaming of check_awards.sh -> awards_check.sh consistent in the comments (as in change the name of the script in the comments to the new name).
None of these are super important as they're temporary files but they are still incorrect so have to be fixed in my mind.

Temporary (? :-) ) fixes in tmp/ scripts

---

2020/endoh3/run_clock.sh
thanks-for-fixes.md
tmp/awards_check.sh
tmp/check_path_list.sh
tmp/fix_manifest_csv.sh
tmp/gen_path_list.found.sh

When running the script from the shell one would get:
-bash: ./run_clock.sh: cannot execute: required file not found
and when running from within vim one would get:
/bin/bash: ./run_clock.sh: /usr/bin/end: bad interpreter: No such file or directory
The problem was that the script had in the shebang /usr/bin/end not 
/usr/bin/env.
When I updated the thanks-for-fixes.md file for this I also noted that I
reported to Yusuke in the preview period back in 2020 that in some 
systems (it was macOS) due possibly to a timing issue there the script 
(which the judges had added) did not work properly with 'make' so Yusuke
changed it to compile the code directly.

Fix odd error message in 2020/endoh3/run_clock.sh

---

1984/mullender/.gitignore
1984/mullender/Makefile
1984/mullender/README.md
1984/mullender/gentab.c
1984/mullender/mullender.alt.c
1984/mullender/mullender.alt2.c
2020/endoh3/run_clock.sh
bugs.md
faq.md
thanks-for-fixes.md
tmp/awards_check.sh
tmp/check_path_list.sh
tmp/fix_manifest_csv.sh
tmp/gen_path_list.found.sh

Swap order of alt and original code in build/try sections so that the 
original code is suggested second, after alt code, with the bugs and 
(mis)features added to the README.md file, pointing out that it'll only
work on VAX-11 / PDP-11 machines. This is added in the bugs.md (it was 
actually missing from the bugs.md file).
The alt code (both versions, see below) now have a lower limit on the
microseconds at 500 (still defaults at 10000). This is because anything
much lower and it's nigh impossible to see and in some cases it won't
work at all (at least in the MacBook Pro with the M1 chip).
Added second alt code which is like the first except that once it times
out it starts over.
Running make alt will compile both alt versions.
The gentab.c file that I added (found from the author) and …

Many fixes and additions to 1984/mullender

---

1984/decot/README.md
1984/mullender/.gitignore
1984/mullender/Makefile
1984/mullender/README.md
1984/mullender/gentab.c
1984/mullender/mullender.alt.c
1984/mullender/mullender.alt2.c
1985/lycklama/README.md
1985/sicherman/Makefile
1985/sicherman/README.md
1985/sicherman/sicherman.c
2020/endoh3/run_clock.sh
bugs.md
faq.md
thanks-for-fixes.md
tmp/awards_check.sh
tmp/check_path_list.sh
tmp/fix_manifest_csv.sh
tmp/gen_path_list.found.sh

By changing some macros to what they used to expand to more of the code
can be used / not commented out. For instance now subr() no longer is
commented out. It cannot be used but it now is uncommented to make it
more like the original, even using the C macro as the arg (albeit
without a type specified as it actually just translates to /**/). The
macro that C used to use, 'b' (which is '*'), is still used just not in
C as doing so will cause compilation problems.
The single arg of main() was commented out because some versions of
clang do not only allow one arg to main().
There might have been other things to make it more like the original as
well.

Make 1985/sicherman even more like original

---

1986/marshall/README.md
1986/marshall/compilers.md

The file compilers.md has been added with rewording of the README.md (which has naturally been updated as well) and there is some fun in it too.

Update 1986/marshall about gcc versus clang

---

1984/laman/README.md
1984/laman/laman.c
bugs.md
thanks-for-fixes.md

As the definition of INABIAF changed, again, and since it took no more than ten seconds to fix, I have fixed this entry.
As the thanks file was updated for this some other things that had been left out were also fixed at the same time as these were already in the file but not committed. There was also a typo fix in there.

Fix 1984/laman if no arg specified

---

1984/laman/README.md
1984/laman/laman.c
1992/westley/westley.alt.c
1992/westley/westley.c
1993/plummer/README.md
1993/plummer/plummer.alt.c
1993/plummer/plummer.c
1994/horton/Makefile
1994/horton/README.md
1994/horton/horton.c
2001/cheong/README.md
2001/cheong/cheong.c
2001/ollinger/ollinger.c
2001/schweikh/README.md
2001/schweikh/schweikh.c
2006/stewart/README.md
2006/stewart/stewart.c
bugs.md
thanks-for-fixes.md

For both check args.
For alt move main()'s code to new function as some versions of clang do
not allow four args. Instead main() has two args now, the traditional
argc and argv, and the other two are passed 0.

Fix both original and alt code for 1992/westley

---

1984/laman/README.md
1984/laman/laman.c
1990/westley/README.md
1990/westley/westley.c
1991/dds/dds.c
1992/buzzard.1/README.md
1992/buzzard.1/buzzard.1.c
1992/gson/README.md
1992/westley/westley.alt.c
1992/westley/westley.c
1993/plummer/README.md
1993/plummer/plummer.alt.c
1993/plummer/plummer.c
1994/horton/Makefile
1994/horton/README.md
1994/horton/horton.c
2001/cheong/README.md
2001/cheong/cheong.c
2001/ollinger/ollinger.c
2001/schweikh/README.md
2001/schweikh/schweikh.c
2006/stewart/README.md
2006/stewart/stewart.c
bugs.md
thanks-for-fixes.md

If no arg is specified it crashed. If arg was not a number > 0 it
entered an infinite loop. Both have been fixed, exiting 1.
These checks were NOT done in the alt code as that's a copy of the 
original code.

Fix bugs in 1990/westley

---

1984/laman/README.md
1984/laman/laman.c
1990/jaw/Makefile
1990/jaw/README.md
1990/jaw/jaw.c
1990/jaw/shark.sh
1990/jaw/try.sh
1990/westley/README.md
1990/westley/westley.c
1991/dds/dds.c
1992/buzzard.1/README.md
1992/buzzard.1/buzzard.1.c
1992/gson/README.md
1992/westley/westley.alt.c
1992/westley/westley.c
1993/plummer/README.md
1993/plummer/plummer.alt.c
1993/plummer/plummer.c
1994/horton/Makefile
1994/horton/README.md
1994/horton/horton.c
2001/cheong/README.md
2001/cheong/cheong.c
2001/ollinger/ollinger.c
2001/schweikh/README.md
2001/schweikh/schweikh.c
2006/stewart/README.md
2006/stewart/stewart.c
bugs.md
thanks-for-fixes.md

The program (and the generated program made by shark.sh) no longer use
perror(3) and instead use fprintf(3) (writing to stderr). This is mostly
because in macOS errno == 0 looks like an error.
Some updates to the shark.sh script were also made.
The bug status has been updated as there is apparently another bug
though I was sure it was solved when I last looked at it. It happens
with and without the above updates. I'm unsure about other things too 
but these are not in the bugs.md yet as I'm not even sure what to say 
just yet.
Added try.sh script which does some of the commands. However as there is
that bug it doesn't do any comparisons - for now.

Fixes in 1990/jaw

---

1996/gandalf/Makefile

Remove outdated message about compilation not working in modern systems as I fixed this quite some time ago but failed to remove the message.

Update 1996/gandalf/Makefile about modern systems

---

1992/lush/README.md
1996/gandalf/Makefile
bugs.md

Rather than have:
STATUS: doesn't work with some compilers - please provide alternative code
It might be better to have:
STATUS: doesn't work with some compilers - please provide alternative code or fix for all compilers
which it now is.
Only one entry had it in so that entry and bugs.md were both updated.
Another entry in bugs.md was modified before and the README.md but the
status was not changed. That will be in the next commit which will be
this retitled one.

Retitle a bug status about some compilers

---

1995/cdua/README.md
1996/august/README.md
bugs.md
thanks-for-fixes.md

It is recommended that with 1995/cdua one should start out with the 
alternate version as the original goes too fast in modern systems to see
it do its task. The alternate code section has been changed to original
code.
Format and typo checked the README.md too. This is the only entry in 
1995 that I have done this for so far and is only done because I wanted
to make the alt code the suggested version to use first.

Swap alt/original in 1995/cdua

---

1992/westley/README.md

Removed the INABIAF section.
Added to alt section the subsections for build and to run. I did not add an alternate try command because I would have to look up some coordinates in the US (that's what it's for) and that takes time. I can do that when I do a proper check of this file.

Fix 1992/westley/README.md about fixed bug

---

2006/hamre/README.md
2006/hamre/hamre.c
bugs.md

Since I fixed all the entries that required this it was only cluttering
up the already very long file which doesn't seem like a good idea.

Remove bug status of -traditional-cpp from bugs.md

---

1986/wall/Makefile

This is because of what the entry is, the author's remarks and the fact that the warning produces fun output for the entry itself. The author had stated other warnings were fun but what these warnings were are no longer known and the messages almost certainly would be different now.

Disable -Wno-macro-redefined in 1986/wall/Makefile

---

1986/wall/Makefile
2000/primenum/primenum.c
bugs.md
thanks-for-fixes.md

To make the entry more portable the void main was changed to int main.
The no arg check was NOT fixed: this is a documented feature not a bug 
and should not be fixed. If one wants to fix it for personal enjoyment 
(if they can get pleasure from a couple seconds :-) ) they may do so but
it is not to be committed.

Fixes in 2000/primenum - int main from void main

---

bugs.md

Fix a few things. Now it's in good state. There were some fixes made already but it still only works for i386 linux (except the supplementary program can compile and work in modern systems for fun after I fixed it) and if anyone wants to provide a version for x86_64 linux, for example, they can do so.

Minor update 2001/bellard in bugs.md

---

1994/schnitzi/.gitignore
1994/schnitzi/Makefile
1994/schnitzi/README.md
1994/schnitzi/schnitzi.alt2.c
bugs.md
thanks-for-fixes.md

The first version uses fgets(3). This version will compile (note that it does not compile right away: one has to make other adjustments; it is not a matter of just changing the code to use fgets()!) but when fed its own source code it will not generate code that can be compiled let alone use fgets(3).
The second version, schnitzi.alt2.c, has an increased buffer size but it will not generate code with the same buffer size; rather the size will be the original. I explain this in detail (did this quite some time back) in the bugs.md file. I noticed today that the author gives quite some details too which will be something I can look at later on. Right now it's more important to get the website in order so that the next contest can run! I will only look at this later on or else at a time …

Add alt versions to 1994/schnitzi

---

1994/schnitzi/.gitignore
1994/schnitzi/Makefile
1994/schnitzi/README.md
1994/schnitzi/schnitzi.alt2.c
bugs.md
faq.md
thanks-for-fixes.md
todo.md

The FAQ has been updated to add something that was missing to the entry
about the general Makefile rules (make clobber, make all, make alt etc.)
that was in the todo. This has been removed from the todo.md as well.
Fix link in FAQ: not how-to-bugfix.md but how-to-help.md as I changed
this a while back as it isn't a matter of fixing a bug (which could be
any number of problems) but rather how to help with the website etc.
Make sure before a line starting with '#' that there are two blank lines
above it. Some already had this but many did not.
Change other things in todo.md file based on some things that have been
done (with corrections needed in some cases and otherwise the need to
verify no corrections are needed).
Typo fix in todo.md (swap a letter with a space).
I am aware that the …

Fixes in FAQ and todo files

---

1994/schnitzi/.gitignore
1994/schnitzi/Makefile
1994/schnitzi/README.md
1994/schnitzi/schnitzi.alt2.c
1998/schnitzi/Makefile
1998/schnitzi/README.md
1998/schnitzi/schnitzi.c
1998/schnitzi/try.sh
bugs.md
faq.md
thanks-for-fixes.md
todo.md

The author stated that there was no 'if's and I have made it that way
now.
The author stated that the number should be > 0 && < 27 so I added the
range check (was previously != 0). Too high value could segfault and < 0
was problematic too. 27 itself was code that could not compile. Since
the program is so beautiful it had been decided to fix the problems
which is why these changes were added too.
The above was done like:
((V[1]&&((atoi(V[1])>0&&atoi(V[1])<27)||(exit(1),1))));
The try.sh script has been added to the entry to try out a lot of
commands instead of copy pasting it from the judges' remarks.
Removed duplicate INABIAF information from README.md (which is why the
other updates).
Updated bugs.md with more information to the features like how output
can end up being gigabytes in …

Improve fixes to 1998/schnitzi

---

1984/anonymous/README.md
1984/anonymous/anonymous.c
1994/schnitzi/.gitignore
1994/schnitzi/Makefile
1994/schnitzi/README.md
1994/schnitzi/schnitzi.alt2.c
1998/schnitzi/Makefile
1998/schnitzi/README.md
1998/schnitzi/schnitzi.c
1998/schnitzi/try.sh
bugs.md
faq.md
thanks-for-fixes.md
todo.md

Somehow I ended up having the string on one line when the author had it
on two lines which is also something they liked.
This update should (unless the format of the alt code section needs to 
change with discussion) be the final edit of README.md.

Fix fix on 1984/anonymous

---

bugs.md

The new text saying that there are no known bugs or (mis)features in a year is great but rather than say:
There was no known bugs and (Mis)features for [0-9]{4}.
(which has a typo: was -> were)
it now says:
There are no known bugs and (Mis)features for entries in [0-9]{4}.
as this is clearer and it's possible that bugs or (mis)features might be discovered yet.

Typo fixes in bugs.md

---

bugs.md
tmp/format-headers.sh

With a slight modification so that the script uses git ls-files so that 
it only acts on files called README.md under the directories of the
years (i.e.  '[0-9]{4}/*README.md') that are under git control this
script formats headers so that the spacing before lines starting with
'##' (as in '^##') are correct. It checks for specific header names. 
More could be added if necessary and if any heading level is wrong or it 
is decided that a different heading level might be better the regexp can
be modified to fix it as well.
This script will be useful to run after every README.md file has been
updated. 
Added to tmp/ as it is likely (or possibly?) a temporary tool that might
not be needed after the temp-test-ioccc repo is merged back into the
winner repo. On the other hand it might be useful …

Add tmp/format-headers.sh script from Landon

---

bugs.md
thanks-for-fixes.md
tmp/format-headers.sh

This includes one in code that had to be changed that happened after I
changed the code to be slightly more portable, not hardcoding gcc but
rather cc in 1998/schweikh1 but forgot to update the thanks file, 
forgetting that part was in the file.

Typo fixes in thanks-for-fixes.md

---

1990/baruch/README.md
1990/dds/README.md
1998/schweikh3/.gitignore
1998/schweikh3/Makefile
1998/schweikh3/README.md
1998/schweikh3/try.sh
bugs.md
thanks-for-fixes.md
tmp/format-headers.sh

In order to try and speed things along some of the things that might be
good to have in code blocks (as in '`` ` ``' ) have not been done so it can be
seen if this can be omitted. If it works out it's almost certain that
this can be done with other README.md files which also have places where
'`` ` ``'s might be useful. An example here where it's not used but might be
is in the section 'Program commands' with variables NOT enclosed in '`'s
and other things that might look a little better with them.

Format check and test 1990/dds/README.md

---

1990/baruch/README.md
1990/dds/README.md
1991/dds/README.md
1998/schweikh3/.gitignore
1998/schweikh3/Makefile
1998/schweikh3/README.md
1998/schweikh3/try.sh
bugs.md
thanks-for-fixes.md
tmp/format-headers.sh

As the definition of a bug and feature was changed numerous times the 
feature or bug of if a file could not be opened for reading or a file 
could not be opened for writing was actually fixed to not crash. This 
has not been done in other entries and almost certainly won't be but 
with this one it was done (recently when there was a change of bug
status in several entries as how the bugs.md file being referred to in 
the README.md files was improved) so this has inconvenient feature was 
removed from the README.md file. It was not noted in the thanks file 
either so that has been updated as well.

Remove outdated feature/bug in 1991/dds/README.md

---

1990/baruch/README.md
1990/dds/README.md
1990/pjr/.gitignore
1990/pjr/Makefile
1990/pjr/README.md
1990/pjr/pjr.alt.c
1991/dds/README.md
1998/schweikh3/.gitignore
1998/schweikh3/Makefile
1998/schweikh3/README.md
1998/schweikh3/try.sh
bugs.md
thanks-for-fixes.md
tmp/format-headers.sh

This alt code is recommended by the judges in the case the compiler 
cannot compile main() due to lack of temporary stack space but it is
also recommended by the author as it does something else.

Add alt code to 1990/pjr

---

1998/schweikh3/.gitignore
1998/schweikh3/Makefile
1998/schweikh3/README.md
1998/schweikh3/try.sh
bugs.md
thanks-for-fixes.md
tmp/format-headers.sh

The try.sh script runs the commands in the try section of the README.md.
The README.md had SOME format fixes.
The Makefile symlinks the program to samefile.
The author stated on their website that:
the Internet Systems Consortium (ISC) has added my samefile utility
to its treasure of software gems.
and this has been added to the README.md in the judges' remarks, along
with the web page for the program!

Add 1998/schweikh3/try.sh + other fixes & updates

---

1990/jaw/README.md
1990/jaw/btoa
bugs.md
thanks-for-fixes.md

This now lets the command in the judges' remarks:
echo "Quartz glyph jocks vend, fix, BMW." | compress | ./btoa | ./jaw
not report just:
oops
oops
and instead it outputs data which suggests, I believe, that the program is not buggy but instead the script had to have the 'xbtoa' changed to 'btoa'.
Updated bugs.md and thanks-for-fixes.md and README.md file too.
Other changes were made to thanks file as they are more appropriate than in the README.md (of 1990/theorem) after the (once again sounding like a broken record) vastly superior idea of the thanks file came up. This addition here is unintentional; it was just already there but not ready for committing as 1990/theorem/README.md was not yet ready. That file will be committed today.

Fix 1990/jaw/btoa script

---

1990/jaw/Makefile
1990/jaw/README.md
1990/jaw/btoa
1990/jaw/shark.sh
bugs.md
thanks-for-fixes.md

It is not actually necessary to mess with the path and in fact the $PATH variable is no longer modified or even referred to. The purpose of the program was that even without btoa and uncompress the script should be able to extract the tarball.
Now only the tarball path is hard coded as reading a tarball from stdin is problematic though I'm pretty sure it used to work.

Don't hard code paths in 1990/jaw/shark.sh

---

1990/jaw/Makefile
1990/jaw/README.md
1990/jaw/btoa
1990/jaw/shark.sh
1990/tbr/README.md
1990/westley/README.md
bugs.md
thanks-for-fixes.md

This also fixes a typo I introduced that would result in a syntax error
in use.
It also adds proper '### Alternate build' and '### Alternate use' 
sections.
I've decided that for the rest of the README.md files I will try not 
worrying much about grammar unless it makes it harder to understand the
information or it's very quick. This way all these can get done sooner.

Typo/format check 1990/westley/README.md

---

1990/jaw/Makefile
1990/jaw/README.md
1990/jaw/btoa
1990/jaw/shark.sh
1990/tbr/README.md
1990/theorem/README.md
1990/westley/README.md
2020/tsoj/.gitignore
2020/tsoj/Makefile
2020/tsoj/README.md
2020/tsoj/prog.alt.c
bugs.md
thanks-for-fixes.md

This version will feel more at home for those who are familiar with vi
movement keys. It does not use curses so no arrow keys but the entry
itself uses the old wasd movement controls. Now one can use k, h, j and 
l for movement.
Updated .gitignore and README.md file. The file was NOT format fixed. 
Work on this entry was not supposed to happen yet but looking for 
something I came across this one and decided to make it more friendly to
vi users (the wasd movement has always been a problem for me another 
winner in 2020 also told me that they found it difficult).

Add alt code to 2020/tsoj

---

index.html
tmp/README.md
tmp/run_all.sh

Including one that has bugged me for years now, the 'Ideas of March' :-)
instead of the Ides of March.
Fun facts: ides can be used for other months too, in Roman times. It was 
the middle of the month so depending on the month it would be the 15th
or the 13th. 'Calends'/'kalends' for first day of the month and 'nones'
for before they had months! :-) (no: actually it was the ninth day
before the ides by inclusive reckoning so the 7th or 5th depending on
the month).

Typo fixes in index.html

---

1991/fine/try.sh
1996/jonth/README.md
bugs.md
index.html
thanks-for-fixes.md
tmp/README.md
tmp/run_all.sh

There are two issues to be aware of, both features, that have been added
to the bugs.md. The status has been added to the README.md as well. 
These issues are that if X is not running the program is likely to crash
and also the two windows are likely to be on top of each other so 
you'll have to move one off the other.
Since it's been requested and since I am editing the README.md file 
anyway the award and author information has been removed from the file
so that the first line is '## How to build:'. Other README.md files are
also currently modified and this will happen that way before a mass 
edit.

Update bug status of 1996/jonth + format README.md

---

1991/ant/README.md
1991/fine/try.sh
1996/jonth/README.md
bugs.md
index.html
thanks-for-fixes.md
tmp/README.md
tmp/run_all.sh

This file has not been completely checked but some fixes were made. As 
well since it has been requested that the award and author information 
be removed from the file, making '## To build:' the first line, this has
been done as these other changes were already made. When all README.md 
files have been updated a mass edit will be done for this. There 
currently are six others.

(Some) fixes in 1991/ant/README.md

---

1991/ant/README.md
1991/cdupont/README.md
1991/fine/try.sh
1996/jonth/README.md
1998/dlowe/README.md
bugs.md
index.html
thanks-for-fixes.md
tmp/README.md
tmp/run_all.sh

The description said to run 'make dlowe.alt' and this is incorrect: it 
should be 'make alt'.
Also since it has been requested that the award and author information 
be removed from the README.md files this has been done since this fix 
was already made but not yet committed.
In the previous commit it was stated that there were five more README.md
files counting this one, but that's incorrect as that one only was 
removing the home(?) address of one of the authors (two I believe) so 
that can happen with the mass edit of removing award and author 
information. Thus not counting this one there are another three 
README.md files I believe it is before that mass edit can happen.

Minor fix in 1998/dlowe/README.md wrt alt code

---

1991/ant/.gitignore
1991/ant/Makefile
1991/ant/README.md
1991/buzzard/.gitignore
1991/buzzard/Makefile
1991/buzzard/README.md
1991/buzzard/buzzard.alt.c
1991/buzzard/buzzard.c
1991/fine/Makefile
1991/fine/README.md
1991/fine/fine.c
bugs.md
thanks-for-fixes.md

With more clever use of the Makefile the number of characters is back 
down to 80 which is what the original was!
This also fixes the warning that was introduced when it was dropped back
down to 85. 'B' is defined as '(int)b' which is used in two places where
a cast is necessary or otherwise will silent a warning.
The README.md file has been checked and this should complete this entry
now.

Drop 1991/fine back to its original 80 chars

---

1991/buzzard/.gitignore
1991/buzzard/Makefile
1991/buzzard/README.md
1991/buzzard/buzzard.alt.c
1991/buzzard/buzzard.c
bugs.md
thanks-for-fixes.md

There were two crashes that I noticed, both due to atoi(3) being called on an arg without a type which ended up being an implicit int rather than a 'char *'. This is for the x and y coordinates. I don't have an example command line to test different configurations but now the program shouldn't crash unless the file cannot be opened. See bugs.md for details there (whether it should crash or not on not being able to open the file is debatable I suppose but I left it in as a feature, not a bug; the others made the program unusable which is why they were fixed).
The alt version can be more at home for those familiar with vi(m) (it certainly is for me): instead of 'f' for forwards, 'l' for left and 'r' for right it is now 'k', 'h' and 'l' respectively. The program does not allow one to go …

Fix 1991/buzzard and add alt code

---

1991/ant/.gitignore
1991/ant/Makefile
1991/ant/README.md
1991/buzzard/.gitignore
1991/buzzard/Makefile
1991/buzzard/README.md
1991/buzzard/buzzard.alt.c
1991/buzzard/buzzard.c
bugs.md
thanks-for-fixes.md

The alt code will make it a bit less unwieldy for vi(m) users by 
changing the following input keys to be like in vi(m):
- Use 0 to go to first column.
- Use $ to go to last column.
- Hit ESC to go back to command mode (instead of form-feed, ctrl-L).
- Use w to go forwards one word.
- Use b to go backwards one word.
- Use q to exit.
The rest of the keys were left unchanged.
Format fix README.md file.
This completes 1991/ant checks unless I'm very much mistaken.

Add alt code to 1991/ant and format README.md

---

1991/ant/.gitignore
1991/ant/Makefile
1991/ant/README.md
1991/buzzard/.gitignore
1991/buzzard/Makefile
1991/buzzard/README.md
1991/buzzard/buzzard.alt.c
1991/buzzard/buzzard.c
bugs.md
thanks-for-fixes.md

Now allows for 'q' to exit the maze. This is to be a bit more intuitive
at least for those who use the alt version, which is not the recommended
version to try first nor should it be. This change is not in the 
original nor should it be.

Slight improvement to 1991/buzzard alt code

---

1991/ant/.gitignore
1991/ant/Makefile
1991/ant/README.md
1991/buzzard/.gitignore
1991/buzzard/Makefile
1991/buzzard/README.md
1991/buzzard/buzzard.alt.c
1991/buzzard/buzzard.c
1991/dds/README.md
1991/fine/Makefile
1991/fine/README.md
1991/fine/fine.c
bugs.md
thanks-for-fixes.md

Remove the 2>/dev/null as that is no longer needed as the code was 
updated a while ago to use fgets() in the enciphered string (the output
program used gets() but now it uses fgets()).
Format and typo fix README.md.
I believe this completes 1991/dds.

Fixes in 1991/dds/README.md

---

1992/albert/.gitignore
1992/albert/README.md
1992/albert/albert.alt.c
1992/albert/albert.c
1992/westley/.gitignore
1992/westley/Makefile
1992/westley/README.md
1992/westley/try.sh
1992/westley/westley.alt.c
1992/westley/westley.c
bugs.md
thanks-for-fixes.md

The alt code was the original; the entry was a bug fixed version by Leo
(before he was a judge). However that version, the fixed version, was
not obfuscated and as the judges say in the FAQ:
the contest is called the IOCCC, not the INVOCCC :-)
so it seems better to have the version that has a bug as the entry. But
that code no longer compiled. This has been fixed. 
Minor changes to README.md wrt the swapping of alt code/entry code. The
formatting has not been checked and no typos have been fixed either. 
These will come later.

Fix 1992/albert, swap alt/main code

---

1992/westley/Makefile
1992/westley/README.md
1992/westley/try.sh
1992/westley/westley.alt.orig.c
1992/westley/whereami.alt.c
1992/westley/whereami.c
thanks-for-fixes.md

Added whereami.c and whereami.alt.c which, using curses, gets the number of columns of the terminal. If < 80 it is an error. Otherwise it will try compiling the westley.c or westley.alt.c and if successful it will run the program with the args specified.
The try.sh script will use whereami or whereami.alt if it's possible to compile and link (it might not if curses is not installed) and otherwise westley and westley.alt.
Running make all will compile westley.c and also whereami.c; running make alt will compile westley.alt.c and whereami.alt.c. The try.sh script does NOT use that but instead uses make westley alt: this is because we need to be sure that westley.c and westley.alt.c can compile but it is NOT an error if whereami.c or whereami.alt.c cannot compile. So the Makefile was done in …

Greatly improve 1992/westley presentation

---

1992/adrian/Makefile
1992/adrian/README.md
1992/adrian/adrian.c
1992/albert/README.md
1992/ant/Makefile
1992/ant/README.md
1992/ant/ant.README
1992/ant/ant.c
1992/ant/ant.test.mk
1992/westley/Makefile
1992/westley/README.md
1992/westley/try.sh
1992/westley/westley.alt.orig.c
1992/westley/whereami.alt.c
1992/westley/whereami.c
bugs.md
thanks-for-fixes.md

The Makefile has had a new rule added and another fixed as 'am' does not 
support certain features that the Makefile uses.
Added #include <time.h> as the author stated that for some systems it 
might be necessary (like DOS with Turbo C assuming anyone here uses 
that).
Typo fixes including references to files that do not exist (am.c -> 
ant.c and so on).
Typo/format check README.md and ant.README.

Fixes to 1992/ant

---

1992/adrian/Makefile
1992/adrian/README.md
1992/adrian/adrian.c
1992/albert/README.md
1992/ant/Makefile
1992/ant/README.md
1992/ant/ant.README
1992/ant/ant.c
1992/ant/ant.test.mk
1992/buzzard.1/README.md
1992/buzzard.1/try.sh
1992/buzzard.2/Makefile
1992/buzzard.2/README.md
1992/buzzard.2/buzzard.2.README.md
1992/westley/Makefile
1992/westley/README.md
1992/westley/try.sh
1992/westley/westley.alt.orig.c
1992/westley/whereami.alt.c
1992/westley/whereami.c
bugs.md
thanks-for-fixes.md

Running make all now links first.
The README.md now has been checked for formatting and typos.
The buzzard.2.README.md file has also been checked for formatting and 
typos.

Fixes to 1992/buzzard.2

---

1992/gson/Makefile
1992/gson/README.md
thanks-for-fixes.md

The fix is simply disabling the optimiser. This allows the specific cases where it crashed on start in macOS to not happen. An example command where it crashed:
./gson free software foundation < /usr/share/dict/words
The README.md file has been typo/format checked.

Fix 1992/gson in macOS + format/typo checks

---

thanks-for-fixes.md

It's not that it needs any 32-bit binaries but rather the files opened/modified must be 32-bit ELF binaries.

Minor correction in thanks wrt 2001/anonymous

---

1991/dds/dds.c
thanks-for-fixes.md

It came to my attention that some versions of clang trigger and additional warning that has to be disabled in order to compile the a.c that the entry generates. This has been fixed.
I am NOT including the translate.c file that I wrote to come up with the proper string (it encrypts and decrypts though with some limitations) as I don't want to give it away too much. I MIGHT include it on my website another time in case it is ever necessary (though the hope and belief is it won't be but who knows with clang). This would be AFTER the website has been looked at. This has already taken too much time to fix. It is now time to finish 1992 and then go on to 1993.

Further clang fixes for 1991/dds

---

1991/dds/dds.c
1992/imc/README.md
1992/imc/imc.c
thanks-for-fixes.md

The original imc code assumed that exit(3) returns a value but it was
changed to use the comma operator:
#define                       ext(a) (exit(a),0)
Instead of this, I redefined exit like I have done with other fixes, to
make it more like the original.
I also format/typo checked the README.md file.
I cannot test the raster files as I don't have access to a Sun box but 
the text seems good. I tried some of the example commands given by the 
author but I did not try all the options. What I tested looks good as 
best I can tell.
For fun and because I have fond memories I added a link to dot matrix 
printers where the author noted that they are useful, though I guess 
most people don't have access to them nowadays (and many don't even know
what they are which is another reason for a link …

Make 1992/imc more like original + formatting

---

1992/nathan/.gitignore
1992/nathan/README.md
1992/nathan/try.sh
thanks-for-fixes.md

The try.sh script runs the commands provided by the judges in the try section (which has been updated to just refer to './try.sh') and one I included as well.

Add 1992/nathan/try.sh + format fixes

---

1993/leo/Makefile
1993/leo/README.md
1993/lmfjyh/README.md

Running 'make' now links 'mind' to 'leo' (via the 'mind' rule).
Format/typo check the README.md file. 
This should complete the entry unless a certain thing I found is a bug 
in which case the bugs.md has to be updated (and the README.md refer to
it). This is not certain yet.

Fixes in 1993/leo

---

1993/cmills/.gitignore
1993/cmills/Makefile
1993/cmills/README.md
1993/cmills/cmills.alt.c
1993/dgibson/README.md
1993/ejb/README.md
1993/ejb/patience.md
1993/jonth/README.md
1993/leo/Makefile
1993/leo/README.md
1993/lmfjyh/README.md
bugs.md
thanks-for-fixes.md

The alt version uses usleep(3) with a configurable time (at compile 
time). This version is suggested first as it apparently goes too fast in
modern systems. I say apparently as it doesn't appear to work with 
macOS. I don't know if it works in other platforms but it is in bugs.md,
that there is a problem.

Updates to 1993/cmills - alt code + bugs + format

---

1993/ant/README.md
1993/ant/ant.txt
1993/cmills/.gitignore
1993/cmills/Makefile
1993/cmills/README.md
1993/cmills/cmills.alt.c
1993/dgibson/README.md
1993/ejb/README.md
1993/ejb/patience.md
1993/jonth/README.md
1993/leo/Makefile
1993/leo/README.md
1993/lmfjyh/README.md
bugs.md
thanks-for-fixes.md

Format/typo check ant.txt. I kept the terms the same like 'period' for 
'.' as I believe that's the way it is in POSIX (even though I'd prefer
dot or full stop). I added in parentheses some symbols where they were 
missing and there was a typo here and there. I was considering adding 's
round some characters to make things stand out a bit better but I did 
not do that. If that's useful it can be done another time.
The bugs.md has been updated as well, both with INABIAF and missing file
statuses.
I believe that this completes 1993/ant the 's idea noted above 
notwithstanding.

Format/typo check 1993/ant

---

1993/cmills/Makefile

When adding the alt code I yank pasted the rule for cmills but by accident neglected to add the '.alt' to the rule. This was not seen because of the way the Makefile 'alt' rule is designed (in some cases one need not have more than just that 'alt' rule) and other reasons besides.

Minor fix in 1993/cmills/Makefile

---

thanks-for-fixes.md

Moved notes about gets() versus gets() closer to the top, BEFORE thanks (of individual entries and mass fixes like those of the Makefiles).
Added section (also at top before thanks for individual entries and mass fixes like those of the Makefiles) with notes about bugs versus (mis)features as this can be a fine line at times.
Format fixes in some entries and perhaps some other minor changes as well.

General improvements to thanks-for-fixes.md

---

1994/horton/Makefile
1994/horton/README.md
faq.md
thanks-for-fixes.md

The alt code was being compiled with 'all' rather than 'alt'.
The README.md file also has had format updates including referring to
the alt code as well as the gtface.c.
This should complete 1994/horton.

Fix 1994/horton/Makefile and README.md

---

1994/horton/Makefile
1994/horton/README.md
1994/imc/README.md
1994/schnitzi/README.md
1994/shapiro/README.md
1994/shapiro/shapiro.md
faq.md
thanks-for-fixes.md

This completes 1994/shapiro as long as a formatting change in shapiro.md
is correct. That will be checked and if necessary it will be fixed.

Format/typo fixes in 1994/shapiro

---

1994/horton/Makefile
1994/horton/README.md
1994/imc/README.md
1994/schnitzi/README.md
1994/shapiro/README.md
1994/shapiro/shapiro.md
1994/smr/README.md
1994/tvr/Makefile
1994/tvr/README.md
1994/tvr/tvr.c
bugs.md
faq.md
thanks-for-fixes.md

Format/typo fix README.md.
The entry now uses fgets(3); the alt code that the author included does
not (yet?).
Added entry to bugs.md for the fgets(3) for the alt code and a bug that
is noted by the judges, asking if [you] can fix it.

Fixes in 1994/tvr

---

1991/dds/dds.c
1994/horton/Makefile
1994/horton/README.md
1994/imc/README.md
1994/schnitzi/README.md
1994/shapiro/README.md
1994/shapiro/shapiro.md
1994/smr/README.md
1994/tvr/Makefile
1994/tvr/README.md
1994/tvr/tvr.c
1994/weisberg/Makefile
1994/weisberg/README.md
1994/westley/README.md
bugs.md
faq.md
thanks-for-fixes.md

Rather than having the string that is run via system(3) use 
-Wno-return-type the generated code (also in the string) now returns 1;
rather than 'return;' so that main() has a proper return statement.
This means the string was updated and the call to system(3) was also 
updated but it is a bit better now. It is hoped that this is the last 
time (..yet again..) that this will have to be updated to work with 
various systems but as before the magic is in the thanks file, at least 
for now.

Further improvements to 1991/dds fix

---

1995/dodsond1/README.md
1995/dodsond1/try.sh
thanks-for-fixes.md

The try.sh script uses the text file that I added a while back which has the text that the judges recommended one try with the program.

Add try.sh to 1995/dodsond1 + format/typo checks

---

1995/dodsond1/README.md
1995/dodsond1/try.sh
1995/esde/README.md
1995/esde/try.sh
1995/garry/README.md
1995/garry/garry.alt.test.sh
1995/heathbar/README.md
1995/leo/README.md
1995/leo/spoiler1.md
1995/vanschnitz/README.md
thanks-for-fixes.md

The spoiler1.md file is what was once uuencoded (and still is in the
author's remarks) but is no longer desired to be so.
This should complete 1995/leo and I believe this finishes 1995 too.

Format/typo checks in 1995/leo + add spoiler1.md

---

1990/pjr/README.md

A code block was erroneously stated to be C due to the -> operator being there but actually it's not any operator but rather a transition from one to the next.

Format fix in 1990/pjr

---

1991/ant/ant.alt.c
1992/kivinen/.gitignore
1992/kivinen/Makefile
1992/kivinen/README.md
1992/kivinen/kivinen.alt.c
1998/fanf/.gitignore
1998/fanf/Makefile
1998/fanf/README.md
1998/fanf/try.sh
1998/schnitzi/README.md
1998/schweikh1/README.md
1998/schweikh1/charcount.pl
1998/schweikh1/macos.md
1998/schweikh2/README.md
1998/schweikh3/Makefile
1998/schweikh3/README.md
1998/schweikh3/schweikh3.c
1998/schweikh3/try.sh
1998/tomtorfs/README.md
1998/tomtorfs/tomtorfs.c
1998/tomtorfs/try.sh
2006/toledo2/toledo2.alt.c
bugs.md
faq.md
thanks-for-fixes.md

The try.sh script has been added to run the various inputs the judges 
recommended one try.
The Makefile now can do the intermediate steps. This is possible with 
the way I fixed the entry to compile. If you look at the original code 
it's different than the fixed version which is post processing (if I 
recall correctly).
Unless there's a mistake in markdown formatting this should complete 
1998/fanf's review.

Updates and fixes to 1998/fanf

---

bugs.md

It has been confirmed that this issue, a blank screen, occurs in multiple systems, not just macOS. A RHEL 9.3 system also has the problem.

Update bug description of 1993/cmills

---

bugs.md

The alt code in the bug section more clearly states that it will work 
for modern systems. Probably already implied but it's now clearer.

Minor update to 1993/lmfjyh in bugs.md wrt alt

---

1991/ant/ant.alt.c
1992/kivinen/.gitignore
1992/kivinen/Makefile
1992/kivinen/README.md
1992/kivinen/kivinen.alt.c
2006/toledo2/toledo2.alt.c
bugs.md
thanks-for-fixes.md

Originally the main version was changed to have a call to usleep(3) as
the game moves so fast. It was discussed a while back however to in
cases like this to make it so that the build/use/try sections refer to
the alt code and then instead of an alternate code section have an
original code section. Because of this the modified code was changed to
be an alt version and then restore the original with the fixed code.
As for the fixed code (and also alt code) I have made it look more like 
the original by changing the 'ext' macro to be 'exit' (with the comma
operator). I tried and believe I succeeded (mostly if not totally) in
making the lines start and end on the same columns and in at least some
lines the same character starts and ends the lines as the original.

Make 1992/kivinen/kivinen.c alt code

---

1991/ant/ant.alt.c
1992/kivinen/.gitignore
1992/kivinen/Makefile
1992/kivinen/README.md
1992/kivinen/kivinen.alt.c
1998/tomtorfs/README.md
1998/tomtorfs/tomtorfs.c
1998/tomtorfs/try.sh
2006/toledo2/toledo2.alt.c
bugs.md
faq.md
thanks-for-fixes.md

The author stated that the program assumes EOF is -1 but for systems
that do not have this it will fail. This is indeed a valid concern as
the standard mandates that it's a value < 0 but it doesn't require it to
be -1.
The author also stated that the program could fail if 1 is not a return
value that indicates error so this was changed to EXIT_FAILURE as the
suggested was made. It is possible of course that I missed a place where
this should have been updated but I don't believe so. I am unaware of
any system where this would be a problem and I don't know why it matters
anyway but I made the change as the author stated it could be a problem
with portability.
The README.md file has been formatted and typo checked.
Added try.sh script.
This should complete this entry's review.

Fixes in 1998/tomtorfs, add try.sh & format fixes

---

1991/ant/ant.alt.c
1992/kivinen/.gitignore
1992/kivinen/Makefile
1992/kivinen/README.md
1992/kivinen/kivinen.alt.c
1998/schweikh1/README.md
1998/schweikh1/charcount.pl
1998/schweikh1/macos.md
1998/schweikh2/README.md
1998/schweikh3/Makefile
1998/schweikh3/README.md
1998/schweikh3/schweikh3.c
1998/schweikh3/try.sh
1998/tomtorfs/README.md
1998/tomtorfs/tomtorfs.c
1998/tomtorfs/try.sh
2006/toledo2/toledo2.alt.c
bugs.md
faq.md
thanks-for-fixes.md

The perl script that the author said they use to count chars in the code
(according to the IOCCC rules at the time) was added as charcount.pl.
Moved the macOS details/spoiler (though it has information about the 
main entry as well) to macos.md.
README.md file format and typo checked.
This should complete this entry's review.

Updates and fixes to 1998/schweikh1

---

1998/dloweneil/.gitignore
1998/dloweneil/Makefile
1998/dloweneil/README.md
1998/dloweneil/dloweneil.alt.c
thanks-for-fixes.md

The alt code should feel more at home for vi(m) users with movements. With the exception of the drop key (d in the original) you can use the original keys as well. Keys to drop the letter in alt version j or space, whichever you prefer. Also you can quit the game gracefully (q). That was something the author(s)? noted as something they wish they could have done but due to contest size restrictions they could not.
The README.md file has been format and typo checked and this should complete the review of this entry.

Add 1998/dloweneil alt code + formatting

---

faq.md

This includes typos, inconsistencies as well as updates to referring to an entry to show how clang can complicate matters (sometimes greatly) but making your entries work with clang will make your entry better.

Minor fixes and clarifications in FAQ

---

1989/westley/Makefile
1989/westley/compile.sh
1989/westley/try.sh

The scripts now allow one to pass in CC=foo. If a path is specified it'll use that path (for instance in case you want a different version or because in macOS /usr/bin/gcc is actually clang); otherwise the shell will try working it out. If one does not do CC=foo then it'll default to 'cc'.
Both try.sh and compile.sh allow this and try.sh will pass CC to compile.sh before running the commands.
The CSILENCE variable in the Makefile has been updated as well. It is not possible to silence all warnings with clang but most of them are, at least in macOS clang (not tested linux yet).

Improve try.sh and compile.sh in 1989/westley

---

1988/westley/Makefile
1988/westley/try.sh
1988/westley/westley.c
1991/fine/try.sh
1992/buzzard.1/Makefile
1992/buzzard.1/try.sh
1992/nathan/try.sh
1992/westley/Makefile
1992/westley/try.sh
1992/westley/whereami.alt.c
1992/westley/whereami.c
thanks-for-fixes.md

The try.sh now allows for specifying CC=foo.
The whereami.c and whereami.alt.c also allows for this. It leaks memory
but the OS should reclaim it and it's not a lot. It leaks memory because
if calloc(3) returns NULL it sets the string to a literal string to
prevent any problems with it (though one might wonder if the rest of it
will work).

Improve 1992/westley/try.sh + whereami code

---

2013/birken/Makefile
2013/birken/README.md
2013/birken/birken.alt.c
2013/birken/birken.c
2013/birken/try.sh
thanks-for-fixes.md

As long as the program (alt code and otherwise) runs to completion the program will return instead of 0:
system("reset");
so that the terminal becomes sane again (otherwise cursor is invisible).  One could also use 'tput cvvis' but this is longer and I wanted to make the column as close to the original ending as possible.
After that (next commit, meant to be commit --amend) it was changed to redefine exit(3) so that the line length would be the same as before.

Make 2013/birken restore sanity after exit

---

2000/thadgavin/Makefile
2000/thadgavin/README.md
2000/thadgavin/thadgavin.alt.c
faq.md
thanks-for-fixes.md

The alt code now allows one to quit early (in curses mode) and this calls endwin() to restore terminal sanity. Due to the way the code is designed the function which does that has to be defined three times but only one has any code in it, that of the curses one. This means that nodelay() is also called when initialising curses. At least at this time the original entry does not have this feature and so one will have to type 'reset' after they end the program to restore terminal sanity.
The alt code has been improved in another way too: now one does not have to specify both macros at the command line when wishing to configure only one of the programs. This is accomplished by #ifndef..#endif blocks at the beginning of the file. That has not been done in other entries but probably should be …

Updates and improvements to 2000/thadgavin

---

2019/karns/Makefile
2019/karns/README.md
2019/karns/try.sh

It was already documented as such (in the thanks file) but it was still the old name (demo.sh). The README.md had demo.sh still but this has been updated as it's all for the try section.

Rename 2019/karns/demo.sh try.sh

---

2000/dlowe/README.md
bugs.md

This entry crashes in macOS. This MIGHT be related to the version of perl, both with MacPorts and Homebrew. See the bugs.md for many more details.
The author gave an example command and output (well several) and one I tried (I did not try all) did not report correct output (some did). Again the bugs.md file has many more details.
Format/typo fix README.md.
With the exception of possibly fixing the bugs noted in bugs.md this should complete the review of 2000/dlowe.

Update bug status of 2000/dlowe

---

1996/huffman/try.sh

It should be more like:
```
Well the wolf-man fell dead
As you can plainly see
And that's the end the story for you and me
You still give a listen, you just may
Hear a big wolf-man or little piggy say
Little pig, little pig, let me in
Not by the hair of my chinny, chin, chin
Little pig, little pig, let me in
Not by the hair of my chinny, chin, chin
Well I'm huffin', I'm puffin'
I'll blow your house in
Huffin', puffin', blow your house in
Huffin', puffin', blow your house in
Huffin', puffin', blow your house in
Huffin' and a puffin' and
I'll blow your house in!
Huffin' and a puffin' and
I'll blow your house in!
Huffin' and a puffin' and
I'll blow your house in!
Huffin' and a puffin' and
I'll blow your house in!
And the moral of the story is that
bands with no talent can easily amuse
Idiots …
```

Fix typos (from paste) in 1996/huffman/try.sh

---

1985/shapiro/.gitignore
1985/shapiro/Makefile
1985/shapiro/README.md
1985/shapiro/shapiro.alt.c
1985/shapiro/try.alt.sh
thanks-for-fixes.md

This alt code allows one to resize the maze. Obviously if one uses -D with a value that's not a number it will fail to compile. If it's <= 0 || >= 5000 it will set to the default of 39.
The try.alt.sh script plays with this, first selecting a random number (in range $RANDOM % 38) to compile with and then run. After that it runs in an infinite loop, exiting only if input includes non-digit characters. A value >= 5000 sets it to the default of 39 (in the code).

Add alt code to 1985/shapiro

---

1991/buzzard/Makefile
1991/buzzard/README.md
1991/buzzard/buzzard.alt.c
1991/buzzard/buzzard.c

The parameter type of q in function z() should be a 'char *', not a 'char **'.
Added to CSILENCE -Wno-implicit-int.
Note that if including files for abs(3), strlen(3) or other functions implicitly declared the program will not work (or at least it won't work if at least one of them is #included?).

Fix fix on 1991/buzzard

---

thanks-for-fixes.md

This was done by changing the section at the top about fgets() a bit and then removing much of what was previously in each entry that had the change.

Remove duplicate text about fgets() in thanks file

---

2001/anonymous/Makefile
2001/anonymous/README.md
2001/ctk/Makefile
2001/ctk/README.md
2001/ctk/ctk.c
2001/dgbeards/README.md
2001/dgbeards/dgbeards.alt.c
2001/jason/README.md
2001/ollinger/README.md
2001/schweikh/README.md
2001/schweikh/try.sh
2001/westley/Makefile
2001/westley/README.md
2001/westley/try.sh
bugs.md
thanks-for-fixes.md

The Makefile now always regenerates the .sort.c and the .punch.c 
versions if westley.c has been modified.
The try.sh script had a typo (not in a command that ends up being run
but rather showing what would be run).
Add bugs and (mis)features section with two statuses.
It is not clear to me just yet if this completes the review of the entry 
but it might.

Fixes to 2001/westley

---

2001/ctk/Makefile
2001/ctk/README.md
2001/ctk/ctk.c
2001/jason/README.md
2001/ollinger/README.md
2001/schweikh/README.md
2001/schweikh/try.sh
thanks-for-fixes.md

Fixed bug where if one does not hit 'q' it would mess up the terminal on
exit. I think (but I'm also distracted) this happened if you crashed as
well. Now if you kill the game (ctrl-c for instance), you crash or you 
quit with 'q' it should still be a sane terminal.
The alt code adds (it does not replace) vi(m) movement keys: h for left,
l for right and k for straight.

Bug fix 2001/ctk and alt code added

---

2001/anonymous/Makefile
2001/anonymous/README.md
2001/ctk/Makefile
2001/ctk/README.md
2001/ctk/ctk.c
2001/dgbeards/README.md
2001/dgbeards/dgbeards.alt.c
2001/jason/README.md
2001/ollinger/README.md
2001/schweikh/README.md
2001/schweikh/try.sh
thanks-for-fixes.md

The flaw I suggested that there was in the alt code that the author did
not note is actually from a typo in the code on my part.

Fix 2001/dgbeards alt code + format/typo check

---

2001/anonymous/Makefile
2001/anonymous/README.md
2001/ctk/Makefile
2001/ctk/README.md
2001/ctk/ctk.c
2001/dgbeards/README.md
2001/dgbeards/dgbeards.alt.c
2001/jason/README.md
2001/ollinger/README.md
2001/schweikh/README.md
2001/schweikh/try.sh
bugs.md
thanks-for-fixes.md

There was some inconsistency as far as whether or not the problem was a
bug or feature, where not enough args would result in a crash. At one
point it seems it was changed to a bug, not a feature, and it is then
that I must have fixed it. However the bugs.md file incorrectly labelled
another entry as ollinger and the README.md for ollinger referred to
something that did not exist or rather it existed but it was for another
entry.
A minor fix in bugs.md has been done as well: change the status name of
using fgets() to not refer to getline(3); rather the description does 
that. This is because no other place has that function in the status 
line. Doing this is how I found the problem this commit fixes as another
entry should have that status.

Fix 2001/ollinger bug status in bugs.md

---

2001/coupard/Makefile
2001/coupard/README.md
2001/coupard/coupard.c
thanks-for-fixes.md

main() now returns a value rather than just 'return' to be more portable.
I believe this completes the review of this entry.

Minor fixes and formatting to 2001/coupard

---

2001/williams/Makefile
2001/williams/README.md
2001/williams/williams.c

There are two bugs that are known. First is that at the end of the game (when you lose) it appears to in (an infinite?) while loop call usleep(3). However you can still shoot your missiles at this point. The other bug is that it will eventually crash. It's easy to make it crash if you wait until everything is destroyed (that is when it starts printing the lines in a loop, sleeping over and over again) and only then start shooting your missiles, over and over again until it crashes. It appears that it's the 'Window *d' getting corrupted but I'm not sure why. These details have been added to bugs.md.
The README.md file has been format fixed.
There was a minor change to williams.c as well though this was only rolling back a change that should not have been committed yesterday.

Add bug status to 2001/williams

---

1985/sicherman/Makefile
1985/sicherman/sicherman.c
thanks-for-fixes.md

... I think :-)
The thanks file gives much more details on how this works and as I am very tired and want to get this in so I can do other things I will not duplicate it here. It might become clear in that file why I believe it cannot be made any more like the original without breaking it though I left some questions for the reader to answer for themselves.
The Makefile also had a fix: the 'alt' rule was in error so that running 'make alt' in the directory would compile it to 'alt', not 'sicherman.alt'.

Make 1985/sicherman close to original as possible

---

1985/sicherman/Makefile
1985/sicherman/sicherman.c
1998/schweikh3/.gitignore
1998/schweikh3/Makefile
1998/schweikh3/README.md
1998/schweikh3/schweikh3.alt.c
thanks-for-fixes.md

This is for the rare case that the author described where the size needs
to be increased: it can now be done when compiling without having to 
update the code. The original code is the recommended one try first; if
any of '-D' macros are not defined it will use the default, including 
the size one. This so to make it easier to redefine just one, rather 
than having to specify all the -D options.

Add 1998/schweikh3 alt code

---

1992/vern/Makefile
1992/vern/README.md
1992/vern/vern.c
bugs.md
thanks-for-fixes.md

If one entered input < 0 || > 077 (octal) the program would enter an infinite loop that flooded the screen, forcing the user to terminate the program.
The problem was that scanf(3) (with "%o %o" specifier string) was in a loop checking for return value of 2 (this was not a problem because scanf(3) does not return until all the specifiers are processed or I suppose some error occurs) and not checking the values. Instead it just checked a function on the numbers. This fix involves using scanf(3) with the specifier "%4s %4s" and then using strtol(3) with base 8 and then checking for < 0 || > 077 (using "%o %o" will not work).
The game now functions as expected without flooding the terminal if invalid input is given. The judges' remarks about the range has been kept in as it's still invalid …

Fix infinite loop in 1992/vern

---

1992/vern/Makefile
1992/vern/README.md
1992/vern/vern.c
2004/vik2/Makefile
bugs.md
thanks-for-fixes.md

It's now possible to see the messages even if warnings flood the screen
(which is quite likely). One might update the CSILENCE but this is 
easier and prevents any problem of compilers not having the respective 
-Wno- option but it doesn't matter anyway as if it was a clean compile 
it would show nothing at all.

Improve 2004/vik2 cat-killing-curiosity rule

---

2004/jdalbec/.gitignore
2004/jdalbec/Makefile
2004/jdalbec/README.md
2004/jdalbec/jdalbec.alt.c
2004/jdalbec/try.alt.sh
2004/jdalbec/try.sh
bugs.md
thanks-for-fixes.md

The alt code allows one to set how many numbers to print on a line before adding a line break. This is done because the more numbers that there are the harder it is to see where it 'belongs'. Defaults to 11 (protons, salt) but the macro name is Ag, silver (because silver is my favourite precious metal, it wasn't used already and it allowed for some irony in the alt build section).
The try.alt.sh script uses the alt code.
The try.sh script uses the fixed code (fixes I made quite a while back).
The bugs.md has had INAFIAB section added to this entry.
This should complete the review of 2004/jdalbec.

Alt code/try scripts added to 2004/jdalbec

---

2004/gavin/.gitignore
2004/gavin/Makefile
2004/gavin/README.md
2004/gavin/gavin.alt.c
2005/aidan/Makefile
2005/aidan/README.md
2005/aidan/try.alt.sh
2005/aidan/try.sh
2005/giljade/Makefile
2005/giljade/README.md
2005/giljade/test.sh
2005/giljade/try.sh
thanks-for-fixes.md

Based on the remarks for QEMU one has to have the macro K defined as 1 
so in the alt code it does an #undef K and then a #define K 1. The other
macros are defined if not defined (#ifndef .. #endif).
The instructions could be improved upon. As of now it only tells how to
compile it and that use is similar to the main entry except that one 
uses QEMU instead. The file names like kernel, vi etc. are still those 
names with the alt version build. I have no good way to test this out 
but unless I made a typo in the Makefile everything should be good 
assuming that it still works.
This should (if all is good with the Makefile rules) complete 
2004/gavin.

Add alt code to 2004/gavin for QEMU

---

2005/aidan/Makefile
2005/aidan/README.md
2005/aidan/try.alt.sh
2005/aidan/try.sh
thanks-for-fixes.md

The try.sh script is for aidan.c; the try.alt.sh is for aidan.alt.c (which I added some while back based on the author's remarks).
The README.md file has been format and typo fixed.

Add try scripts to 2005/aidan + format/typo checks

---

2005/aidan/Makefile
2005/aidan/README.md
2005/aidan/try.alt.sh
2005/aidan/try.sh
2005/giljade/Makefile
2005/giljade/README.md
2005/giljade/test.sh
2005/giljade/try.sh
thanks-for-fixes.md

The try.sh script lets one experience the entry without having to use
vi(m) .. you know, in case they're afraid of getting stuck :-) (and it
is easier too). The script leaves the file there (rather than piping to
less(1)) so that one can view it in a text editor if they wish.
The file test.sh runs the test suite mode but it filters out the running
of 'make', instead only showing the lines matching '^Line'. When it's
all done it checks if 180 versions (lines) were found (it writes to 
stdout and another file with tee(1)). If it does not find 180 it is an
error and this is reported (with exit 1). If it does find 180 all is
good. The make test rule was added and uses this script.
Format and typo check README.md file.

Many improvements to 2005/giljade presentation

---

2005/anon/Makefile
2005/anon/README.md
2005/anon/anon.alt.c
thanks-for-fixes.md

Previously the alt rule in the Makefile defined NO_STTY which stops the code from using stty(1) at the beginning and at the end. The stty sane resulted in a bus error in macOS and since the sole purpose was to set echo back on I changed it to stty echo (which works). (The NO_STTY macro is still checked, see below.)
Added alt code with vi(m) like movements.
The way to get it to not use stty is to use either make alt-no_stty or no_stty. The former will compile into anon.alt and the latter will compile into anon.
Format and typo fix README.md file.

Bug fix and add alt code to 2005/anon

---

2005/giljade/try.sh

After one exited less(1) the text about leaving the file there for one to look at it with an editor was on the same line as other output.
Also use less -X so that the screen is not cleared. That way one can see the last part of the file that they looked at.

Fix and improve 2005/giljade/try.sh

---

2005/vince/README.md
2005/vince/vince.alt.c
2005/vince/vince.c
faq.md
thanks-for-fixes.md

Refer to thanks file, not the README.md file of the entry when fixing 
entries.
Refer to how-to-help.md, not how-to-bugfix.md as I renamed it a while 
back as the file doesn't really say how to fix bugs (how could it?) but
rather how to help.

Fix invalid file references in FAQ

---

2005/sykes/Makefile
2005/sykes/README.md
2005/sykes/test.sh
2005/sykes/try.sh
2005/timwi/README.md
2005/timwi/try.sh
2005/toledo/README.md
2005/vik/README.md
bugs.md
thanks-for-fixes.md

The try.sh is different from others in that it is a loop showing a menu
with different options to use the emulator. It notes at the start of 
each iteration that one has to hit ctrl-c or whatever they have set 
their interrupt as.
The test.sh is run by make test. The exit status is ignored as it 
returns non-zero.
I am not done with this entry as the bugs.md should probably be updated
to note some things the author noted. This will have to come another 
time.

Add 2005/sykes/try.sh and test.sh + make test rule

---

2020/endoh2/Makefile

This happened when I extracted the spoiler.zip into spoiler/ and forgot to update the Makefile.

Fix 2020/endoh2/Makefile - DATA var out of date

---

2006/sykes2/README.md
2006/sykes2/sykes2.sh
2006/sykes2/try.sh
thanks-for-fixes.md

The README.md did not need anything done other than changing it to refer to try.sh instead of sykes2.sh.

Rename and improve 2006/sykes2/sykes2.sh -> try.sh

---

1984/decot/Makefile
1984/decot/decot.c
thanks-for-fixes.md
tmp/README.md

The #define char can be used as long as main() does not have two args
which it does not need to work. But since some versions have an
additional defect that main() can only have 0, 2 or 3 args (but see
below) it was made so that main() no longer has any args: instead the
'int i' was moved to be inside main() and set to 1 (it cannot be 0).
The version where I noticed that clang whines about the number of args
to main() will whine if it has, say, 4 args, but it will not if it has
1 and it has never whined (as an error) about passing too many args to a
function. Thus on line 29 the call to main() still passes the same
variable to main().
If clang or the ANSI C committee ruin more perfectly fun programs (both
of which seem possible) then the #define char could be renamed say to
shar or else …

Make my fix to 1984/decot more like original

---

thanks-for-fixes.md
tmp/README.md

Moved 'README and thanks' to top and made it '.. and thanks for all the
fish. :-)' instead.. This is because it talked about how the judges 
wish to thank the various people but at the bottom it would serve no 
purpose and yet it felt like it should still be in the file. The heading
or subheading title is an experiment but I think it is probably better 
than 'README and thanks'.

Minor improvements in thanks file

---

1984/decot/Makefile
1984/decot/decot.c
1985/august/Makefile
1985/august/august.c
thanks-for-fixes.md
tmp/README.md

Due to clang defect in number of args allowed in main(). Some versions 
will if you use, say, 4 args, object and report that main() can only 
have 0, 2 or 3 args. That same version does not appear to object to 1 
arg (bug?) but it's entirely possible that this changes so I have 
changed the number of args of main() to 2 even though it's unused just 
out of abundance of caution.
Updated CSILENCE for no implicit int. I have to test the unused 
parameter warning. That might need to be added to, 
-Wno-unused-parameter, but I have to find out which compilers will or 
will not object to it and that can come later on.

Add second arg to main() in 1985/august

---

1984/decot/Makefile
1984/decot/decot.c
1985/august/Makefile
1985/august/august.c
1985/sicherman/Makefile
1985/sicherman/README.md
1985/sicherman/sicherman.alt2.c
thanks-for-fixes.md
tmp/README.md

Since some versions of clang object to the number of args to main() 
(requiring, supposedly, 0, 2 or 3[0] args) and in the case that it is 
enforced to not allow 1 I have added a second alt code that will be 
compiled IF sicherman.c fails to compile (and it'll compile into
sicherman, not sicherman.alt2 or something like that). This required 
another change which also is in sicherman.c.
The macros in the code that were C (which only translated to '/**/') and 
V were changed to lower case letters. Then the 'c' in 'subr()' was 
changed back to upper case. This also feels better since the 'C' (now 
'c') in main() is although used it is not necessary either since it just
is an empty comment. The primary reason for this change is that in the 
new version we obviously want the first arg of …

Second alt version added to 1985/sicherman

---

1991/cdupont/.gitignore
1991/cdupont/Makefile
1991/cdupont/README.md
1991/cdupont/cdupont.alt.c
1991/cdupont/cdupont.alt2.c
1991/cdupont/cdupont.alt3.c
thanks-for-fixes.md

There are three alt versions. One has a comment and an unused goto label removed that are warned against being removed; another has this done and is also beautified (which is also warned against) and the third is one that is just beautified.
This involved changing the 's' macro to be '__FILE__' because otherwise it would read in the original code and not show the problem.

Add alt versions to 1991/cdupont

---

1991/cdupont/.gitignore
1991/cdupont/Makefile
1991/cdupont/README.md
1991/cdupont/cdupont.alt.c
1991/cdupont/cdupont.alt2.c
1991/cdupont/cdupont.alt3.c
1992/kivinen/Makefile
1992/kivinen/kivinen.alt.c
1992/kivinen/kivinen.c
1992/marangon/Makefile
1992/marangon/marangon.c
thanks-for-fixes.md

Due to the fact that void main() will not work in some systems, of 
course.

Make 1992/marangon main() return int, not void

---

1991/cdupont/.gitignore
1991/cdupont/Makefile
1991/cdupont/README.md
1991/cdupont/cdupont.alt.c
1991/cdupont/cdupont.alt2.c
1991/cdupont/cdupont.alt3.c
1992/kivinen/Makefile
1992/kivinen/kivinen.alt.c
1992/kivinen/kivinen.c
1992/marangon/Makefile
1992/marangon/marangon.c
1994/weisberg/Makefile
1994/weisberg/README.md
thanks-for-fixes.md

To make the entry a bit more user friendly and also easier to use with
other tools (in a pipeline - if anyone wanted to for some reason) the
Makefile was modified to print a newline after each number rather than a
space.
I noticed that the Alternate code section had no subsections for 
'Alternate build' or 'Alternate use' and these were added as well. I am
not sure how this happened but I might do a quick pass through over all 
entries once everything else is done just to be sure.

Minor update to 1994/weisberg

---

2011/dlowe/README.md
2011/dlowe/try.sh
thanks-for-fixes.md

The README.md file has been typo/format checked/fixed.
The try.sh script has been updated with some improvements and additional commands.
The bug status was changed to INABIAF as these limitations were documented by the author.
I believe this should complete the review of 2011/dlowe.

Format/typo check and other fixes in 2011/dlowe

---

2005/giljade/test.sh

Instead of grep -C5 it's now grep -C10 in case there's ever a compilation eror.
Make it say 'successfully compiled' rather than just 'compiled'.

Minor improvements to 2005/giljade/test.sh

---

2012/hou/hint.md
2012/hou/try.sh
thanks-for-fixes.md

The hint.md file is necessary as the '#' header in it specifies the title and stylesheet as part of the entry.
The try.sh script is as usual.
Format/typo check README.md file. The hint.md file formatting was not changed due to the regexp engine amongst other reasons. Just obvious spelling errors were updated.

Add try.sh and hint.md to 2012/hou + formatting

---

2012/omoikane/.gitignore
2012/omoikane/Makefile
2012/omoikane/README.md
2012/omoikane/nyaruko.alt.c
2012/omoikane/nyaruko.alt2.c
2012/omoikane/try.alt.sh
2012/omoikane/try.sh
news.html
thanks-for-fixes.md

There are two alt versions which should be useful for (respectively)
those who do not have /dev/urandom and those who use Windows. Both of 
these versions read from argv[0] instead of /dev/urandom but the second
one sets binary mode on stdin and stdout. This is to be consistent with
the fact that other entries also have this as an alt version.
The try.sh and try.alt.sh scripts work on the entry and the first
version of the alt code, the one that is not Windows specific. The
scripts consist of commands from both the to use section of the 
README.md (which is still there) and the try section (which now refers
to try.sh).
Format/typo checks in README.md file.

Add alt code to 2012/omoikane + try + formatting

---

2012/endoh1/.gitignore
2012/endoh1/Makefile
2012/endoh1/README.md
2012/endoh1/endoh1.alt2.c
2012/endoh1/endoh1_color.alt.c
thanks-for-fixes.md

The alt versions let one control how long to sleep between writes as in modern systems it goes pretty fast. There are two, one for the colour version that was added by Yusuke at the request of the judges and one for the original. But the one for the original is called endoh1.alt2.c as Yusuke provided endoh1.alt.c as a deobfuscated version.
The new alt versions let one only redefine certain macros should they choose but they can define them all or not define them all because of the #ifndef..#endif guards. These macros include the sleep time (S) as well as the others that Yusuke suggested one might want to change.

Add alt versions to 2012/endoh1 + formatting

---

2012/endoh1/Makefile
2012/endoh1/README.md
2012/endoh1/endoh1.alt.c
2012/endoh1/endoh1.alt2.c
2012/endoh1/endoh1_color.alt.c
thanks-for-fixes.md

The alt2 is the deobfuscated version; the alt one is the one with the ability to slow down/speed up the fluid and control the gravity factor, the pressure factor and/or the viscosity factor.
The alt version no longer imposes a lower limit on the factors because doing so prevents the ability to define them to 'I' which the author noted is a functional difference.

Swap alt and alt2 of 2012/endoh1

---

2013/cable3/README.md
bugs.md
thanks-for-fixes.md

As the bug status was a missing file and it was actually hd.img and as 
that was added to the repo the entry can be removed from the bugs.md 
file.
I also added some important points for the entry about quitting 
(elaborating) and also how to input certain keys like alt/ctrl 
combinations (amongst others) that the author had later on in the 
README.md file. The former might especially be important if someone did
it at the console and was not aware of how to open another console but
even so it can be annoying having to close a tab just to stop a program.
Now I can say that 2013/cable3 is almost certainly complete (review 
wise?).

Remove 2013/cable3 from bugs.md

---

2014/wiedijk/README.md
2014/wiedijk/try.sh
thanks-for-fixes.md

The try.sh allows one to override the default indent(1) and sed(1) tools
and also verifies that they are executable. This means one can use, for
example, bcpp, instead of indent, or if one wants to specify a different
path to sed(1) they can. The README.md file explains this more.
README.md file format/typo checked.
This should complete the review of this entry.

Add 2014/wiedijk/try.sh + formatting/typo checks

---

2000/primenum/.gitignore
2000/primenum/try.sh
2000/rince/try.sh
2013/dlowe/README.md

Although it appears to accept non digits I did not have time to test it
more and I see now it has no real purpose, showing the same thing, so I
have removed that and noted that it expects numbers.

Fix synopsis in 2013/dlowe/README.md file

---

2000/primenum/.gitignore
2000/primenum/try.sh
2000/rince/try.sh
2013/dlowe/README.md
2014/birken/Makefile
2014/deak/Makefile
2014/endoh1/Makefile
2014/endoh2/Makefile
2014/maffiodo1/Makefile
2014/maffiodo2/Makefile
2014/morgan/Makefile
2014/sinon/Makefile
2014/sinon/README.md
2014/sinon/prog.c
2014/sinon/try.sh
2014/skeggs/Makefile
2014/vik/Makefile
2014/wiedijk/Makefile
thanks-for-fixes.md

The mode where the game would play by itself did not work because the 
code had 'sinon.c' in it but this does not exist. Now the code refers to
'prog.c'.
Add try.sh script that is an improvement over the previous try command 
(or commands in a sequence) in that it loops, asking if you wish to try
again in case of a jam (or any other reason).
This should complete the review of 2014/sinon.

Fix 2014/sinon + add try.sh + formatting

---

2000/primenum/.gitignore
2000/primenum/try.sh
2000/rince/try.sh
2013/dlowe/README.md
2014/birken/Makefile
2014/deak/Makefile
2014/endoh1/Makefile
2014/endoh2/Makefile
2014/maffiodo1/Makefile
2014/maffiodo2/Makefile
2014/morgan/Makefile
2014/sinon/Makefile
2014/sinon/README.md
2014/sinon/prog.c
2014/sinon/try.sh
2014/skeggs/Makefile
2014/skeggs/README.md
2014/vik/Makefile
2014/wiedijk/Makefile
thanks-for-fixes.md

This includes updating the run of iocccsize -i on the README.md file as
the size has changed (it also referred to REMARKS.md but I changed it to
README.md). This is to make things consistent.

Format/typo check 2014/skeggs

---

2014/birken/.gitignore
2014/birken/Makefile
2014/birken/README.md
2014/birken/prog.alt.c
2014/deak/README.md
2014/deak/prog.alt.c
2014/endoh1/README.md
2014/endoh1/rake.sh
2014/endoh1/spoilers.md
2014/endoh1/try.sh
2014/sinon/.gitignore
inc/README.md
thanks-for-fixes.md

The rake.sh script had a typo where '1>&2' was just '1>2'.
The README.md and spoilers.md files were format and typo checked.
I believe this should complete 2014/endoh1.

Add 2014/endoh1/try.sh, fix rake.sh, format/typos

---

2014/birken/.gitignore
2014/birken/Makefile
2014/birken/README.md
2014/birken/prog.alt.c
2014/sinon/.gitignore
inc/README.md
thanks-for-fixes.md

The alt code lets one redefine the port and also redefine the timing
constants. The reason for the port is in case of firewall (though on
localhost that shouldn't be a problem but it does appear to be that it
might bind to other addresses too). The timing one the author specifies
some uses for changing it. Uses #ifndef..#endif.

Add alt code to 2014/birken + format/typo checks

---

2014/birken/.gitignore
2014/birken/Makefile
2014/birken/README.md
2014/birken/prog.alt.c
2014/deak/README.md
2014/deak/prog.alt.c
2014/sinon/.gitignore
inc/README.md
thanks-for-fixes.md

The alt code now lets one redefine the coordinates (which was
deliberately not obfuscated by the author for this purpose). A casual
look at the code would make one think it's not an alt code but it's a
fixed version that the author provided if a certain statement was not
true (see README.md file) so the only thing that is different is that
there is the #ifndef..#define..#endif of coordinates and the fix to
compile (missing a return value, possibly also fixed in the README.md 
file, and an added #include <stdio.h> for putchar(3)).

Update 2014/deak alt code + format/typo checks

---

2014/birken/.gitignore
2014/birken/Makefile
2014/birken/README.md
2014/birken/prog.alt.c
2014/deak/README.md
2014/deak/prog.alt.c
2014/endoh1/README.md
2014/endoh1/rake.sh
2014/endoh1/spoilers.md
2014/endoh1/try.sh
2014/endoh2/.gitignore
2014/endoh2/README.md
2014/endoh2/try.sh
2014/maffiodo1/README.md
2014/maffiodo1/giana.sh
2014/maffiodo1/mario.sh
2014/maffiodo2/Makefile
2014/maffiodo2/README.md
2014/maffiodo2/prog.alt.c
2014/maffiodo2/try.sh
2014/morgan/README.md
2014/morgan/try.sh
2014/sinon/.gitignore
2014/vik/README.md
bugs.md
inc/README.md
thanks-for-fixes.md

The alt code is from the author.
The try.sh script has the example command provided by the judges as well
as some by the author. One was removed because of a syntax error 
(removed from the author's examples).
The only thing that has to be done is to update the references to 
twitter to note how the IOCCC no longer endorses twitter or whatever the
rocket destroyer wishes to call it (though certainly it won't be worded
like that :-) ).

Add alt code to 2014/maffiodo2 + try.sh script

---

2014/birken/.gitignore
2014/birken/Makefile
2014/birken/README.md
2014/birken/prog.alt.c
2014/deak/README.md
2014/deak/prog.alt.c
2014/endoh1/README.md
2014/endoh1/rake.sh
2014/endoh1/spoilers.md
2014/endoh1/try.sh
2014/endoh2/.gitignore
2014/endoh2/README.md
2014/endoh2/try.sh
2014/maffiodo1/README.md
2014/maffiodo1/giana.sh
2014/maffiodo1/mario.sh
2014/morgan/README.md
2014/morgan/try.sh
2014/sinon/.gitignore
2014/vik/README.md
bugs.md
inc/README.md
thanks-for-fixes.md

The mario.sh script runs Super Mario Brothers and the giana.sh script 
runs the Great Giana Sisters but each allows the user to specify the 
width and height of the game.
The bugs.md was updated with features, not bugs to fix.

Format/typo check 2014/maffiodo1, add scripts

---

1994/dodsond2/README.md
2000/dlowe/README.md
2000/dlowe/try.sh
2001/ctk/ctk.alt.c
2011/akari/.gitignore
bugs.md
thanks-for-fixes.md

The try.sh script also has some fixes in the author's remarks (as in
they were fixed in the author's remarks) - it had "s in the command line
rather than single quotes but some of these command lines had * which
would expand to the files in the directory, causing errors.
The bugs.md has been updated with the issue of not printing 'poot' when
it should. I did some debugging and removed some (obviously nonsense) 
ideas I had put in before (without thinking, being too tired, whatever
other reason or reasons). The real issue is a very strange one to be 
sure.
I am pretty sure the reason it does not work with macOS (this was 
already noted but worth repeating) is the version of perl as the author
noted this as an issue. We still have it as a known bug (some platforms)
but I don't think it's …

Add 2000/dlowe/try.sh, update bugs.md, format

---

1994/dodsond2/README.md
2000/dlowe/README.md
2000/dlowe/try.sh
2001/ctk/ctk.alt.c
2011/akari/.gitignore
2015/mills1/Makefile
2015/mills1/README.md
2015/mills1/try.sh
2015/muth/README.md
2015/muth/try.sh
2015/yang/README.md
2015/yang/try.sh
bugs.md
thanks-for-fixes.md

The try.sh script runs the make command in the judges' remarks to make
it easier.
A warning is that if you have good eye-hand coordination and you're good
at games and you have too much time you might end up falling asleep
playing it as you'll probably never die. I only died because I was
trying to mark a reminder complete on the other side of the screen at
the same time as playing .. and I almost survived that .. and 'Cody's
also blind' as the joke goes in the family. That's probably why I ended
up dying. At that point I already had over 90 points. 
Still the purpose is to make it easier to play if the default settings 
are too frustrating. I contemplated playing with other settings but I
decided not to. An example where it might be improved is to let the user
pass in the environmental …

Add 2015/mills1/try.sh + format/typo checks

---

2015/hou/README.md
2015/hou/rfc1321.txt
2015/howe/spoiler/err.h
2015/muth/machine_beaver_4_2.h
2015/muth/machine_champ_2_4.h
2015/muth/machine_chaos_5_2.h
2015/muth/machine_cmplx_5_2.h
2015/muth/machine_count_5_2.h
2015/muth/machine_great_3_2.h
2015/muth/machine_ru_2_4.h
thanks-for-fixes.md

With the exception of those on the IOCCC website (maybe one other place
but don't think so) the links were dead. These have been replaced for
historical purposes with a captured copy on the Internet Wayback
Machine.
This entry should now be entirely complete.

Fix dead links in 2015/muth/machine_*.h

---

inc/md2html.cfg
inc/sidenav.default.html
tmp/template-header.html
tmp/test.html
tmp/things-todo.md

As the thanks-for-fixes.md file was renamed (at my suggestion) thanks-for-help.md I have made sure that the file referred to in the repo is thanks-for-help and that the text regarding it also refers to help and not fixes ('Thanks for the fixes' -> 'Thanks for the help').

Fix references to thanks-for-fixes -> help

---

2006/sloane/README.md

There were some minor problems with how the original code sections were set up (also some duplicate text) that I missed.

Fixes in 2006/sloane/README.md file

---

thanks-for-help.md

Unfortunately the renaming of the thanks-for-fixes.md to thanks-for-help.md along with other changes with the it caused massive merge conflicts. The file was out of order, there were a lot of >>> lines etc.
I had to checkout the old file and update it for the changes I made this morning. Unfortunately this does mean that the <a ..> anchors are no longer there, relying on markdown to do that instead. That will have to be fixed but I also noticed an error in that too. I am not sure if that's because of the merge conflict or not though.
I will have to check that I got everything in order but I think I did as I also added what I had added to it today.

Fix major merge conflicts in thanks file

---

2020/ferguson2/.gitignore
2020/ferguson2/Makefile
2020/ferguson2/README.md
2020/ferguson2/prog.alt.c
thanks-for-help.md

This alt code prints out the text one character at a time to make it
easier to read and more generally so it's not dumped out at once. This
also makes it a bit more like the original thing (at least as I recall
it :-) ).
The default sleep time is 400000 microseconds but one can change it
like:
make clobber SLEEP=0 alt
which would disable the delay, making it like the original.
If it's < 0 then it's set to the default.
I did not yet add a try.sh script. That'll likely come later when 
working on 2020. I only did this now as I thought of this idea and 
didn't want to forget it.

Add alt code to 2020/ferguson2

---

2012/endoh1/Makefile
2012/endoh1/README.md
2012/endoh1/try.alt.sh
2013/birken/Makefile
2013/birken/README.md
2014/birken/Makefile
2014/birken/README.md
2018/poikola/README.md
2018/poikola/try.sh
thanks-for-help.md

Now one can use variables SLEEP, TIMER, GRAVITY, PRESSURE and VISCOSITY,
rather than single letter variables. This is like other commits where
instead of having to redefine CDEFINE one can do something like
make clobber SLEEP=50 GRAVITY=I TIMER=15 alt
Notice that some can be set to I rather than a number. See the author's
remarks for details.
The try.alt.sh script was updated for this improvement.

Improve how to redefine macros in 2012/endoh1 alt

---

2018/endoh2/Makefile
2018/endoh2/README.md
2018/endoh2/python.sh
2018/endoh2/python3.sh
2018/endoh2/run.sh
2018/endoh2/try.sh
thanks-for-help.md

The run.sh script was fixed to work. It did not work because it had a command that does not even exist ('tempfile') and even after that was resolved there was another problem to be resolved.
The Makefile rule make python runs the python.sh script but it sets a trap so one can exit that script but not exit everything (see below). The python3.sh script is what python.sh is but for the make rule python3 and it works in the same way. The try.sh script runs all of these scripts as well as the commands suggested by the judges.
The README.md file has been format/typo checked. For the link (twice referenced) that has flashing lights (and quite a few at that) I put a warning in parentheses for those who are (like me) sensitive to it (more important for some people with epilepsy, depending on how …

Add helper scripts to 2018/endoh2 + formatting

---

2018/endoh1/README.md
2018/endoh1/try.sh
2018/endoh2/Makefile
2018/endoh2/README.md
2018/endoh2/python.sh
2018/endoh2/python3.sh
2018/endoh2/run.sh
2018/endoh2/try.sh
thanks-for-help.md

The try.sh script shows each input file first so that one can see how it
turns out as a GIF file. The input files include those not suggested by
the judges including the source code itself (the author suggested it has
a message too).

Add 2018/endoh1/try.sh + format/typo checks

---

2018/bellard/prog.alt.c
2018/bellard/prog.c
thanks-for-help.md

Out of an abundance of caution with clang defects / the ANSI C Committee I have added a second arg to main() in case they decide to enforce the rule that main() has 0, 2, 3 args.

Fix number of args in main() in 2018/bellard

---

1984/mullender/.gitignore
1984/mullender/Makefile
1984/mullender/README.md
1984/mullender/mullender.alt.c
1984/mullender/mullender.alt2.c
2018/bellard/prog.alt.c
2018/bellard/prog.c
thanks-for-help.md

Using 2018/mills (an amazing entry) with trial and error I was able to 
determine the approximate speed that the :-) moved across the screen and
now the alt code moves at almost exactly (I believe, at least) that 
speed.
The mullender.alt2.c was deleted; instead that became mullender.alt.c. 
This is because (I believe but have not confirmed) that the original did
not exit after it timed out and there's no need to have two alt versions
when they're so similar. One is good enough and the obvious choice is 
the one that can keep going on.
.gitignore updated.

Improve 1984/mullender alt code

---

1984/mullender/.gitignore
1984/mullender/Makefile
1984/mullender/README.md
1984/mullender/mullender.alt.c
1984/mullender/mullender.alt2.c
2018/bellard/prog.alt.c
2018/bellard/prog.c
thanks-for-help.md

The fixes made were accidentally put in 2019 instead of 2018.

Fix year in thanks file for poikola

---

faq.md

This update was supposed to be committed in
0cbd1db76445674bcc1ace9ed0b468cc2dbd5d78 which was for 2018/algmyr but it was accidentally left out.

Update FAQ about entries requiring sound libraries

---

2019/diels-grabsch2/try.sh
2019/dogon/.gitignore
2019/dogon/Makefile
2019/dogon/README.md
2019/dogon/apholife.c
2019/dogon/try.sh
bugs.md
faq.md
thanks-for-help.md

Updated Makefile so one can easily change the 'Z' macro by doing:
make clobber MEMORY=... all
This is not usually useful but there are occasions where it is. As the 
README.md points out this value must be a power of two!
The try.sh script runs the program on a number of the mc files, first
showing the input keys as a reminder (it also reminds one to keep in
mind the focus of windows).
The bugs.md is updated to note that it uses gets(3).
Format/typo check README.md file. 
I changed the number of years ago that microorganisms appeared on Earth 
as the number was off: there are those wondrous hydrothermal vents that
spewed mineral rich waters. Fun fact on the history of the Earth: did 
you know that as of 2013 the number of years since the dinosaurs were
wiped out is not 65m years but …

Add 2019/dogon/try.sh, update bugs.md, README.md

---

1988/spinellis/.gitignore
1988/spinellis/Makefile
1988/spinellis/README.md
1988/spinellis/input.txt
1988/spinellis/spinellis.alt.c
1988/spinellis/try.alt.sh
1988/spinellis/try.sh
2019/duble/Makefile
2019/duble/README.md
2019/duble/fullscreen.sh
2019/endoh/.gitignore
2019/endoh/Makefile
2019/endoh/README.md
2019/endoh/ascii.c
2019/endoh/try.sh
bugs.md
thanks-for-help.md

The helper program ascii.c converts args passed to it to char values (if
isascii() returns non-zero) which with try.sh allows one to reconstruct
the code with the backtrace rather than having to memorise ascii(7) (and
even if they did it would be hard to put it together). One should of 
course use xargs(1) and try.sh does.
The try.sh script checks that gdb is installed first, telling the user
to install it if they don't have it. The README.md file notes that for
macOS It's not a simple matter of just installing gdb - there are 
additional steps.

Add 2019/endoh/try.sh, helper program + formatting

---

1988/spinellis/.gitignore
1988/spinellis/Makefile
1988/spinellis/README.md
1988/spinellis/input.txt
1988/spinellis/spinellis.alt.c
1988/spinellis/try.alt.sh
1988/spinellis/try.sh

There is no need to compile to 'runme': the way I designed the alt code is so that it can be compiled and used exactly like the original entry. Since the original entry need not compile to another file neither does the alt version. It just compiles to spinellis.alt instead. (Perhaps both should compile to something else though?)
The instructions of how to build/how to use in the README.md file have been fixed and improved (it referred to the old way). The alt code subsections have been added as well.
I also added to spinellis.alt.c #include <stdlib.h> as it's not a one-liner anyway and this way system(3) is available without worrying about warnings. The -Wno-everything still remains there in the system(3) call in case there is a problem with the code that is typed in (though that's not …

Improve instructions/alt code for 1988/spinellis

---

1988/spinellis/.gitignore
1988/spinellis/Makefile
1988/spinellis/README.md
1988/spinellis/input.txt
1988/spinellis/spinellis.alt.c
1988/spinellis/try.alt.sh
1988/spinellis/try.sh
2019/duble/Makefile
2019/duble/README.md
2019/duble/fullscreen.sh
bugs.md
thanks-for-help.md

The Makefile now uses the script fullscreen.sh which should also be
slightly more portable in that it doesn't rely on both stty(1) and
sed(1). Instead it relies on tput(1). Like the Makefile did for stty(1),
the script checks for tput(1). But rather than suggesting that the user
manually update the Makefile (without instructions) it now gives a
command that one can use to do the equivalent. This is assuming that the
environmental variables LINES and COLUMNS exist. Unfortunately these
variables are not available to scripts so it can't be done
automatically. This script also (if tput(1) cannot be found) shows a
more general way of how to change the size of the editor (the README.md
also does this). One can do something like
make clobber LINES=20 COLUMNS=20 all
to get a 20 x 20 editor.
The …

Improve make fullscreen in 2019/duble + formatting

---

2019/endoh/Makefile
2019/endoh/README.md

Previously only -g was after ${CFLAGS} but it needs to have -O0 in case someone decides to run something like
make clobber OPT= all
Use of OPT+= in the Makefile will not fix that problem. Thus if someone does NOT mess with OPT or any other variables that are added to CFLAGS it will look like:
-O0 -g -O0 -g prog.c -o prog
Previously it was just '-g' and no '-O0' but if someone were to do instead
make clobber OPT=-O3 all
it would have messed that up.

Force use of -O0 -g in 2019/endoh

---

1986/marshall/Makefile
1986/marshall/README.md
1987/lievaart/Makefile
1987/lievaart/lievaart.c
1987/lievaart/lievaart2.c
2019/endoh/Makefile
2019/endoh/README.md

The optimiser was left disabled by accident.
Check for !isdigit(*A) before using atoi(3) on A. This was part of the
bug fixes I made (infinite loop flooding the user with invalid input
which is frequent if one does not know how to play or if one makes a
typo). This is in both versions, the one with the board and the entry 
itself (the board being too big to fit in the contest size limits of the
time).

Fixes in 1987/lievaart

---

1986/marshall/Makefile
1986/marshall/README.md
1987/lievaart/Makefile
1987/lievaart/lievaart.c
1987/lievaart/lievaart2.c
1989/ovdluhe/Makefile
1989/ovdluhe/README.md
1989/ovdluhe/try.sh
2019/endoh/Makefile
2019/endoh/README.md
thanks-for-help.md

The try.sh script runs the program on the source file, the README.md and
the Makefile in a loop that runs four times. It has one loop so that
there is a better chance that it won't show the same output on the same
file more than once though it's certainly possible that it will.
The optimiser had been left disabled by accident and this has been 
restored.

Add 1989/ovdluhe/try.sh and fix Makefile

---

1986/marshall/Makefile
1986/marshall/README.md
1987/lievaart/Makefile
1987/lievaart/lievaart.c
1987/lievaart/lievaart2.c
1989/ovdluhe/Makefile
1989/ovdluhe/README.md
1989/ovdluhe/try.sh
1990/jaw/Makefile
1990/jaw/try.sh
2019/endoh/Makefile
2019/endoh/README.md
bugs.md
thanks-for-help.md

The optimiser was left disabled by accident.
The try.sh now adds another file in the archive.
Add entry to bugs.md. There are two issues, or at least one. One issue
might not be an issue but it appears to be. The one that appears to be 
was supposed to be added to the bugs.md file ages ago but was missed by
accident.

Fix 1990/jaw/Makefile, improve try.sh + bugs.md

---

1986/marshall/Makefile
1986/marshall/README.md
1987/lievaart/Makefile
1987/lievaart/lievaart.c
1987/lievaart/lievaart2.c
1989/ovdluhe/Makefile
1989/ovdluhe/README.md
1989/ovdluhe/try.sh
1990/jaw/Makefile
1990/jaw/try.sh
2000/tomx/try.sh
2019/endoh/Makefile
2019/endoh/README.md
bugs.md
thanks-for-help.md

After doing make all || exit 1 it checked for the existence of tomx and
it being executable but that should not be necessary after compilation.

Remove redundancy in 2000/tomx/try.sh

---

1986/marshall/Makefile
1986/marshall/README.md
1987/lievaart/Makefile
1987/lievaart/lievaart.c
1987/lievaart/lievaart2.c
1989/ovdluhe/Makefile
1989/ovdluhe/README.md
1989/ovdluhe/try.sh
1990/jaw/Makefile
1990/jaw/try.sh
1992/gson/Makefile
1992/gson/README.md
1992/gson/try.sh
2000/tomx/try.sh
2019/endoh/Makefile
2019/endoh/README.md
bugs.md
thanks-for-help.md

The optimiser must be disabled due to it otherwise crashing in macOS in some invocations. This has been added to the Makefile, the use of -O0 is forced and a note has been added to the README.md file.
The bugs.md file has been updated on details of how it uses gets() and that text has been removed from the thanks file.
Minor format fixes in README.md.
The script added makes use of the author's script (that I added as mkdict.sh for easier use) after first trying to find a dictionary file.  But one can override the dictionary file with the DICT environmental variable.

Add 1992/gson/try.sh, add note about optimiser

---

1986/marshall/Makefile
1986/marshall/README.md
1987/lievaart/Makefile
1987/lievaart/lievaart.c
1987/lievaart/lievaart2.c
1989/ovdluhe/Makefile
1989/ovdluhe/README.md
1989/ovdluhe/try.sh
1990/jaw/Makefile
1990/jaw/try.sh
1992/gson/Makefile
1992/gson/README.md
1992/gson/try.sh
2000/tomx/try.sh
2001/anonymous/Makefile
2019/endoh/Makefile
2019/endoh/README.md
bugs.md
thanks-for-help.md

Don't exit if it can't find a 'normal' dictionary file, skipping the 
creation of one from mkdict.sh. Just use the one generated from 
mkdict.sh if no other file can be opened (which most likely won't happen
but it can happen as not all systems have /usr/share/dict/words and the
others are unlikely in modern systems).

Improve 1992/gson/try.sh

---

1986/marshall/Makefile
1986/marshall/README.md
1987/lievaart/Makefile
1987/lievaart/lievaart.c
1987/lievaart/lievaart2.c
1989/ovdluhe/Makefile
1989/ovdluhe/README.md
1989/ovdluhe/try.sh
1990/jaw/Makefile
1990/jaw/try.sh
1992/gson/Makefile
1992/gson/README.md
1992/gson/try.sh
2000/tomx/try.sh
2001/anonymous/Makefile
2001/williams/Makefile
2019/endoh/Makefile
2019/endoh/README.md
bugs.md
thanks-for-help.md

The bugs.md was updated to remind people when debugging crashes that it
would be wise to have -O0 and -g (or if they can -ggdb3). That should be
noted in general for debugging but it's especially useful for crashes 
and I'm trying to get this part done so I can resume 2019.

Re-enable optimiser in 2001/williams

---

2019/giles/README.md
2019/karns/Makefile
2019/karns/README.md
2019/karns/try.sh
bugs.md

The try.sh script now prompts for input rather than just sleep for 2 
seconds.
Added issues reported by the author to bugs.md.
Force disable optimiser as the program doesn't work in some cases with 
it enabled. If I recall correctly it crashed in some cases, something 
the author noted happens sometimes (it is unknown if it is because they
had it enabled or if it was something else but I have not experienced a
crash since then).

Improve 2019/karns/try.sh, force -O0

---

2018/poikola/Makefile
2019/poikola/.gitignore
2019/poikola/Makefile
2019/poikola/README.md
2019/poikola/prog.alt.c
2019/poikola/try.alt.sh
2019/poikola/try.sh
bugs.md
thanks-for-help.md
var.mk

The alt code is so one can more easily filter the long output: it prints
a newline after each number is printed. The try.alt.sh script uses this.
Force -O0: the author stated that with clang they got correct output for
[0123s] but with GCC 6 they only got that with level 0. Since 0 works
with clang and since the author stated that the compilers used were
picky I changed it to level 0. Similarly and for the same reason I
changed the C standard to gnu11 from gnu17.
Updated bugs.md: noted that the max file size is 1GB.
I would like to give two quotes from the person this entry was dedicated
to:
'When you are about to jump, you are all alone and have to make your own
decisions. Up there, it's all "up yours".'
and
'I will move to Copenhagen and apply for …

Add 2019/poikola alt code, try, try.alt, others

---

2018/poikola/Makefile
2019/poikola/Makefile
thanks-for-help.md
var.mk

This is not strictly necessary any more than some of the others but two entries use this tool (at least since I added them back - they were missing) and it seems better to have it this way.

Add PDFLATEX var to var.mk

---

2020/burton/Makefile
2020/burton/README.md
2020/burton/try.sh
thanks-for-help.md

The make test now uses option -s to show that the output is the same (as it should be), for better demonstration.

Add 2020/burton/try.sh, improve make test

---

2004/sds/README.md

Let the bugs.md file speak for the feature itself rather than saying in the README.md that the program is is expected to crash if the generated code cannot open a file or there's some invalid command line.

Minor update to 2004/sds/README.md

---

2020/giles/.gitignore
2020/giles/README.md
2020/giles/try.sh
2020/kurdyukov1/README.md
2020/kurdyukov1/try.sh
bugs.md
thanks-for-help.md

The try.sh script tries to find md5sum and if it does not succeed it 
tries for openssl. If it is openssl it uses the subcommand md5; 
otherwise it just uses md5sum. Whatever the case if either is found it 
writes the checksum of prog.c to md5.txt and then it uses prog to write
the checksum to prog.md5.txt. Then it uses diff -s on the two. If 
neither tool is found it just skips that check.

Add 2020/kurdyukov1/try.sh + format/typo checks

---

2020/giles/.gitignore
2020/giles/README.md
2020/giles/try.sh
bugs.md
thanks-for-help.md

The try.sh script does a number of things. First it checks if either
play(1) or aplay(1) are installed. If neither are installed it warns the
user and tells them they will have to play the WAV files manually (it'll
also refer them to the FAQ about SoX which is where play(1) comes from).
If either are installed it'll use that program (in order given above).
After setting that up it converts pi.wav to the digits and then plays
pi.wav (if possible). Then it does the same with jenny (see README.md
for details). Finally it does it for 10666-28 (the closest that
resembles IOCCC-28). It also plays one (if possible, obviously) from
stdin (written from the program).
Updated bugs.md with a limitation the author noted.
Format/typo checked README.md file.

Add 2020/giles/try.sh, update bugs.md, formatting

---

1986/stein/stein.orig.c
thanks-for-help.md

The entry won best one liner but (in 1986 they could be longer) but to make mail and news happy it was split to three lines. As it's not distributed in news or mail now it can be one line. This was only updated in stein.orig.c (for now?).

Restore original entry of 1986/stein

---

1992/kivinen/README.md
tmp/things-todo.md

In alt code where a call to usleep(3) is made to allow for configuring 
speed originally I used the macro 'Z'. In one case 'Z' was already taken
so I changed it to 'S' for that entry. I had the thought it might be 
nice to make it always the same. This however is not possible as more 
entries already have 'S' used. Also it's not important since I changed 
the Makefiles so that one can specify it like 'make clobber SLEEP=500 
alt' or whatever, removing the macro name and having to mess with 
'CDEFINE'.

Remove item about usleep macro name from todo file

---

1986/stein/README.md
1986/stein/stein.sh
thanks-for-help.md
tmp/things-todo.md

This script runs the two commands suggested in order to get it to output cleanly. It is suggested other systems might need another set of characters but one can also get away with just using ./stein so this is also done but at the end of the script to not cause any problems (it doesn't show a newline at output).

Add 1986/stein/stein.sh

---

1986/stein/README.md
1986/stein/stein.sh
thanks-for-help.md
tmp/things-todo.md

I found another place where the wrong file is referred to in an entry:
in particular 1992/buzzard.2 refers to a file in 2020/ferguson2. This 
type of thing will have to be checked for for all entries but this is an
example for future reference (I discovered it as I am working on a task
of 1992/buzzard.2).

Update todo file for future issue

---

bugs.md
thanks-for-help.md

The link and the section itself had different names. The anchor name has
also been renamed to be consistent with what it is now.

Make Makefiles thanks consistent

---

1992/buzzard.2/README.md
1992/buzzard.2/buzzard.2.README.md
1992/buzzard.2/buzzard.2.design.md

The file buzzard.2.README.md was formatted in markdown style.
The file buzzard.2.design was turned into a markdown file, buzzard.2.design.md, and formatted in markdown style. This one was problematic in some ways but I think it's sorted out now. In a few places it was not entirely clear if certain things should be in code blocks or not but they were made to be as they were on the same line as code (after). It doesn't appear to be a comment in the syntax of comments that later appears, however. Another one I was not sure about is if the author meant '{ .. .. }' to be a way to say this is code without the {}s or if that should be part of the code. As these are not clear there might be some mistakes.

Convert to/format markdown in 1992/buzzard.2

---

1987/biggar/README.md
1987/biggar/try.sh
1987/heckbert/README.md
1987/heckbert/try.sh
1987/hines/.gitignore
1987/hines/README.md
1987/hines/goto.c
1987/hines/goto.txt
1987/hines/try.sh
thanks-for-help.md

The files goto.c and goto.txt were also added. The first one is a short
file that is easy to see how many 'goto's there are and the goto.txt 
file has seven 'goto's and one 'Goto' to demonstrate that the program is
case-sensitive.
The .gitignore file was updated with 'goto' though the Makefile does not
have (of course) a 'goto' rule as it's only there to have a C file which 
is easy to see how many 'goto's there are.

Add 1987/hines/try.sh

---

bugs.md
thanks-for-help.md

Should be in thanks file as it updates what I originally fixed (maybe my changing the implicit ints to 'FILE *'s only worked for arm64 for some reason but I don't know): not in bugs.md file.

Fix location of fix details of 2006/toledo2

---

1993/lmfjyh/Makefile
1993/lmfjyh/README.md
thanks-for-help.md

In the case that the original entry fails to compile (if you don't have gcc < 2.3.3 this will happen) the alt code will automatically be built. One can still manually compile the alt code, of course, but this way one can at least use the entry. Note that in the case the alt code is automatically compiled it is compiled to the lmfjyh just like what I did with 1985/sicherman. This was discussed after I did the 1985/sicherman (which will compile anyway after my fixes unless a compiler objects to main() having only one arg).

Fix how 1993/lmfjyh alt code is built

---

1993/lmfjyh/Makefile
1993/lmfjyh/README.md
2001/anonymous/.gitignore
2001/anonymous/Makefile
2001/anonymous/README.md
2001/anonymous/anonymous.c
2001/anonymous/try.sh
thanks-for-help.md

The 64-bit code binaries have been renamed to .alt: anonymous.ten.alt 
and anonymous.bed.alt. This is because it's theoretically possible that
they are not compiled as 64-bit binaries (though how this might be I 
cannot think of at this time) and in any case they are alt builds 
(though they use the same source).
In the case the -m32 fails (whether due to compiler[0] or no access to 
32-bit binary compilation) make alt will be used with warnings that the
entry cannot work with them. The reason these are built as .alt and not
the original is to be clearer whereas in other cases (like 
1985/sicherman) the point was just a backup plan in case a compiler 
objects to it. Here they must be compiled as 32-bit ELF binaries (though
we cannot check if they are ELF - at least not easily and in an …

Fix how 2001/anonymous alt code is built

---

2011/toledo/Makefile

The macros for width and height can't be in CFLAGS as in the original entry it assigns to these variables.

Fix build of 2011/toledo

---

bugs.md

I revised the 1992/adrian.c program and I noticed that function E generates the error messages. I tested the E function to generate all the messages using this code:
E(0, 5, "haha"); generates too_many_states(5): haha
E(1, 5, "hoho"); generates too_many_rules(5): hoho
E(2, 5, "hehe"); generates no_destination(5): hehe
Then I searched for its use on the program and found all the cases E(0) E(1) and E(2), and the comparisons were done correctly with P (value 257) and G (value 17). So I then created two test files to generate the error messages, and the program indeed generates the error messages.
[test_set_adrian_1992.zip](https://github.com/ioccc-src/temp-test-ioccc/files/13880945/test_set_adrian_1992.zip)
With no code to correct, I just removed the bug from the bugs.md file and corrected …

Removed non-bug 1992/adrian.c and corrected links

---

bugs.md

Rather than it not being a bug only the links were wrong (likely due to a yank paste error on my part). Thus the bug noted in 1992/adrian/README.md was added back to bugs.md because it is considered a bug and it is the correct entry as well.

Fix bugs.md wrt 1992/adrian

---

1998/fanf/Makefile
2001/bellard/Makefile
thanks-for-help.md

Some versions of clang need -Wno-int-conversion.

Further fixes to 1998/fanf for clang

---

1989/jar.1/README.md
1989/jar.2/README.md
1989/jar.2/try.sh

Now it will cat each file before running jar.2 on it, prompting for both
cat and the command itself. Spaces are added in between commands to help
let things stand out better.

Improve 1989/jar.2/try.sh

---

1990/baruch/README.md
1990/baruch/try.sh
1991/brnstnd/README.md
1991/brnstnd/try.sh
1991/brnstnd/try.txt
bugs.md
thanks-for-help.md

The try.txt is a file for the rot13 SORTA file. All but one of the 
sorta.* files is used. The only one that is not prints out a verr long 
line of output and would flood the screen. The try section in the 
README.md does suggest one try it just to be complete.

Add 1991/brnstnd/try.sh and try.txt

---

1989/fubar/fubar.c
1989/fubar/fubar.sh
thanks-for-help.md

In some cases if one were to modify the C code (possibly the same with the script) in certain ways the program would fail to work even after changing the code back. Trying to figure out what to put in bugs.md and on a hunch, changing the fubar.sh script (in particular the ex(1) part) remedies the problem (or so it seems from the various tests I have performed including some that caused a problem). In particular:
--- i/1989/fubar/fubar.sh
+++ w/1989/fubar/fubar.sh
@@ -7,13 +7,12 @@ if [[ $# -ne 1 ]]; then
exit 1
fi
rm -f ouroboros.c x1 x
-ex - <<EOF
-r fubar.c
+ex fubar.c <<EOF
8,9j
w ouroboros.c
EOF
chmod +x ouroboros.c
The C code was also changed to make it even more like the original code.

Fix funny problem in 1989/fubar

---

1989/fubar/fubar.c
1989/fubar/fubar.sh
1992/buzzard.2/.gitignore
1992/buzzard.2/Makefile
1992/buzzard.2/README.md
1992/buzzard.2/buzzard.2.alt.c
1992/buzzard.2/help.th
1992/buzzard.2/try.alt.sh
1992/buzzard.2/try.sh
thanks-for-help.md

The bug fix is simply so it can compile. It assumed exit(3) returned a
value, not void. The fixes noted in the remarks (though I did not see
them at a quick glance) of the author are not in the alt version (that's
the purpose of it).
The try.sh and try.alt.sh scripts correspond to the entry and the alt
code.
Added 'first.alt' to Makefile for the try.alt.sh script.

Fix 1992/buzzard.2 alt code, add try scripts

---

1989/fubar/fubar.c
1989/fubar/fubar.sh
1992/adrian/.gitignore
1992/adrian/README.md
1992/adrian/try.sh
1992/albert/README.md
1992/albert/try.alt.sh
1992/albert/try.sh
1992/ant/README.md
1992/ant/ant.test.mk
1992/ant/try.sh
1992/buzzard.2/.gitignore
1992/buzzard.2/Makefile
1992/buzzard.2/README.md
1992/buzzard.2/buzzard.2.alt.c
1992/buzzard.2/help.th
1992/buzzard.2/try.alt.sh
1992/buzzard.2/try.sh
thanks-for-help.md

This script shows the entry itself as well as some of the other tools 
that the entry generates. The adwc / wc one uses a pipeline to show the
output (with leading spaces and filename removed along with squeezing 
spaces) and also writes each to a text file to use diff on, to show how
they have the same output.
Not all the tools are in the script. The adbasename might have a bug 
(in any case it doesn't appear to function exactly like basename(1) in 
that it requires two args, not one) so it is not used and adgrep is not
used either. For the latter one the author's remarks might provide some
clues as to why I did not include it.

Add 1992/adrian/try.sh

---

1994/tvr/README.md
1994/tvr/try.alt.bw.sh
1994/tvr/try.alt.color.sh
1994/tvr/try.bw.sh
1994/tvr/try.color.sh
thanks-for-help.md

There are four scripts:
try.color.sh	# original entry colour mode
try.bw.sh		# original entry black and white mode
try.alt.color.sh	# alt code colour mode
try.alt.bw.sh	# alt code black and white mode
NOTE: This is an experiment using the gh tools to process a pull
request and "modify" it.  In this case the modification is **ONLY**
to add this note to the commit message and the text that follows.
In the future, such as after the **great fork merge**, where
a pull request is made on the [official IOCCC repo](https://github.com/ioccc-src/winner),
the IOCCC judges may have to modify the pull request to include various
other changes.  
For example, if someone were to add a missing file to a winner, the
IOCCC judges would need to update the manifest in the winner
`.winner.json` file.  We would …

Add 1994/tvr try scripts

---

2000/rince/README.md
2012/vik/README.md

We all know what is meant by 'brain$#@$' and there's no need to censor
it especially when it links to the article on wiki that does not censor
it (not that grawlixes are even censoring anything). This means there's
no need to escape the '$' as they are not there now.

Remove grawlixes from 2012/vik/README.md

---

2000/rince/README.md

The bugs.md file is all that's needed; the information is already there in bugs.md and the purpose of having the 'STATUS: ...' lines in the bugs and (mis)features section of the README.md files was to not have that. Still having the reference to DISPLAY being unset being a problem seems like a good idea.

Remove reference to jargon file in 2000/rince

---

2000/rince/README.md
2012/vik/README.md
2018/burton1/README.md

I believe that the previous commit got the ordering wrong. The
significant inspiration for the contest was linked to directly in
markdown rather than a '[...]: ...' style link so reference 3 should
actually be reference 2 (instead of the link to the main IOCCC readme
file). A question of course is what to do about the link
http://ioccc.org/all/README
since all README files have been changed to README.md files. 
Nevertheless right now the ioccc.org site has README, not README.md, so
it would be either a broken link or it would refer to say /all/README.md
(which might be the best way?).

Fix references in 2018/burton1/README.md

---

2000/rince/README.md
2012/vik/README.md
2018/burton1/README.md
2020/carlini/README.md
2020/carlini/index.html

I believe it was a mistake to add the \ before the $ as it was in a code 
block. In one case a pair of '`'s was missing and those were added there
so that both are now code blocks. If it is not an error to have the '\'
before the '$' then the code block added should still be there but I 
believe it was a mistake anyway.

Remove \ from $ in code blocks in 2020/carlini

---

1995/heathbar/README.md
1995/heathbar/try.sh
1995/savastio/.gitignore
1995/savastio/Makefile
1995/savastio/README.md
1995/savastio/try.sh
2000/rince/README.md
2012/vik/README.md
2018/burton1/README.md
2020/carlini/README.md
bugs.md
thanks-for-help.md

The try.sh script demonstrates both positive numbers and input that is
not a number at all (comparing two different strings).
The bugs.md has a new INABIAF - negative numbers will hang the program.
It is not clear if another version should be added to gracefully handle
this but that can be decided another time. It is not a documented
feature so it might be called a bug to fix.

Add 1995/savastio/try.sh and update bugs.md

---

1995/garry/garry.data
1995/garry/try.alt.sh
1995/garry/try.sh
thanks-for-help.md

They now show the garry.data file and also show a bit more of what is being done (in the script).
In the thanks file I removed the details as to why there are two scripts, one for the main version and one for the alt, as that was only there as at one point using environmental variables was the way it was being done, but that is no longer important or useful to know.

Improve 1995/garry try scripts

---

1995/makarios/Makefile
1995/makarios/makarios.c
faq.md
thanks-for-help.md

The parameters to the functions spell out (backwards) the function name.
As for main() since there can only be three args it has in comments a
fourth to spell out main (backwards). Also use old style
( main(n,i,a)char**i,**a;{/*..*/} ) as that's how the original code is
(and the added function is that way too though only ints like main()
used to be).
Added -Wno-implicit-int -Wno-return-type to CSILENCE in Makefile. 
There's still one more warning but I'm not sure if it's supported by all
compilers so I haven't disabled it (yet?).

Make my fix to 1995/makarios more like original

---

1995/makarios/Makefile
1995/makarios/makarios.c
1996/rcm/.gitignore
1996/rcm/README.md
1996/rcm/try.sh
faq.md
thanks-for-help.md

The 'to use' section was fixed also: it's not just specific gzipped
files but any so it now says 'file.gz' and adds that file.gz is any
gzipped file.
The try.sh script now has the command that used to be in to use and also
what was in the try section. It also copies rcm.c to rcm.cp.c and gzips
that file and then runs the program on that to show the source. All
paged through less(1), of course. Finally it does what the judges have
in their comments (which have been updated to say that the command is in
the try.sh script). The judges' command is naturally a shorter way to do
the one added in the try.sh script but it uses tee(1) to write both to 
another file (piped to less(1)) so that it can compare the two. 
Obviously the files will be the same but it shows how it works in 
multiple ways.

Add 1996/rcm/try.sh

---

1995/makarios/Makefile
1995/makarios/makarios.c
1996/rcm/.gitignore
1996/rcm/README.md
1996/rcm/try.sh
1996/schweikh1/README.md
1996/schweikh1/try.sh
1996/schweikh2/README.md
1996/schweikh2/try.sh
1996/schweikh3/Makefile
1996/schweikh3/README.md
faq.md
thanks-for-help.md

Rather than make anyone manually update the Makefile (the command in the
README.md file suggested that one would use Makefile variables) or type
a more complicated command the Makefile now tries to compile the entry 
as suggested if compilation fails. Thus one can type 'make all' and if 
compilation fails it will try the SunOS way.

Update 1996/schweikh3/Makefile for SunOS

---

1995/makarios/Makefile
1995/makarios/makarios.c
1996/rcm/.gitignore
1996/rcm/README.md
1996/rcm/try.sh
1996/schweikh1/README.md
1996/schweikh1/try.sh
1996/schweikh2/README.md
1996/schweikh2/try.sh
1996/schweikh3/Makefile
1996/schweikh3/README.md
1996/westley/try.alt.sh
1996/westley/try.sh
1998/banks/README.md
1998/bas2/README.md
1998/bas2/try.sh
1998/chaos/README.md
1998/chaos/try.sh
1998/df/README.md
1998/df/try.sh
1998/dlowe/README.md
1998/dlowe/try.alt.sh
1998/dlowe/try.sh
faq.md
thanks-for-help.md

Allow specifying paths to man, col and cat. This is done in a way that
the CC variable should have been done in all the other scripts
(and this one) but I didn't think about it at the time.

Slightly modify 1998/dlowe/try scripts

---

1995/makarios/Makefile
1995/makarios/makarios.c
1996/rcm/.gitignore
1996/rcm/README.md
1996/rcm/try.sh
1996/schweikh1/README.md
1996/schweikh1/try.sh
1996/schweikh2/README.md
1996/schweikh2/try.sh
1996/schweikh3/Makefile
1996/schweikh3/README.md
1996/westley/try.alt.sh
1996/westley/try.sh
1998/banks/README.md
1998/bas2/README.md
1998/bas2/try.sh
1998/chaos/README.md
1998/chaos/try.sh
1998/df/README.md
1998/df/try.sh
1998/dlowe/README.md
1998/dlowe/try.alt.sh
1998/dlowe/try.sh
1998/dloweneil/README.md
faq.md
thanks-for-help.md

This is a cosmetic change only and rather unimportant but I have to be
complete: when I added the alt code I used the word anticlockwise (as I 
would) instead of counterclockwise. But since the original entry
referred only to counterclockwise I decided to make it use both like the
alt code does.

Make usage of 1998/dloweneil more inclusive

---

1998/bas1/README.md
1998/bas1/bas1.sh
2000/natori/README.md
2000/natori/try.alt.sh
2004/arachnid/README.md
thanks-for-help.md

I had renamed the arachnid.info to arachnid.txt as it's not really an 
informative file but I forgot to update the command in the README.md 
file. I was tempted to rename it to arachnid.maz as it's a maze file but
I kept it as a text file so that (some?) browsers know what to do with 
it (though I'm not sure how strictly necessary that is it doesn't hurt 
to have it as .txt either).

Fix typo (bad filename) in 2004/arachnid

---

1998/bas1/README.md
1998/bas1/bas1.sh
2000/natori/README.md
2000/natori/try.alt.sh
2004/arachnid/README.md
2004/gavare/README.md
2004/hibachi/README.md
2004/hibachi/src/localhost/index.html
2004/hibachi/src/localhost/test/shell/test0.sh
thanks-for-help.md

Many links no longer worked, had changed or are https enabled now. In at
least two cases the Internet Wayback Machine was required but most were
just changed to https. The link to cygwin had changed entirely. The link
to lynx(1) had changed too.
Typo fixes in src/localhost/test0.sh.
Minor updates to README.md.

Fix 2004/hibachi/src/localhost/index.html

---

2004/omoikane/README.md
2004/omoikane/try.sh
2004/schnitzi/try.sh
thanks-for-help.md

It also now checks that vi is installed (for the unlikely case it's not 
installed).

Improve 2004/schnitzi/try.sh

---

1985/sicherman/try.alt.sh
1985/sicherman/try.sh

In these scripts, try.sh and try.alt.sh, the warning triggered is entirely incorrect and not a problem so they are now disabled.

Deal with shellcheck warnings in 1985/sicherman

---

1985/sicherman/try.alt.sh
1985/sicherman/try.sh
1988/dale/try.sh

In these scripts, try.sh and try.alt.sh, the warning triggered is
entirely incorrect and not a problem so they are now disabled. The 
comments explain why this is.

Deal with shellcheck warnings in 1988/dale

---

1985/sicherman/try.alt.sh
1985/sicherman/try.sh
1988/dale/try.sh
1993/plummer/try.alt.sh
1993/plummer/try.sh

This was only in try.sh: SLEEP is not needed which is why the error was
not detected. SLEEP is only relevant to the alt code. But the try.alt.sh
was updated to make it shorter for assigning the default:
[[ -z "$SLEEP" ]] && SLEEP=1000
1000 is the default in the Makefile.

Deal with shellcheck warnings in 1993/plummer

---

bin/ioccc-status.sh

It should be != 1 rather than -gt 1. Not having this meant that if no arg was specified the usage message was not printed and instead the arg of the status.json file (which was not given) was shown to not exist (because it was empty so not a file).

Fix arg check in ioccc-status.sh

---

bin/ioccc-status.sh
man/man1/ioccc-status.1

The man page is in /man/man1/. It is not clear to me if man/man1 should
be under another directory but that can be decided later and if
necessary it can be moved over. The man page has a few examples. More 
could be contrived if necessary. It has no SEE ALSO section because it 
is not clear to me what should be linked to (perhaps the IOCCC 
website?). I felt like I should write this man page first, in 
particular, because I wrote the script too and the benefit is I 
discovered some bugs in the script as well that are now fixed. 
The script only checked if the status.json file was readable but it did
not check if it is writable. It should check for both and it now does.
The exit code is the same as if the file does not exist, is not a
regular file or not readable: 1. It also now explicitly …

Add ioccc-status.1, bug fix ioccc-status.sh

---

2006/grothe/README.md
2006/grothe/try.sh
2006/hamre/try.sh
2006/monge/README.md
2006/monge/try.alt.sh
2006/monge/try.sh
2006/stewart/README.md
2006/stewart/try.sh
bin/ioccc-status.sh
man/man1/ioccc-status.1
thanks-for-help.md

It will run the program on a few files but before it runs it on the
remaining files (as there are quite a lot) it will ask you if you wish
to do so. It only asks once. If convert is found it will run convert on
the xbm images to convert to png. If it's not installed it will only
warn the user once so as to not spam them. If convert fails (say because
the convert is not convert from ImageMagick) it will warn once at the
end of the script. In any event if any files were converted it will list
the png files that exist at the end of the script. Otherwise it'll list
the xbm files. It does not first check if any of those file types exist
as it is presumed that at least a few will exist. If none do it is 
likely an error in the program or a corrupted data file.

Add 2006/stewart/try.sh

---

google14c794c9a2efaf03.html

Adding the domain verification page that is now present in the official site.
This web page has to stay in place for the google search console property to remain valid.
"Nothing to see here, people. Move alone!"  :-)

add domain verification page

---

1992/gson/mkdict.sh
bin/gen-inventory.sh

As a test of the new format of disabling warnings/errors from shellcheck(1) I have done it for this script which is an important one to consider as every warning and error should be disabled as the author provided the script (that I added as a script file) as an obfuscated script and therefore to not follow best practices, not at the time or now. But this way it's just one script to see if this works well, rather than fixing all the others (which will happen later in any case).

Silence 1992/gson/mkdict.sh shellcheck warnings

---

1994/westley/.gitignore
1994/westley/Makefile
1994/westley/README.md
1994/westley/try.alt.sh
1994/westley/westley.alt.c
1996/gandalf/try.sh

Rather than showing something like:
Showing diff between 'cmd' and 'cmd':
Press any key to run: diff ...
it now shows instead (for example):
$ diff hatcat.txt cathat.txt (diff between 'hatcat' and './cathat'):
Press any key to continue:
The reason it's two lines is because having it on one line makes it a
kind long line. Probably not an issue with modern systems but I have
tried to keep the lines close to 80 columns and not doing it this way
would make it almost 90.
The script now has -C 1 used to show context. This way the file names 
are shown in the output to help distinguish the files being compared. Of
course it might be possible to diff the command outputs themselves but 
this works better because it will show the files that are the same 
(when they are) rather than '.. and - are …

Slight UI improvements in 1996/gandalf/try.sh

---

1994/westley/.gitignore
1994/westley/Makefile
1994/westley/README.md
1994/westley/try.alt.sh
1994/westley/westley.alt.c

The to build/original build, to use/original use and try/original try sections have been changed in the README.md to be much more consistent and clearer (and detailed in some ways).
The to run section (not the original run section as that one is not supposed to be compilable and is not compilable either) has './westley.alt' now as that will give you a message even right after running 'make clobber alt'.
The alt code was changed in that blank lines were removed and (as a cosmetic change) the 'return 0;'s were changed to 'exit(0);'s. Originally the idea was to have 'int main()' be 'main()' (like the original in the #if 0..#else..#endif block) but this will trigger -Wimplicit-int and since one would not want to run a more complicated 'make' invocation (instead of a simple 'cc' invocation or …

Improve 1994/westley alt + to use etc.

---

2011/vik/.gitignore
2011/vik/README.md
2011/vik/try.sh
thanks-for-help.md

The script will check that mplayer(1) is installed. If it is it will pipe vik to mplayer. In that case it will still use the raw2wav program just in case something goes wrong (or for some reason mplayer is not what is expected). If mplayer cannot be found or is not a regular executable file then it will just use raw2wav. The raw2wav function in the script tells you the name of the converted file. In the case that mplayer cannot be found the script also suggests that you play the WAV files with a program that can play WAV files.

Add 2011/vik/try.sh

---

2012/blakely/.gitignore
2012/blakely/try.sh
2012/deckmyn/.gitignore
2012/deckmyn/try.sh

Improve less(1) options so that the screen is not cleared (to keep the 
source visible after it's seen) and to exit at EOF.
Try converting image files to png files. If this fails then as long as 
pbm files exist it will print those (telling the user to open them in 
their graphics viewer of choice). Otherwise if png files exist it lists
the png files (with the same message). If no png and no pbm files exist
it warns them that something went wrong and they are free to fix and 
open a pull request. This handling of convert(1) checks should probably
be done in other scripts where I neglected to do this (it's entirely 
possible though unlikely that a convert program exists that returns
success but does not do what we expect).

Improve 2012/deckmyn/try.sh

---

1986/bright/try.sh
2012/blakely/.gitignore
2012/blakely/try.sh
2012/deckmyn/.gitignore
2012/deckmyn/try.sh
2012/endoh1/.gitignore
2012/endoh1/Makefile
2012/endoh1/README.md
2012/endoh1/endoh1.alt.c
2012/endoh1/try.alt.bw.sh
2012/endoh1/try.bw.sh
2012/endoh1/try.sh
thanks-for-help.md

The new try.sh and try.bw.sh scripts run the program on one file (passed 
to the script) in colour and without colour respectively. One file
because one has to terminate the program.
The new try.alt.bw.sh is like try.alt.sh but uses the black and white
(original submitted entry) version.
The scripts for the alt code allow one to set the different variables
that can be redefined. The use is the same variable names as in the
Makefile. For instance:
TIMER=5 SLEEP=5000 GRAVITY=I VISCOSITY=4 PRESSURE=1 ./try.alt.sh
TIMER=5 SLEEP=5000 GRAVITY=I VISCOSITY=4 PRESSURE=1 ./try.bw.alt.sh
for the gravity 'I' and:
TIMER=5 SLEEP=5000 GRAVITY=N VISCOSITY=4 PRESSURE=1 ./try.alt.sh
TIMER=5 SLEEP=5000 GRAVITY=N VISCOSITY=4 PRESSURE=1 ./try.bw.alt.sh
where 'N' is some number. Obviously the other values can …

Improve and add 2012/endoh1 try scripts

---

2012/hamano/Makefile
2012/hamano/README.md
2012/hamano/try.sh
thanks-for-help.md

The Makefile rules added:
hint.pdf
hint
hello.pdf
hello
The hint rules generate the hint.pdf (which is the README.md file obfuscated in a pdf) by feeding the program README.md and then it compiles hint.pdf as C code. Running it will print the README.md file!
The hello rules generate hello.pdf which is (inside the pdf) an obfuscated 'Hello World!' program. This is done by a simple echo piped o the program which redirects it to hello.pdf. Then hello.pdf will be compiled as C code which when run (as ./hello2) will print 'Hello World!'.
The script now uses these rules to do what was once done manually. These rules are .PHONY rules as otherwise they might not always run.
The clobber rule now removes these files.

Improve 2012/hamano/try.sh + add helper make rules

---

2012/hamano/Makefile
2012/hamano/README.md
2012/hamano/try.sh
2012/hou/try.sh
2012/kang/README.md
2012/kang/de.alt.sh
2012/kang/de.sh
2012/kang/en.alt.sh
2012/kang/en.sh
2012/kang/try.alt.sh
2012/kang/try.sh
2012/konno/README.md
2012/konno/try.sh
2012/omoikane/try.alt.sh
2012/omoikane/try.sh
2012/tromp/try.sh
thanks-for-help.md

As for the shellcheck warning could be fixed (missing '\' before a '"') 
and the useless cat ones had the rationale updated (it's what the author
used so it's easier to verify it's okay though I still say - and so does
the script - that there's no such thing as a useless cat) and the format
of what warning is disabled (URL included).

Improve and shellcheck fix 2012/tromp/try.sh

---

2012/hamano/Makefile
2012/hamano/README.md
2012/hamano/try.sh
2012/hou/try.sh
2012/kang/README.md
2012/kang/de.alt.sh
2012/kang/de.sh
2012/kang/en.alt.sh
2012/kang/en.sh
2012/kang/try.alt.sh
2012/kang/try.sh
2012/konno/README.md
2012/konno/try.sh
2012/omoikane/try.alt.sh
2012/omoikane/try.sh
2012/tromp/try.sh
2012/vik/try.sh
bugs.md
thanks-for-help.md

The additional commands I added cannot come first because the program 
(as the bugs.md states and now more clearly) will likely crash (and does
in all the systems I tested) if the file does not exist. This did not 
show itself the first time because the files already existed but running
make clobber before the script would remove the image files and thus a
crash (or actually two) would occur the first time the script was run 
(second time it would be fine as the files it uses then exist).

Bug fix 2012/vik/try.sh

---

2013/endoh2/README.md
2013/endoh3/.gitignore
2013/endoh3/Makefile
2013/endoh3/README.md
2013/endoh3/endoh3.c
2013/endoh3/try.sh
thanks-for-help.md

The script checks for SoX, padsp and otherwise ruby. It allows one to
pass in args: each one is first checked to be a readable file and if
it is it'll be processed as a file; otherwise it'll be processed as a
string. If no arg is specified it runs the program on twinkle.abc and
the strings ABC and CDEFGABc (the latter suggested by the author).
If none of the three tools noted above are installed it tells the user
to install one of them first. I was not able to test the padsp(1) one
but the invocation matches the author's remarks. /dev/dsp seems to not
be installed in modern linux systems so it would be useful to have
padsp(1) if not SoX (which is preferable in general for entries that
play sound). The ruby script wavify.rb provided by the author is the
last resort which turns the output …

Add 2013/endoh3/try.sh

---

2013/endoh2/README.md
2013/endoh3/.gitignore
2013/endoh3/Makefile
2013/endoh3/README.md
2013/endoh3/endoh3.c
2013/endoh3/try.sh
2013/endoh4/Makefile
2013/endoh4/README.md
2013/endoh4/endoh4.sh
bugs.md
thanks-for-help.md

The Makefile was modified in such a way that allows one to easily
redefine the size (in the code the S macro). For instance:
make clobber SIZE=50,50 all
The try.sh was renamed to endoh4.sh as it's more of a wrapper to the
program rather than things to try. Also it now lets one specify more
than one file to feed to the program (in sequence).
The bugs.md was updated - added INABIAF. If the file format is invalid
it will very likely crash.

Improvements to build and script of 2013/endoh4 

---

1998/schweikh3/.gitignore
1998/schweikh3/Makefile
2013/endoh2/README.md
2013/endoh3/.gitignore
2013/endoh3/Makefile
2013/endoh3/README.md
2013/endoh3/endoh3.c
2013/endoh3/try.sh
2013/endoh4/Makefile
2013/endoh4/README.md
2013/endoh4/endoh4.sh
2013/hou/README.md
2013/hou/try.sh
2013/misaka/try.sh
2013/morgan1/README.md
2013/morgan1/try.sh
bin/all-run.sh
bugs.md
thanks-for-help.md

Have to remove *.wav files. This is important for updating the manifest
if the program was run and generated wav files (because the other tools
were not found).

Fix make clobber in 2013/endoh3

---

1998/schweikh3/.gitignore
1998/schweikh3/Makefile
2013/endoh2/README.md
2013/endoh3/.gitignore
2013/endoh3/Makefile
2013/endoh3/README.md
2013/endoh3/endoh3.c
2013/endoh3/try.sh
2013/endoh4/Makefile
2013/endoh4/README.md
2013/endoh4/endoh4.sh
2013/hou/README.md
2013/hou/try.sh
2013/misaka/try.sh
2013/morgan1/README.md
2013/morgan1/try.sh
2015/yang/.gitignore
2015/yang/Makefile
2018/burton1/.gitignore
2018/burton1/Makefile
bin/all-run.sh
bugs.md
thanks-for-help.md

When scripthd was renamed to scripthd.sh the DATA field should have been
updated to have scripthd.sh. Also make clobber should remove scripthd
(but not scripthd.sh).

Fix make clobber in 2018/burton1

---

.gitignore
1998/schweikh3/.gitignore
1998/schweikh3/Makefile
2013/endoh2/README.md
2013/endoh3/.gitignore
2013/endoh3/Makefile
2013/endoh3/README.md
2013/endoh3/endoh3.c
2013/endoh3/try.sh
2013/endoh4/Makefile
2013/endoh4/README.md
2013/endoh4/endoh4.sh
2013/hou/README.md
2013/hou/try.sh
2013/misaka/try.sh
2013/morgan1/README.md
2013/morgan1/try.sh
2014/deak/try.alt.sh
2014/endoh1/try.sh
2014/endoh2/Makefile
2014/endoh2/try.sh
2015/yang/.gitignore
2015/yang/Makefile
2018/burton1/.gitignore
2018/burton1/Makefile
bin/all-run.sh
bugs.md
thanks-for-help.md

Since the try script creates the files hello.c, hello, ioccc.c and ioccc
the clobber rule needs to remove those files.
The script now uses less(1) for longer output (it's possible there are 
still small enough displays where it would be useful).

Fix make clobber in 2014/endoh2

---

2013/endoh3/try.sh
2014/vik/.gitignore
2014/vik/Makefile
2014/vik/README.md
2014/vik/try.sh
bugs.md
thanks-for-help.md

The bugs.md has more details on the bug I discovered when working on
2020/ferguson2. Even the usage in the try section (now in try.sh)
resulted in files that cannot be translated to English right.
The make clobber rule now removes *.raw instead of specific raw files.
This is important for clean up prior to updating the manifest.

Add 2014/vik/try.sh, update bugs.md, fix clobber

---

2020/kurdyukov1/try.sh
2020/kurdyukov2/.gitignore
2020/kurdyukov2/Makefile
2020/kurdyukov2/README.md
2020/kurdyukov2/makegif.sh
2020/kurdyukov2/try.sh
2020/kurdyukov4/try.sh
2020/otterness/.gitignore
2020/otterness/README.md
2020/otterness/try.sh
thanks-for-help.md

The .gitignore was updated but it cannot be sorted because it excludes
'*.mid' but then negates the .mid files in the repo, cvikl.mid and
entertainer.mid. These have to come after the exclusion of '*.mid'. This
is important as one might use the entry to create a .mid file that is 
not done in the try script. The make clobber rule does not remove 
'*.mid' files as doing so would remove the ones we want to keep.

Add 2020/otterness/try.sh

---

2005/giljade/.gitignore
2005/giljade/Makefile
2005/giljade/test.sh

The script now lets one keep the out and out.count file even if the test suite passes. This is done because the try script does that too in case the user wants to see the out file to open in vim for fun (though the try script actually simulates this for them).
The make clobber rule needs to remove out.count too in case they decide to keep the file OR in the case before this commit the detecting errors is terminated prematurely. This is especially important for updating the manifest but even then it shouldn't leave files lying about.
Updated .gitignore with out.count added.

Improve 2005/giljade test.sh and fix make clobber

---

1992/westley/whereami.alt.sh
1992/westley/whereami.sh
2001/coupard/README.md
2001/coupard/try.sh
2001/ollinger/try.sh
thanks-for-help.md

There was a typo: awkf instead of awk.
ShellCheck fix as well.

Fix 1992/westley/whereami scripts if tput fails

---

1992/westley/whereami.alt.sh
1992/westley/whereami.sh
2001/coupard/README.md
2001/coupard/try.sh
2001/ollinger/try.sh
thanks-for-help.md

Use of awk(1) is actually overkill and there is already enough overkill
if no location is specified: it might nuke the world or the US,
depending on submitted entry or alt code (provided in remarks of the
author)! :-)

Change awk(1) to cut(1) in 1992/westley/whereami*

---

2005/aidan/try.alt.sh
2005/aidan/try.sh
2005/chia/chia.c
2005/jetro/README.md

The wording 'this entry requires SDL to be installed' has more than one
interpretation: 'it requires SDL to install the entry' (which seems more
likely even though it's incorrect) or 'it requires SDL to be built' 
(less likely as that is not what it said). Now it just says 'this entry
requires SDL'. Now it's monosemic and it says exactly what it should 
(okay - it could say something else like 'it requires SDL to compile' 
but that's bordering on unnecessary semantics).

Remove ambiguity in 2005/jetro/README.md

---

2005/klausler/try.sh
2005/mikeash/try.sh
2005/persano/.gitignore
2005/persano/Makefile
2005/persano/try.sh

The make clobber fix is important for updating the manifest. The 
.gitignore left a .gif file out but now it just ignores '*.gif'. The
script was updated with some newlines to separate commands.

Fix 2005/persano make clobber, .gitignore, try.sh

---

2011/akari/Makefile

Can't remove *.ppm as that removes example.ppm. Instead specific ppm files are removed.
Also two text files have to be removed.

Fix fix of 2011/akari make clobber

---

Makefile

To do with the build of html files in particular. The comments for each now have the tool being used in the form of ${FOO} tool (bin/foo).
The entry_index rule has been aliased to readme2index as that is what the rule uses (well bin/readme2index.sh).
The quick_entry_index rule has been aliased to quick_readme2index as that is what the rule uses (well bin/quick-readme2index.sh).

Typo fixes and comments updated in top Makefile

---

README.md

'Other fixes' also include an expansion on some thoughts. For instance it was suggested that to understand an entry one might change variable and label names but some entries will actually break if you do this. Another example is that some beautifiers will actually prevent code from compiling. Another is that some lints crash (it was already stated 'abort' but that does not necessarily mean crash; splint for instance will stop parsing quite easily if it doesn't like what it sees which happens quite often). There probably were other things like this that were updated/added/changed.
The format and typo fixes are less significant but I believe and hope it should look better now (in particular the format fixes and adjustments).

Typo/format and other fixes to top README.md

---

2011/vik/try.sh

Check for perl(1) before trying to run ./raw2wav. If neither mplayer(1) nor perl(1) are installed then the script tells the user to install one or both and try again.
Function raw2wav() checks that perl(1) is installed. If it's not it silently returns. With this change and the above it no longer makes any assumption about what is installed and also tells the user what they need to do if they don't have the proper tools installed.
Typo fix.

Fixes and improvements in 2011/vik/try.sh

---

2000/natori/README.md

This seems like a good thing to point out as on a Full Moon it'll be the same output and no variation at all. This note is in the README.md for the try sections.
There was also a typo fix.

Add note to 2000/natori wrt try.sh about Full Moon

---

2018/ferguson/weasel.spec
tmp/things-todo.md

The task of weasel.spec was removed as it's complete.
Rather than have to open a link to find the links to check (many if not
all are probably done already but they have to be confirmed yet) at
issue 3 I have just put the direct links in the file.
Also removed the embed video task. It might be useful but it's probably
not worth delaying things more.

Update todo file

---

news.html
news.md

Typo fix in news.{md,html}

---

index.html
index.md
news.html
news.md

'sort' -> 'sorted'. This is because the former CAN suggests that one 
might be able to sort the list when actually the list is sorted (it is
also synchronous with the previous list where it says sorted, not sort).

Typo fix in index.{md,html}

---

1984/README.md
1987/README.md
1988/README.md
1989/README.md
1991/README.md
1992/README.md
1993/README.md
1994/README.md
1995/README.md
1996/README.md
1998/README.md
2000/README.md
2001/README.md
2005/README.md
2006/README.md
2011/README.md
2012/README.md
2014/README.md
2015/README.md
2018/README.md
2019/README.md
2020/README.md
Makefile
faq.html
faq.md
tmp/things-todo.md

It should be pointed out that there are a few inconsistencies as noted
below.
In some years the title of entries that were explicitly listed were
linked to but as the README.md files no longer have the title it was not
as easy to locate the title (I could go back in archive/historic and I
did in some cases but I was trying to hurry this up to close #3).
It's most likely that some have backticks surrounding certain words like
gcc or something else but not in all files. An example that might be
there is '#define'.
Some wording is different. Usually this is due to the original wording
which I did not think was good to change. There might be other cases
that were missed as well. One thing is that comes to mind is that in
some README.md files it refers to the Makefile to check for build …

Format / typo check YYYY/README.md files

---

2020/ferguson1/Makefile

There was a \ instead of a - which broke compilation.

Fix 2020/ferguson1/Makefile from silence commit

---

1986/marshall/Makefile
1986/marshall/marshall.alt.c
2020/ferguson1/Makefile
thanks-for-help.html
thanks-for-help.md

This warning was previously not possible to silence but by changing the
(alt) code slightly (with same functionality including indeed the 
problem I documented in compilers.md) it now is.

Silence another warning in 1986/marshall

---

1986/marshall/Makefile
1986/marshall/marshall.alt.c
1989/jar.2/Makefile
2020/ferguson1/Makefile
thanks-for-help.html
thanks-for-help.md

The problem was that the alt rule had the ${CC} ... when it's not supposed to. That's for the rule ${PROG}.alt which there is none in this entry as there is no alt code.

Fix 1989/jar.2/Makefile for make everything/alt

---

Makefile
thanks-for-help.html
thanks-for-help.md

Also the thanks file had some fixes in them including a consistency problem: a place that refers to markdown had been updated to refer to index.html when it should have remained README.md.

Fix make genfilelist to use var.mk variables

---

2020/yang/Makefile
bin/README.md
bin/index.html
faq.html
faq.md

The file wrongcoded is now removed.
This should fix the make www step of verify_entry_files which allows all 
of it to complete (should because I did not test make www but the direct
command that is run on 2020/yang now exits 0).

Fix make clobber in 2020/yang

---

1984/mullender/Makefile
bin/all-run.sh
bin/all-years.sh
bin/chk-entry.sh
bin/gen-authors.sh
bin/gen-location.sh
bin/gen-other-html.sh
bin/gen-sitemap.sh
bin/gen-status.sh
bin/gen-top-html.sh
bin/gen-year-index.sh
bin/gen-years.sh
bin/md2html.sh
bin/output-index-author.sh
bin/output-index-inventory.sh
bin/output-year-index.sh
bin/pandoc-wrapper.sh
bin/quick-readme2index.sh
bin/readme2index.sh
bin/sort.gitignore.sh
bin/status2html.sh
bin/subst.default.sh
bin/subst.entry-index.sh
bin/subst.year-index.sh
bin/tar-all.sh
bin/tar-entry.sh
bin/tar-year.sh

The wording in the comments and the error message (in particular for
macOS) should now be clearer. Now in both places it shows how to install
bash in Homebrew. In commands I surrounded them like what was already
used, with " rather than 's, to make it consistent. There were other
cosmetic consistency changes as well.
Except in paths 'homebrew' was changed to 'Homebrew'.
In bin/output-year-index.sh there was a typo fix: it said to use it one
typically would do: 
-a bin/output-year-index.sh
which obviously is not correct.

Improve bash version notes in bin/*.sh

---

1993/lmfjyh/Makefile
thanks-for-help.html
thanks-for-help.md

The problem it had is that it was reverted back to trying to compile the very unsafe file name without deleting it after the ${CC} line. Thus the ${RM} part was moved back to the end of the rule. I added the file (or a glob that will match the file) to .gitignore a long time ago possibly when I added the alt code.
The thanks file was fixed to account for the fact that the Makefile no longer automatically builds the alt version if the code fails to compile.

Fix 1993/lmfjyh/Makefile

---

1984/README.md
1984/index.html
1987/README.md
1987/index.html
1988/README.md
1988/index.html
1989/README.md
1989/index.html

A point of interest is that in 1987 the README.md referred to Mark R Horton but it is now Mary Ann Horton so I changed it to that. Also as she has won I linked to not the Amazon author page but rather the authors.html link. It's important to note though that the author page on Amazon says Mark still, perhaps because that is how the book was published (I guess - I didn't look). Still it seems right to change it to how she identifies, rather than not.
Links were added for entries where referred to. Links were added to results where not linked to. It is unclear if links to USENET groups should be kept (besides the ones where the direct posts are known) or removed so I have not added any that have missing links even those that were already in other README.md files.
What remains to be done for …

Fixes and improvements in 1980s index.html files

---

1984/README.md
1984/index.html
1985/README.md
1985/index.html
1986/README.md
1986/index.html
1987/README.md
1987/index.html
1989/README.md
1989/index.html

Where there is not a direct post when referring to a USENET group (for results etc.) it is no longer a link to the group itself but just made italic. That means only 1984 has it and only for the contest announcement.
In 1989 the point about the Makefiles for fubar and tromp have been clarified a bit. They were ambiguous before: it could have been read as the Makefile for ALL entries but it was only for that entry. Also since these points are about the Makefile (and in particular portability of the original or alt versions) I moved the paragraph to right under the part about running make to compile (this part has some additional fixes that will be applied later on).
The years: 1984, 1985, 1986, 1987 and 1989 were updated. There was nothing to do (for this commit) for 1988 but there is a …

More fixes in 1980s README.md files

---

faq.html
faq.md

This FAQ entry explains that the IOCCC only supports GNU make(1) Makefiles.

Add FAQ 3.19: make(1) compatibility

---

1984/laman/README.md
1984/laman/index.html
1984/mullender/README.md
1984/mullender/index.html
2013/misaka/Makefile
faq.html
faq.md

Numerous typo fixes (like in links with an extraneous ')') and format fixes
were done.
Rebuilt index.html.

Typo and format fixes 1984/mullender/README.md

---

Makefile

The make help rule now has a summary of each rule so that one need not check the Makefile every time. Of course for more details they still have to but it's helpful for those who know what they need to do but still might not remember all the rule names (as there are quite a few).
Typo fixes include things like incorrect statements (in comments) of what a rule does, some being yank paste errors.

Improve make help and typo fixes in Makefile

---

bin/md2html.sh
faq.html
faq.md

The problem is that bin/md2html.sh had the line:
cp "$TMP_STRIPPED_MD" z
It did not use the file and it did not delete it either.

Fix stray and bogus file 'z' after make www

---

2020/ferguson1/README.md
2020/ferguson1/index.html
2020/ferguson2/README.md
2020/ferguson2/index.html

Some of the removed text referred to things that no longer exist due to shortening the text (a bit).
Others were that the text used to say that one should try the markdown or html file depending on if read in GitHub or not but now it's only the html files so that reference to GitHub was removed.
Other problems were discovered and fixed as well.

Fix links/text in 2020/ferguson[12]

---

1994/shapiro/README.md
1994/shapiro/index.html
1994/weisberg/README.md
1994/weisberg/index.html
1995/vanschnitz/README.md
1995/vanschnitz/index.html
2013/hou/Makefile
2013/hou/README.md
2013/hou/index.html

I noticed a problem with my improvement to the Makefile allowing one to
not use a temporary file so although the 'all' rule uses that method one
can still generate a.c so one can follow the author's remarks.
Links to this file were changed to code blocks, however, as the file
does not always exist. make clobber will remove a and a.c.

Fix 2013/hou/Makefile for a.c

---

1985/sicherman/Makefile
1985/sicherman/README.md
1985/sicherman/index.html
Makefile
bin/gen-top-html.sh

This was done at first to try and protect against clang but this was 
decided against. The thanks file has this updated too but it is not 
being committed yet as there are many other fixes and more to be done 
before that can happen. README.md was updated and index.html was 
rebuilt, however.

Don't build alt automatically in 1985/sicherman

---

Makefile
bin/gen-top-html.sh

It is now possible to specify select files to generate like the comment at the top suggested (but was not actually allowed). This is useful rarely but there is a case for it and that has been updated and it runs a fair bit quicker now.
It is an error if no files specified are in the allowed set (the variable TOP_MD_SET). If at least one file specified is in TOP_MD_SET it will process that or those files but it will skip any that are not. This is to prevent trying to process other markdown files like README.md files without the proper script.

Improve bin/gen-top-html.sh

---

1985/sicherman/Makefile
1985/sicherman/README.md
1985/sicherman/index.html
1986/marshall/README.md
1986/marshall/compilers.html
1986/marshall/compilers.md
1986/marshall/index.html
Makefile
bin/gen-top-html.sh
faq.html
faq.md

The text in markdown was gets&#x28;3&#x28; which resulted in gets(( 
rather than gets().

Typo fix in FAQ 4.1

---

thanks-for-help.html
thanks-for-help.md

This does not mean I have checked every link. Most have been checked but more checks will follow.
Also as for the fgets() changes in the file it links to the FAQ about this. It felt like a good idea as this is one where it can seem like (and a judgement call had to be made) tampering with the entry. This felt a better way than having a section about the fgets() change in the file which really isn't to do with thanks but rather why. With this change one can look at a specific entry, see the change and then if they have any concerns see the FAQ that's directly linked to right there.

Make fixes in thanks file through 1987

---

faq.html
faq.md

It ended up being just:
3.9 - How do I compile an IOCCC entry that requires (n)?
instead of:
3.9 - How do I compile an IOCCC entry that requires (n)curses?
and this has been corrected.

Typo fix in FAQ 3.9 title

---

1991/dds/Makefile

It has to remove a.c too, not just a.out.

Fix make clobber in 1991/dds

---

.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/other_issue.yml
.github/ISSUE_TEMPLATE/website_issue.yml

I believe that with this commit issue #858 can be marked complete but this can only be determined once this has been merged. From a test repo I made it does look pretty nice.
Things are more consistent, there is a place for attaching images explicitly (though not required as it's not always relevant though very helpful), typo fixes and rewording at the least.

Update template issue forms

---

2012/zeitak/Makefile
thanks-for-help.html
thanks-for-help.md

An error (a typo) in the CSILENCE prevented the code from compiling.

Fix 2012/zeitak/Makefile

---

2012/zeitak/Makefile
2018/burton2/author-README.txt
thanks-for-help.html
thanks-for-help.md

Added './' to command invocations for scripts etc.
Noted that the tests/ directory (or the files in it) were moved to entry
directory. The same for variations/ files.

Minor fixes in 2018/burton2/author-README.txt

---

1991/brnstnd/Makefile
faq.html
faq.md
thanks-for-help.html
thanks-for-help.md

This includes broken links and typos but also a stylistic change as
well. In particular each index.html file is preceded with the text:
Winning entry:
and the next line, the source code, is preceded with:
Winning entry source code:
This is to make them stand out more. It's not, maybe, immediately
obvious that the first links to index.html but I have not come up with a
way to make it obvious that looks nice as adding 'index.html' to
'Winning entry' might take from the fact that the section below is about
the fixes to the entry (or I might be taking it too literally too which
is entirely possible :-) ).
Missing links were also added for the years beyond 1995 at least for the
YYYY/index.html links. Those have not been checked for typos but when I
get to those years I will check those too.
I …

Many fixes in thanks file through 1995

---

1991/brnstnd/Makefile

It left 'sorta' in the directory even after the target file was deleted.

Fix make clobber in 1991/brnstnd

---

1996/august/README.md
1996/august/index.html

I fixed the problem of it not working with some compilers/systems ages ago but the README.md file still had:
STATUS: doesn't work with some compilers - please provide alternative code or fix for more compilers
Rebuilt index.html.

Remove outdated bug status in 1996/august

---

1996/august/README.md
1996/august/index.html
2020/kurdyukov4/README.md
2020/kurdyukov4/index.html
thanks-for-help.html
thanks-for-help.md

For each year it now shows which IOCCC it was. In other words for 1984
the link title is now:
1984 - The 1st IOCCC
and 1985 is:
1985 - The 2nd IOCCC
and 1986 is:
1986 - The 3rd IOCCC
and so on up to 2020 which is:
2020 - The 27th IOCCC
This helps it stand out better and it shows which contest it was.
There were a few other fixes. This edit does NOT check further years
from yesterday's commit 2647827d94a48d89cd70c5dfb387d32fb9127bec and it
is possible I won't do more years until another day (though I started 
1996 but nothing needed to be fixed, I think).
Other minor fixes in formatting were also made.
Rebuilt thanks-for-help.html.

Minor fixes and improvements in thanks file

---

faq.html
faq.md

It now clarifies that the CC=... checks by substring so that one can do make CC=gcc-mp-12, for example, and it will register as gcc.
It also clarifies that the top level Makefile and the year Makefiles recurse into subdirectories so that one can compile individual entries, entries for a given year or all entries.

Improve FAQ 3.0 - about Makefile rules

---

2001/cheong/README.md
2001/cheong/cheong.c
2001/cheong/index.html
bugs.html
bugs.md
news.html
news.md
thanks-for-help.html
thanks-for-help.md

Once upon a time after I had put in the bugs file that there is no arg 
check and it was a feature, not a bug, it was changed to bug status.
This was a very simple fix that I then made but it's not necessary
either so I have undone it to make it more like the original. Now the 
only difference from the original is my fix so that it compiles with
clang. This means the bugs file was also updated as was the index.html 
file and the thanks file (which also has some other fixes that are
unrelated).

Add back bug status to 2001/cheong

---

2001/ollinger/README.md
2001/ollinger/index.html
2001/ollinger/ollinger.c
bugs.html
bugs.md
thanks-for-help.html
thanks-for-help.md

Once upon a time after adding the entry to the bugs file it was changed so that it should be a bug to be fixed and when verifying things since it was very quick to fix I added it. It now has been restored to the original.
The bugs file was updated and the thanks file was updated accordingly along with the index.html and README.md files.

Restore bug status to 2001/ollinger

---

2004/anonymous/README.md
2004/anonymous/index.html

The problem is that the link itself had ()s and the script did not expect this. Instead use the html '&' codes.

Fix find_missing_links or 2004/anonymous

---

bin/md2html.sh
news.html
news.md

There were URLs that linked to https://www.ioccc.org/bin/README.md#foo 
but at ioccc.org it will be index.html so the README.md has been changed
to index.html.

Fix URLs in bin/md2html.sh

---

bin/md2html.sh
news.html
news.md

It might be useful to know that the majority of the files should be 
relatively quick to review and that of the three slower files one is 
almost done.
I did not change the date of the news update but this seems like a
useful change (though maybe better wording could be used). If the date 
is changed it would allow to update the status.json and status.html file
news date.

Add note about top prio issue 2006 to news

---

faq.html
faq.md

As numerous entries had to have arg type or arg count in main() changed (usually to do with clang but not always) it seems like this should be added to the FAQ.

Add FAQ 4.6 - about changes to main() args

---

faq.html
faq.md

There were some cases where the wrong JSON member was referenced when 
explaining a different JSON member (in author details).
Also to help clarify the part about if the value is unknown, I have 
changed it to be 'it should be ...' rather than 'they should use' since
obviously the author themselves ought to know their email, URL, alt URL
etc. :-)

Important typo fixes in FAQ

---

1984/laman/README.md
1984/laman/index.html
1984/laman/laman.c
bugs.html
bugs.md
faq.html
faq.md
thanks-for-help.html
thanks-for-help.md

The bugs.{md,html} files, 1984/laman/README.md (and index.html) file and
thanks files were updated. The thanks file has some additional fixes 
that were already in place but are relevant to this commit.

Restore bug status in 1984/laman

---

1984/laman/README.md
1984/laman/index.html
1984/laman/laman.c
2011/konno/README.md
2011/konno/index.html
2011/konno/konno.c
bugs.html
bugs.md
faq.html
faq.md
thanks-for-help.html
thanks-for-help.md

The paths in bugs.{md,html} were yank paste errors.
More fixes in thanks file with 2011 almost done.

Restore 2011/konno bug status, fix paths in bugs

---

faq.html
faq.md

This question is called '3.20 - How do I download individual entries or entries of a given year?' and discusses both the individual entry tarballs as well as the year based tarballs, each in a subsection. Each part explains files that exist in the tarball and there are examples of how one might make use of them after extracting the tarball. It gives an example tarball name for each, including the path.
Two typo fixes were made in the FAQ 3.13 title (in the link at the top and the actual question/answer as well).
Although the links in this new entry should work I have not yet checked the file (though I did check those links added) and I will not until it becomes clearer that not much more has to be done with the FAQ. Instead I will focus on the entry html files and possibly together with …

Add FAQ 3.20 - about entry/year tarballs

---

faq.html
faq.md

In the FAQ entry for downloading the tarballs (which has been renamed to be a bit clearer) the example tarball for each kind (individual entry and an entire year) it now links to the tarball in question so one can more easily determine the path. It also shows where one can find the tarballs (for each type). Other improvements have also been made but this and the rest of the file will be further reviewed at another time.
Typo fixes.

Minor fixes in FAQ 3.20 + typo fixes

---

1984/decot/decot.c
1990/westley/Makefile
1990/westley/README.md
1990/westley/index.html
1990/westley/westley.c
bugs.html
bugs.md
faq.html
faq.md
thanks-for-help.html
thanks-for-help.md

The entry that was referred to (not named but I remember it as 
1986/hague) as having an alternate version for the purpose that it
showed correct output but crashed was fixed quite some time back and so
this has been removed.

Fix no longer true statement in FAQ 4.1

---

1990/westley/Makefile
1990/westley/README.md
1990/westley/index.html
1990/westley/westley.c
bugs.html
bugs.md
thanks-for-help.html
thanks-for-help.md

The other one cannot be restored or at least should not be as it floods the screen in an unsuspecting way. If no arg is specified though, it now will likely crash (previously because of the use of argv[1] later in the code but now to prevent the code from flooding the screen if the number is < 0).

Restore one INABIAF in 1990/westley

---

1984/decot/decot.c
1990/westley/Makefile
1990/westley/README.md
1990/westley/index.html
1990/westley/westley.c
bugs.html
bugs.md
thanks-for-help.html
thanks-for-help.md

One of the lines in the fix (which is the same code as the original) had
an extra space in front of the first char which showed a difference. Not
a big deal but fixes should modify as little as possible.

Restore a first char in line in 1984/decot

---

2011/dlowe/dlowe-aux-data/english-1/Wireless_Days_2011_CFP.txt

Since GitHub has a problem with showing really big commits it seemed like my attempts at changing 'web site' to 'website' were incomplete but they were not. Something I noticed the first time shortly before I closed that commit (as it seemed to be a problem) that I ended up changing the file:
2011/dlowe/dlowe-aux-data/english-1/Wireless_Days_2011_CFP.txt
as well. The problem is that this was a file used to train the neural network of the entry so it should not have the change made.

Restore web site to 2011/dlowe training data

---

next/README.md
next/index.html

One typo was fixed and wording was slightly changed in one thing which is not really a typo but might be clearer now (if only slightly).
The links seem okay though I did not go through them in the browser as each section has the same links and it is easier to check them in vim than going back and forth in the browser between pages. It should all be good.
Thus next/README.md and next/index.html have been updated and can be considered completely reviewed at this time.

Fix typos in next/README.md, run make gen_top_html

---

next/guidelines.html
next/guidelines.md
next/rules.html
next/rules.md

Some links were fixed. For instance instead of index.html#enter it's now the relevant FAQ. A markdown link was broken so that it did not create a link at all.
Some formatting was updated mostly to make points bold or in code block (if it's going to be html it might as well especially as they are important).
And although there were some typo fixes there still are some typos in there. If you don't know why that is see the FAQ 1.0: How did the IOCCC get started?. :-) Besides much will be changed in these files by the judges and the purpose of this commit was to make sure links were valid and that the files are rendered okay, not to try and change the rules (although I did update the IOCCC email and make it the 28th IOCCC and fix the judges [list] .. to make a reference to something recent …

Check links/formatting in remaining next/ files

---

bin/README.md
bin/find-missing-links.sh
bin/index.html

A few typos were fixed.
One tool had the description reworded a bit to make it (hopefully) a bit clearer.
A link was fixed but I am not sure if, since it's a script, it should link to the GitHub repo or not, like with other markdown files. I changed it to use the %%var%% that the bin/README.md file uses. This is one reason links have not been checked. The other reason is I have not gone through the entire file yet.
I notice some tools do not have example usage and those could be added too.
There was an apparent typo in bin/find-missing-links.sh and this same typo was fixed in bin/README.md. I am not sure exactly what was meant, however, so it might need further modifications.
I have (the caveats above notwithstanding) gone up through pandoc-wrapper.sh or just before it.
Regenerated …

Minor fixes in bin/README.md

---

inc/guidelines.closed.hdr
inc/rules.closed.hdr
next/guidelines.html
next/guidelines.md
next/rules.html
next/rules.md

I was asked to actually make corrections in the rules and guidelines and to make sure that the look and feel seems good. The typos and other features will be added back later. Some things worth noting below.
First references to twitter were changed to mastodon. I also in some cases (this should be in the FAQ too and I'm not sure if it is) when referring to mastodon noted that unless you are mentioned (also if someone reposts your toot but this is not mentioned as it's not relevant) you will not get a notification so one should still refresh the page as otherwise they might not get an update.
The current iocccsize in the mkiocccentry repo checks for 2503 not 2053 like it used to. Only some of the references can be changed to 2503, however. For why this is read the file!
I changed the word …

Finish format/typo checks in next/

---

bugs.md
faq.html
faq.md

It seems pandoc actually handles it okay but the markdown was fixed 
anyway (in other words it does not change the html file). A line that 
was part of a sentence (the end of) started with '256.' This was changed
to '256\.' (another option would be to move the '256.' to the end of the
previous line). With pandoc the html file does not change but this very
issue has caused me problems before so I fixed it.

Format fix bugs.md

---

bin/README.md
bin/index.html

Usage for scripts where the usage was missing added, even if that's just that it is used in another file.
The script links have been changed to use %%REPO_URL%% for the GitHub syntax highlighting. Some other files have also been changed to this.
Other changes were probably made too.
Links still have to be checked but this has to be done next time.

Mostly finish bin/README.md

---

bin/README.md
bin/index.html
index.html
index.md
next/guidelines.html
next/guidelines.md
next/rules.html
next/rules.md
tmp/README.md

... including the index.{md,html} which was in all caps ..
The bin/README.md file (and index.html) was updated slightly with an added comma: not strictly necessary but for some it might be easier to read. This was discovered as I was going through the links (not done checking them yet but so far so good).

Fix missing cases of 'web site' to 'website'

---

bin/README.md
bin/index.html
inc/md2html.cfg
index.html
index.md
next/guidelines.html
next/guidelines.md
next/rules.html
next/rules.md
thanks-for-help.html
thanks-for-help.md
tmp/README.md

The inc/md2html.cfg file was in this case updated for the keywords (not
that many would think of it, maybe, but since I was making another fix I
added the keyword 'ta') and more importantly HEADER_2. The file is not
just about fixing old entries but rather help in every other way too.
Thus it now reads 'Thanking people for their help'.
The thanks-for-help.{md,html} has also been fixed in the above way and 
the 'thanks for all the fish' is now a link.
'Ta ta and thanks for all the fish :-)'

Fixes in thanks file

---

bin/README.md
bin/index.html

This completes bin/ except that one file is likely to be moved to bin/ which will mean that the file has to be updated again but not in a big way.
Very few top level html files (including inc/ and some other subdirectories that are not the years) have to be checked now, I believe. Some did not require any fixes at all. Still it might be a couple days before this is done. It is hoped that the entry html files will go quicker and then the final FAQ and bugs checks can be done.

Links and format fixes in bin/README.md

---

Makefile
bugs.html
inc/md2html.cfg

This commit changes inc/md2html.cfg also and it is done to make the header (under the line 'The International Obfuscated C Code Contest') match the header in the bugs.md file, in case. Updating bugs.md is not necessary. A keyword was also added to the html file, mis-features, along with the already existing misfeatures.

Minor update to bugs.html

---

CODE_OF_CONDUCT.html
Makefile
README.html
archive/historic/index.html
bin/index.html
bugs.html
contact.html
faq.html
inc/index.html
inc/md2html.cfg
inc/topbar.default.html
index.html
judges.html
license.html
markdown.html
markdown.md
news.html
next/guidelines.html
next/index.html
next/rules.html
nojs-menu.html
nojs-menu.md
status.html
thanks-for-help.html

In some pages at the top it had 'and' but in the menu it had instead a
'&'. The menus (JavaScript and otherwise) now has 'and' to match the
pages. The file nojs-menu.html has been checked for broken links and
indeed one at least was fixed. Very few top level html files need to be
checked now. Some that are entirely generated should be okay but links
will still be checked to be sure.
Some cases of '(Mis)features' from the previous commit were also
corrected to '(mis)features' as this is also part of menu and page
consistency.
The files markdown.{md,html} have had the menus updated too but there
are some other changes that were works in progress. This file is not
thus completed but will be sometime soon.

Fix consistency in menus and pages

---

index.html
index.md

The words 'press and hold words in the upper right corner' is less clear than 'press and hold the menu you wish to activate'. It is obvious, perhaps, to most, but it is better to be clearer.

Improve menu how-to for tablet devices

---

contact.html
contact.md
faq.html
faq.md

The fixes in the FAQ correspond to the fixes in the contact.html file.
With this commit the contact.html file seems okay but the FAQ is not yet looked at.

Fixes in contact.html and FAQ

---

1984/decot/.gitignore
1984/decot/Makefile
1984/decot/README.md
1984/decot/index.html
bugs.html
bugs.md
thanks-for-help.html
thanks-for-help.md
tmp/update-manifest.sh

In the case of this entry, it is so screwy that having the CFLAGS 
conflicts with the -traditional-cpp option in some systems. Thus the alt
rule has ONLY the -traditional-cpp option. The thanks file notes this
oddity and how to view the diff between the original and the alternate 
code.
Also the bugs file was changed to be worded like the README.md file.
The index.html file was improved for the fix to the Makefile (for the
alt build) and it also links to the specific lines in the code on GitHub
(see the index.html file how it talks about specific lines in the
judges' remarks).

Fix 1984/decot alt build

---

tmp/update-manifest.sh

To avoid problems the script now runs make find_missing_links at the end. It does it in such a way, though, as to make sure everything is fine before that. It runs the rule after everything is fine but if it fails it tells them they do not have to run the script all over again but they do need to fix the links and then run the appropriate make rules in order to fix the html file(s). It does note that if you're in doubt running 'make www' will be the safest bet.
There are two reasons the script does not run make www: first is that it uses verbosity not used in the make rule and second is it offers to run the quick-readme2index.sh script to go quicker if one knows that only a few README.md files were modified. The script now warns that this will only work if the README.md files have been …

Add make find_missing_links to update-manifest.sh

---

1984/decot/.gitignore
1984/decot/Makefile
1984/decot/README.md
1984/decot/index.html
1984/mullender/README.md
1984/mullender/index.html
bugs.html
bugs.md
thanks-for-help.html
thanks-for-help.md
tmp/update-manifest.sh

The link to 'stack' was for abstract data type which not only has no
article but should be call stack. This has been corrected.
Also with this commit the index.html files of 1984 look good. This
includes the 1984/index.html file itself. There is a change in 1986 that
might come before 1985 but this is to be determined later.

Fix link in 1984/mullender/index.html

---

1984/index.html
1985/index.html
1986/index.html
1987/index.html
1988/index.html
1989/index.html
1990/index.html
1991/index.html
1992/index.html
1993/index.html
1994/index.html
1995/index.html
1996/index.html
1998/index.html
2000/index.html
2001/index.html
2004/index.html
2005/index.html
2006/index.html
2011/index.html
2012/index.html
2013/index.html
2014/index.html
2015/index.html
2018/index.html
2019/index.html
2020/index.html
bin/output-year-index.sh

Make it consistent with my improvement to bin/gen-years.sh: the entry awards in the links (to each entry) are now in bold and so are the link names. This helps them stand out a bit more.

Improve bin/output-year-index.sh

---

ioccc.css

To help the fact it's a quote stand out better the vertical bar is a bit thicker (4px instead of 2px) and the colour is a bit darker (darkgrey instead of #e6e6e6). Also the font style is italic (as quotes often are shown) and the font weight is bold to help it stand out even more (that might be worth changing). Finally the colour of the text is blue (which looks nice with bold so it might also be changed if the weight is not bold).
A point worth noting is that in CSS (tested on my apache server and also W3Schools) having:
blockquote {
color: blue;
}
does not work (for <blockquote><p>...</p></blockquote>) as in the colour stays what was left for <p>...</p. which earlier in the stylesheet is set to black. On W3Schools what does work is:
blockquote p {
color: blue;
}
but on the server for …

Improve blockquote styling

---

ioccc.css

The problem was that later in the stylesheet there is '.content p' and since the <blockquote><p>..</p></blockquote> is in the content class the colour was being overridden. Thus there is now:
.content blockquote p {
color: blue;
}
which fixes the problem.

Fix colouring problem in blockquote

---

.gitignore
1992/westley/README.md
1992/westley/index.html
1993/cmills/.gitignore
ioccc.css

Although blockquote already is set to italic now blockquote p explicitly
sets it. The colour is dark green and the rationale is explained in the
comments as thus:
/* This rule makes sure that text in `<blockquote><p>..</p></blockquote>` is
* coloured right. Note that this MUST BE HERE and not earlier where the
* 'blockquote' rule is as otherwise the above '.content p' rule would
* override it.
*
* The following rationale with the blockquote rule above (in particular
* with italics) and the dark green selection, so that this is understood
* better:
*
*  0. Purple should NOT be used as this is being used for visited links.
*  1. Blue should NOT be used as this is being used for non-visited links.
*
* Now with context this might be okay but links can also be in blockquotes
* so this alone is …

Make blockquote p dark green italics

---

next/guidelines.html
next/guidelines.md

There were several places where a code block was used for text that is more like a quote (and in one case it is a quote) and these have been converted to a blockquote.
A few links were added instead of having the link in a code block.
In a case where a paragraph was split with blank lines in between each line (with the '|' marker at each line) I added a `<br>` to it so that it looked more natural.
With the recent changes to this file and the rules file more checks have to be made as well.

Improvements in formatting of guidelines

---

1993/vanb/README.md
1993/vanb/index.html

The list of expressions in the judges' remarks has been changed so that it fits nicer on smaller screens (it is no longer a code block but a list and each operator is surrounded by backticks).
The grammar provided by the author (not the code that explains it but the grammar) now also fits on smaller screens in a nicer way by breaking it into multiple lines.

Format improvements in 1993/vanb/index.html

---

ioccc.css

It is very hard to find a shade of green that works well in all cases against the white background and as already established blue and purple cannot work (and some of those would be hard to work with especially purple unless very dark maybe). Many possibilities were proposed but they all seem to be a problem so instead of changing the text to green there is a border on all sides now (forming a box or if you wish a 'block') and the text colour is black. The box / border is dark green.
The text style is still italic but it is unclear if this is wise. On the one hand quotes are often in italics but with italics in quotes it means that any quote with italics will not have those italics stand out.
Tested this change in two different forms: a blockquote where there are blank lines in between …

Improve blockquote styling (.. hopefully :-) )

---

1984/anonymous/README.md
1984/anonymous/index.html
ioccc.css
thanks-for-help.html
thanks-for-help.md

There is a back and forth dialogue between Landon and the author that
should have been quotes but was code and this commit changes them to
blockquotes. This was one of the tests for commit 
95db577489ede4dc5e7d388c9b02b0d8b82dfaf2.

Fix quotes in 1984/anonymous

---

Makefile
faq.html
faq.md
next/rules.html
next/rules.md

There were numerous things that had to be fixed and there will likely have to be some discussion as well.
Some formatting fixes and additional links were also added.
This commit involves some updates to the FAQ and while I was at it I fixed some references of 'entry'/'entries' to 'submission'/'submissions' (those that should not be 'entry' or 'entries').

Fix technical details with rules (esp 17)

---

inc/guidelines.closed.hdr
inc/guidelines.open.hdr
inc/guidelines.pending.hdr
inc/rules.open.hdr
inc/rules.pending.hdr
next/guidelines.html
next/guidelines.md

A typo that was missed because I did not look at that part of the file was 'quidelines' instead of 'guidelines'. This has been fixed in inc/ and next/.

Typo fixes in inc/ and next/

---

ioccc.css
next/guidelines.html
next/guidelines.md

A problem was discovered in blockquotes for really long text, in particular in the guidelines: 2305567963945518424753102147331756070. The problem was that the number flowed outside the border. That should no longer happen. Below is what should happen instead, though it's hard to be sure how it will look in every case.
In Safari on a 16" MacBook Pro with Safari all across the screen it is not a problem but shorter text will be in a smaller box (this means the green box will vary in size depending on what is in it but this does not seem to be a big problem).
With Safari in an old iPhone 8 Plus the box can go a bit further beyond the screen width but text does not go beyond the boundary and one can scroll left/right at need.
With Safari in an iPhone 14 Pro Max there is currently a cache …

Attempt to fix overflow problem in blockquotes

---

ioccc.css
next/guidelines.html
next/guidelines.md

A guideline that was there in previous years still had the '|' marker 
which is supposed to be only for changes. This has been removed.

Minor fixes in guidelines

---

bin/chk-entry.sh

Instead of using just git use "$GIT_TOOL" as the script already establishes what git to use.
The comment I added also explains the rationale about this a bit, as it might not seem immediately clear why it's useful over find(1).
And although it was already tested I forced what would have caused a failure before, to happen, so that I could verify that this works as I had originally imagined it: put a file in an entry directory that does not belong there and then run the script again, to make sure it does not detect any problem.
Of course with this change one still has to make sure to add valid files to git but that always was how it was anyway.

Slight improvement to 7af7a8 (bin/chk-entry.sh)

---

bin/chk-entry.sh
index.html
index.md

It now is a nicer name and allows for us to reorder the FAQ. This was
only done as I saw it and it's a quick fix. More have to be fixed 
another time.

Remove FAQ 0.0 reference in /index.html

---

ioccc.css
next/guidelines.html
next/guidelines.md
next/rules.html
next/rules.md

Rather than have a literal vertical bar (|) for lines that indicate a change from the last contest, it is now a CSS class which has a solid black left border of 4 pixels. This not only makes it easier to see but it fixes some formatting issues too (see below for tests).
This means that if a change mark is needed one can do:
<p class="leftbar">
...
</p>
A tip for vim users: in the .vimrc file add the following line (temporarily or otherwise):
abbr leftbar <p class="leftbar">
Then you only need to type:
leftbar
and it will automatically add the proper block.
As for testing how this looks I have checked it with Safari with:
- an iPhone 14 Pro Max
- an iPhone 8 Plus
- a MacBook Pro 16 inch (both at full width and smallest width)
- an iPad Pro 11 inch 4th generation in both portrait and …

Improve change mark in guidelines and rules

---

next/guidelines.html
next/guidelines.md
next/rules.html
next/rules.md

This was caused because I had accidentally put a leftbar class before 
the '*' rather than on the same line (after it). This commit should fix
it.

Fix validation of guidelines.html

---

1992/gson/README.md
1992/gson/gson.c
1992/gson/index.html
bugs.html
bugs.md
next/guidelines.html
next/guidelines.md
next/rules.html
next/rules.md
thanks-for-help.html
thanks-for-help.md

An additional look shows that the gets(3) call is for the dictionary 
file. It is highly unlikely (though not impossible) that the dictionary
file would ever have a line 256 in length and this as well as because it
was documented is why I changed the buffer size back to the original.
The bug status does still suggest it would be nice if fgets(3) could be 
used but it also lists the bugs and limitations the author stated in the
first place which actually does refer to the 256 limit.
I moved the notice to those who want a challenge up a bit in the 
README.md file to be right above obfuscatory notes rather than before 
those notes get into the details.

Change bug status in 1992/gson

---

bugs.html
bugs.md
thanks-for-help.html
thanks-for-help.md

The line '... and thanks for all the fish' was changed to 'Thanks for All
the Fish' (despite not being the full title it seemed more correct this
way).

Minor change to thanks file wrt fish

---

ioccc.css

This does mean that in some cases there is now redundant markdown '**'s to make the links bold but those can be removed as they are discovered - or not.

Make all links bold

---

var.mk

The link, for now, refers to the GitHub repo html file (https://ioccc-src.github.io/temp-test-ioccc/faq.html#SDL) instead of what it will be later, https://www.ioccc.org/faq.html#SDL.
The title has been changed to not refer to which FAQ (number) it is, instead saying 'the FAQ on how to compile and use IOCCC entries that require SDL1 or SDL1'.

Fix title and link to SDL FAQ in var.mk

---

ioccc.css

This solves a problem with smaller screens where the code would wrap to the next line which ruins the formatting of the code on smaller devices. A downside to this is that it makes it not fit on the screen but since it technically did not fit on the screen before and this way line breaks are not added this seems a much better way. It also will mean we shouldn't need to try and fix all the other long lines in code blocks (which not only can be problematic but in some cases it can be wrong - plus it is taking too much time away from moving from entry to the next entry to the next entry).

Add overflow scroll bar to code blocks

---

faq.html
faq.md

It is preferable that unobfuscated code is by the author if they have (and many have done exactly that).
It would also be preferable to include the author or authors of the entry or entries if at all possible.
This update includes a link to how to find more information about an author and I think that FAQ was slightly improved as well.

Improve FAQ about providing deobfuscated code

---

Makefile
bin/README.md
bin/index.html

The variables CSV2ENTRY and ENTRY2CSV have been added for the new rules that run the new rules, csv2entry and entry2csv, respectively, according to the log in 097dd49cc7e15cdc3458fe0b9e74b09da2e0852f.
The rules have been added to .PHONY (thinking about this quickly I believe this is correct but if not it can be corrected) but not make help as I am not sure where in that rule they should be and I am also not sure what should be said even as a summary. The rules have a comment for which tool it runs but it also does not have a summary as I am not sure what it should say and I do not currently have the time to look into it.
With this commit it is now easier to run these tools for testing and otherwise.

Update Makefile for csv2entry and entry2csv

---

bin/README.md
bin/csv2entry.sh
bin/index.html

The fixes in bin/README.md include typo fixes, link fixes, format fixes as well as adding a couple terms that are now used by the IOCCC (submission and submitter).
The typo fixes in bin/csv2entry.sh were deemed worth putting in this commit as a lot of the changes in the document are related.

Fixes in bin/README.md, typo fixes in csv2entry.sh

---

1992/gson/README.md
1992/gson/index.html
1992/gson/try.sh
bin/README.md
bin/csv2entry.sh
bin/index.html

For fun more strings have been added and the dictionary constructed with
mkdict.sh now uses index.html as well.
Some fun anagrams that might amuse some people, some from the program
and some that I noticed:
foundation was set for free
foundations for free waste
relaxation unit inn
nun relaxation in it
inline no tar at unix
stale glib
routine and waste offer of (software)
idea for fun software note
try ansi op forms ioccc
any op first forms ioccc
first conspiracy container main tool
force locations contains primary tin
but there are plenty others to find with the script and otherwise.

Improve 1992/gson/try.sh + fix index.html

---

1992/gson/README.md
1992/gson/index.html
1992/gson/try.sh
1992/marangon/README.md
1992/marangon/index.html
1992/vern/README.md
1992/vern/index.html
1992/westley/README.md
1992/westley/index.html
bin/README.md
bin/csv2entry.sh
bin/index.html
bugs.html
bugs.md

With the exception of 1992/nathan/index.html the entries of 1992 should
all be okay. The reason nathan cannot be done yet is some things have to
be decided first.
This commit fixes:
1992/marangon/index.html
1992/vern/index.html
1992/westley/index.html

Fixes in most of 1992 index.html files

---

1992/gson/README.md
1992/gson/index.html
1992/gson/try.sh
1992/marangon/README.md
1992/marangon/index.html
1992/vern/README.md
1992/vern/index.html
1992/westley/README.md
1992/westley/index.html
1993/ant/README.md
1993/ant/index.html
bin/README.md
bin/csv2entry.sh
bin/index.html
bugs.html
bugs.md

The unobfuscated version was recently provided by the author so this is
no longer an issue.
A code block in the INABIAF was changed to a quote as it's not code but
something the author wrote.
This entry's index.html might not be done as a question also has to be 
addressed before the manifest can be fixed.

Fix bug status (missing file) in 1993/ant

---

1993/ant/.entry.json
1993/ant/index.html
2020/endoh2/.entry.json
2020/endoh2/index.html
2020/endoh2/obfuscation/index.html
2020/endoh2/obfuscation/index.md

For 1993/ant it clarifies (even though the extension of the file probably would suggest it) that the man page is in text format.
For 2020/endoh2 there were some mistakes introduced with the renaming of spoiler to other things.
Rebuilt the .entry.json and the index.html files for both.
Rebuilt 2020/endoh2/obfuscation/index.html.

Manifest updates for 1993/ant and 2020/endoh2

---

1992/nathan/.entry.json
1992/nathan/.gitignore
1992/nathan/Makefile
1992/nathan/README.md
1992/nathan/index.html
1992/nathan/nathan.alt.c
thanks-for-help.html
thanks-for-help.md

This is so one can see what the originally published code did. The index.html has a bold important note that one should NOT send an email to the address as it is not only no longer necessary but it is not known if it is still valid. Unlike the index.html where the email was omitted/redacted the alt code still has the email as the original code as it is an exact copy thereof, including the typos in it.
Rebuilt .entry.json and index.html.

Copy 1992/nathan.orig.c to nathan.alt.c

---

bin/new-year.sh

In a couple places the variable 'status' was checked for a value by comparing that value to 'status' instead of '$status'.

Bug fix in bin/new-year.sh

---

1991/README.md
1991/index.html
1992/README.md
1992/index.html
1993/README.md
1993/index.html
1994/README.md
1994/index.html
1995/README.md
1995/index.html
markdown.html
markdown.md

In the years 1991, 1992, 1993, 1994 and 1995 the README.md/index.html
files referred to the UUCP for mail with the text:
For those who appreciate a bit of Internet history, this is how
people used to contact the IOCCC in this given year
and I added to it the text:
via Unix to Unix CoPy (UUCP)
where 'Unix to Unix CoPy (UUCP)' is a link to 'complete' the history.

Add to Internet history about UUCP

---

markdown.html
markdown.md

Improved wording of some of the titles.
Added div ids to each guideline so that we can link directly to them if necessary.
The code block examples now specify a language so that when language highlighting is available it will show up better. I added this for those that are not wanted and those that are in the hopes it will stand out more.
I added a guideline that for italics one should use underscores (_) as using single asterisks is known to cause some parsers problems (and this goes more so, perhaps, when it is bold italic text which would otherwise be three asterisks in a row). I first became aware of this from a document on some markdown parsers and it seems like a good idea to note.
Added that it is preferable and easier to use markdown links if possible (along the lines of how it's …

Fix and expand markdown guidelines

---

faq.html
faq.md

The fields are now in the order that the mkiocccentry tool writes them.
A brief note on how to verify that the .auth.json and .info.json files are valid JSON (not valid according to the IOCCC rules but valid JSON) is at the end of each of these FAQs. Given that there are numerous FAQs on different JSON files it seems like that it might be better to have an entire FAQ on this (it links to a subsection in an FAQ about another kind of JSON file). Where this might go is unclear to me so it has not been done yet.

Fix FAQs on .auth.json and .info.json

---

bin/README.md
bin/index.html
faq.html
faq.md

This FAQ was added as part of updates to bin/index.html. I did notice that there are some inconsistencies with formatting in some FAQs compared to this (and others also). The example here is that for JSON members it would be better to use inline code blocks than italics but some use italics instead. There are others as well. I did look at the format and the links in this updated FAQ but the format inconsistencies can be addressed another time - after it is clear that new FAQs will not have to be added. Even so this FAQ that was added here could also possibly be improved further - also later on.
The bin/index.html updates need to be more thoroughly checked as part of further documenting the newer tools (and any additional ones that might be added) but there should be some improvements as …

Add FAQ on .entry.json files

---

bin/README.md
bin/index.html
bugs.html
bugs.md
faq.html
faq.md

That is make inline code blocks to help them stand out a bit more 
(previously they were just normal text).
Another entry in this file just linked to another entry by the same
authors and not even to the discussion in the bugs file but just the
source code. This has been corrected too.

Dead URL fixes in bugs file

---

faq.html
faq.md
next/guidelines.html
next/guidelines.md

Several new FAQ entries have been added to discuss some of the details of chkentry, txzchk, fnamchk, jparse and maybe others that are related to the rules and guidelines (and in particular rule 17 and how to package submission tarballs). As there are new FAQ entries on these (which is much of what was in the guidelines) the guidelines have been shortened for these additions.
Looking over the rendered html files it seems okay but I believe that these entries are works in progress and not complete.
For reference the new FAQ version is 28.0.3 2024-07-27 and the new guidelines version is 28.11 2024-07-27.

Add FAQs about the mkiocccentry tools

---

1998/banks/README.md
1998/banks/index.html
1998/chaos/README.md
1998/chaos/index.html
1998/dlowe/README.md
1998/dlowe/index.html
1998/dloweneil/README.md
1998/dloweneil/index.html
1998/dorssel/README.md
1998/dorssel/dorssel.html
1998/dorssel/dorssel.md
1998/dorssel/index.html
1998/schnitzi/README.md
1998/schnitzi/index.html
1998/schweikh1/README.md
1998/schweikh1/index.html
1998/schweikh1/macos.html
1998/schweikh1/macos.md
1998/schweikh2/README.md
1998/schweikh2/index.html
1998/schweikh3/README.md
1998/schweikh3/index.html
1998/schweikh3/samefile.1
1998/schweikh3/samefile.1.dupe
1998/tomtorfs/README.md
1998/tomtorfs/index.html
bugs.html
bugs.md

This includes some notices to those who wish for a greater challenge.
In the 1998/schweikh3 the man page (and its copy to demonstrate the entry) have been updated slightly but only in comment (move 'or' from the command suggested to render it in text to its own line before the next command also in comment).
The bugs file was updated for an entry or two.

Fixes in 1998 html files

---

2001/README.md
2001/index.html
2004/README.md
2004/index.html
2005/README.md
2005/index.html
2006/README.md
2006/index.html
2011/README.md
2011/index.html
2012/README.md
2012/index.html
2013/README.md
2013/index.html
2014/README.md
2014/index.html
2015/README.md
2015/index.html

There are places where references to mirror sites should be kept in like in the FAQ (currently FAQ 6.2 with the title 'May I mirror the IOCCC website?' and with the named anchor 'mirrors', 'website_mirrors' and 'website_mirroring').

Remove reference to mirrors in index.html files

---

2001/README.md
2001/index.html
2004/README.md
2004/index.html
2005/README.md
2005/index.html
2006/README.md
2006/index.html
2011/README.md
2011/index.html
2012/README.md
2012/index.html
2013/README.md
2013/index.html
2014/README.md
2014/index.html
2015/README.md
2015/index.html

Instead of having the mirror note in the YYYY/index.html files completely removed it is back but as a historical note.

Add mirror references back as historical note

---

2004/gavare/README.md
2004/gavare/index.html
2004/gavin/README.md
2004/gavin/gavin.html
2004/gavin/gavin.md
2004/gavin/index.html
2004/hibachi/.entry.json
2004/hibachi/README.md
2004/hibachi/index.html
author/Anders_Gavare.json
authors.html
bugs.html
bugs.md

Some bug statuses have been changed so the bugs file was also updated (some removed, some added).
The manifest of 2004/hibachi was fixed some.
The alt_url of 2004/gavare was fixed which required a rebuild of authors.html.
For 2004/gavin a proper link to QEMU was added. It strikes me as it possibly being a good idea to have an FAQ about QEMU (as it is not just 2004/gavin that might benefit from it) but I don't know and in any case I have zero experience with it.
The entries 2004/gavare, 2004/gavin and 2004/hibachi have been checked for format / display issues. This would suggest that the next entry to look at is 2004/hoyle.

More html files of 2004 fixed

---

2001/bellard/Makefile
Makefile
next/guidelines.html
next/guidelines.md

Having a '\' at the EOL of an echo followed by the rest of the string on
the next line will obviously not work as the '\' doesn't start a new 
command but continues it (scripts notwithstanding). I am not sure how 
this even got there but it resulted in a very long line of output.

Fix warning in 2001/bellard/Makefile

---

2001/bellard/Makefile
2004/burley/Makefile
2012/kang/Makefile
Makefile
next/guidelines.html
next/guidelines.md

The warning -Wmisleading-indentation is nothing but style policing, can 
causes unnecessary edits to working code which is error prone itself and
even beginner C programmers can parse it as it's one of the first things
learnt, blocks of code. And if someone can't perhaps they should be
using another language or not programming at all. As for the IOCCC it
would be considered a good thing to be 'misleading' except that it's not
misleading to anyone participating in the IOCCC and certainly not to the
judges if it even is to anyone else.

Disable useless and annoying warning in 2012/kang

---

2001/bellard/Makefile
2004/burley/Makefile
2012/kang/Makefile
2012/zeitak/Makefile
2013/birken/Makefile
Makefile
next/guidelines.html
next/guidelines.md

That warning is -Wdocumentation:
prog.c:1:1: warning: line splicing in Doxygen comments are not supported [-Wdocumentation]
1 | /**??/
| ^
... and is obviously confused by trigraphs.

Silence funny warning (linux) in 2013/birken

---

2001/bellard/Makefile
2004/burley/Makefile
2012/kang/Makefile
2012/zeitak/Makefile
2013/birken/Makefile
2019/adamovsky/Makefile
Makefile
next/guidelines.html
next/guidelines.md

The funny warning is:
prog.c:19:515: warning: line splicing in Doxygen comments are not supported [-Wdocumentation]
19 | void X(char*f,int r){ fputs(f,stderr);exit(r);}typedef w{w* (*t) (w*x);w* (*l) (w*x,w*y);w*a;long long p;}A;h(R) {x[N-1].p++;e x;}h(Ch) ;h(Y) ;h(fA) ;d(fD) ;d(fT) ;d(fW) ;d(fCh) ;d(rA2) ;d(fA2) ;d(rY2) ;d(Y2) ;d(rS2) ;d(fS22) ;d(rD) ;d(rE) ;d(rT) ;d(rC) ;void D(A*f) {if(f&&!--f[N-1].p) {if(u(f)!=fW&&u(f)!=fCh) D(f[1].a);if(u(f)!=fT) D(f[2].a);if(u(f)!=rE&&u(f)!=rT&&u(f)!=rC) D(f[3].a);free(f);}}int ch=EOF,c;FILE*p;A T[256][2];void U(void) {do{if(c==EOF) e;if(T[c][0].t) e;if(!T[c][1].p) E;if(T[c][1].p==4) for(/**??/
|
^
1 warning generated.
.. obviously confused by trigraphs.

Silence funny warning in 2019/adamovsky

---

2001/bellard/Makefile
2004/burley/Makefile
2012/kang/Makefile
2012/zeitak/Makefile
2013/birken/Makefile
2019/adamovsky/Makefile
2019/mills/Makefile
Makefile
next/guidelines.html
next/guidelines.md

The warning -Wunsafe-buffer-usage is triggered (iirc) on pretty much 
every use of 'char *' and some of the previous commits also had to 
silence this warning. It is triggered by clang -Weverything.

Silence 2019/mills in linux (clang)

---

2001/bellard/Makefile
2004/burley/Makefile
2012/kang/Makefile
2012/zeitak/Makefile
2013/birken/Makefile
2019/adamovsky/Makefile
2019/mills/Makefile
2020/ferguson2/Makefile
Makefile
next/guidelines.html
next/guidelines.md

The warning is also -Wdocumentation:
recode.c:17:7: warning: line splicing in Doxygen comments are not supported [-Wdocumentation]
17 |                            /\
|                            ^
1 warning generated.
.. and I guess it's confused by the line splicing, actually, just like 
the others as I see more clearly now, rereading the warning message as I
did not use trigraphs.

Silence funny warning in 2020/ferguson2/recode.c

---

1993/leo/leo.c
2013/birken/Makefile
2014/birken/Makefile

The entry that triggered the funny warning (-Wdocumentation) was not in
2013/birken but 2014/birken. Thus the -Wno-documentation was removed 
from 2013/birken/Makefile and added to 2014/birken/Makefile.
With this commit I believe that every warning that can be disabled has 
been disabled in some way or another, though this is with an earlier
version of clang (clang version 17.0.6 but the most recent one is,
according to its website and contrary to wiki claiming 17, 18.1.8, and I
also know that fedora linux clang had more problems).

Fix fa807fdb7fd1d1294b5d8e4a570c53a64f431d6d

---

ioccc.css

A problem existed where in a superscript if there is a line immediately above it the superscript text would cover part of the line and in subscript the same problem occurred with the line below it.
This change can possibly be improved but it now does not cover text (though admittedly I did not test the subscript before the change, only after, but it seems highly unlikely it was not a problem).

Fix sub/superscript cover text

---

next/guidelines.html
next/guidelines.md

The jparse/ subdirectory in the mkiocccentry repo is self-contained but it was suggested to put in parentheses the original source and this has been done now.

Add jparse repo to guidelines

---

faq.html
faq.md

The FAQ now notes that there can be times where the jparse repo (https://github.com/xexyl/jparse/) is different from the mkiocccentry repo's subdirectory jparse. This is one of the reasons the tools in the mkiocccentry and the jparse repo show the jparse API with the -V (version) option.
I believe that this is all that's needed for the jparse repo in the FAQ but time will tell on that.

Minor fixes to FAQ wrt other repos

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/other_issue.yml

The render: markdown causes formatting problems (too long lines) in the post, at least sometimes.

Fix environment field in issue templates

---

Makefile
bin/README.md

It had:
#build authors.html if out of date with author JSON files'!/usr/bin/env make
so it was changed to:
!/usr/bin/env make
It seems like this was somehow yanked pasted from make help.

Fix shebang in top level Makefile

---

2014/birken/README.md
2014/birken/index.html
2014/maffiodo1/README.md
2014/maffiodo1/index.html
2014/skeggs/README.md
2014/skeggs/index.html
2014/vik/README.md
2014/vik/index.html
bin/find-missing-links.sh
bugs.html
faq.html
faq.md

The code 5 was missing. The reason other lines changed is simply 
formatting (aligned to 4 chars).

Fix exit code text in bin/find-missing-links.sh

---

faq.html
faq.md

This commit is the first step in reordering/restructuring the FAQ.
Something important to notice is that except for the FAQ sections, the anchor names starting with the regexp '^faq[0-9]' have been removed. The numbers have not been removed otherwise, however, and as one FAQ was a duplicate there might be a labelling problem too.
As the FAQ links do not refer to the number but rather what they are about, and since the FAQ is being heavily restructured, the numbers are a burden. Even after everything is reordered it could be a potential problem when adding a new FAQ (though that should hopefully be pretty rare). Perhaps a list that's not numbered (unordered instead of ordered in html terms) is what is needed but this can be decided later.
This is a work in progress but since a lot was done …

Add anchor to all FAQ entries

---

faq.html
faq.md
next/guidelines.html
next/guidelines.md
next/rules.html
next/rules.md

Numerous sections have had questions moved to another section including the new sections 'The mkiocccentry toolkit: finer details' and 'History of the IOCCC'.
The first section was renamed (pending any better name as it might not be quite right) 'Entering the IOCCC: the bare minimum you need to know'.
Renamed some questions to better (hopefully) account for what they are about.
The purpose of not making the actual content match this reordering is so that if any changes need to be made they do not have to be done again (though a few were moved). Thus before more work can be done some discussion is needed.
The guidelines and rules now refer at the top to the general FAQ especially about the bare minimum one needs to know.

Reorder FAQ table of contents

---

faq.html
faq.md

New sections were added. Not all anchors work yet. The questions/answers are not yet in the right order. That is the next step.
Instead of relying on having to manually add numbers use ordered lists. The sections are in unordered lists so we have control over the number. The downside with this is with the long file it is harder to find the section one is in but as each question/answer has a jump to the top that should be worth the gain of not having to manually edit every question (in the table of contents as well as the question/answers) every time a question is moved to another place (or a new one is added) above others.
Another downside is minor: it does not allow for 0 as html lists do not start with 0 but 1.
Another thing that has to be done is to make sure that the html lint is …

Reorder FAQ table of contents, adding new sections

---

faq.html
faq.md

This was forgotten in the previous commit.
Also shorten some command lines (end line with '\').

Remove <ul>/</ul> in FAQ

---

bin/find-invalid-json.sh
faq.html
faq.md
next/guidelines.html
next/guidelines.md

It incorrectly calculated the number of invalid JSON files.
Redirect jparse stderr to /dev/null as the script will be able to tell without the extra clutter.

Bug fixes in bin/find-invalid-json.sh

---

faq.html
faq.md

In the case of JSON code blocks many had lines that ended in ',' which would, when syntax highlighting works, be flagged as a syntax error.
A typo was fixed in a JSON code block (for the IOCCC affiliation).
In entry_set JSON description the formatting was wrong and it also had a syntax error. Instead it now has the full set of the author in question (Yusuke Endoh) as of this time.

More format fixes in FAQ

---

2006/toledo2/README.md
2006/toledo2/index.html
2006/toledo3/README.md
2006/toledo3/index.html
bin/README.md
bin/format-headers.sh
bin/index.html
bin/md2html.cfg
bin/subst.default.sh
nojs-menu.html
nojs-menu.md
thanks-for-help.html
thanks-for-help.md

Typos were fixed in bin/md2html.cfg, bin/subst.default.sh,
nojs-menu.html and nojs-menu.md.
The nojs-menu.html now links to bin/index.html and inc/index.html but 
the rest of the html files for now do not. It seems like it might be 
good if they do, at least bin/index.html, but if that is decided against
this can be rolled back instead.

Typo fixes 

---

2001/westley/README.md
2001/westley/index.html
Makefile
bugs.html
bugs.md

For certain rules that build specific html files there was a missing 
.PHONY target.

Fix .PHONY in top level Makefile

---

2001/herrmann1/README.md
2001/herrmann1/index.html
bugs.html
bugs.md

With thanks to Leo, the filenames have been corrected in the README.md/index.html file. As the manifest already has them (they were under different names) the .entry.json file did not have to be updated.

Address missing files in 2001/herrmann1

---

1986/bright/.entry.json
1986/bright/index.html
1988/litmaath/.entry.json
1988/litmaath/index.html
1992/albert/.entry.json
1992/albert/index.html
2018/burton1/README.md
2018/burton1/index.html
2018/burton2/README.md
2018/burton2/index.html
2018/ferguson/README.md
2018/ferguson/index.html
2020/ferguson1/terminals.html
2020/ferguson1/terminals.md

In the case of two which had an abstract (.entry.json file) that includes one (in one case) '<' or two (in another case) '<'s a markdown code block had to be used as otherwise the abstract would have to have a &lt; which looks even worse. This is not ideal but if we want it to pass lint this is what has to be done. Use of json \uxxxx won't work as that encodes it to < literally.
In the case of 2018/burton[12] the author had a section called Coda. This conflicted with the problem that all generated html files have such a section. To fix this problem I renamed it 'Final remarks'. Not ideal but at least it now passes as valid.
There were a number of different kinds of problems and in one case the symbols < and > could be fixed by changing it to a code block (which it should have been anyway) …

Fix html lint (W3C Nu) errors

---

1986/bright/.entry.json
1986/bright/index.html
1992/albert/.entry.json
1992/albert/index.html

The way the abstract is used for the index.html files does not allow for parsing by pandoc so it did not work as expected (I did not verify the two entries this is a problem).
The index.html files of these two entries have been modified. Unless the script is updated the only other way is to update the abstract to use &lt; but this can be discussed.

Remove `s from .entry.json files

---

1986/marshall/README.md
1986/marshall/compilers.html
1986/marshall/compilers.md
1986/marshall/index.html
thanks-for-help.html
thanks-for-help.md

This includes the compilers.html and index.html file.
I also threw in a slight formatting change in the thanks file.

Fixes in html files in 1986/marshall

---

1986/marshall/README.md
1986/marshall/compilers.html
1986/marshall/compilers.md
1986/marshall/index.html
bin/html.sed
bin/output-index-inventory.sh
thanks-for-help.html
thanks-for-help.md

The script, for now, translates the following characters to their html
entity:
&, <, >
An important note that is in a comment is that the & MUST come first as
otherwise the & in the others will be corrupted.
One script uses this but in order to make sure it is okay make www will
have to be run first. Another script, the one that needs it even more,
has a problem that has to be discussed, before it can be used.
Nonetheless the html.sed file is at least added for the scripts once
things are tested okay.

Add html.sed to translate certain characters

---

1986/bright/README.md
1986/bright/index.html
1987/wall/index.html
1988/robison/index.html
1990/theorem/index.html
1992/albert/index.html
2018/burton2/index.html
bin/README.md
bin/html.sed
bin/index.html
bin/md2html.sh
bin/subst.entry-index.sh

The file bin/html.sed has been fixed so that it works with bin/md2html.sh (which has been modified and which is used via bin/subst.entry-index.sh and output-index-inventory.sh). The script output-index-inventory.sh was already updated to use html.sed so this file has not been modified but the md2html.sh and subst.entry-index.sh scripts have, along with bin/html.sed itself.
Tested make www which rebuilt several index.html files.
Updated bin/README.md as well as bin/index.html.
Testing that all the html files now are correct wrt Nu checker will have to be done another time, however.

Fix html.sed and related scripts

---

bin/README.md
bin/cvt-submission.sh
bin/entry2csv.sh
bin/gen-authors.sh
bin/gen-location.sh
bin/gen-years.sh
bin/index.html
bin/manifest.entry.json.awk
bin/output-index-author.sh
bin/output-year-index.sh
bin/subst.default.sh
bin/subst.entry-index.sh

This happened because when focusing on a bug for several days that had to do with decoding code points (which so happens to be encoding but in JSON it should be converted to unicode even when decoding) I lost sight of the fact that jstrencode is meant to be **JSON** encoder. In the process of this I have uncovered a number of other bugs but that's with jstrencode and the website uses jstrdecode so this should not delay the contest at all.

Swap out (again) jstrencode for jstrdecode

---

bin/cvt-submission.sh

When jparse is not found it did not show how to install it, which is needed for the script to function. It might be worth pointing out that it does not use the jparse repo as that requires one to install the libraries needed, whereas the mkiocccentry clone of the repo has the libraries needed as part of its ecosystem.

Add missing link to bin/cvt-submission.sh

---

faq.html
faq.md

The question of why did it jump from
28.1.3 2024-10-25
to
28.1.6 2024-12-05
can be explained as such. There were three edits since the last version update so there should be three version updates. As for why 5 December 2024 when today is 6 December 2024: it's because the last update to the contents was yesterday, 5 December 2024, although I believe there could be some improvements (menu wise) for Makefile.example. This has to be looked into and if it is done the version will be bumped again.

Fix version in FAQ

---

faq.html
faq.md
next/guidelines.html
next/guidelines.md

The FAQ now has a list to view or download the example Makefile.
The guidelines had some reordering of things and some additional information was also added, like noting better how one does not need to install jparse, dbg or dyn_array to use mkiocccentry, and how even if they do, mkiocccentry will use its own clone.

More corrections in FAQ and guidelines

---

faq.html
faq.md
next/guidelines.html
next/guidelines.md
next/rules.html
next/rules.md

There were numerous fixes and clarifications. One important fix was a typo for jparse(3), being instead jparse(8) which is obviously very wrong.
Other things were improved upon. The FAQ simply stresses something a bit better as the guidelines (or maybe it was the rules) links to that FAQ.

Updates/fixes to guidelines, rules and FAQ

---

next/Makefile.example

Remove the install rule as that's included in 1337.mk.
Remove the indent.c rule as that's included in 1337.mk.
Add to make clobber removal of *.dSYM.
Removed -g3 from OPT variable. This is more useful in macOS but with optimised code debug symbols are not nearly as useful anyway.

Improve next/Makefile.example

---

.gitignore

Rather than have several globs for vim swap files it is now a single glob (explanation below):
.s[a-zA-Z][a-zA-Z0-9]
I encountered another letter, 'v', after the '.s', and instead of having several globs the glob just has [a-zA-Z] followed by [a-zA-Z0-9]. I believe this new way should cover everything. I have not checked the vim source code so I don't know if numbers are necessary and I don't know if it ever (if there were an incredible amount of swap files which might indicate rather a problem with the tree on the user's system) has more than three characters but this should theoretically cover everything and it is not a problem as no files in this glob should ever be in the website and definitely not in an entry as txzchk(1) and chkentry(1) verify.

Fix .gitignore for more vim swap files

---

.gitignore
1986/wall/.entry.json
1986/wall/index.html
1987/lievaart/.entry.json
1987/lievaart/index.html
1988/applin/.entry.json
1988/applin/index.html
1991/westley/README.md
1994/dodsond1/.entry.json
1994/dodsond1/index.html
1994/dodsond2/.entry.json
1994/dodsond2/index.html
1998/bas1/.entry.json
1998/bas1/index.html
faq.html
faq.md
next/try.alt.sh
next/try.sh
thanks-for-help.html
thanks-for-help.md

At least one link in the FAQ was fixed (not to a file but a named reference). The FAQ has not been checked entirely for broken links because the changes have got a bit out of hand and an entire make www will have to be performed due to a problem I discovered doing the below. Other improvements were made.
When going through the FAQ for broken links another problem was discovered, one that broke the scripts that rely on jstrdecode(1). These have been fixed but need further testing with make www. Some index.html files were modified; for why this can be done without make quick_readme2index see below on what changed and why it could be done this way.
When going through the FAQ for broken links I discovered some issues with some entries' synopsis. This means that a number of index.html and …

Various somewhat interconnected fixes

---

2018/ciura/README.md
2018/ciura/index.html

The to use should refer to a file, not some text.

Fix in 2018/ciura/index.html

---

1985/sicherman/.entry.json
1985/sicherman/index.html
1988/phillipps/.entry.json
1988/phillipps/index.html
2018/ciura/README.md
2018/ciura/index.html

1985/sicherman now has an abstract of: rot13 w/strange #defines that
create comment headers etc.
I note that this is longer than what I believe was what was desired.
However it is the same length as it was before, only that it now has #defines
instead of #defs.
1988/phillipps has: 12 Days of Christmas recursive main() calls w/tables
instead of 'days of christmas heavily main() calling with tables'. The 
rewording was necessary to keep the length the same but to be more 
clear. I just remembered however, that to fix it for modern systems, a 
new function had to be added which is the recursive function, so it no 
longer is strictly true that it it is recursive main() calls. It might 
be better to keep it main(), however, as that was the original award. 
The difference here is that it is now …

Update/improve two entries' abstracts

---

1984/mullender/README.md
1984/mullender/index.html
1985/shapiro/.entry.json
1985/shapiro/index.html
1991/ant/README.md
1991/ant/index.html
1994/shapiro/.entry.json
1994/shapiro/index.html
1998/schnitzi/README.md
1998/schnitzi/index.html
2001/dgbeards/README.md
2001/dgbeards/index.html
2004/anonymous/README.md
2004/anonymous/index.html
2019/duble/README.md
2019/duble/index.html
2020/ferguson1/troubleshooting.html
2020/ferguson1/troubleshooting.md
2020/ferguson2/README.md
2020/ferguson2/index.html
2020/ferguson2/recode.html
2020/ferguson2/recode.md
Makefile
next/guidelines.html
next/guidelines.md
next/register.html
next/register.md
thanks-for-help.html
thanks-for-help.md

Make lines beginning (in markdown files) 'BTW' bold. Rebuilt the respective html pages.
Slight update to abstract in two entries (1985/shapiro and 1994/shapiro). One is changing 'defines' to '#defines' and the other was a typo fix.
Fixed make gen_next: added missing new files.
Various fixes in next/register.html (typos and other things).

Various fixes and updates

---

faq.html
faq.md
next/README.md
next/index.html
next/pw-change.html
next/pw-change.md
next/submit.html
next/submit.md
status.html
status.md

Some broken links were fixed in some of the files like next/index.html, next/pw-change.html, next/index.html and status.html.
Some wrong images were used in next/submit.html (or at least referred to wrong if not wrong image).
Useful update to FAQ about the answers file in mkiocccentry.
There might have been other things.
This might be all that is needed for next/ wrt the register/change password/submit but it's possible something has slipped through.

Various fixes in next and top level directory
